### ISSUE TITLE
Redistribution of GPL-ed binaries linked with OpenSSL is not permitted

### ISSUE THREAD

**Issue by lkundrak** [adrienverge/openfortivpn#10]
There's a well known clash between the licenses (OpenSSL adds an "additional restriction" which is specifically not allowed by GPL). Therefore the license doesn't allow anyone to redistribute the resulting binaries (since a e.g. a Linux distro shipping both is technically a derived work of the package).

I'd be very thankful if this could be solved and I could distribute the code in Fedora. One obvious solution would be to port it to some other library that does encryption; be it NSS or GNU TLS. Another solution is to add an exception to the openfortivpn license which would allow it to be linked with OpenSSL. I'd prefer the latter as the former takes some non-trivial effort.

See this document for analysis; the possible solutions and links to examples how it has been dealt with:
https://people.gnome.org/~markmc/openssl-and-the-gpl.html

Thank you
Lubo

**Comment by adrienverge** [comment]
Lubomir, first, thank you for your recent contributions to this project and for your informed advice.

I wasn't aware of that clash. I'll do a pull request to solve this issue. Fell free to review.

**Comment by lkundrak** [comment]
Thank you.
