### ISSUE TITLE
Connects but can't reach any hosts - then disconnects

### ISSUE THREAD

**Issue by milesbarry** [adrienverge/openfortivpn#100]
Hi, I've just built the client on a Raspberry Pi 3, and I can connect, auth, and it's pushing the correct DNS servers etc. Routing table looks good (at least to me), but I can't ping nor SSH to any hosts.

After about 2-3 minutes the VPN then disconnects with an Input/Output error. Anyone have any ideas what could be wrong please?

TIA

Version: openfortivpn-1.3.0

Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.110.254 0.0.0.0         UG    202    0        0 eth0
1.1.1.1         0.0.0.0         255.255.255.255 UH    0      0        0 ppp0
100.78.0.0      10.248.0.2      255.255.0.0     UG    0      0        0 ppp0
172.15.15.0     10.248.0.2      255.255.255.0   UG    0      0        0 ppp0
192.168.0.0     10.248.0.2      255.255.0.0     UG    0      0        0 ppp0
192.168.110.0   0.0.0.0         255.255.255.0   U     202    0        0 eth0
195.244.160.0   10.248.0.2      255.255.224.0   UG    0      0        0 ppp0

INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [10.248.0.2], ns [192.168.34.250, 192.168.34.251]
INFO:   Got addresses: [10.248.0.2], ns [192.168.34.250, 192.168.34.251]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
INFO:   Removing VPN nameservers...
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

**Comment by adrienverge** [comment]
Hi, it is possible that openfortivpn is not compatible with your gateway. Do you know what software / version it is running?

Also, I recommend you to test previous versions of openfortivpn (1.2 and 1.1), they could be working better!

**Comment by milesbarry** [comment]
Hi thanks Adrien,

I'll ask the networking team exactly what they've got and update the info here. Likewise I will try the 1.2 and 1.1 versions.

All the best

**Comment by milesbarry** [comment]
Hi Adrien,

I tried as you recommended 1.2 and 1.1, neither worked (FYI 1.1 segfaulted on auth). The network team just informed me that they're running:

Fortigate 1000D v5.4.0,build1102

Hope this gives you some better info.

All the best

**Comment by milesbarry** [comment]
Hi Adrien,

I'm just with the guy who is deploying the Fortinet and he's saying actually 5.4.3, but he's going to upgrade to 5.4.4 FYI.

Cheers

**Comment by milesbarry** [comment]
Hello again, OK problem found.

195.244.160.0 10.248.0.2 255.255.224.0 UG 0 0 0 ppp0 

This range covered the IP address of the VPN public IP, so we set up a static route to send the traffic over the default gateway, et voila.... worked.

For your reference the official Windows client works correctly even with this range, so would it be possible for you to alter your code to make it also force any traffic destined for the VPN gateway to use the default GW, not the ppp vpn? For sure it would eradicate this problem.

For the rest, it's working great, so many thanks Adrien!

**Comment by mrbaseman** [comment]
There is already a fix for this on the master branch. Two pull requests around the routing topic are still open: we have an issue on Mac OS X and if the route is added manually before the vpn is started, the route is removed by mistake when the connection is closed.

**Comment by milesbarry** [comment]
Thanks mrbaseman, I'll keep an eye on future releases.

**Comment by adrienverge** [comment]
Hi @milesbarry, I'm glad to hear you found the problem!

If I understand correctly version 1.3.0 did not work, but have you tried latest master (commit d9141f9)?

**Comment by milesbarry** [comment]
Hi Adrien,

1.3 is A-OK ... working fine. The whole issue was our network admin pushing out routes for public IP space to go over the VPN.

The route below, has the IP address we connect to in it:

195.244.160.0 10.248.0.2 255.255.224.0 UG 0 0 0 ppp0

Once I added a static route to ensure it went out over eth0, it works great! 

All the best

Miles

**Comment by mrbaseman** [comment]
I think this can be closed. Newer versions circumvent the problem, and for older versions (up to 1.3.0) manually adding a host route is a workaround.
