### ISSUE TITLE
Connecting to SSL with another IP

### ISSUE THREAD

**Issue by xkrst** [adrienverge/openfortivpn#1001]
Hello,
I have got SSL-VPN configured with two IPs. After configuring openforti for one of IP's it runs correctly. But when I am changing IP for "second tunnel" (IP) openforti has nothing to do. It recognizes IP, username and password correctly, but when it comes to check for certificate it just stops, gives no errors and after some time shows timeout and could not login.

**Comment by DimitriPapadopoulos** [comment]
Are you running a VPN tunnel within a VPN tunnel?

Logs would help understand the context.
