### ISSUE TITLE
Question/Help on proper configuration FortiVPN + Microsoft Authenticator

### ISSUE THREAD

**Issue by marcelbonnet** [adrienverge/openfortivpn#1002]
Hi. Please, I need help, maybe to proper configure the client.
In my organization, when I connect to  FortiVPN, I receive a popup in my Mobile phone, from Microsoft Authenticator app. I expected the connection to work after I approve it on my phone, but the client hangs.

I've been using openforti VPN GUI + openfortivpn on and AMD64 Ubuntu with no problems. But now I'm setting up a desktop for Raspberry Pi 4, and openfortivpn GUI isn't available as a package. Maybe that GUI did some configuration that I wasn't able to reproduce with the command line client ?

Here is the configuration I created:

```
host=asdf.org
port=443
username=usernamehere
password=passwordhere
trusted-cert=certificatehere
pppd-log=/var/log/openfortivpn.log
set-dns=1
set-routes=1
persistent=0
```

Starting the connection:

```
root@pi:/etc/openfortivpn#  openfortivpn 
INFO:   Connected to gateway.
```

At this point, I am asked (android mobile phone) to approve/deny the connection. But after hitting approve button:

```
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
ERROR:  pppd: An immediately fatal error of some kind occurred, such as an essential system call failing, or running out of virtual memory.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

**Comment by marcelbonnet** [comment]
I found its not a problem of configuration. The same config works on amd64 Ubuntu 20.04.4 .

**Comment by DimitriPapadopoulos** [comment]
If it works on Ubuntu 20.04, it has to be a problem with PPP on your Raspberry Pi 4 machine. See for example https://github.com/adrienverge/openfortivpn/issues/870#issuecomment-890464938.

**Comment by marcelbonnet** [comment]
# Solved

Thanks @DimitriPapadopoulos . I investigated and found a solution. As you said, the problem was my system (raspberry pi 4). 

# Understading the Error Message

Considering that the problem was related to _set tty to PPP_, I compared the installed modules between _amd64 Ubuntu 20_ and _aarch64 Ubuntu 22_.

I realized that _amd64 Ubuntu 20_ installed a module _/lib/modules/5.4.0-124-generic/kernel/drivers/net/ppp/ppp_synctty.ko_ through a package named _linux-generic_. My pi, running _Ubuntu 22 aarch64_, was missing that package and so, the named module.

The package _linux-generic_, installs modules for an older kernel.

The chapter "PPP Implementation in the Linux Kernel", https://flylib.com/books/en/3.475.1.47/1/, says "The asynchronous PPP module essentially supplies a new TTY line discipline". So I decided to focus on compile and install _ppp_async.ko_ and all other possible _ko_s.

# Solution

As you see, the current package linux-modules for my kernel does not provide ppp modules.

```
root@pi:/lib/modules# dpkg -L linux-modules-5.15.0-1013-raspi | grep ppp
```

The solution is to build them.

```
# apt install linux-headers-$(uname -r)
# apt install build-essential
```

Set sources for in _/etc/apt/sources.list_:

```
deb-src http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ jammy-security universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ jammy-security multiverse
```

Now, download the package source, compile and install.

```
$ cd ~/Downloads
$ apt source linux-modules-5.15.0-1013-raspi
$ cd linux-raspi-5.15.0/
$ chmod +x scripts/pahole-*
$ sudo apt install flex bison
$ cd ~/Downloads/linux-raspi-5.15.0/drivers/net/ppp

Following instructions from Kernel Documentation, since we need to compile only this sub set of modules and not all things (https://www.kernel.org/doc/html/latest/kbuild/modules.html) :

$ make -C /lib/modules/`uname -r`/build M=$PWD
$ sudo make -C /lib/modules/`uname -r`/build M=$PWD modules_install
# cd /lib/modules/5.15.0-1013-raspi/extra
# for f in *; do insmod $f; done
```

# Solved

```
# openfortivpn 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [192.168.104.13], ns [10.10.1.81, 10.10.1.4], ns_suffix [foo.bar.org]
INFO:   Negotiation complete.
INFO:   Negotiation complete.
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

VPN is working!

**Comment by DimitriPapadopoulos** [comment]
That's great news! Thank you for the detailed explanation of the solution.

**Comment by DimitriPapadopoulos** [comment]
I have Ubuntu 22.04 running on my workstation, and I don't see this problem. Looks specific to the `aarch64` architecture.

**Comment by DimitriPapadopoulos** [comment]
Handling DNS parameters on Linux is hell. DNS subsystems differ across distributions and depend on individual configurations. Finding the proper subsystem to use for DNS changes, and using that subsystem, is way too complex.

I know `openfortivpn` does not play well with recent distributions. I would recommend moving routing and DNS changes to an external script, the way [`vpnc-script`](https://gitlab.com/openconnect/vpnc-scripts) is called by [OpenConnect](https://gitlab.com/openconnect/openconnect). But that script doesn't play well either with systemd-based distributions (see [openconnect/vpnc-scripts#43](https://gitlab.com/openconnect/vpnc-scripts/-/merge_requests/43)) – which confirms my point that handling DNS parameters on Linux is hell!

**Comment by falz** [comment]
For future folk that come across this - i had this issue on Ubuntu 22. it was because ppp_async module wasnt loading dynamically. `modprobe ppp_async` also wouldnt work.

to fix, I told it to load on boot by creating "/etc/modules-load.d/openfortigui.conf" with contents:

```ppp_async```

and rebooting
