### ISSUE TITLE
Connection error on fedora36 & openfortivpn 1.17.0

### ISSUE THREAD

**Issue by ralequi** [adrienverge/openfortivpn#1014]
Hi, I'm having issues trying to connect to a fortinet VPN.

I got the following error, both calling it on console and by gnome+network manager:

```
sudo openfortivpn -v xxxxx:10443 -u aaaaaaaa -p ********* --trusted-cert zzzzz --insecure-ssl
WARN:   You should not pass the password on the command line. Type it interactively or use a configuration file instead.
DEBUG:  openfortivpn 1.17.0
DEBUG:  revision unavailable
DEBUG:  Loaded configuration file "/etc/openfortivpn/config".
DEBUG:  Configuration host = "xxxxx"
DEBUG:  Configuration realm = ""
DEBUG:  Configuration port = "10443"
DEBUG:  Configuration username = "aaaaaaaa"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  SO_KEEPALIVE: 0
DEBUG:  SO_SNDBUF: 6
DEBUG:  SO_RCVBUF: 60
DEBUG:  server_addr: xxxxx
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: xxxxx
DEBUG:  gateway_port: 10443
ERROR:  SSL_CTX_new: error:0700006D:configuration file routines::module initialization error
INFO:   Closed connection to gateway.
DEBUG:  SO_KEEPALIVE: 0
DEBUG:  SO_SNDBUF: 6
DEBUG:  SO_RCVBUF: 60
DEBUG:  server_addr: xxxxx
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: xxxxx
DEBUG:  gateway_port: 10443
DEBUG:  Setting minimum protocol version to: 0x303.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.
```

The contents of `/etc/openfortivpn/config` are none/empty:
```
### configuration file for openfortivpn, see man openfortivpn(1) ###

# host = vpn.example.org
# port = 443
# username = vpnuser
# password = VPNpassw0rd
```

I have tested to include the CA but got the same error. (same omitting the `--insecure-ssl`)

What I'm missing?

Thank you in advance!

**Comment by DimitriPapadopoulos** [comment]
The following message shows there is a problem with the certificate of the VPN portal:
```
DEBUG:  Gateway certificate validation failed.
```
but as far as I can see option `--trusted-cert zzzzz` works around the bad certificate:
```
DEBUG:  Gateway certificate digest found in white list.
```

The initial SSL connection appears to fail with:
```
ERROR:  SSL_CTX_new: error:0700006D:configuration file routines::module initialization error
INFO:   Closed connection to gateway.
```
but then I think `openfortivpn` goes on and succeeds in logging out properly:
```
DEBUG:  Setting minimum protocol version to: 0x303.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.
```

So I think the relevant error message is:
```
ERROR:  SSL_CTX_new: error:0700006D:configuration file routines::module initialization error
```
At this point, I have no clue what this OpenSSL error message means.

**Comment by DimitriPapadopoulos** [comment]
A few hits in Google:
* [building a simple engine for openssl fails](https://stackoverflow.com/questions/18507790/building-a-simple-engine-for-openssl-fails#18896629)
* [Openssl install broken after dist upgrade](https://askubuntu.com/questions/1412421/openssl-install-broken-after-dist-upgrade)

Have you modified **`openssl.cnf`** on your computer?
Is environment variable **`OPENSSL_CONF`** set?
What is the output of `openssl engine`?

**Comment by ralequi** [comment]
Thank you @DimitriPapadopoulos 

I did not remember to have touch the file `openssl.cnf` but must check if a related config is broken (it seems to)

From `openssl engine` i get:

```
FATAL: Startup failure (dev note: apps_startup()) for openssl
40FC08DB157F0000:error:07800069:common libcrypto routines:provider_conf_init:provider section error:crypto/provider_conf.c:298:
40FC08DB157F0000:error:0700006D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:270:module=providers, value=provider_sect retcode=-1    
```

Thank you,
I'm closing this issue since it is not an openfortivpn issue.

**Comment by ralequi** [comment]
Confirmed!
Found something weird on openssl.cnf, fixed and now openfortivpn works!!!

Thanks!!
