### ISSUE TITLE
Cannot save setting

### ISSUE THREAD

**Issue by kydner** [adrienverge/openfortivpn#1017]
![image](https://user-images.githubusercontent.com/40586726/190867624-c3968c05-cb9e-4f2f-bc7f-20e68c50fade.png)
cannot save setting on fedora 36 gnome, because cannot be resize

**Comment by DimitriPapadopoulos** [comment]
Unless I'm wrong, this is not related to openfortivpn.

**Comment by kydner** [comment]
Lol, sorry I guess this is github openfortigui, misrepresentation
