### ISSUE TITLE
Can't get OTP prompt

### ISSUE THREAD

**Issue by proactif** [adrienverge/openfortivpn#1019]
I need to send an OTP to connect to my company's Forti VPN, this is working fine :
`openfortivpn xxx.xxxxx.xx:443 --username=xxxxxx -p 'xxxxxxxx' -o 194876  -vv`

But this won't work (pinentry is never called) :
`openfortivpn xxx.xxxxx.xx:443 --username=xxxxxx -p 'xxxxxxxx' --otp-prompt='Enter token code' --pinentry=pinentry-gnome3  -vv`

Logs from a successful connection :

What should my --otp-prompt value be in this case ? 'Enter token code' seemed correct, but that doesn't trigger pinentry.

```
openfortivpn cas.tessi.eu:443 --username=xxx -p 'xxx' -o 194876  -vv
WARN:   You should not pass the password on the command line. Type it interactively or use a configuration file instead.
DEBUG:  openfortivpn 1.17.0
DEBUG:  revision unavailable
DEBUG:  Loaded configuration file "/etc/openfortivpn/config".
DEBUG:  Configuration host = "xxx.xxx.xx"
DEBUG:  Configuration realm = ""
DEBUG:  Configuration port = "443"
DEBUG:  Configuration username = "xxx"
DEBUG:  One-time password = "194876"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  SO_KEEPALIVE: 0
DEBUG:  SO_SNDBUF: 6
DEBUG:  SO_RCVBUF: 60
DEBUG:  server_addr: xxx.xxx.xxx.xxx
DEBUG:  server_port: 443
DEBUG:  gateway_addr: xxx.xxx.xx.xxx
DEBUG:  gateway_port: 443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
DEBUG:  Setting minimum protocol version to: 0x303.
DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.
DEBUG:  http_send:
POST /remote/logincheck HTTP/1.1
Host: xxx.xxx.xx:443
User-Agent: Mozilla/5.0 SV1
Accept: */*
Accept-Encoding: gzip, deflate, br
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
Content-Type: application/x-www-form-urlencoded
Cookie: 
Content-Length: 57

username=xxx&credential=**********1%21&realm=&ajax=1
DEBUG:  http_receive:
HTTP/1.1 200 OK
Date: Sun, 25 Sep 2022 13:37:25 GMT
Server: xxxxxxxx-xxxxx
Set-Cookie:  SVPNCOOKIE=; path=/; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly;
Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly
Transfer-Encoding: chunked
Content-Type: text/plain
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'; object-src 'self'; script-src 'self' https  (null) 'unsafe-eval' 'unsafe-inline' blob:;
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

cf    
ret=2,reqid=1025921749,polid=99-1-427a6aa2,grp=G_Nomades_xxx,portal=PORTAIL_xxx,magic=1-427a6aa2,tokeninfo=ftm_push,chal_msg=Enter token code or no code to send a notification to your FortiToken Mobile
0


DEBUG:  http_send:
POST /remote/logincheck HTTP/1.1
Host: xxx.xxx.xx:443
User-Agent: Mozilla/5.0 SV1
Accept: */*
Accept-Encoding: gzip, deflate, br
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
Content-Type: application/x-www-form-urlencoded
Cookie: 
Content-Length: 146

username=xxx&realm=&reqid=1025921749&polid=99-1-427a6aa2&grp=G_Nomades_xxx&portal=PORTAIL_xxx&peer=&code=194876&code2=&magic=1-427a6aa2
DEBUG:  http_receive:
HTTP/1.1 200 OK
Date: Sun, 25 Sep 2022 13:37:28 GMT
Server: xxxxxxxx-xxxxx
Set-Cookie: SVPNCOOKIE=xxxxxxxxxxxxxxxxxxxxxx; path=/; secure; httponly
Transfer-Encoding: chunked
Content-Type: text/html
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'; object-src 'self'; script-src 'self' https  (null) 'unsafe-eval' 'unsafe-inline' blob:;
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

6e    
<html><head>
<script language='javascript'>
document.location='/sslvpn/portal.html';
</script>
</head></html>

0


DEBUG:  Cookie: SVPNCOOKIE=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
INFO:   Authenticated.
```

**Comment by DimitriPapadopoulos** [comment]
The log from a connection that doesn't work might be helpful.

**Comment by proactif** [comment]
Maybe. So here are the logs for a non-working call :

> openfortivpn xxx.xxx.xx:443 --username=xxx -p 'xxx' --otp-prompt='Enter token code' --pinentry=pinentry-gnome3  -vv
> WARN:   You should not pass the password on the command line. Type it interactively or use a configuration file instead.
> DEBUG:  openfortivpn 1.17.0
> DEBUG:  revision unavailable
> DEBUG:  Loaded configuration file "/etc/openfortivpn/config".
> DEBUG:  Configuration host = "xxx.xxx.xx"
> DEBUG:  Configuration realm = ""
> DEBUG:  Configuration port = "443"
> DEBUG:  Configuration username = "xxx"
> DEBUG:  Resolving gateway host ip
> DEBUG:  Establishing ssl connection
> DEBUG:  SO_KEEPALIVE: 0
> DEBUG:  SO_SNDBUF: 6
> DEBUG:  SO_RCVBUF: 60
> DEBUG:  server_addr: xxx.xxx.xxx.xxx
> DEBUG:  server_port: 443
> DEBUG:  gateway_addr: xxx.xxx.xxx.xxx
> DEBUG:  gateway_port: 443
> DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
> DEBUG:  Setting minimum protocol version to: 0x303.
> DEBUG:  Gateway certificate validation succeeded.
> INFO:   Connected to gateway.
> DEBUG:  http_send:
> POST /remote/logincheck HTTP/1.1
> Host: xxx.xxx.xx:443
> User-Agent: Mozilla/5.0 SV1
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Pragma: no-cache
> Cache-Control: no-store, no-cache, must-revalidate
> If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
> Content-Type: application/x-www-form-urlencoded
> Cookie: 
> Content-Length: 57
> 
> username=xxx&credential=**********1%21&realm=&ajax=1
> DEBUG:  http_receive:
> HTTP/1.1 200 OK
> Date: Thu, 29 Sep 2022 22:46:06 GMT
> Server: xxxxxxxx-xxxxx
> Set-Cookie:  SVPNCOOKIE=; path=/; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly;
> Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly
> Transfer-Encoding: chunked
> Content-Type: text/plain
> X-Frame-Options: SAMEORIGIN
> Content-Security-Policy: frame-ancestors 'self'; object-src 'self'; script-src 'self' https  (null) 'unsafe-eval' 'unsafe-inline' blob:;
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Strict-Transport-Security: max-age=31536000
> 
> cf    
> ret=2,reqid=1025967280,polid=99-1-1a5b4078,grp=G_xxx,portal=PORTAIL_xxx,magic=1-1a5b4078,tokeninfo=ftm_push,chal_msg=Enter token code or no code to send a notification to your FortiToken Mobile
> 0
> 
> 
> DEBUG:  http_send:
> POST /remote/logincheck HTTP/1.1
> Host: xxx.xxx.xx:443
> User-Agent: Mozilla/5.0 SV1
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Pragma: no-cache
> Cache-Control: no-store, no-cache, must-revalidate
> If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
> Content-Type: application/x-www-form-urlencoded
> Cookie: 
> Content-Length: 120
> 
> username=xxx&realm=&reqid=1025967280&polid=99-1-1a5b4078&grp=G_xxx&portal=PORTAIL_xxx&peer=&ftmpush=1
> DEBUG:  http_receive:
> HTTP/1.1 405 Method Not Allowed
> Date: Thu, 29 Sep 2022 22:46:09 GMT
> Server: xxxxxxxx-xxxxx
> Set-Cookie:  SVPNCOOKIE=; path=/; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly;
> Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly
> Transfer-Encoding: chunked
> Content-Type: text/html
> X-Frame-Options: SAMEORIGIN
> Content-Security-Policy: frame-ancestors 'self'; object-src 'self'; script-src 'self' https  (null) 'unsafe-eval' 'unsafe-inline' blob:;
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Strict-Transport-Security: max-age=31536000
> 
> 656   
> <HTML>
> <HEAD>
> <META http-equiv="Content-Type" content="text/html; charset=utf-8">
> <META HTTP-EQUIV="Pragma" CONTENT="no-cache">
> <link href="/sslvpn/css/ssl_style.css" rel="stylesheet" type="text/css">
> <script type='text/javascript' src='/remote/fgt_lang?lang=en'></script>
> </head>
> <body class="main">
> <table class="container" cellpadding="0" cellspacing="0">
> <tr>
> <td><table class="dialog" width=300 align="center" cellpadding="0" cellspacing="0">
> <tr>
> <td><table class="header" cellpadding="0" cellspacing="0">
> <tr>
> <td id="err_title"></td>
> </tr>
> </table></td>
> </tr>
> <script>document.getElementById('err_title').innerHTML=fgt_lang['error'];</script>
> <tr>
> <td class="body" height=100><table class="body"><tr><td id='err_val' title='405' align="center">
> <script>
> var errval_elem=document.getElementById('err_val');
> var errval=errval_elem.getAttribute('title').split(',');
> var err_str = fgt_lang[errval[0]];
> if (err_str == undefined) {
>    errval_elem.innerHTML = "some unknown error!<br>";
> } else {   if (errval.length == 2) {
>        err_str = err_str.replace("%d", errval[1]);
>    }
>    errval_elem.innerHTML = err_str;
> }
> </script></td></tr></table></td>
> </tr>
> <tr><td>
> <table class="footer" cellpadding="0" cellspacing="0">
> <tr><td>
> <input id="ok_button" type="button" value="" onclick="chkbrowser()" style="width:80px">
> </td></tr>
> </table>
> </td></tr>
> </table>
> </body>
> <script language = "javascript">
> document.getElementById('ok_button').value=fgt_lang['ok'];
> function chkbrowser() {
> if (window.location.pathname == "/remote/login")
> window.location.reload();
> else
> window.location.href = "/remote/login";}
> </script>
> </html>
> 
> 0
> 
> 
> ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
> DEBUG:  HTTP status code (405)
> INFO:   Closed connection to gateway.
> DEBUG:  SO_KEEPALIVE: 0
> DEBUG:  SO_SNDBUF: 6
> DEBUG:  SO_RCVBUF: 60
> DEBUG:  server_addr: xxx.xxx.xxx.xxx
> DEBUG:  server_port: 443
> DEBUG:  gateway_addr: xxx.xxx.xxx.xxx
> DEBUG:  gateway_port: 443
> DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
> DEBUG:  Setting minimum protocol version to: 0x303.
> DEBUG:  Gateway certificate validation succeeded.
> DEBUG:  http_send:
> GET /remote/logout HTTP/1.1
> Host: xxx.xxx.xx:443
> User-Agent: Mozilla/5.0 SV1
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Pragma: no-cache
> Cache-Control: no-store, no-cache, must-revalidate
> If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
> Content-Type: application/x-www-form-urlencoded
> Cookie: 
> Content-Length: 0
> 
> 
> DEBUG:  http_receive:
> HTTP/1.1 200 OK
> Date: Thu, 29 Sep 2022 22:47:11 GMT
> Server: xxxxxxxx-xxxxx
> Set-Cookie:  SVPNCOOKIE=; path=/; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly;
> Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly
> Content-Length: 643
> Content-Type: text/html; charset=utf-8
> X-Frame-Options: SAMEORIGIN
> Content-Security-Policy: frame-ancestors 'self'; object-src 'self'; script-src 'self' https  (null) 'unsafe-eval' 'unsafe-inline' blob:;
> X-XSS-Protection: 1; mode=block
> X-Content-Type-Options: nosniff
> Strict-Transport-Security: max-age=31536000
> 
> <html><head><script>function fgt_clear_cookies() {var cookies = document.cookie.split(';');var domain = document.domain.split('.');var new_date='; expires=Thu, 21 Sep 1979 00:00:01 UTC';if (domain.length > 1) {domain.shift();}for (var i = 0; i < cookies.length; i++) {var spcook =  cookies[i].split('=');document.cookie = spcook[0] + '=; path=/' + new_date;document.cookie = spcook[0] + '=; domain=.' + domain.join('.') + '; path=/' + new_date;document.cookie = spcook[0] + '=; domain=' + domain.join('.') + '; path=/' + new_date;}window.location.href ='/remote/login';}</script></head><body><script>fgt_clear_cookies();</script></body></html>
> INFO:   Logged out.

**Comment by DimitriPapadopoulos** [comment]
From the man page:
* **`-p`/`--password`** VPN account password in plain text.  For a secure alternative, use pinentry or let openfortivpn prompt for the password.
* **`-o`/`--otp`** One-Time-Password.

Therefore, for both the regular password and the one-time password, you may:
1. pass the password in plain text using the `-p`/`--password` and `-o`/`--otp` options,
2. let openfortivpn prompt for the password,
3. use `--pinentry` to define a 3rd party program to use.

All these options should be equivalent. If one works, the others should work too.

In your case, I believe it doesn't work because of option `--otp-prompt`. I believe there is a misunderstanding what this option is about:
* **`--otp-prompt`** Search for the OTP password prompt starting with the string prompt.

Does it work any better when you do **not** use option `--otp-prompt`?
