### ISSUE TITLE
garbage is appended to /etc/resolv.conf

### ISSUE THREAD

**Issue by gilligan** [adrienverge/openfortivpn#103]
I just wanted to update the openfortivpn package for NixOS to the latest version. Everything seemed to be working fine and I can in fact connect to our vpn. The problem is that after disconnecting VPN some garbage is being appended to `/etc/resolv.conf`:

```
^S^]AddTrust Exte<91>
```

As you can see in my package update [PR](https://github.com/NixOS/nixpkgs/pull/23215#issuecomment-282562019) for openfortivpn the best guess from some other contributor is that it might be some pointer corruption.

How can I provide useful information to figure out what is going on ?

**Comment by gilligan** [comment]
I ran this through valgrind - here is the output: https://gist.github.com/gilligan/f973eac77bbb87206afbc32e3eed174c

```
==15669== LEAK SUMMARY:
==15669==    definitely lost: 824 bytes in 1 blocks
==15669==    indirectly lost: 71,519 bytes in 653 blocks
==15669==      possibly lost: 47 bytes in 2 blocks
==15669==    still reachable: 88,011 bytes in 2,876 blocks
==15669==         suppressed: 0 bytes in 0 blocks
==15669== Reachable blocks (those to which a pointer was found) are not shown.
==15669== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

**Comment by gilligan** [comment]
As noted in the linked PR I notcied that there is a `read` happening somewhere towards the end that reads some data containing `AddTrust` so I'm guessing there is some memory corruption going on when the nameserver entries are removed from `/etc/resolv.conf` in `src/ipv4.c` - Can't really point at anything in specific though

**Comment by gilligan** [comment]
@adrienverge ping ;-)

**Comment by DimitriPapadopoulos** [comment]
It's a long shot, but perhaps #117 could help...

**Comment by adrienverge** [comment]
Sorry about the delay. I hope #117 will fix the problem!

**Comment by DimitriPapadopoulos** [comment]
@gilligan Does it work any better with openfortivpn 1.3.1 (which includes patch #117)?

**Comment by DimitriPapadopoulos** [comment]
I'll close this issue as #117 should have fixed the problem!
