### ISSUE TITLE
how to input dynamic token with openfortivpn when connect to the vpn

### ISSUE THREAD

**Issue by Git-Kyro** [adrienverge/openfortivpn#1033]
I am trying to connect VPN with openfortivpn on the Debian system, when I input the password and then should be input a dynamic token, but can not find an input option in openfortivpn, may I know if the dynamic token is supported? if yes what should I do?

**Comment by DimitriPapadopoulos** [comment]
Does option`-o` help?

Perhaps openfortivpn does not support the way this server works. Hard to tell without more information.

**Comment by Git-Kyro** [comment]
Actually, I should use fortivpn connect, but fortivpn does not support Debian, I would like to use openfortivpn as my proxy tool, please check the picture for your reference. thanks.
![20200904174911693](https://user-images.githubusercontent.com/77045987/198659245-9a324e54-029e-4bf1-9f4d-aeee9e06eafb.jpeg)

**Comment by DimitriPapadopoulos** [comment]
As I said, hard to tell without more information, like (redacted) logs.

**Comment by DimitriPapadopoulos** [comment]
Doesn't the [DEB package](https://links.fortinet.com/forticlient/deb/vpnagent) available from thos page wotk on Debian?

https://www.fortinet.com/support/product-downloads#vpn

**Comment by Git-Kyro** [comment]
Because my Debian is ARM64 and FortiCLient VPN DEB package just supports AMD64.

**Comment by DimitriPapadopoulos** [comment]
I see. Does option`-o` help?

**Comment by Git-Kyro** [comment]
I didn't find an answer to this issue

**Comment by DimitriPapadopoulos** [comment]
I don't understand:
* What have you tried?
* Where are your logs?
* Have tried option `-o`?

**Comment by tobip** [comment]
I think I am looking for the same functionality like OP.
Option `-o` does indeed work for me, I just give the Token from the app on my phone as parameter and connection works.

**Comment by DimitriPapadopoulos** [comment]
Yes, that's precisely the case where `-o`  is supposed to help.

@Git-Kyro If it doesn't work in your case, please do not hesitate to re-open this issue and add the requested information.
