### ISSUE TITLE
openfortivpn, NetworkManager and OTP

### ISSUE THREAD

**Issue by diegombeltran** [adrienverge/openfortivpn#1043]
Hello!

I've been used openfortivpn with NetworkManager applet for a long time and everything works as expected. Well, everything but the OTP prompt using NetworkManager GUI. Using the CLI, everything is ok. Using the nm-applet, the OTP prompt does not show even though the OTP code is sent by my company's appliance. It works ok on version 1.10.0-2 (I've pinned the package since) but it does not on later builds.

This happens, at least, with Fedora from last 2019 release to the newest one (37) and Arch.

Not sure which logs are useful to debug this problem, but I'll be glad to help.

**Comment by DimitriPapadopoulos** [comment]
If the command line `openfortivpn` works for you, I guess this is a [NetworkManager-fortisslvpn](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) issue.

**Comment by diegombeltran** [comment]
I guess this can be closed then.

Just to share info, I'm not sure if this is the exact problem:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/45

Thank you @DimitriPapadopoulos
