### ISSUE TITLE
Skype (web/desktop) not sending messages

### ISSUE THREAD

**Issue by raffaele-morelli** [adrienverge/openfortivpn#1050]
I am using openfortigui and works just fine... except with skype.

When connected to my VPN messages hangs forever and calls do not start.
If I disconnect messages are sent.

Here follow my profile

```
[cert]
ca_file=
trusted_cert=
user_cert=
user_key=
verify_cert=false

[options]
autostart=false
debug=false
half_internet_routers=false
insecure_ssl=false
pppd_call=
pppd_ifname=
pppd_ipparam=
pppd_log_file=
pppd_no_peerdns=false
pppd_plugin_file=
realm=
set_dns=true
set_routes=true

[vpn]
gateway_host=xxx.xxx.xxx.xxx
gateway_port=10443
name=WORK
password="====================="
username=user.name
```

**Comment by DimitriPapadopoulos** [comment]
I don't think this is related to openfortivpn. Rather, the network you connect to does not let Skype through.

What sort of network do you connect to? A corporate network? Chances are they are blocking Skype.

Also, this is the place for openfortivpn issues, so the openfortigui profile does not help us. This is the place for openfortigui issues:
https://github.com/theinvisible/openfortigui
