### ISSUE TITLE
Execute a command upone connect

### ISSUE THREAD

**Issue by mario-almeida** [adrienverge/openfortivpn#1053]
Once  VPN  is established, need an option to execute and command with sudo

**Comment by DimitriPapadopoulos** [comment]
[Using pppd ip-up / ip-down scripts](https://github.com/adrienverge/openfortivpn/wiki#using-pppd-ip-up--ip-down-scripts)?

**Comment by DimitriPapadopoulos** [comment]
Also, openfortivpn notifies systemd when it's connected:
https://github.com/adrienverge/openfortivpn/blob/04dc8d40c8d9bf839ccaa665ab5a6795bbefafd1/src/tunnel.c#L130-L132

Perhaps you can plug into systemd and use this notication.

**Comment by mario-almeida** [comment]
How to do this from GUI?

**Comment by DimitriPapadopoulos** [comment]
openfortivpn does not provide a GUI.
