### ISSUE TITLE
OpenFortiVPN on ARM64 produces errors wheras on AMD64 it works fine

### ISSUE THREAD

**Issue by in4matix** [adrienverge/openfortivpn#1056]
I was using OpenFortiVPN very successfully on my laptop running Ubuntu 22.04.1 to connect to a Fortigate VPN. Recently, after my laptop finally kicked the bucket, I decided to get a Raspberry PI 4 and installed Ubuntu 22.04.1. I am running the exact same config, same network, etc, but on the PI I just cannot initiate a successful connection.

This is the Terminal info I keep getting:

INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Couldn't set tty to PPP discipline: Invalid argument
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
ERROR:  pppd: An immediately fatal error of some kind occurred, such as an essential system call failing, or running out of virtual memory.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

Can someone maybe point me in the right direction?

P.S. I am fairly new to Linux environment.

**Comment by DimitriPapadopoulos** [comment]
I doubt it's an ARM64 vs. AMD64 issue. The Raspberry Linux distribution lacks a working `pppd`, probably because of missing kernel modules.

Something like this might help:
```
sudo apt install linux-modules-extra-raspi
```

**Comment by in4matix** [comment]
@DimitriPapadopoulos Thank you, thank you, thank you !! Works perfectly now !! Thank you so very much.
