### ISSUE TITLE
Error reading from SSL connection (Protocol violation with EOF).

### ISSUE THREAD

**Issue by jwpit** [adrienverge/openfortivpn#106]
Hello,

a ppp0 Interface exists for some seconds, but does not get an IP.
The Debug log shows several Error reading from SSL connection (Protocol violation with EOF).

openfortivpn version: 1.2.0

openfortivpn --no-routes --no-dns -vvv &
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "vpn.[...]"
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = "[...]"
DEBUG:  Config password = "********"
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=[...]
DEBUG:  Error reading from SSL connection (Protocol violation with EOF).
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Remote gateway has allocated a VPN.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Error reading from SSL connection (Protocol violation with EOF).
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  pppd_read_thread
DEBUG:  ssl_write_thread
DEBUG:  if_config thread
DEBUG:  ssl_read_thread
DEBUG:  pppd_write thread
DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 ba 9a d0 9b

DEBUG:  Error reading from SSL connection (Protocol violation with EOF).
INFO:   Cancelling threads...
DEBUG:  Waiting for pppd to exit...
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.

**Comment by DimitriPapadopoulos** [comment]
This might be related to issue #92

Is this on Linux or Mac OS? Have you tried with a recent checkout of _openfortivpn_?
