### ISSUE TITLE
ERROR:  pppd: Is not setuid-root and the invoking user is not root.

### ISSUE THREAD

**Issue by julianov** [adrienverge/openfortivpn#1062]
Running openfortivpn on ubuntu server I get this output:

INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
ERROR:  pppd: Is not setuid-root and the invoking user is not root.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

pppd is up and running:
ps aux | grep pppd
root     29585  0.0  0.1  13208  1124 pts/1    S+   02:42   0:00 grep --color=auto pppd

and it has permission: 
ls -l $(which pppd)
-rwsr-sr-x 1 root dip 378600 Jul 23  2020 /usr/sbin/pppd

**Comment by DimitriPapadopoulos** [comment]
Use `sudo`.

**Comment by julianov** [comment]
Yes I use sudo and also I'm in the root user.

**Comment by julianov** [comment]
Thanks. I alredy did it whit: 

$ sudo apt-get remove ppp
$ sudo apt-get install ppp

$  ls -l /usr/sbin/pppd
-rwsr-xr-- 1 root dip 378600 Jul 23  2020 /usr/sbin/pppd

The problem could be the version right? because Jul 23 2020 brings me here. The problem is that I am using the apt package manager and it is updated

**Comment by DimitriPapadopoulos** [comment]
I have tested openfortivpn on Ubuntu 18.04, 20.04, 22.04 over time. It works for me. I really don't know.

**Comment by DimitriPapadopoulos** [comment]
Is this a recent version of openfortivpn?

**Comment by julianov** [comment]
$openfortivpn --version
1.6.0

It's ubuntu server 18. 

Also: 

$ sudo pppd
Couldn't open the /dev/ppp device: Operation not permitted
pppd: Sorry - this system lacks PPP kernel support

but pppd is installed and it's up and running

$ ps aux | grep pppd
root 29585 0.0 0.1 13208 1124 pts/1 S+ 02:42 0:00 grep --color=auto pppd

and it has permission:
$ ls -l $(which pppd)
-rwsr-sr-x 1 root dip 378600 Jul 23 2020 /usr/sbin/pppd

**Comment by DimitriPapadopoulos** [comment]
Try a recent version (current version is 1.19.0).

**Comment by DimitriPapadopoulos** [comment]
But then I believe the answer is in this error message:
```
pppd: Sorry - this system lacks PPP kernel support
```

**Comment by DimitriPapadopoulos** [comment]
Alternatively, you can give [OpenConnect](https://gitlab.com/openconnect/openconnect) a try, as it embarks its own PPP code and does not rely on the `ppp` package or PPP support in the kernel.

**Comment by DimitriPapadopoulos** [comment]
Or try the [tun](https://github.com/adrienverge/openfortivpn/tree/tun) branch which does not depend on PPP any more.

Did any of these help?
