### ISSUE TITLE
Build an deb packages for openfortivpn

### ISSUE THREAD

**Issue by boospy** [adrienverge/openfortivpn#107]
Hello, 

i build an packages for the program. Here you can install openfortivpn from us repo:

`deb [trusted=yes] http://styrion.at/apt ./`

:+1:

**Comment by DimitriPapadopoulos** [comment]
Debian/Ubuntu packages are already in the works (#81). Do your packages add something new? If so please do send any additional changes to the package maintainer:
https://git.devuan.org/devuan-packages/openfortivpn/activity

**Comment by boospy** [comment]
Not for that. But we developed new GUI: https://github.com/adrienverge/openfortivpn/issues/116

**Comment by DimitriPapadopoulos** [comment]
The repository contains:
* `forticlient-sslvpn_*.deb` packages which contain the original FortiClient vendor software as [packaged by Rene Hadler and readily available from his blog](https://hadler.me/linux/forticlient-sslvpn-deb-packages/),
* `openfortigui_*.deb` packages which contain [OpenFortiGUI](https://github.com/theinvisible/openfortigui), an open source GUI client based on *openfortivpn*.

I understand this was a post to inform about the new *OpenFortiGUI* software. Thank you for making it available. I suggest we close the issue if that's OK with you.
