### ISSUE TITLE
Disable password Rotation/Expiration 

### ISSUE THREAD

**Issue by wildborn** [adrienverge/openfortivpn#1078]
Kindly provide a solution for issue where we can disable the password expiration option in CLI (OS: Ubuntu 20.04.5). As for now I'm using the config file to initiate the VPN and for continuous use but when password expires it has to be changed and to get rid of the changing password option refer me to the configurational changes required for stopping the service of password expiration.

![image](https://user-images.githubusercontent.com/52389620/226313804-cc68e3f9-dcb3-4386-941d-88cf9ec09259.png)

**Comment by DimitriPapadopoulos** [comment]
How is this related to openfortivpn?

**Comment by wildborn** [comment]
Actually in openfortivpn after the password expires it stops the connection of VPN and when we call the command for connecting to the network via openfortivpn it asks for onetime password which is required to be stopped as the current password gets expired. Please let me know if now it is clear?
![image](https://user-images.githubusercontent.com/52389620/226523634-30ca6e3e-60b0-420b-b4be-e29b07acad69.png) 

@avenjamin I'm talking about the expiration of the password which is similar in client and openfortivpn where I want to ask that is there any possibility that password don't gets expired.

**Comment by avenjamin** [comment]
@wildborn maybe i'm missing something, but anything to do with password expiry is configured on the FortiGate VPN server side, not the client side.

There are password expiry policies that determine how often it expires and how much warning you get etc etc.
https://community.fortinet.com/t5/FortiGate/Technical-Tip-Password-expiration-policy-for-SSL-VPN-local-user/ta-p/192723

In regards to the one-time password, that's independent to the password expiring.

Hopefully that helps a bit - but I suspect I may be missing something or not understanding the issue properly 😄

**Comment by avenjamin** [comment]
@wildborn just to add to my last reply - if users could disable the password expiry policies that would be a big security issue.

The idea of the expiry policy is an attempt to increase security and stop hackers from using old passwords to access networks.

**Comment by wildborn** [comment]
@avenjamin Thanks, the article of KB actually might solve the issue but need to test and validate. Although it is server side from where openfortivpn is dialed up. It seems there's by-default 40 days password expiration policy as after the password expires need to change the onetime password it again works for next 40 days.

actually you got max out of it please let me know if still some more understanding required.😁

**Comment by DimitriPapadopoulos** [comment]
Setting password expiry is a server thing, I still fail to understand how this is related to openfortivpn.
Changing the password is a client thing, currently not supported by openfortivpn. Merge requests are welcome.
Please clarify your question.
