### ISSUE TITLE
Authenticate with AD user

### ISSUE THREAD

**Issue by RicardoPQ-com** [adrienverge/openfortivpn#1080]
I can't find a way to authenticate a vpn gateway which requires "domain\username" login. ¿Has somebody tried it? I've google a lot and found nothing about it.

**Comment by RicardoPQ-com** [comment]
Yes, I tried with both forms. In the official client it works ok, I just write my "domain\username" in the Username field.

**Comment by DimitriPapadopoulos** [comment]
This might be a terminology issue. Perhaps what you call domain, Fortinet call **realm**.

Try `--realm=DOMAIN --user=login`.

**Comment by RicardoPQ-com** [comment]
> 

Actually I tried that too, but no luck yet

**Comment by DimitriPapadopoulos** [comment]
Have you enclosed DOMAIN\login in quotes? Like `--user=DOMAIN\login`?

**Comment by DimitriPapadopoulos** [comment]
Otherwise, it won't be possible to help without logs.

Chances are you need to authenticate on a web page with JavaScript, which is beyond the capability of a command line program. Try authenticating directly in a web browser, retrieving the cookie, and feeding it to openfortivpn.

**Comment by VVD** [comment]
For me it work without any "domain" and "realm" - just "username = USER" in config file.
Server's admin send "DOMAIN\USER".

**Comment by peterhoeg** [comment]
It's the firewall that's responsible for setting the domain (or realm) so as @VVD says, `username = some.user.name` is all that's needed. Using this scenario almost every day for multiple customers.

**Comment by DimitriPapadopoulos** [comment]
Don't new Fortinet firewalls offer 2FA which may require to open a web page with JavaScript in a browser?

I don't have access to such a Fortinet appliance myself, but I thought newer firewalls may support such configurations that a command line program cannot easily support.

**Comment by peterhoeg** [comment]
> Don’t new Fortinet firewalls offer 2FA which may require to open a web page with JavaScript in a browser?

I’ve made a note of trying that out.

**Comment by DimitriPapadopoulos** [comment]
Thanks. See also:
* https://github.com/adrienverge/openfortivpn/pull/974 added option `--cookie-on-stdin` to use an existing session cookie instead of authenticating.
* In https://github.com/adrienverge/openfortivpn/pull/1042 we decided **not** to link with [WebKitGTK](https://webkitgtk.org/) to support SAML/SSO/2FA, and instead rely on an external command/script such as https://github.com/gm-vm/openfortivpn-webview to retrieve the session cookie and pass it to openfortivpn using `--cookie-on-stdin`.

**Comment by DimitriPapadopoulos** [comment]
@RicardoPQ-com Have you tried plain `--user=username`, completely dropping `domain`?
