### ISSUE TITLE
Password with '#' in config file doesn't work

### ISSUE THREAD

**Issue by VVD** [adrienverge/openfortivpn#1081]
With config:
<pre>
host = SERVER
port = PORT
username = USER
password = PASSWORD_WITH_#_SYMBOL
persistent = 10
trusted-cert = SERT
set-dns = 0
use-resolvconf = 0
</pre>
Connection refused.
If remove/comment line with password and run `/usr/local/bin/openfortivpn -p 'PASSWORD_WITH_#_SYMBOL'` - connected without errors.

Tried different "masking" in config:
<pre>
password = "PASSWORD_WITH_#_SYMBOL"
password = 'PASSWORD_WITH_#_SYMBOL'
password = PASSWORD_WITH_\#_SYMBOL
</pre>
Nothing helped.

**Comment by DimitriPapadopoulos** [comment]
I had a look at the source code. It skips lines that **start** with `#`:
https://github.com/adrienverge/openfortivpn/blob/a24d467b70eef22b64fd53133910fed009374000/src/config.c#L206-L207
I cannot find anything else special about `#` in config files.

**Comment by DimitriPapadopoulos** [comment]
Try `openfortivpn -v -v -v` which will show you the password in clear and other details. Perhaps the config file is not read.

**Comment by VVD** [comment]
Very weird - it work now without any changes in config…
Maybe server's admin just didn't turn on this login…

It work before, then server's admin send new login and password, I edited config and start client, but it didn't work.
So I created this issue.
> I had a look at the source code. It skips lines that start with #:
This is my next step if no answer. :-D

Sorry for noise and my poor english.
