### ISSUE TITLE
openfortivpn, it close connection randomly

### ISSUE THREAD

**Issue by salvavidal** [adrienverge/openfortivpn#1083]
openfortivpn ver: 1.17.0
OS CentOS Linux release 7.9.2009 (Core)

i open "openfortivpn" and the screen show the next:

```
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/0
INFO:   Got addresses: [X.X.X.X], ns [X.X.X.X, X.X.X.X]
INFO:   Negotiation complete.
INFO:   Negotiation complete.
local  IP address 10.221.6.208
remote IP address X.X.X.X
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
INFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
INFO:   Setting ppp0 interface down.
INFO:   Restoring routes...
INFO:   Removing VPN nameservers...
Hangup (SIGHUP)
Modem hangup
Connect time 0.5 minutes.
Sent 1256 bytes, received 1256 bytes.
Connection terminated.
**ERROR:  pppd: The link was terminated by the modem hanging up.**
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

The screen show 'ERROR:  pppd: The link was terminated by the modem hanging up.' but i dont know de reason.

some times is connected 4 minutes, other times 2 or the example showed above 0.5 minutes.

perssistent mode doesnt be valid for me, because i need a connection without interruptions.

**Comment by DimitriPapadopoulos** [comment]
@salvavidal I believe the VPN server is closing the connection. Do continuous ping in the background help?
```sh
while true ; do ping -4 -c 1 -q github.com ; sleep 5 ; done
```

Also, what sort of network connection do you have? A reliable one? DO you experience network outages here and there?

**Comment by peterhoeg** [comment]
I'm inclined to say that it's either the server or the network causing the disconnect. I"m using openfortivpn almost every day for multiple customers and it's rock solid (and has been for as long as I can remember).

**Comment by DimitriPapadopoulos** [comment]
@salvavidal I have closed this issue as it lacks actionable information, but I am happy to re-open it if you can provide information that can help identify an openfortivpn problem.

**Comment by aromano-tif** [comment]
Hello,
I have the exact same issue with version 1.23.1. The only error printed is:
`**ERROR:  pppd: The link was terminated by the modem hanging up.**`
