### ISSUE TITLE
Openssl conf references missing section

### ISSUE THREAD

**Issue by ShaharTamir** [adrienverge/openfortivpn#1084]
Hello, 
I'm on ubuntu22 and I keep getting this error: 
ERROR:  SSL_CTX_new: error:0700007C:configuration file routines::openssl conf references missing section

I have tried everything I can with no success:
- configuration file is OK (compared with a friend).
- defined env variables and there is no change.
- using --insecure-ssl
- reinstalled openssl and installed openssl-pkg11
- I've looked for the openssl default file and it exists.

I don't know what else can I do. 
Please help!

**Comment by DimitriPapadopoulos** [comment]
Have you modified the OpenSSL config file?

This doesn't seem directly related to openfortivpn.

**Comment by DimitriPapadopoulos** [comment]
Perhaps the file contains subtle differences: different newline characters, non-printable characters, etc.

Have you set the `OPENSSL_CONF` variable, hence pointing to an alternative config file, and not `/etc/ssl/openssl.cnf`?

**Comment by DimitriPapadopoulos** [comment]
I am afraid I have no clue at this point, and Google searches do not find anything useful at first sight.

This has to be an OpenSSL issue, though. Have you installed multiple OpenSSL libraries on your computer? Are you using the default OpenSSL library bundled with Ubuntu 22.04?

**Comment by DimitriPapadopoulos** [comment]
@ShaharTamir Have you been able to fix this?

**Comment by ShaharTamir** [comment]
Sorry but I decided to let it go. I can handle without it for now.
Thank you for your help @DimitriPapadopoulos .
