### ISSUE TITLE
Define multiple SSL VPN destinations in Config file

### ISSUE THREAD

**Issue by thewifininja** [adrienverge/openfortivpn#1086]
Out of the box, openfortivpn can connect to multiple SSL VPN destinations simultaneously. I cannot find a way to pre-define this in a configuration file. Is this possible, or is support needed to be added?

**Comment by DimitriPapadopoulos** [comment]
> Out of the box, openfortivpn can connect to multiple SSL VPN destinations simultaneously.

By chance rather than by design.

**Comment by DimitriPapadopoulos** [comment]
What do you mean exactly by “_openfortivpn can connect to multiple SSL VPN destinations simultaneously_”?

**Comment by DimitriPapadopoulos** [comment]
Multiple instances do indeed support VPN connexions, provided routing is properly taken care of - openfortivpn may not properly handle routing.

**Comment by mrbaseman** [comment]
@thewifininja I'm glad to read that the user experience is quite good with two connections. I have put some effort into this, several years ago. Depending on the routes pushed by those two connections, it even may not be straight forward to decide, what the "right thing to do" is. The order in which vpn connections are established may be of importance, especially in scenarios of one vpn tunnel being established through another one. Another problematic situation would be two independent connections, that provide access to private networks with colliding private ip ranges.
