### ISSUE TITLE
Huge delay in VPN connection

### ISSUE THREAD

**Issue by Ud4ba** [adrienverge/openfortivpn#1087]
Hello everyone, im using openfortivpn for my work. I use it with a remote desktop client and i receive calls. Im facing an issue that the delay is very big on calls. Over 5 seconds some times.
Using the official windows client on windows fixes the problem. Its not VPN's problem or the PC.
Any ideas?

**Comment by DimitriPapadopoulos** [comment]
Hard to tell without details about the setup and logs. Besides, you wrote it's not a VPN problem.
