### ISSUE TITLE
Duplicate routes question

### ISSUE THREAD

**Issue by mjv39474** [adrienverge/openfortivpn#1088]
I connect to a centrally managed (i.e not by me) VPN. It advertises a ton of routes. Two of the routes advertised in the XML are:

    <addr ip="x.y.208.0" mask="255.255.255.240"/>
    <addr ip="x.y.208.0" mask="255.255.252.0"/>

This used to work just fine in version 1.17.

As of version 1.19, connections to the VPN are successful, but looking at the log, in version 1.19 the second range is not longer added to the routing tables. So connections to machines in the second range won't work.

I'll try to see if I can get the folks managing this thing to remove the first route, since it's a subset of the second, but it seems that the logic deciding if the route is duplicate is not quite correct. I know I could [manage this myself](https://github.com/adrienverge/openfortivpn/wiki#how-to-add-specific-routes-using-pppd), but the list of routes is long (*350+*, sigh) and I'd have to somehow maintain this.

Any thoughts on this?

**Comment by DimitriPapadopoulos** [comment]
Are you positive the behaviour changed between 1.17 and 1.19? Then this is certainly an effect of https://github.com/adrienverge/openfortivpn/pull/1009.

I don't know how to best handle this, as openfortivpn is supposed to fail with "WARN: Route to gateway exists already" without this patch.

**Comment by mjv39474** [comment]
Yes, I am positive. I use the Fedora 37 built version and when it was released for that Fedora release (1.19.0-1.fc37 is that Fedora build), it stopped doing the routing correctly.

I tried to run the new Fedora 38 and it only has 1.19 available, so I took that as a reason to go figure this out. Using the '-v -v' option I can see that the route never gets added. In version 1.17 it does complain about duplicate routes (actual duplicates) but in 1.19 it just does not add the example above at all.

In 1.17:
> DEBUG:  ip route add to x.y.208.0/255.255.255.240 dev ppp0
> DEBUG:  ip route add to x.y.91.208.0/255.255.252.0 dev ppp0

In 1.19:
> ip route add to x.y.208.0/255.255.255.240 dev ppp0

and nothing for the second route.

In 1.17 I do see (for actual identical routes)
> DEBUG:  ip route add to a.b.89.46/255.255.255.255 dev ppp0
> WARN:   Route to gateway exists already.

Which is twice in the XML:

     <addr ip="a.b.89.46" mask="255.255.255.255"/>
     <addr ip="a.b.89.46" mask="255.255.255.255"/>

Note that I don't see _any_ `Route to gateway exists already.` in the log for 1.19.

**Comment by DimitriPapadopoulos** [comment]
OK, then I guess we need to avoid setting **exactly** duplicate routes (gateway + mask), not routes with a duplicate gateway.

**Comment by DimitriPapadopoulos** [comment]
Actually, we can simply revert #1009, and change the log level from `WARN` to `INFO` since this is nothing end-users can fix.

**Comment by mjv39474** [comment]
It seems reasonable for the openfortivpn code to use the larger of the two subnets. In my case the /22 is a superset of the /28. And just because the fortigate advertises the smaller subnet first, I get in this situation.

At the same time it also seems reasonable for the fortinet to actually figure out that these ranges overlap and only advertise the larger subnet. But that seems too much common sense.

I took a very short look at the code and it's been a long time since I messed with c code, so not sure I can get you something that would do what I suggest above.

**Comment by DimitriPapadopoulos** [comment]
Does #1089 fix the issue for you? It just reverts #1009 and changes `WARN: Route to gateway exists already` to `INFO: Route to gateway exists already`.

**Comment by mjv39474** [comment]
I'll have to spend some time wiring this up for Fedora. That may take me a bit and I'm not sure I can get to that this week (I have a medical procedure scheduled; it's not for lack of interest).

**Comment by DimitriPapadopoulos** [comment]
Don't worry.

In the meantime, I will merge my changes, because applying routes in the order sent by the VPN server is what makes most sense - and is probably what the official FortiClient does any way, since the VPN server syadmins have not noticed the duplicate routes in their config.

**Comment by DimitriPapadopoulos** [comment]
You're welcome. Thank you for taking the time to report this issue.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos so you have just reverted #1009 - is a better solution still needed?

**Comment by DimitriPapadopoulos** [comment]
Hi Martin. I find the current situation good enough: we let the system handle the case where a route cannot be applied.
