### ISSUE TITLE
Integration with NetworkManager / nm-applet

### ISSUE THREAD

**Issue by ochosi** [adrienverge/openfortivpn#109]
Hi,
it'd really handy if openfortivpn could be integrated with [NetworkManager](https://wiki.gnome.org/Projects/NetworkManager) / nm-applet for
 * having an overview of the connection status
 * avoiding the CLI part for connecting (plus the sudo)
 * reconnecting
 * two-factor input box (probably brings some integration work)

Has anyone ever attempted this or is this something you'd see on your roadmap?

**Comment by Mabin-J** [comment]
I found 'network-manager-fortisslvpn' in NetworkManager. (https://wiki.gnome.org/Projects/NetworkManager)
and It use openfortivpn.

**Comment by ochosi** [comment]
Is this packaged anywhere? Couldn't find it in the debian-verse.

**Comment by Mabin-J** [comment]
Oh, I missed to understand... sorry.

**Comment by DimitriPapadopoulos** [comment]
See #81: @sandrotosi had uploaded a [Debian openfortivpn package](https://anonscm.debian.org/cgit/collab-maint/openfortivpn.git) and had started looking into nm-fortisslvpn. Not sure there has been much activity on that front lately though. You could ask him...

**Comment by sandrotosi** [comment]
i have a package ready for nm-fortisslvpn but it seems it's not able to establish a connection (i suspect it might be a permissions issue) but i havent investigated it further - if you're interested in testing/debugging this issue i'd be happy to share what i've done

**Comment by BlueCase** [comment]
I already had a chat with Lubomir Rintel who is the main maintainer of the nm project.
https://git.gnome.org/browse/network-manager-fortisslvpn

I can't use the plugin at the moment because otp not supported by the plugin.
Hope he will find time in the near future to add this feature.

**Comment by smares** [comment]
I tried the OTP branch but unfortunately, I get segfaults in openfortivpn.

`Jul 20 10:48:09 sm-ux510uwk NetworkManager[1043]: <info>  [1500540489.0834] audit: op="connection-activate" uuid="bb220e6a-0253-4788-9bf5-520a0cacdfaa" name="test" pid=2142 uid=1000 result="success"
Jul 20 10:48:09 sm-ux510uwk NetworkManager[1043]: <info>  [1500540489.0910] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: Started the VPN service, PID 2808
Jul 20 10:48:09 sm-ux510uwk NetworkManager[1043]: <info>  [1500540489.1002] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: Saw the service appear; activating connection
Jul 20 10:48:09 sm-ux510uwk nm-fortisslvpn-[2815]: GtkDialog mapped without a transient parent. This is discouraged.
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.4602] keyfile: update /etc/NetworkManager/system-connections/test (bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test")
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.4834] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN connection: (ConnectInteractive) reply received
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.4886] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN plugin: state changed: starting (3)
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: WARN:   Bad key in config file: "otp".
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: WARN:   Could not load config file "/bb220e6a-0253-4788-9bf5-520a0cacdfaa.config" (unknown).
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: INFO:   Connected to gateway.
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: 2factor authentication token:
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: ERROR:  Could not authenticate to gateway (No cookie given).
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: INFO:   Closed connection to gateway.
Jul 20 10:48:19 sm-ux510uwk kernel: [  116.316865] show_signal_msg: 22 callbacks suppressed
Jul 20 10:48:19 sm-ux510uwk kernel: [  116.316876] openfortivpn[2823]: segfault at 7fffd8000000 ip 00007fd602300d22 sp 00007fffdbd1cdc0 error 4 in libc-2.24.so[7fd60227a000+1be000]
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: INFO:   Logged out.
Jul 20 10:48:19 sm-ux510uwk systemd[1571]: Starting Notification regarding a crash report...
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <warn>  [1500540499.9719] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN plugin: failed: connect-failed (1)
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.9719] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN plugin: state changed: stopping (5)
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.9726] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN plugin: state changed: stopped (6)
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.9732] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN plugin: state change reason: unknown (0)
Jul 20 10:48:19 sm-ux510uwk NetworkManager[1043]: <info>  [1500540499.9738] vpn-connection[0x564f366ae1a0,bb220e6a-0253-4788-9bf5-520a0cacdfaa,"test",0]: VPN service disappeared
Jul 20 10:48:20 sm-ux510uwk systemd[1571]: Started Notification regarding a crash report.`

**Comment by mrbaseman** [comment]
Lubomir Rintel has recently submitted a patch for the otp issue which is still in the queue with a bunch of other changes: https://github.com/adrienverge/openfortivpn/pull/151/commits/220e25a90c74d90dc7e92aac00a25599f5fc1892

**Comment by mrbaseman** [comment]
the fix for `WARN:   Bad key in config file: "otp".` has been landed on current master. However, I'm not sure if the segfault is in any way related to the missing support for the config option of otp

**Comment by ochosi** [comment]
@sandrotosi Wanna share the package you created?

**Comment by ochosi** [comment]
Just as an additional note: I managed to install the rpm packages from Fedora in Ubuntu via alien and I can now add and configure the VPN connection with FortiSSL.

However I never get the second two-factor challenge, so I can't connect successfully. Is the two-factor auth not implemented in the network-manager plugin?

**Comment by mrbaseman** [comment]
The maintainer of the network manager plugin has added the 2 factor support very recently to [this branch](https://git.gnome.org/browse/network-manager-fortisslvpn/log/?h=lr/otp), and landed https://github.com/adrienverge/openfortivpn/commit/1e204dfae0a5ce95e9157bb75ad7125e9452dcda on the master branch of openfortivpn, which he also needs to pass the one time password from the plugin ot openfortivpn. So, it could well be that the packages that you have tried out don't yet contain the otp support

**Comment by BlueCase** [comment]
Downloaded and compiled network-manager-fortisslvpn-1.2.6.
NM OTP switch seems to work in this version. But now I have a problem with openfortivpn self.
See my last comment in #104

**Comment by DimitriPapadopoulos** [comment]
@BlueCase Thank you for coming back to us. I guess we can close this ticket. Please open a new ticket about the `--otp` issue.
