### ISSUE TITLE
Does not work with ppp 2.5.0

### ISSUE THREAD

**Issue by aminvakil** [adrienverge/openfortivpn#1114]
After upgrading ppp to 2.5.0, openfortivpn fails with this error:
`Peer refused to agree to his IP address`.

I have tried rebuilding openfortivpn with ppp 2.5.0, but still openfortivpn has the same error, and I can also confirm my vpn server works downgrading ppp to 2.4.9 .

**Comment by DimitriPapadopoulos** [comment]
Which exact version of openfortivpn? Have you tried branche `master` with the fix from https://github.com/adrienverge/openfortivpn/pull/1111?

**Comment by aminvakil** [comment]
Oops, I forgot to mention openfortivpn version.

`openfortivpn 1.20.3`

**Comment by DimitriPapadopoulos** [comment]
Can you give https://github.com/adrienverge/openfortivpn/pull/1111 a try? If it works for you too, we'll release a new version with this fix.

**Comment by aminvakil** [comment]
> Can you give #1111 a try? If it works for you too, we'll release a new version with this fix.

Sure, I'll try in a couple of hours.

**Comment by aminvakil** [comment]
OK, I just tested and it works! Thanks and sorry I didn't search issues through and find #1111.

**Comment by DimitriPapadopoulos** [comment]
No worries, and thank you for testing. I'll prepare a new release.

**Comment by namaiiee2222** [comment]
we have this issue with version 1.20.5 with version ppp 2.5.0. Any update to fix it?

**Comment by DimitriPapadopoulos** [comment]
Pull requests welcome.

**Comment by wapmorgan** [comment]
Any updates on this? Got 2.5.0 in ubuntu 24.10, there is no way backward!

**Comment by DimitriPapadopoulos** [comment]
@wapmorgan The update is that this issue is closed because it has been fixed. Which exacts version of openfortivpn ships with Ubuntu 24.10?

**Comment by wapmorgan** [comment]
@DimitriPapadopoulos 1.22.1-1 in latest 24.10 (oracular) https://packages.ubuntu.com/search?keywords=openfortivpn&searchon=names&suite=oracular&section=all

**Comment by DimitriPapadopoulos** [comment]
It's not the latest openfortivpn version, it should have been updated together with pppd. This is an Ubuntu bug.

**Comment by wapmorgan** [comment]
Which one is latest? There's a 1.22.1 in this repo the latest one

**Comment by DimitriPapadopoulos** [comment]
Try building from the sources if Ubuntu insist on shipping old versions.

**Comment by wapmorgan** [comment]
this on openfortivpn 1.21.0 (ubuntu 24.04):
```
INFO:   Connected to gateway.
DEBUG:  http_send:
POST /remote/logincheck HTTP/1.1
Host: MY_FORTI_HOSTNAME
User-Agent: Mozilla/5.0 SV1
Accept: */*
Accept-Encoding: gzip, deflate, br
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
Content-Type: application/x-www-form-urlencoded
Cookie: 
Content-Length: 61
...
DEBUG:  http_receive:
HTTP/1.1 200 OK
```

this on openfortivpn 1.22.1 (ubuntu 24.10):

**Comment by wapmorgan** [comment]
> Try building from the sources if Ubuntu insist on shipping old versions

Which one is the latest version?
- https://repology.org/project/openfortivpn/versions - 1.22.1
- https://github.com/adrienverge/openfortivpn/tags - 1.22.1 (and no commits after 1.22.1)

**Comment by Neustradamus** [comment]
For information, PPP 2.5.2 has been released (2024-12-31):
- https://github.com/ppp-project/ppp/releases/tag/v2.5.2
