### ISSUE TITLE
publish_entry SCDSet() failed: Success!

### ISSUE THREAD

**Issue by newnight** [adrienverge/openfortivpn#1117]
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Tue Jun 20 11:16:09 2023 : publish_entry SCDSet() failed: Success!
Tue Jun 20 11:16:09 2023 : publish_entry SCDSet() failed: Success!
Tue Jun 20 11:16:09 2023 : Using interface ppp0
Tue Jun 20 11:16:09 2023 : Connect: ppp0 <--> /dev/ttys007
......

MacOS 13.4 and openfortivpn's version is 1.20.4

**Comment by DimitriPapadopoulos** [comment]
I have no clue about `publish_entry SCDSet() failed: Success!`? What is the actual problem?

**Comment by molexa** [comment]
Probably the same issue as #1118
