### ISSUE TITLE
macOS brew service problem in 1.20.4

### ISSUE THREAD

**Issue by ohanedan** [adrienverge/openfortivpn#1118]
Hello,
I updated openfortivpn using brew from 1.20.3 to 1.20.4 today. 

I can run it from the terminal without any problems using following command.
sudo /usr/local/opt/openfortivpn/bin/openfortivpn -c /usr/local/etc/openfortivpn/openfortivpn/config

but if I want to start as a service using brew, I get the log below and it closes. (v1.20.3 was working fine.)

```
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Wed Jun 21 09:21:00 2023 : publish_entry SCDSet() failed: Success!
Wed Jun 21 09:21:00 2023 : publish_entry SCDSet() failed: Success!
Wed Jun 21 09:21:00 2023 : Using interface ppp0
Wed Jun 21 09:21:00 2023 : Connect: ppp0 <--> /dev/ttys000
INFO:   Got addresses: [10.212.100.51], ns [10.5.5.20, 10.5.5.21], ns_suffix [xyz.local]
Wed Jun 21 09:21:01 2023 : local  IP address 10.212.100.51
Wed Jun 21 09:21:01 2023 : remote IP address REDACTED
Wed Jun 21 09:21:01 2023 : primary   DNS address 10.5.5.20
Wed Jun 21 09:21:01 2023 : secondary DNS address 10.5.5.21
Wed Jun 21 09:21:01 2023 : Committed PPP store
Wed Jun 21 09:21:01 2023 : Committed PPP store
INFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
WARN:   Could not get current default route (Parsing /proc/net/route failed).
WARN:   Protecting tunnel route has failed. But this can be working except for some cases.
Wed Jun 21 09:21:25 2023 : Hangup (SIGHUP)
Wed Jun 21 09:21:25 2023 : Modem hangup
Wed Jun 21 09:21:25 2023 : Connection terminated.
Wed Jun 21 09:21:25 2023 : LCP close (User request).
Wed Jun 21 09:21:25 2023 : Connect time 0.5 minutes.
Wed Jun 21 09:21:25 2023 : Sent 6174 bytes, received 3226 bytes.
INFO:   pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

Any idea?

**Comment by DimitriPapadopoulos** [comment]
Is the service started as user root or a different user? Have you asked the brew maitainers?

**Comment by ohanedan** [comment]
It started as root user. I haven't asked them because I checked changes in brew repo. They only changed the version to new.
https://github.com/Homebrew/homebrew-core/commit/938b7bccb431a498ef6d7e1f7e7b311ea860ded8

**Comment by ohanedan** [comment]
I have checked the issue in more detail, and even when I run it from the CLI, I occasionally encounter the same error. It seems like there might be a race condition. I have looked into verbose mode, but it is challenging to deduce anything meaningful from the hashes. I'll download and check with version 1.20.3 again.

**Comment by DimitriPapadopoulos** [comment]
The only change in 1.20.4 is indeed the addition of `ipcp-accept-remote` which is supposed to fix the `Peer refused to agree to his IP address` error with pppd 2.5.0. So that has to be the change that triggers the problem. Not sure what to do about it though.

**Comment by DimitriPapadopoulos** [comment]
Verbose `pppd` logs (with/without `ipcp-accept-remote`) might help understand why `pppd` fails.

**Comment by DimitriPapadopoulos** [comment]
There's also the option of not using `pppd` at all (experimental [_tun_](https://github.com/adrienverge/openfortivpn/tree/tun) branch).

**Comment by aparajita** [comment]
Definitely seems to be a race condition, because it works sometimes and fails other times. When it gets stuck and I terminate, I see this warning:

> WARN:   Could not get current default route (Parsing /proc/net/route failed).
> WARN:   Protecting tunnel route has failed. But this can be working except for some cases.

**Comment by foss4ever** [comment]
> Definitely seems to be a race condition, because it works sometimes and fails other times. When it gets stuck, the output always stops at the second `Committed PPP store`. When I terminate, I see this warning:
> 
> > WARN:   Could not get current default route (Parsing /proc/net/route failed).
> > WARN:   Protecting tunnel route has failed. But this can be working except for some cases.

I see this exact same issue. And it has gone away after downgrading to the second-newest release of openfortivpn in homebrew.

**Comment by ehaupt** [comment]
I'm experiencing the same issue. This is for anyone looking to downgrade:

```sh
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/f092f4c9ab02d535b9444bf90656fd0955c51e6b/Formula/openfortivpn.rb
brew reinstall ./openfortivpn.rb
brew pin openfortivpn
```

**Comment by DimitriPapadopoulos** [comment]
With `ipcp-accept-remote` pppd will accept the peer's idea of its (remote) IP address, instead of `169.254.2.1`. Perhaps the remote IP address suggested by the peer collides with a local LAN. Unfortunately, `ipcp-accept-remote` appears to be required with pppd 2.5.0, at least on Linux.

As a short term solution, I suggest we disable this change on Apple machines.

**Comment by ohanedan** [comment]
According to docs, Is it ok to use ipcp-accept-remote and ipcp-accept-local at the same time? Maybe we should add new config and choosing between remote and local with using it.

**Comment by DimitriPapadopoulos** [comment]
Why would using both be a problem? One option refers to the local address, the other to the remote address.

**Comment by ohanedan** [comment]
> Why would using both be a problem? One option refers to the local address, the other to the remote address.

You're right about that. sorry for the confusion.

**Comment by DimitriPapadopoulos** [comment]
I am nevertheless open to all ideas, even if I do not understand them at first sight. What happens if you keep `ipcp-accept-remote` but remove `ipcp-accept-local`? Does it work?

I am asking because we could possibly change  `ipcp-accept-local` into `noipdefault`:
```
# Disables the default behaviour when no local IP address is specified,
# which is to determine (if possible) the local IP address from the
# hostname. With this option, the peer will have to supply the local IP
# address during IPCP negotiation (unless it specified explicitly on the
# command line or in an options file).
#noipdefault
```

**Comment by DimitriPapadopoulos** [comment]
Could you test #1119? Does it work for you?

**Comment by aparajita** [comment]
> Unfortunately, `ipcp-accept-remote` appears to be required with pppd 2.5.0, at least on Linux. As a short term solution, I suggest we disable this change on Apple machines.

Since the problem is only occurring on macOS, and this is the cause of the problem, that would seem to be the best solution.

**Comment by psevdaisthisi** [comment]
> Could you test #1119? Does it work for you?

Thank you, I was having the same problem and can confirm that #1119 works fine.

```
Mac Mini (M2 Pro)
macOS Ventura 13.4.1
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

**Comment by joyfulrabbit** [comment]
Can confirm I'm seeing this issue. MBP 13" M1  / OSX 13.4 (22F66)

**Comment by MohamadKh75** [comment]
This issue was recreated in the latest (1.21.0)

**Comment by DimitriPapadopoulos** [comment]
This ticket is closed, you should create a new one.

1. Packagers need to build openfortivpn with **`configure --enable-legacy-pppd`** when targeting platforms with ppp < 2.5.0. I don't know how to reach them.
2. End-users can work around this issue with option **`openfortivpn --pppd-accept-remote=0`**.

**Comment by nickegli** [comment]
> > Definitely seems to be a race condition, because it works sometimes and fails other times. When it gets stuck, the output always stops at the second `Committed PPP store`. When I terminate, I see this warning:
> > > WARN:   Could not get current default route (Parsing /proc/net/route failed).
> > > WARN:   Protecting tunnel route has failed. But this can be working except for some cases.
> 
> I see this exact same issue. And it has gone away after downgrading to the second-newest release of openfortivpn in homebrew.

how did you go about downgrading through homebrew as no older versions seem to be available?

**Comment by grishy** [comment]
@DimitriPapadopoulos `--pppd-accept-remote=0` works fine

**Comment by DimitriPapadopoulos** [comment]
I fixed the openfortivpn formula in #1111. I would have expected package to be rebuilt to take into account this fix. If so, ` --pppd-accept-remote=0` should not be needed. If not, packages might be rebuilt only with the next release of openfortivpn.

**Comment by pkotronis** [comment]
Hi to everyone
The problem seems to reappear in Sonoma 14.2 and openfortivpn 1.21.0 I get the following error: 
Thu Dec 14 16:06:17 2023 : Committed PPP store
Thu Dec 14 16:06:17 2023 : Committed PPP store
^CINFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
WARN:   Could not get current default route (Parsing /proc/net/route failed).
WARN:   Protecting tunnel route has failed. But this can be working except for some cases.
WARN:   Adding route table is incomplete. Please check route table.
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
INFO:   Setting ppp0 interface down.
INFO:   Restoring routes...
INFO:   Removing VPN nameservers...
Thu Dec 14 16:06:20 2023 : Hangup (SIGHUP)
Thu Dec 14 16:06:20 2023 : Modem hangup
Thu Dec 14 16:06:20 2023 : Connection terminated.
Thu Dec 14 16:06:20 2023 : LCP close (User request).
Thu Dec 14 16:06:20 2023 : Connect time 0.1 minutes.
Thu Dec 14 16:06:20 2023 : Sent 0 bytes, received 0 bytes.
INFO:   pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

Any ideas to solve it ?
Thanks in advance

**Comment by kebrahimpour** [comment]
I am experiencing same issues on my Apple M1 Max/ 14.2.1
I am using openfortivpn 1.21.0 with --pppd-accept-remote=0:

INFO:   Connected to gateway.
Two-factor authentication token:
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Mon Feb 12 15:39:35 2024 : publish_entry SCDSet() failed: Success!
Mon Feb 12 15:39:35 2024 : publish_entry SCDSet() failed: Success!
Mon Feb 12 15:39:35 2024 : Using interface ppp0
Mon Feb 12 15:39:35 2024 : Connect: ppp0 <--> /dev/ttys001

**Comment by nickegli** [comment]
Hi @kebrahimpour am I misreading something? Based on the logs you've provided despite the initial fails the connection can be established successfully?

**Comment by DimitriPapadopoulos** [comment]
@kebrahimpour I doubt this is the same issue, besides this ticket is closed.
