### ISSUE TITLE
Arch Linux link is dead

### ISSUE THREAD

**Issue by raffaem** [adrienverge/openfortivpn#1125]
The link to the Arch Linux package [here](https://github.com/adrienverge/openfortivpn#installing-existing-packages) is dead.

Don't know what happened to it.

There seems to be the git version on the AUR tough.

**Comment by DimitriPapadopoulos** [comment]
It was there yesterday. Perhaps a temporary problem?

**Comment by DimitriPapadopoulos** [comment]
Oh, it moved from https://www.archlinux.org/packages/community/ to https://archlinux.org/packages/extra/.
