### ISSUE TITLE
how to use fotitoken moblie token code about openfortivpn

### ISSUE THREAD

**Issue by kaixa** [adrienverge/openfortivpn#113]
I can't connet the server use openfortivpn use username and password, I think the moblie token code isn't input ,but I don't konw  how to use?

**Comment by DimitriPapadopoulos** [comment]
It works for me using an ActivID token to connect to a corporate FortiGate VPN server.

I your case it would help if you could describe what you have tried. Have you tried with the vendor FortiClient SSL VPN client?

**Comment by mrbaseman** [comment]
If the server expects a mobile token, openfortivpn should ask you interactively. I have both, client certificates and mobile tokens. I this case it first asks me for the PEM passphrase, and then there is a prompt `2factor authentication token:` and your input is not shown on the screen. Some time ago there was an issue with the colors in  terminals with light background. Some messages were printed white on light gray which made it difficult to read, but this is fixed on the current master. Username may come from the command line or from the config file, the password may be specified on the command line (not recommended), in the config file (also not best practice), or you are asked interactively for it (in that case this is the first thing you are asked for).

**Comment by DimitriPapadopoulos** [comment]
I guess it really depends on how the server is configured. In my case I have to enter a composite password looking like as `01234567989898` which would be the concatenation of:

- a one-time password provided by the ActivID token, `01234567` in the above example,
- a personal immutable code, `989898` in the above example.

So it would help if you could give give details on your setup: Linux or MacOS, perhaps a screen capture of what you're attempting, etc.

**Comment by DimitriPapadopoulos** [comment]
@kaixa Could you provide details? Does this still not work for you?
