### ISSUE TITLE
Gateway certificate validation failed, and the certificate digest is not in the local whitelist. Since updated server certificate

### ISSUE THREAD

**Issue by xflamed** [adrienverge/openfortivpn#1133]
This morning our certificate got updated and now when trying to connect i get this error:
ERROR:  Gateway certificate validation failed, and the certificate digest is not in the local whitelist.
The new certificate is not self signed, it is signed by a proper CA.
Connecting works with the IOS app on a M2 macbook
Is there a way to allow it to the local whitelist so that all my colleagues dont get that message anymore?

**Comment by DimitriPapadopoulos** [comment]
The new certificate is signed by an unknown CA, lacking intermediate certificates, or something similar. Web browsers (and perhaps the iOS app) are more lenient.

Any way, `openfortivpn --help` suggests:
```
  --trusted-cert=<digest>       Trust a given gateway. If classical SSL
                                certificate validation fails, the gateway
                                certificate will be matched against this value.
                                <digest> is the X509 certificate's sha256 sum.
                                This option can be used multiple times to trust
                                several certificates.
```
