### ISSUE TITLE
ubuntu 16 - crash due to buffer overrun in ipv4.c

### ISSUE THREAD

**Issue by kam2630** [adrienverge/openfortivpn#114]
During modify of resolv.conf in routine ipv4_add_nameservers_to_resolv_conf()  openfortivpn crashes. 

Inspecting code shows up that the length for ns1 and ns2 strings are too short with 27 bytes for my configuration.

"nameserver " = (11 bytes)  + "111.111.111.111" = (15 bytes) + \n (1 Byte) + "\0" (1 Byte) = 28 bytes total
see line (474,478)

please increase length for both ns1 and ns2 at least to 28 bytes

**Comment by DimitriPapadopoulos** [comment]
The definitions of ns1 and ns2 are:
```
	char ns1[27], ns2[27]; // 11 + 15 + 1
```
Then these variables are assigned here:
```
	strcpy(ns1, "nameserver ");
	strncat(ns1, inet_ntoa(tunnel->ipv4.ns1_addr), 15);
```
```
		strcpy(ns2, "nameserver ");
		strncat(ns2, inet_ntoa(tunnel->ipv4.ns2_addr), 15);
```
The length of `"nameserver "` is 11, then `strncat()` appends a string of 15 characters **at most**, and if we take into account the final `'\0'` that's indeed: 11 + 15 + 1 characters. Unless I'm missing something, the error has to be elsewhere.

**Comment by kam2630** [comment]
Hi Dimitri
    Indeed you miss something, a few lines below the assignment the
      source shows up with
    
    strcat(ns1, "\n");  and strcat(ns2, "\n");
    before writing to resolv.conf
    
    which will add an additional char and a final '\0' growing the
      string to a length of 28 bytes.
    rgds,
    Karl
    
    
    
    
    
    Am 2017-04-26 um 18:18 schrieb Dimitri
      Papadopoulos Orfanos:
    
    
      The definitions of ns1 and ns2 are:
      	char ns1[27], ns2[27]; // 11 + 15 + 1

      Then these variables are assigned here:
      	strcpy(ns1, "nameserver ");
	strncat(ns1, inet_ntoa(tunnel->ipv4.ns1_addr), 15);

      		strcpy(ns2, "nameserver ");
		strncat(ns2, inet_ntoa(tunnel->ipv4.ns2_addr), 15);

      The length of "nameserver " is 11, then strncat()
        appends a string of 15 characters at most, and
        if we take into account the final '\0' that's
        indeed: 11 + 15 + 1 characters. Unless I'm missing something,
        the error has to be elsewhere.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adrienverge/openfortivpn","title":"adrienverge/openfortivpn","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adrienverge/openfortivpn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DimitriPapadopoulos in #114: The definitions of ns1 and ns2 are:\r\n```\r\n\tchar ns1[27], ns2[27]; // 11 + 15 + 1\r\n```\r\nThen these variables are assigned here:\r\n```\r\n\tstrcpy(ns1, \"nameserver \");\r\n\tstrncat(ns1, inet_ntoa(tunnel-\u003eipv4.ns1_addr), 15);\r\n```\r\n```\r\n\t\tstrcpy(ns2, \"nameserver \");\r\n\t\tstrncat(ns2, inet_ntoa(tunnel-\u003eipv4.ns2_addr), 15);\r\n```\r\nThe length of `\"nameserver \"` is 11, then `strncat()` appends a string of 15 characters **at most**, and if we take into account the final `'\\0'` that's indeed: 11 + 15 + 1 characters. Unless I'm missing something, the error has to be elsewhere."}],"action":{"name":"View Issue","url":"https://github.com/adrienverge/openfortivpn/issues/114#issuecomment-297463881"}}}
    
    
    -- 
Mit freundlichen Grüßen

DebugProfi
Hard- und Softwareentwicklung
Mautweg 33
A-2630 Ternitz

Tel.: +43.(0)720.505.508
Fax.: +43.(0)720.505.508.9

Web:   www.debugprofi.at
EMail: office@debugprofi.at

**Comment by DimitriPapadopoulos** [comment]
Right. Perhaps that could explain other memory corruption issues (#103) - or not.
