### ISSUE TITLE
Peer refuses IP with Openfortivpn 1.20.5

### ISSUE THREAD

**Issue by juanscr** [adrienverge/openfortivpn#1140]
In my latest upgrade of `openfortivpn`, I am not able to connect to my corprate VPN anymore. The logs when I try to connect are the following:

![image](https://github.com/adrienverge/openfortivpn/assets/31258166/7d5279aa-c3c6-4b93-9d7b-a3a4b46a226f)

I have tinkered with the flags I currently use in my configuration to see if any of them is related to the issue but I am not able to make it work with any possible combination.

Downgrading to `1.20.4` makes it work instantly.

## Additional Information
- OS: Arch Linux
- Kernel: Linux `6.5.5-arch1-1`
- `openfortivpn`: 1.20.5
- `pppd`: 2.5.0
- For network, I use `NetworkManger` with `systemd-resolved` for DNS resolution and caching.

**Comment by Theos48** [comment]
sudo openfortivpn --pppd-accept-remote

**Comment by juanscr** [comment]
Yup... You're right, using that command makes it work. Thanks! Sorry for any inconvience
