### ISSUE TITLE
openfortivpn stops working after 1 hour

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [adrienverge/openfortivpn#1145]
Hi ,
I am using openfortivpn 1.19.0 but for some reason after around 1 hour the connection hangs and stops.
The log messages remain the same, not giving any sign of exiting or error.

```
brun0@b:~
VPN account password:
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/3
INFO:   Got addresses: [10.69.100.4], ns [10.69.70.3, 10.69.70.4], ns_suffix [<company>.int]
INFO:   Negotiation complete.
INFO:   Negotiation complete.
local  IP address 10.69.100.4
remote IP address 169.254.2.1
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

The connection remains active for around 1h and then stops but theres no error message.

I am using Debian 12

**Comment by DimitriPapadopoulos** [comment]
See https://github.com/adrienverge/openfortivpn/wiki#debugging-openfortivpn.

**Comment by BrunoTeixeira1996** [comment]
Adding to the above log output. Here is the result of `ip route`.
![image](https://github.com/adrienverge/openfortivpn/assets/12052283/5b114900-564a-4a5a-9534-00e90ccd467d)
I think this has duplicates interfaces for some reason

**Comment by DimitriPapadopoulos** [comment]
Something must be happening when you lose connectivity. Something else might overwrite network parameters.

What do you see in system logs when you lose connectivity?

**Comment by BrunoTeixeira1996** [comment]
I realy think its network managers fault for some reason.
In the systems logs everything is normal and looks like everything is working. But that is not the case

**Comment by DimitriPapadopoulos** [comment]
Yes, it probably has to do with the network manager. To tell the truth, openfortivpn does not do the right thing when directly modifying `/etc/resolv.conf`. Having `resolvconf` installed might help.

**Comment by BrunoTeixeira1996** [comment]
I can confirm I don't have `resolvconf` installed
```
$ resolvconf
bash: resolvconf: command not found
```
Do you think that might help? I can install and test and come back with further information if that worked or no

**Comment by DimitriPapadopoulos** [comment]
It may help **if** resolvconf does the right thing.

**Comment by BrunoTeixeira1996** [comment]
> It may help **if** resolvconf does the right thing.
By installing resolvconf I have the following error, wut

```
brun0@hhh:~
$ sudo apt install resolvconf
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  resolvconf
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 55.6 kB of archives.
After this operation, 184 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 resolvconf all 1.91+nmu1 [55.6 kB]
Fetched 55.6 kB in 0s (516 kB/s)    
Preconfiguring packages ...
Selecting previously unselected package resolvconf.
(Reading database ... 189751 files and directories currently installed.)
Preparing to unpack .../resolvconf_1.91+nmu1_all.deb ...
Unpacking resolvconf (1.91+nmu1) ...
Setting up resolvconf (1.91+nmu1) ...
Created symlink /etc/systemd/system/sysinit.target.wants/resolvconf.service → /lib/systemd/system/resolvconf.service.
Created symlink /etc/systemd/system/systemd-resolved.service.wants/resolvconf-pull-resolved.path → /lib/systemd/system/resolvconf-pull-resolved.path.
Unit /lib/systemd/system/resolvconf-pull-resolved.path is added as a dependency to a non-existent unit systemd-resolved.service.
Created symlink /etc/systemd/system/systemd-resolved.service.wants/resolvconf-pull-resolved.service → /lib/systemd/system/resolvconf-pull-resolved.service.
Unit /lib/systemd/system/resolvconf-pull-resolved.service is added as a dependency to a non-existent unit systemd-resolved.service.
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xeu dnsmasq.service" for details.
invoke-rc.d: initscript dnsmasq, action "restart" failed.
× dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
     Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-10-24 16:52:52 WEST; 4ms ago
   Duration: 2h 29min 19.723s
    Process: 11364 ExecStartPre=/etc/init.d/dnsmasq checkconfig (code=exited, status=0/SUCCESS)
    Process: 11374 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
        CPU: 20ms

Oct 24 16:52:52 L8-BTeixeira systemd[1]: Starting dnsmasq.service - dnsmasq - A lightweight DH
CP and caching DNS server...
Oct 24 16:52:52 L8-BTeixeira dnsmasq[11374]: dnsmasq: failed to create listening socket for po
rt 53: Address already in use
Oct 24 16:52:52 L8-BTeixeira dnsmasq[11374]: failed to create listening socket for port 53: Ad
dress already in use
Oct 24 16:52:52 L8-BTeixeira dnsmasq[11374]: FAILED to start up
Oct 24 16:52:52 L8-BTeixeira systemd[1]: dnsmasq.service: Control process exited, code=exited,
 status=2/INVALIDARGUMENT
Oct 24 16:52:52 L8-BTeixeira systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Oct 24 16:52:52 L8-BTeixeira systemd[1]: Failed to start dnsmasq.service - dnsmasq - A lightwe
ight DHCP and caching DNS server.
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for resolvconf (1.91+nmu1) ...
brun0@hhh:~
$ resolvconf
bash: resolvconf: command not found
```

**Comment by BrunoTeixeira1996** [comment]
> There are multiple variants of resolvconf:
> 
> * [resolvconf](https://salsa.debian.org/debian/resolvconf) – initial Debian implementation
> * [openresolv](https://roy.marples.name/projects/openresolv) ([GitHub](https://github.com/NetworkConfiguration/openresolv)) – compatible implementation
> * [systemd](https://www.freedesktop.org/software/systemd/man/latest/resolvectl.html) `resolvectl` alias
> 
> You have installed the first one, which might be a good idea as you seem to run Debian. Not sure about the error messages you see. Have they been fixed [maemo-leste/libicd-network-ipv4#3](https://github.com/maemo-leste/libicd-network-ipv4/pull/3)? Hasn't the fix been propagated to your distribution?

I dont remember why i was using dnsmasq to be fair. I think I wanted to access some internal services by name but I dont use that anymore so I just removed it and installed resolvconf.
Tomorrow Ill test if the openfortivpn works fine and If yes we can close this

**Comment by BrunoTeixeira1996** [comment]
@DimitriPapadopoulos After around 4 hours of using `openfortivpn` the connection remained fine. I realy think the problem was the dnsmasq and the unused resolvconf. Ill let the vpn today for around 5+ hours and see the final result

**Comment by BrunoTeixeira1996** [comment]
@DimitriPapadopoulos I can confirm that this is working as intended!
