### ISSUE TITLE
Keep connection up in background

### ISSUE THREAD

**Issue by kleuf** [adrienverge/openfortivpn#115]
hi there, is there a way that after you run openfortivpn command, it keeps on running in the background?
it starts the tunnel on my console and then when i do anything it terminates the connection.

any help will be appreciated.

Thanks

**Comment by DimitriPapadopoulos** [comment]
If I put the _openfortivpn_ process in the background (Ctrl+Z and bg) then kill the console, I don't see the connection terminated. What do you mean by _when i do anything it terminates the connection_? What do you do exactly?

**Comment by DimitriPapadopoulos** [comment]
Hopefully the above has answered your questions. I'll close the issue for now.
