### ISSUE TITLE
openfortiGUI now available for Ubuntu

### ISSUE THREAD

**Issue by boospy** [adrienverge/openfortivpn#116]
We developed a brand new GUI for Openfortivpn. Longtimetest with Ubuntu and Kubuntu 16.04. You can install it with
```
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2FAB19E7CCB7F415
echo "deb http://styrion.at/apt/ ./" > /etc/apt/sources.list.d/styrion.list
apt install openfortigui
```
Features: 

- QT5 Gui
- Interface for Uservpn's
- Interface for Gloablvpn's (for rollouts, for example foreman/puppet)
- Trayicon
- VPN-Connectgroups
- Multible Connections (tested to about 30 VPN's at the same time with one click)
- Certificate Integration
- ...

Source code will come soon. Thanks to the DEV Rene Hadler.

**Comment by ion-storm** [comment]
nice, gonna have to try this after work.  Any screenshots? Also does 2FA work?

**Comment by boospy** [comment]
Not 2FA, but with Clientcert. 
![screenshot_20170426_193005](https://cloud.githubusercontent.com/assets/7432752/25448472/e56ae878-2ab8-11e7-960e-ecd888002226.png)
![screenshot_20170426_193124](https://cloud.githubusercontent.com/assets/7432752/25448475/e56ee310-2ab8-11e7-963e-6384bf723b8f.png)
![screenshot_20170426_193158](https://cloud.githubusercontent.com/assets/7432752/25448474/e56be2be-2ab8-11e7-96aa-e8a542ca6f13.png)
![screenshot_20170426_193225](https://cloud.githubusercontent.com/assets/7432752/25448473/e56bc95a-2ab8-11e7-9054-ffc33e88e208.png)

**Comment by adrienverge** [comment]
@boospy Nice, good job!

But this is not an issue, so I'll close this ;)

**Comment by boospy** [comment]
https://github.com/theinvisible/openfortigui
https://hadler.me/linux/openfortigui/
