### ISSUE TITLE
OpenFortiVPN Client Won't Open With Fedora 39

### ISSUE THREAD

**Issue by Sp3ctroR3tro** [adrienverge/openfortivpn#1162]
I just updated to Fedora 39 while using version 1.19.0 of openfortivpn and since then I haven't been able to connect. When running I get the following error:
`INFO:   Negotiation complete. Peer refused to agree to his IP address`. I have seen other posts regarding this issue and have tried running `pppd ipcp-accept-remote` and `ipcp-accept-local` to resolve the issue and neither one seems to work. 

I have tried, re-installation of openforti, kernel switching, and attempted downgrading of ppp from 2.5.0. To this point nothing has worked so far.

**Comment by DimitriPapadopoulos** [comment]
Either use pppd < 2.5.0 or use the latest openfortivpn version.

**Comment by Sp3ctroR3tro** [comment]
When looking at the packages for fedora it appears that I am using the most recent version of openforticlient and for fedora 29 it appears that I can’t downgrade past 2.5.0.

**Comment by DimitriPapadopoulos** [comment]
If you cannot downgrade pppd, use the latest version of openfortivpn (1.21).

**Comment by DimitriPapadopoulos** [comment]
Alternatively, find a way to pass option `ipcp-accept-remote` to `pppd`. Typically, you would have to add it to a file under `/etc/ppp` or something similar.

**Comment by Sp3ctroR3tro** [comment]
I was able to edit the options file to add the recommend entry and was able to connect again.

**Comment by adrienverge** [comment]
I just changed the issue title (Fedora 29 → Fedora 39).

**Comment by woprandi** [comment]
Connection now works on F39 with specified options (thanks !) but I cannot reach any IP inside

**Comment by yakupkaya** [comment]
> Connection now works on F39 with specified options (thanks !) but I cannot reach any IP inside remote network

Same here. After the option "ipcp-accept-remote", I can connect. I even see the correct routes are added. But I cannot access the IP addresses.

**Comment by woprandi** [comment]
@yakupkaya You can use openconnect as a alternative client to use at least until this issue is resolved.

**Comment by yakupkaya** [comment]
> @yakupkaya You can use openconnect as a alternative client to use at least until this issue is resolved.

Sure, I can try that. Thank you very much!

**Comment by jcesclapez** [comment]
> Connection now works on F39 with specified options (thanks !) but I cannot reach any IP inside remote network

Same here..

**Comment by DimitriPapadopoulos** [comment]
This issue is closed, posting "#metoo" messages here just adds noise. Note that there are two issues at hand:
1. the `ipcp-accept-remote` issue solved in openfortivpn 1.21,
2. setting routing and DNS parameters, which needs additional steps such as using `resolveconf`.
