### ISSUE TITLE
Route hosts through VPN

### ISSUE THREAD

**Issue by jorgeluislazo** [adrienverge/openfortivpn#1163]
Hi,

Is there a way to replicate [VPN slice](https://github.com/dlenski/vpn-slice) behaviour for openconnect in which a hostname is passed to fortivpn and any traffic to that hostname will be routed via the VPN?

I am connected to a VPN that by default only acts on certain subnets, I want to add IPs to the default config setup by the VPN (and since they are a range of IPs and may change, I'd like to do it via hostname value).

**Comment by DimitriPapadopoulos** [comment]
You would need to have a script do that for you.

Right now, openfoprtivpn does not call an external script, although I would very much like it to defer routing and DNS changes to an external such as [vpnc-script](https://gitlab.com/openconnect/vpnc-scripts) or [vpn-slice](https://github.com/dlenski/vpn-slice). So you only option would be to [add such a script under `ip-up` / `ip-down`](https://github.com/adrienverge/openfortivpn/wiki#using-pppd-ip-up--ip-down-scripts).
