### ISSUE TITLE
VPN does not connect on Fedora 39

### ISSUE THREAD

**Issue by yakupkaya** [adrienverge/openfortivpn#1164]
After updating my system to Fedora 39, VPN connections cannot be established. The version of openfortivpn coming with Fedora 39 is 1.19.0
I get the following error when I try to connect:

`
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/4
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.17.200.3], ns [10.17.15.3, 10.17.15.4]
INFO:   Negotiation complete.
INFO:   Negotiation complete.
Peer refused to agree to his IP address
Connect time 0.4 minutes.
Sent 1171 bytes, received 1151 bytes.
ERROR:  Timed out waiting for the ppp interface to be UP.
INFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
Hangup (SIGHUP)
Modem hangup
Connection terminated.
ERROR:  pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

`

When I manually compile the version 1.21.0 from github, I can connect without any issues. But since network manager uses the version coming from Fedora repos, I can only connect from command line.

**Comment by DimitriPapadopoulos** [comment]
https://github.com/adrienverge/openfortivpn/issues/1162
