### ISSUE TITLE
Openfortivpn seems broken on my Macbook since last update

### ISSUE THREAD

**Issue by foss4ever** [adrienverge/openfortivpn#1165]
Since last week I have been unable to use openfortivpn as it no longer manages connect to our FortiGate VPN gateway.
 
When starting a connection I do get to the 2FA prompt, and having authenticated in the FortiToken app, openfortivpn then halts at "Committed PPP store" - seemingly unble to bring up the vpn tunnel adapter / interface, ppp0.

After having waited a while, I then hit ctrl+c and this results in additional output as seen below the yellow line:

![image](https://github.com/adrienverge/openfortivpn/assets/72194332/34172c3d-a103-4cd4-ac2c-935a35bf2435)

I tested the same VPN connection in the official FortiClient app for MacOS and that works just fine. 

I then ended up downgrading openfortivpn to previous version 1.20.5 and that has resolved the issue, however I of course do hope I can get back on the latest version when the underlying problem introduced with version 1.21.0 has been taken care of.

My platform is MacOS, specifically Sonoma 14.0, and hardware-wise I'm on a Macbook Air M1 (2020).

**Comment by liamhess** [comment]
Hi, currently facing the same issue but I'm having a hard time downgrading as I installed the package with brew and brew versioning is not so straight forward. If you have the time could you maybe provide some instructions on how you downgraded, would be greatly appreciated😅
Greetings, liam

**Comment by VadimYakovliev** [comment]
the same

**Comment by DimitriPapadopoulos** [comment]
@foss4ever I don't know how to reach the brew packagers.
1. Packagers should probably build openfortivpn with **`configure --enable-legacy-pppd`**, required for platforms still shipping pppd < 2.5.0.
2. End-users can work around this issue with option **`openfortivpn --pppd-accept-remote=0`**.

**Comment by HacDan** [comment]
Thank you @DimitriPapadopoulos just saved my bacon! (Or I could have just rolled back a version, haha!)

**Comment by foss4ever** [comment]
> @foss4ever I don't know how to reach the Homebrew packagers.
> 
>     1. Packagers should build openfortivpn with **`configure --enable-legacy-pppd`**, required for platforms still shipping pppd < 2.5.0.
> 
>     2. End-users can work around this issue with option **`openfortivpn --pppd-accept-remote=0`**.

Alright, thank you for letting me know. 

I have asked in the Homebrew github discussions area, how to get in contact with the packagers of openfortivpn for homebrew and will get back to you on this thread if and when I manage to get hold of them.

**Comment by DimitriPapadopoulos** [comment]
I have modified the formula in https://github.com/Homebrew/homebrew-core/pull/154460. Hopefully new packages will be out soon.
