### ISSUE TITLE
v1.21.0 Segmentation fault

### ISSUE THREAD

**Issue by Drotak** [adrienverge/openfortivpn#1172]
When I try to run v1.21.0 I'm getting just the message "Segmentation fault", reverting to v1.20.5 everything works as expected!

I'm using NixOS and building my openfortivpn with an overlay fetching the tar.gz archive from github.

```
$ nixos-version
23.05.885.bb8b5735d6f (Stoat)

$ sudo openfortivpn --version
1.21.0
$ sudo openfortivpn --pppd-accept-remote
Segmentation fault

$ sudo openfortivpn --version
1.20.5
$ sudo openfortivpn --pppd-accept-remote
VPN account password: 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/1
INFO:   Got addresses: [10.XXX.XXX.XXX], ns [10.XX.XX.XX, 0.0.0.0], ns_suffix [mydomain.local]
INFO:   Negotiation complete.
local  IP address 10.XXX.XXX.XXX
remote IP address 212.XXX.XXX.XXX
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

**Comment by DimitriPapadopoulos** [comment]
Try without `--pppd-accept-remote`, or with `--pppd-accept-remote=0` or `--pppd-accept-remote=1`. Does it help?

I might not handle correctly the case where `--pppd-accept-remote` doesn't take an (optional) argument.

**Comment by DimitriPapadopoulos** [comment]
I can reproduce the segfault on Ubuntu 22.04 with _master_, even without `--pppd-accept-remote`, but not with the 1.21.0 release. It's related to the SNI option

I don't know how NixOS packages work. Are you certain you're using openfortivpn 1.21.0 and not the latest code in the _master_ branch?

**Comment by DimitriPapadopoulos** [comment]
Not at all, you did point me to an issue I had overlooked. Thank you for that.
