### ISSUE TITLE
macOS 14.2 and 1.21  blocks

### ISSUE THREAD

**Issue by pkotronis** [adrienverge/openfortivpn#1178]
Hi to everyone
The problem in #1118 seems to reappear in Sonoma 14.2 and openfortivpn 1.21.0 I get the following error:
Thu Dec 14 16:06:17 2023 : Committed PPP store
Thu Dec 14 16:06:17 2023 : Committed PPP store
^CINFO: Cancelling threads...
INFO: Cleanup, joining threads...
INFO: Interface ppp0 is UP.
INFO: Setting new routes...
WARN: Could not get current default route (Parsing /proc/net/route failed).
WARN: Protecting tunnel route has failed. But this can be working except for some cases.
WARN: Adding route table is incomplete. Please check route table.
INFO: Adding VPN nameservers...
INFO: Tunnel is up and running.
INFO: Setting ppp0 interface down.
INFO: Restoring routes...
INFO: Removing VPN nameservers...
Thu Dec 14 16:06:20 2023 : Hangup (SIGHUP)
Thu Dec 14 16:06:20 2023 : Modem hangup
Thu Dec 14 16:06:20 2023 : Connection terminated.
Thu Dec 14 16:06:20 2023 : LCP close (User request).
Thu Dec 14 16:06:20 2023 : Connect time 0.1 minutes.
Thu Dec 14 16:06:20 2023 : Sent 0 bytes, received 0 bytes.
INFO: pppd: The link was terminated by the modem hanging up.
INFO: Terminated pppd.
INFO: Closed connection to gateway.
INFO: Logged out.

Any ideas to solve it ?
Thanks in advance

**Comment by DimitriPapadopoulos** [comment]
Does it work any better with `--pppd-accept-remote=0`?

Do you know if this problem is specific to openfortivpn 1.21?

**Comment by pkotronis** [comment]
The problem appeared only just after a recent upgrade using brew.
The previous version worked without any pb.

It works when I use 
openfortivpn -c .fortivpn-config --pppd-accept-remote=0
Thanks!
