### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by adrienverge** [adrienverge/openfortivpn#118]
This repository is unfortunately dying because I don't have time to review pull requests and debug problems.

It would be awesome if someone was willing to pick up the torch! The requirements are to make sure you understand the PRs you accept, and take responsibility to fix (or have the author to fix) potential problems they bring. It would also be best to keep a clean git history and nice commit messages, so problematic commits can be `git blame`d and `revert`ed if needed.

@mrbaseman @DimitriPapadopoulos you made relevant contributions recently: I wonder if you are interested in being maintainers?

**Comment by mrbaseman** [comment]
sure, in a team I would have interest to maintain this code. I think that I have enough C programming skills that I can reasonably review the pull requests and also I can to some extend test the proposed changes in my environments. For debugging problems and most of the feature requests coming in I honestly don't feel that I have the time and/or enough background knowledge e.g. about the internal structures of the networking stack.

**Comment by DimitriPapadopoulos** [comment]
Like mrbaseman I have C skills but I don't know enough about the networking stack to be able to review the more complicated PRs - and I can't invest much time in learning about it. I won't have time either to review all PRs either, especially complicated ones that require knowledge of the networking stack. Happy to help from time to time though.

**Comment by adrienverge** [comment]
@mrbaseman @DimitriPapadopoulos Great, thanks for your help! :)
I just added you to the project team.

I don't expect you to review every PR. Feel free to review what you want, but please:
- make sure changes that you merge are atomic and revertable if needed,
- they are documented at least in the commit message, so one can understand what they do,
- help debug bugs brought by the PRs you merge.

**Comment by mrbaseman** [comment]
Thanks. To start with I have just merged #99 but together with squashing the lengthy commit series and rebasing it I have included a few improvements by myself which address the same topic. I must admit that I could have further improved the documentation about the commit, but just squashing it down to a single commit has made th changes much clearer for this issue. I hope that this is ok for you.

**Comment by adrienverge** [comment]
@mrbaseman Thanks a lot! I've looked at your commit (d94915c) and it looks great.
