### ISSUE TITLE
URI missing as configuration parameter

### ISSUE THREAD

**Issue by michiiii** [adrienverge/openfortivpn#1194]
Hi there,

thanks for the project and all the work you put into this. 

I was wondering, if I am missing something here. On my windows client I can define a gateway with a schema like this:

- https://forti.example.com/split

when I am using openforticlient in linux, I can only define the gateway in the host parameter in form a FQDN. I could not find a way to include the /split in the connection like in Windows. I tried quite a few trick but overall did not find a solution. Could you give me a hint? or is this feature not implemented yet.

**Comment by DimitriPapadopoulos** [comment]
See #789, #827, and #906. Do these help?

**Comment by michiiii** [comment]
thank you so much! it worked.

I always think about kerberos when reading the word realm.
