### ISSUE TITLE
Using openvpn breaks openfortivpn

### ISSUE THREAD

**Issue by oerp-odoo** [adrienverge/openfortivpn#1195]
I have this strange issue. Today I added VPN with openvpn to one of my company networks. It was working fine. Though later that day I noticed that `openfortivpn` stopped working (do note I've not used them at the same time). I did not think it had anything to do with openvpn, so I tried to debug openfortivpn, but found nothing.

Interestingly enough, openfortivpn does not produce any errors. You just can't connect to the network. It acts as if you are not connected to VPN (can't open any page, it just keeps loading etc):

```
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Tunnel is up and running.
```
I tried various options, restarting network-manager, restarting systemd-resolve, restarting my laptop, installing latest openfortivpn. Nothing helped.

Then I accidentally started my laptop without ethernet cable, only with wi-fi. And all of a sudden, openfortivpn starts working again. Now if I turn off openfortivpn, turn on openvpn and turn it off. openfortivpn will be bugged again. it wont work. The only way I can unbug it, is by unplugging ethernet cable (which is weird, but it works somehow).

not sure what does `openvpn` does to network that it just conflicts this way. And strangely if I restart network manager it won't help. So not sure how "physically" switching from wired to wi-fi makes it work again (if I switch off wired network via settings, it does not help).

I used `.ovpn` file to import new vpn settings. I guess some configuration makes somehow conflicts with `openfortivpn`?

Details:

```
Ubuntu 20.04
OpenVPN 2.4.12
Openfortivpn 1.21.0
```

**Comment by DimitriPapadopoulos** [comment]
That's somehow expected. The routing or even DNS settings requested by each VPN might not be compatible. You'll have to handle routing yourself.

**Comment by oerp-odoo** [comment]
But both VPNs are not used together. Why it would interfere even after it was turned off?

**Comment by mrbaseman** [comment]
I would suspect that in your case `openvpn` doesn't restore all the settings correctly when it is terminated. Perhaps the default route points to the other interface afterwards. I'd recommend to compare routes, interface configurations, and dns settings before using `openvpn` and after it is terminated, with the ethernet cable plugged in all the time.
