### ISSUE TITLE
Explain OTP Flag

### ISSUE THREAD

**Issue by xChAmeLIoNz** [adrienverge/openfortivpn#1221]
Hello,

Maybe I'm missing something, but what's the purpose of the `-o <otp>` flag?

I mean, how can I specify the OTP token if I don't have it before running the openfortivpn client and receiving it by email?

**Comment by DimitriPapadopoulos** [comment]
You cannot. That's for cases where the OTP password is generated independently of the login process. That's typically a time-based password provided by a hardware token or apps such as the Google Authenticator.
