### ISSUE TITLE
set resolvectl domains at vpn-up

### ISSUE THREAD

**Issue by jmordkoff** [adrienverge/openfortivpn#1232]
Everything is working great, dns servers get set, but resolvectl doesn't route requests right. I have to do 
     resolvectl domain ppp0 dzsi.local dzsi.net dzsi.com
to get it to work right. Any tricks for automating this?

**Comment by mrbaseman** [comment]
maybe this could be done with an [ip-up script](https://github.com/adrienverge/openfortivpn/wiki#using-pppd-ip-up--ip-down-scripts)?

**Comment by jmordkoff** [comment]
thanks. That worked 

I added /etc/ppp/ip-up/0100custom with my commands and I added --no-dns to my openforticlient command line 

note that the ip-up scripts run before openforticlient sets the DNS, so trying to get openforticlient to do some of it and then having my script do some overrides did not work since they run in the wrong order.  So I put everything in my script (really just 2 commands plus some code to detect what server I just connected into).
