### ISSUE TITLE
--cookie-on-stdin option not working

### ISSUE THREAD

**Issue by noriegafam** [adrienverge/openfortivpn#1246]
Greetings! first of all thank you to all of those involved in the development and maintenance of this project. I am a *nix user for a few years now and having tools normally available only for commercial OS's is really a big deal for some of us. I tip my hat.

I recently discover openfortivpn, after some wrestling (instructions are not for the faint-hearted) I managed to get a connection using both openfortivpn and webview. The issue I encounter is that webview works as expected, it prints the SVPNCOOKIE in the terminal and then exits, however using  sudo openfortivp domain.org:port --user=user --cookie-on-stdin withdoes not work. I have to manually copy and paste it using --cookie=WWDFRT888ad8ao....  It is really not a big deal. However it would be quite convenient being that the function is already implemented, just not working for some unknown reason to me. 

Please advise. And, once more thank you much!

verision: 1.21.0
system: Linux fedora-scc-local 6.10.11-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

**Comment by LucaAAntonelli** [comment]
You could pipe the output of `openfortivpn-webview` into `openfortivpn` as follows:

`openfortivpn-webview domain.org:port 2>/dev/null | sudo openfortivpn domain.org:port --cookie-on-stdin`

**Comment by noriegafam** [comment]
It worked! Thanks a lot for your reply.

as follows:

./openfortivpn-webview-1.2.1.AppImage --url 'https://_domain_:_port_/remote/saml/start?realm=Office VPN' | sudo openfortivpn domain:port --username=_user_ --cookie-on-stdin

Cheers!!!
