### ISSUE TITLE
Not technical - > Disk access

### ISSUE THREAD

**Issue by ProdesignerAgency** [adrienverge/openfortivpn#1257]
I have this question (not technical), compared to FortiClient VPN, does this program also need to access the disk / network on mac > https://docs.fortinet.com/document/forticlient/7.0.7/macos-release-notes/223986/special-notices

Best.

**Comment by DimitriPapadopoulos** [comment]
Note that openfortivpn is not an "app", it's a program launched from the command line with root privileges.

**Comment by ProdesignerAgency** [comment]
Ok thank you @DimitriPapadopoulos . What about the contents of disks / networks / programs. I don't want third parties to have influence on this -> like in the case of FortiClient VPN. 


Best

**Comment by DimitriPapadopoulos** [comment]
Of course it does need to the network. It's a VPN client!

**Comment by ProdesignerAgency** [comment]
Thanks @DimitriPapadopoulos . 

Yes I know, but you can see the discussion here > https://www.reddit.com/r/fortinet/comments/1ey11iy/basic_version_of_forticlient_vpn_asks_to_give/ 

I think it has a big impact on my privacy, I can't restrict it to a specific e.g. directory. (On mac).

In addition from what I understand, but please correct me:

Does the FortiClient VPN allow the VPN administrator to manage my network, i.e. he can control what I do within the VPN and what I do privately? 

Does the FortiClient VPN administrator have access to my files?

Can openfortivpn be restricted to a specific directory on my drive ?

Best.
