### ISSUE TITLE
ERROR:  /usr/sbin/pppd: No such file or directory.

### ISSUE THREAD

**Issue by alessio-libardi** [adrienverge/openfortivpn#1259]
Installing `openfortivpn` using `brew` on Linux doesn't install required dependencies. 

Everything was working fine last month but now installing `openfortivpn` using `brew` is not installing `pppd`. The only change I can see from last month is the [update of the brew formulae](https://github.com/Homebrew/homebrew-core/commit/c0f68615c7036869f2060b2f28c372895d77de5c) but I'm not sure if that possibly breaks something. Can anyone help me understand if that's the case?

**Comment by DimitriPapadopoulos** [comment]
Try opening an issue under https://github.com/Homebrew/homebrew-core instead.
