### ISSUE TITLE
Install path in Linux

### ISSUE THREAD

**Issue by Mabin-J** [adrienverge/openfortivpn#128]
I think that '/usr/local/' is better then '/usr/' for install path.  
because I know that usually '/usr' is for install from package and '/usr/local/' is for install from source.

**Comment by mrbaseman** [comment]
personally, I always install 3rd party software which is not shipped with the distro below /usr/local. 
It's a decision at configure time and the choice for the prefix is mentioned only in README.md
Would you like to update your PR #127 ?

**Comment by Mabin-J** [comment]
OK. I'll update
