### ISSUE TITLE
ERROR:  read: Input/output error

### ISSUE THREAD

**Issue by snbakos** [adrienverge/openfortivpn#131]
I have downloaded master and installed in raspberry pi.

I get ERROR:  read: Input/output error, can you help me?

log:
sudo openfortivpn --version
1.3.1

sudo openfortivpn -v
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG:  Config realm = ""
DEBUG:  Config port = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG:  Config username = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG:  Config password = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
INFO:   Authenticated.
DEBUG:  Cookie: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO:   Remote gateway has allocated a VPN.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  ssl_read_thread
DEBUG:  ssl_write_thread
DEBUG:  if_config thread
DEBUG:  pppd_read_thread
DEBUG:  pppd_write thread
DEBUG:  gateway ---> pppd (12 bytes)
ERROR:  read: Input/output error
INFO:   Cancelling threads...
DEBUG:  Waiting for pppd to exit...
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.

**Comment by mrbaseman** [comment]
This error can appear for several reasons. 
Did you check the possible causes discussed in #56 already?

**Comment by snbakos** [comment]
thanks, for your help

I had to install ppp package
sudo apt-get install ppp


One more (little I hope) problem.

How I can make it autostart and run some iptables commands after start?

**Comment by DimitriPapadopoulos** [comment]
Debian and RPM packages do not contain startup scripts, they simply provide the _openfortivpn_ executable.

**Comment by mrbaseman** [comment]
Should we include examples? There are traditional init scripts, upstart, system.d, and maybe even more. One could put a proposal for each flavor in the doc directory

**Comment by DimitriPapadopoulos** [comment]
I really don't know. I am myself using _openfortivpn_ with one time passwords generated by a token. In that context you cannot use startup scripts and I wasn't even aware there are cases where the VPN should be started automatically.

**Comment by mrbaseman** [comment]
Me too, I have mobile tokens which (hopefully) can not be generated in a startup script. Without them, and when storing the password in the config file (which is not recommended) you could start up the vpn during boot after networking has become functional. I don't know how widespread this use case is. 
Perhaps we should not encourage people storing their credentials in a file by providing startup scripts that rely on exactly this practice.

**Comment by mrbaseman** [comment]
@snbakos did you solve your autostart problem by redirecting the output? The commits from #134 might also be important in this context, so it might be worth trying 1.4.0
