### ISSUE TITLE
Is it possible to package openfortivpn as a snap ?

### ISSUE THREAD

**Issue by the-mentor** [adrienverge/openfortivpn#138]
I was wondering if its possible to package openfortivpn as a snap.
this will make it more available to users.
https://build.snapcraft.io/
https://snapcraft.io/

Thanks !!

**Comment by DimitriPapadopoulos** [comment]
The are already RPMs (for Fedora) and an effort to build a DEB package (for Debian) is underway. See #81 and [devuan-packages/openfortivpn](https://git.devuan.org/devuan-packages/openfortivpn). Unfortunately the DEB package has not been updated lately.

Perhaps _snap_ is a good alternative, but I'm not certain what it does after a quick glance at the documentation. Does it generate RPM and DEB packages? If not, I'd rather spend time on updating the DEB packages for Debian and Ubuntu users.

**Comment by DimitriPapadopoulos** [comment]
If someone wants to create a _snap_ package, why not? What would be needed? privileged access to the GitHub repository?

After some more reading, I understand the executable should not rely on a configuration file `/etc` or `/usr/local/etc`. Instead it should first look into `../etc` starting from the location of the executable, then fall back on some pre-defined location such as `etc`.

**Comment by the-mentor** [comment]
@DimitriPapadopoulos  from my understanding it creates a .snap file and publish it at the snap "store"
from the way its described in the instructions you just need to add a yamel file with the configuration to your github and tie build.snapcraft.io to your github.

**Comment by DimitriPapadopoulos** [comment]
Indeed, but I've read the [software must be relocatable](https://snapcraft.io/docs/snaps/philosophy#relocatable-code). Perhaps I have misunderstood (relocatable before or after build time ?) and in any case a wrapper script combined with option `--config` may be used as a workaround.

So my understanding is:
- Anyone can contribute patches or a wrapper script to make _openfortivpn_ relocatable.
- Anyone can contribute a `snapcraft.yaml` file.
- Eventually a collaborator needs to tie [build.snapcraft.io](https://build.snapcraft.io/) to the _openfortivpn_ repository.

Finally I think it's best _openfortivpn_ is integrated to the system, for example on Ubuntu it should be launched by _Network Manager_. In an ideal world it would seldom be used as a standalone program. Therefore again I believe the priority should be to provide DEB packages in addition to RPM packages, and also integration with _Network Manager_.

**Comment by adrienverge** [comment]
I agree with Dimitri.

**Comment by mrbaseman** [comment]
looking through the open issues I came across this one and I'm puzzled, because at the time when this issue was opened here, there was already a snap for _openfortivpn_  available at [snapcraft](https://snapcraft.io/openfortivpn) 
It might be that the snap was built but not yet published at that time. Anyhow, as of today there is one available. It might make sense to update that one to a more recent release.

**Comment by devec0** [comment]
As the author of the snap, I'd be happy to get the snap updated for a newer release. I'll try to work on this over the coming few weeks.

**Comment by DimitriPapadopoulos** [comment]
Since _openfortivpn_ is available from [snapcraft](https://snapcraft.io/openfortivpn) I believe we can close this issue. It would be great if someone could help @devec0 maintain it but that's beyond the scope of this issue.
