### ISSUE TITLE
Fix buffer overrun

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#140]
Commit 8441956 increases MAX_SPLIT_ROUTES from 64 to 128 and thus the potential number of digits in `ipv4_config.split_routes` from 2 to 3. There is a well hidden dependency on the number of digits:
```
		sprintf(env_var, "VPN_ROUTE_GATEWAY_%d",
		        tunnel->ipv4.split_routes);
```

Variable `env_var` must be initialized accordingly.

**Comment by mrbaseman** [comment]
good catch, thanks!
