### ISSUE TITLE
Add openssl location to configure options

### ISSUE THREAD

**Issue by mnencia** [adrienverge/openfortivpn#143]
I've created a formula for homebrew, and the homebrew maintainer has asked if it is possible to add the openssl location to `configure` options instead of using the environment to specify it.

https://github.com/Homebrew/homebrew-core/pull/14344

Please consider adding it, together with an autogen.sh script to automate the generation of the autoconf/automake files

**Comment by DimitriPapadopoulos** [comment]
I've never written an _autogen.sh_ file before. Is DimitriPapadopoulos/openfortivpn@dd09f9c OK?

**Comment by mnencia** [comment]
I'm not an expert, but it looks ok to me.

**Comment by mrbaseman** [comment]
@mnencia I'm not sure if you are watching. _openfortivpn_ 1.5.0 has just been tagged. It supports `PKG_CONFIG_PATH`now, instead of `--with-openssl`. You might want to update the Homebrew formula.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Since a _Homebrew_ package for _openfortivpn_ 1.5.0 is already available (see issue Homebrew/homebrew-core#17382 and commit Homebrew/homebrew-core@bf53714) - and has been briefly tested by @mnencia (Homebrew/homebrew-core#14344), I suggest we close this issue.
