### ISSUE TITLE
Bump version 1.4.0 → 1.4.1

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#147]
Version 1.4.1 has been released but `openfortivpn --version` still reports version 1.4.0.

**Comment by adrienverge** [comment]
Hi Dimitri,

What do you mean by "Version 1.4.1 has been released"?

I don't see it in https://github.com/adrienverge/openfortivpn/releases and I don't remember creating such a tag.

**Comment by DimitriPapadopoulos** [comment]
Blush... I might have mixed 1.3.1 and 1.4.0.
