### ISSUE TITLE
/usr/sbin/netstat

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#155]
While _openfortivpn_ requires `/usr/sbin/netstat` in [src/ipv4.c](https://github.com/adrienverge/openfortivpn/blob/master/src/ipv4.c#L128), this command does not exist in Debian/Ubuntu. Instead the path is `/bin/netstat`. And yet _openfortivpn_ works for me on Ubuntu14.04 or 16.04.

Is `/usr/sbin/netstat` useless? Is it optional?

Location of netstat in Debian/Ubuntu:
https://packages.debian.org/jessie/amd64/net-tools/filelist
https://packages.debian.org/stretch/amd64/net-tools/filelist
https://packages.ubuntu.com/trusty/amd64/net-tools/filelist
https://packages.ubuntu.com/xenial/amd64/net-tools/filelist

**Comment by mrbaseman** [comment]
`/usr/sbin/netstat` is where the program can be found on Mac OSX. On Linux `/proc/net/route` should provide this information, note the `#ifndef __APPLE__` on [L109](https://github.com/adrienverge/openfortivpn/blob/master/src/ipv4.c#L109)

**Comment by DimitriPapadopoulos** [comment]
Of course. I read `ifdef` instead if `ifndef`... Sorry.
