### ISSUE TITLE
{ "DEBUG:  ", "\033[0;90m", LOG_DEBUG}

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#156]
I don't get why the DEBUG log level is defined twice in [src/log.c](https://github.com/adrienverge/openfortivpn/blob/master/src/log.c#L41):
```
static struct log_param_s log_params [OFV_LOG_DEBUG_PACKETS + 1] = {
	{ "        ", "",           LOG_ERR},
	{ "ERROR:  ", "\033[0;31m", LOG_ERR},
	{ "WARN:   ", "\033[0;33m", LOG_WARNING},
	{ "INFO:   ", "",           LOG_INFO},
	{ "DEBUG:  ", "\033[0;90m", LOG_DEBUG},
	{ "DEBUG:  ", "\033[0;90m", LOG_DEBUG},
};
```
This looks like a typo to me. Unless I'm missing something here?

**Comment by DimitriPapadopoulos** [comment]
OK, it's probably defined once for `OFV_LOG_DEBUG` and once for `OFV_LOG_DEBUG_PACKETS`.

But then it looks like `OFV_LOG_DEBUG_PACKETS` is disabled [later on](https://github.com/adrienverge/openfortivpn/blob/master/src/log.c#L90):
```
void do_log(int verbosity, const char *format, ...)
{
	[...]
	// Use sane default if wrong verbosity specified
	if (verbosity > OFV_LOG_DEBUG || verbosity < 0)
		verbosity = OFV_LOG_MUTE;
```

**Comment by mrbaseman** [comment]
Yes, I agree, it should read `OFV_LOG_DEBUG_PACKETS` [here](https://github.com/adrienverge/openfortivpn/blob/master/src/log.c#L90) - that's defined as [5](https://github.com/adrienverge/openfortivpn/blob/master/src/log.h#L30) so we are still in the range of an array with [6](https://github.com/adrienverge/openfortivpn/blob/master/src/log.c#L41) entries - and the size of the array picks up that constant, so in case a future commit changes this range, the compiler should notice if someone forgets to update all places.
And, right, the two entries containing `LOG_DEBUG` (the [syslog_prio](https://github.com/adrienverge/openfortivpn/blob/master/src/log.c#L38) of each entry in the array of structs) are for `OFV_LOG_DEBUG` and `OFV_LOG_DEBUG_PACKETS`

**Comment by DimitriPapadopoulos** [comment]
It's `OFV_LOG_DEBUG` after all because `OFV_LOG_DEBUG_PACKETS` is handled in a different `do_log_packet()` function. See [src/log.h](https://github.com/adrienverge/openfortivpn/blob/master/src/log.h#L58).
