### ISSUE TITLE
[Feature Request] IPsec

### ISSUE THREAD

**Issue by step21** [adrienverge/openfortivpn#159]
Unfortunately the fortigate I need to access allows only ipsec. Is it planned or even possible to implement it?

**Comment by DimitriPapadopoulos** [comment]
I believe you don't need a specific client for that, you should "simply" use the Linux IPSec stack properly. I've seen some blog articles floating around:
* [How to connect to a FortiGate IPSec-VPN using Linux](http://rolandtapken.de/blog/2015-06/how-connect-fortigate-ipsec-vpn-using-linux)
* [Connect to a Fortinet VPN with Ubuntu](https://serverfault.com/questions/152233/connect-to-a-fortinet-vpn-with-ubuntu#154384)
* [Technical Note: How to configure Linux version of Shrew Soft VPN with a FortiGate](http://kb.fortinet.com/kb/documentLink.do?externalID=FD37618)
* [Using an Openswan client with FortiGate VPN](http://kb.fortinet.com/kb/documentLink.do?externalID=11835)
* ...

**Comment by step21** [comment]
Yeah, I know that. But it makes sense in connection with my other feature request about config files - you cannot use the normal vpn stack if you do not have a way to read the config files. I guess then openfortivpn could only decode the files and then hand over the normal openvpn stack?

**Comment by DimitriPapadopoulos** [comment]
I think it would make more sense to have another piece of software read the Windows config files and call either _openfortivpn_ or the IPSec stack. A script language such as Python would be a more efficient language for such tasks.

Actually there are already such pieces of software, such as _NetworkManager_ on Linux, with [SSL VPN support](https://blogs.gnome.org/lkundrak/2015/09/24/fortigate-ssl-vpn-support-added-to-networkmanager/). Wouldn't such software be a better place to handle IPSec VPNs and specific plugins?

Right now the [README](https://github.com/adrienverge/openfortivpn/blob/master/README.md) states "_openfortivpn_ is a client for PPP+SSL VPN tunnel services".

**Comment by step21** [comment]
Ok, fair point. I just also thought I would post here as maybe you have some more in-depth knowledge of fortigate-specific stuff  that could help with config files as well. Apart from this format not being documented, I might contribute to openfortivpn, but I would never contribute to network manager, way too much overhead to understand the codebase etc...

**Comment by DimitriPapadopoulos** [comment]
Then it might make sense to start new software that would:
* parse Windows configuration files,
* attempt to configure IPSec,
* fall back to SSL VPN with _openfortivpn_.

I don't know about other contributors, but unfortunately I don't have admin access to a Fortinet gateway - which would help configure and debug an IPSec connection - and I don't know much about fortigate-specific stuff.

**Comment by step21** [comment]
Ok, all fair points. Thanks anyway for taking the time to discuss this. I will think about what I can do about this, however so far I found no documentation and I am not really good at figuring out encodings and things like that. I mean, maybe it's just base64 but maybe not.

**Comment by step21** [comment]
On some more research, I found some documentation (such as here http://docs.fortinet.com/uploaded/files/2076/forticlient-xml-52.pdf ) and the start of a parser (https://github.com/acidjunk/fortigate-config-parser) but the documentation leaves out how to decrypt the important data. In theory it cannot be that complex, as it is decrypted locally without connecting to the fortigate vpn.
