### ISSUE TITLE
[Feature Request] Read Forticlient v5 config files

### ISSUE THREAD

**Issue by step21** [adrienverge/openfortivpn#160]
Instead of needing the cleartext username/password and so on, or having to ask the network admins for a separate profile, it would be easiest if (at least for ipsec) openfortivpn could just read/decode the config files of the Windows version. They are basically xml, however the username/password or other sensitive information is not in cleartext. It is unclear if it is merely obfuscated or encrypted buy anyway, if this data could be used it would make everyone's life so much easier.

**Comment by DimitriPapadopoulos** [comment]
Since _openfortivpn_ provides VPN SSL, not IPSec, I guess this is not really needed, correct?

**Comment by step21** [comment]
Well... those files can be used for ssl-vpn as well. But for me, I would care most about ipsec. Sure I guess one could also make a separate app that just reads the config files, but I think it might be nice to be integrated with openfortivpn. If it is an ssl-vpn config it can use it directly, if not it can hand it over to network manager or generally openvpn

**Comment by DimitriPapadopoulos** [comment]
I think it should be the other way round: network manager reads the config abd hands it over to the IPSec stack or _openfortivpn_ plugin.

I don't think there's anything very specific to Fortinet when it comes to configuring IPSec. So this should be done in a generic software for configuring IPSec. I think _openfortivpn_ is very specific: unlike IPSec, SSL VPN is less standardized and vendor-specific.

**Comment by step21** [comment]
Mmmh :-/ Ok, it will just never happen then probably, as no one seems to be working on it and I feel like I cannot get into a complicated project like network manager (not even mentioning programming skills)
There is maybe not anything vendor specific for the implementation, but the configuration file is a custom format. The main problem is that often Administrators in small or medium companies just give out the config files, and do not want to hand over plaintext username/password. In the xml file, the username/password (and potentially other data) is obfuscated or encrpyted within a CDATA xml tag. I cannot use this data unless it is known how to decode it. Sometimes you might be able to ask the administrator for the credentials, but often you cannot.

**Comment by DimitriPapadopoulos** [comment]
@step21 Quoting your interesting findings from #159:
> On some more research, I found some documentation (such as here http://docs.fortinet.com/uploaded/files/2076/forticlient-xml-52.pdf) and the start of a parser (https://github.com/acidjunk/fortigate-config-parser) but the documentation leaves out how to decrypt the important data. In theory it cannot be that complex, as it is decrypted locally without connecting to the fortigate vpn.

Following this interesting research and associated discussion, it would seem the best course of action for anyone interested to contribute would be to:
1. Contribute to existing Forticlient config file parsing software (https://github.com/acidjunk/fortigate-config-parser), extending to parsing passwords if needed and helping package the code into a Python library available for example via [PyPI](https://pypi.python.org).
2. Contribute inclusion of above software in _NetworkManager_, or build a command based on the above Python code to translate _Forticlient_ config files into _openfortivpn_ config files.
3. Request _NetworkManager_ to add IPsec support in addition to SSL VPN support, if that's not already the case, using the Linux IPsec stack / [Openswan](https://www.openswan.org). Alternatively write/contribute to command line software that would read Forticlient config files and crate an IPsec tunnel or span _openfortivpn_.

Additionally please note that the official Forticlient for Linux supports SSL VPN only, not IPsec. Therefore it would seem natural to have SSL VPN enabled on the Fortigate device to support Linux - but then I do know many IT departments support only Windows and don't care about Linux or even Mac users.
