### ISSUE TITLE
set-dns=0 is not being honoured

### ISSUE THREAD

**Issue by shalomb** [adrienverge/openfortivpn#164]
I've a config file that looks like this

```
host       = xxx.xxx.xxx.xxx
port         = 443
set-dns      = 0
set-routes   = 1
```

but despite the `set-dns = 0` I find my `/etc/resolv.conf` file being updated with the nameservers for the vpn.

Even more interestingly, `/etc/resolv.conf` maintains the `domain` and `search` directives from before connecting to the VPN (which is expected) but this throws off non-FQDN resolution without the nameservers that I wish to keep from being overridden.

e.g. Before `/etc/resolv.conf` connecting

```
domain tools.internal.example.org
search tools.internal.example.org internal.example.org example.org 
nameserver 10.x.x.x
```

and after connecting, the `10.x.x.x` nameserver is replaced by those given out from the VPN server.

```
nameserver 172.18.x.x
nameserver 172.18.x.y
domain tools.internal.example.org
search tools.internal.example.org internal.example.org example.org
```

**Comment by shalomb** [comment]
Explicitly specifying `--pppd-no-peerdns` on the command line seems to do the trick but it doesn't appear that you can specify this option in a config file.

```
$ sudo grep -i 'dns' /etc/openfortivpn/office-vpn
set-dns      = 0
pppd-no-peerdns

$ sudo openfortivpn --config /etc/openfortivpn/office-vpn
WARN:   Bad line in config file: "pppd-no-peerdns".
2factor authentication token:
INFO:   Authenticated.
INFO:   Got addresses: [10.x.y.z], ns [10.x.x.x, 10.x.x.y]
...
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Tunnel is up and running.
```

```
$ sudo grep -i 'dns' /etc/openfortivpn/office-vpn
set-dns      = 0
pppd-no-peerdns = 1

$ sudo openfortivpn --config /etc/openfortivpn/office-vpn
WARN:   Bad line in config file: "pppd-no-peerdns".
WARN:   Could not load config file "/etc/openfortivpn/office-vpn" (unknown).
2factor authentication token:
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

This works.
```
$ sudo grep -i 'dns' /etc/openfortivpn/office-vpn
set-dns      = 0

$ sudo openfortivpn --pppd-no-peerdns --config /etc/openfortivpn/office-vpn                                      
INFO:   Connected to gateway.
2factor authentication token:
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [10.x.x.x], ns [0.0.0.0, 0.0.0.0]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Tunnel is up and running.
```

I've worked around this for now using this in a wrapper script.
```
#!/bin/bash
vpn_name="${0##*/}"
exec sudo openfortivpn_name --pppd-no-peerdns --config /etc/openfortivpn/"$vpn"
```

**Comment by mrbaseman** [comment]
I suspect that something else than openfortivpn (maybe NetworkManager?) is responsible for this change. Could you run openfortivpn with the -v option and see if the line `INFO:   Adding VPN nameservers...` appears? If yes, then there is something wrong with the config file parsing (but I can't reproduce it right now), if the line does not appear, the modification of your resolv.conf must be caused by something else.

**Comment by shalomb** [comment]
I don't see anything like `INFO: Adding VPN nameservers...` in the verbose output.

To rule out network-manager from the picture, I stopped the service and did this.

```
$ sudo service network-manager stop
$ sudo dhclient -v enp0s31f6
$ cat /etc/resolv.conf   # to verify my expected settings
$ sudo openfortivpn -v --config /etc/openfortivpn/office-vpn
...
$ cat /etc/resolv.conf   # old NSes are gone, new ones appear
$ cd /etc

$ sudo grep -lr 10.x.x.x /etc/      # 10.x.x.x being a nameserver given out by the VPN server
/etc/resolv.conf              # is newly generated
/etc/ppp/resolv.conf
/etc/resolv.conf.sslvpn.backup     # seems to be identical to /etc/ppp/resolv.conf
/etc/resolv.conf.pppd-backup.ppp0   # has my original resolv.conf before connecting

$ diff /etc/resolv.conf.sslvpn.backup /etc/ppp/resolv.conf; echo $?
0

$ sudo pkill openfortivpn
$ sudo grep -lr 10.x.x.x /etc/                                                                          
/etc/ppp/resolv.conf                  # remains the same
/etc/resolv.conf.sslvpn.backup  # remains the same

$ diff /etc/resolv.conf.sslvpn.backup /etc/ppp/resolv.conf; echo $?
0

```

```
$ openfortivpn --version
1.4.0
$ sudo rm /etc/ppp/resolv.conf /etc/resolv.conf.sslvpn.backup /etc/resolv.conf
$ sudo dhclient -v enp0s31f6
$ sudo openfortivpn --config /etc/openfortivpn/office-vpn
$ sudo grep -rl 10.x.x.x /etc/                                                                             
/etc/resolv.conf
/etc/ppp/resolv.conf
/etc/resolv.conf.pppd-backup.ppp0


(ins)$ sed -r -e 's/(1[09])[^ ]+/\1.x.x.x/g' -e 's/(domain|search) .*/\1 example.org/' /etc/resolv.conf
nameserver 10.x.x.x        # these 2 are the same seen in openfortivpn's output
nameserver 10.x.x.x        # INFO: Got addresses: [10.y.y.y], ns [10.x.x.x, 10.x.x.x]
domain example.org
search example.org
(ins)$ sed -r -e 's/(1[09])[^ ]+/\1.x.x.x/g' -e 's/(domain|search) .*/\1 example.org/' /etc/resolv.conf.pppd-backup.ppp0
domain example.org
search example.org
nameserver 10.x.x.x
nameserver 10.x.x.x
nameserver 10.x.x.x
nameserver 19.x.x.x
nameserver 19.x.x.x
(ins)$ sed -r -e 's/(1[09])[^ ]+/\1.x.x.x/g' -e 's/(domain|search) .*/\1 example.org/' /etc/ppp/resolv.conf
nameserver 10.x.x.x
nameserver 10.x.x.x

$ sudo pkill openfortivpn
$ sudo grep -lr 10.x.x.x /etc/
/etc/ppp/resolv.conf


(ins)$ sed -r -e 's/(1[09])[^ ]+/\1.x.x.x/g' -e 's/(domain|search) .*/\1 example.org/' /etc/ppp/resolv.conf
nameserver 10.x.x.x    
nameserver 10.x.x.x

(ins)$ sed -r -e 's/(1[09])[^ ]+/\1.x.x.x/g' -e 's/(domain|search) .*/\1 example.org/' /etc/resolv.conf
domain example.org
search example.org
nameserver 10.x.x.x
nameserver 10.x.x.x
nameserver 10.x.x.x
nameserver 19.x.x.x
nameserver 19.x.x.x

```

I'm not sure what `/etc/resolv.conf.sslvpn.backup` was as it didn't appear after deleting it and reconnecting, etc.

The presence of exactly the same NSes in `/etc/ppp/resolv.conf` in `/etc/resolv.conf` after connecting to the VPN suggests `ppp` is perhaps managing  `/etc/resolv.conf`. And sure enough, using `--pppd-no-peerdns` at the command-line does not generate a new `/etc/resolv.conf` ..

Sounds to me like a discrepancy between `set-dns` and  how `pppd` is managed?? I'll need to investigate more.

`openfortivpn` was built from source here at tag `v1.4.0`.

**Comment by mrbaseman** [comment]
pppd also has a couple of scripts in `/etc/ppp/ip-up.d/` and  `/etc/ppp/ip-down.d/`, one of them is called `000resolvconf` on my Ubuntu 16.04 and comes with the _resolvconf_ package, which is supposed to manage the contents of `/etc/resolv.conf`. This service has configuration files below `/etc/resolvconf/`. I think that I have installed the package explicitly, but there are also other services that have their hook scripts for `pppd`.
And I agree, handling of 'resolv.conf'-updates has room for improvement in _openfortivpn_. There are three options `--no-dns` , `--set-dns` , and `--pppd-no-peerdns` . The first one is kept as an alias for `--set-dns=0` which was introduced recently as a way to override a different setting form the configuration file. These two handle the built-in update of `resolv.conf`in _openfortivpn_, whereas the last one is a way to tell the `pppd` process which is called also not to update the name servers. 
I'm unsure if additional rules like "if A is set, then also assume B" make the things more intuitive. Maybe the details around the name server updates should just be documented in more detail.

**Comment by shalomb** [comment]
@mrbaseman - I don't seem to have anything `resolvconf` related in `/etc/ppp/ip*.d/`

```
$ ls -ld /etc/ppp/ip-*.d/*
-rwxr-xr-x 1 root root 293 Mar  2  2016 /etc/ppp/ip-up.d/exim4

$ cat /etc/ppp/ip-up.d/exim4
#!/bin/sh

if [ -n "$EX4DEBUG" ]; then
  echo "now debugging $0 $@"
  set -x
fi

[ -x /usr/lib/exim4/exim4 ] || exit 0

[ -f /etc/default/exim4 ] && . /etc/default/exim4

if [ "${QUEUERUNNER}" != "no" ] ; then
# Flush exim queue
        /usr/sbin/exim4 -qqf ${QUEUERUNNEROPTIONS} ${COMMONOPTIONS}
fi
```

Something is doing something behind the scenes - and the evidence suggests it is `pppd`.

I think I would be happy if `pppd-no-peerdns` was made an option I could include in a config file - just to be consistent in the way the other `--*` command-line options marry up with those you can specify in config. And that like me, you don't have to workaround with wrapper scripts.

**Comment by mrbaseman** [comment]
doesn't `pppd-use-peerdns=0` in the config file work for you?

**Comment by shalomb** [comment]
@mrbaseman - indeed, it does. I did try this before reporting the issue but must have made a typo when trying it out - but works just right now. Thanks 👍
