### ISSUE TITLE
After a disconnect a logout is required to reconnect

### ISSUE THREAD

**Issue by pedro2555** [adrienverge/openfortivpn#166]
My first connection attempt works correctly, however, once the connection drops I'm not able to reconnect back without logging out from the current OS user session.

The very first connection, works ok:
```bash
$ sudo openfortivpn <our_vpn_ip>:<our_vpn_port> -u <username>
WARN:   Bad port in config file: "0".
VPN account password: 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [x.x.x.x], ns [x.x.x.x, x.x.x.x]
INFO:   Got addresses: [x.x.x.x], ns [x.x.x.x, x.x.x.x]
INFO:   Got addresses: [x.x.x.x], ns [x.x.x.x, x.x.x.x]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```
However, after a connection drop (the case bellow was a simple laptop sleep):
```bash
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
WARN:   Could not delete route to vpn server (No such process).
INFO:   Removing VPN nameservers...
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```
And subsequent connection attempts keep failing:
```bash
$ sudo openfortivpn <our_vpn_ip>:<our_vpn_port> -u <username>
WARN:   Bad port in config file: "0".
VPN account password: 
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

Upon reading [http.c#L507](https://github.com/adrienverge/openfortivpn/blob/acfca243e7554b039e227f5184f4681beb5290bf/src/http.c#L507), this seems to be expected, and after a while (without logging out), the connection does work. But this is something I've never experienced in the Windows client.

_maybe not a bug, I'm sure I'm missing something here, not sure what it is._

**Comment by DimitriPapadopoulos** [comment]
We don't know at this point what happens when the laptop goes to sleep and when you restart you (graphical?) user session.
- You should probably run _opnefortivpn_ in debug mode (`-v`) to get more information.
- Do you experience that with different types of "connection drops" other than the laptop sleep?

Also I fail to understand how line http.c#L507 implies this is expected. Can you please explain?

**Comment by DimitriPapadopoulos** [comment]
@pedro2555 Any additional info on this issue?

**Comment by mrbaseman** [comment]
I assume we can close this one. If you disagree, please reopen.
