### ISSUE TITLE
OpenSSL version "too new"

### ISSUE THREAD

**Issue by calston** [adrienverge/openfortivpn#168]
```
checking for OpenSSL library location... /usr/lib
checking for OpenSSL include path... /usr/include
checking that we can build OpenSSL programs... yes
checking for OpenSSL version < 1.1.0... no
configure: error: in `/home/colin/openfortivpn-1.4.0':
configure: error: OpenSSL version too new
```

_Really_?

Debian GNU/Linux 9.1 (stretch)

**Comment by calston** [comment]
Meh, nevermind. It's fixed in master already

**Comment by mrbaseman** [comment]
the autoconf macros had a problem when linking against an openssl version 1.1 or newer. Unfortunately, this could result in a successful configure run and compile time errors which were difficult to understand. The configure check of the openssl version was a temporary workaround until a better soulution for the autoconf macros was found. As you have noticed, this is fixed on master already.

**Comment by calston** [comment]
Yeah, sorry about not checking that I am a dumbass before opening an issue

**Comment by mrbaseman** [comment]
Never mind. It wasn't documented well, and you have noticed that it's addressed on master even before I could reply. Anyhow, since the workaround is still in use in the current release, I  thought it's a good place to explain the background for the workaround in this issue.

**Comment by mrbaseman** [comment]
Ok, now a new release 1.5 has been tagged that contains the openssl 1.1 support
