### ISSUE TITLE
Increase cookie_size again ?

### ISSUE THREAD

**Issue by fcharras** [adrienverge/openfortivpn#171]
Openfortivpn used to work well, now I have an error that is very similar to https://github.com/adrienverge/openfortivpn/issues/18 and https://github.com/adrienverge/openfortivpn/pull/31 . 

Versions: 1.3 and 1.5.

The error message with -v -v -v options:

```
INFO:   Connected to gateway.
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=fTshQgQmsSaMFx4Yql7kRnV2sq88Da9POSLd1NlpdzYKmcp2PfU0KdM7qVbuv1QSb2HQ5eqEm8iYue0KY6xZEjLdvArS3PoGlEeyeRB7x2M73vJcvZtqO6t7b74M96BEzEOrNsj2FH9XzRVU3W+CrLy03jlv8jQex44YgedD/ZP1bJ410/FBYoRKqRX1pPUIgiyHsKCDW0ByGKM4JvLgihcWNPGrpCroYe4/Xn/Z8hnfdbZ2uDSHC1OpUo1SNprbxAO54ZgGWFuquFg6I7crW6PfBA5BTZipK
INFO:   Remote gateway has allocated a VPN.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  pppd_read_thread
DEBUG:  ssl_read_thread
DEBUG:  if_config thread
DEBUG:  ssl_write_thread
DEBUG:  pppd ---> gateway (16 bytes)
pppd:   c0 21 01 01 00 0e 01 04 05 4a 05 06 85 10 61 1f

DEBUG:  pppd_write thread
ERROR:  Received bad header from gateway:
  (hex) 48 54 54 50 2f 31 2e 31 20 34 30 33 20 46 6f 72 62 69 64 64 65 6e 0d 0a 44 61 74 65 3a 20 4d 6f 6e 2c 20 31 38 20 53 65 70 20 32 30 31 37 20 30 39 3a 32 39 3a 34 39 20 47 4d 54 0d 0a 53 65 72 76 65 72 3a 20 78 78 78 78 78 78 78 78 2d 78 78 78 78 78 0d 0a 53 65 74 2d 43 6f 6f 6b 69 65 3a 20 20 53 56 50 4e 43 4f 4f 4b 49 45 3d 3b 20 70 61 74 68 3d 2f 3b 20 65 78 70 69 72 65 73 3d 4d 6f 6e 2c 20 31 38 2d 53 65 70 2d 32 30 31 37 20 30 39 3a 32 39 3a 34 39 20 47 4d 54 3b 20 73 65 63 75 72 65 3b 20 68 74 74 70 6f 6e 6c 79 3b 0d 0a 53 65 74 2d 43 6f 6f 6b 69 65 3a 20 53 56 50 4e 4e 45 54 57 4f 52 4b 43 4f 4f 4b 49 45 3d 3b 20 70 61 74 68 3d 2f 72 65 6d 6f 74 65 2f 6e 65 74 77 6f 72 6b 3b 20 65 78 70 69 72 65 73 3d 4d 6f 6e 2c 20 31 38 2d 53 65 70 2d 32 30 31 37 20

  (raw) HTTP/1.1 403 Forbidden.
Date: Mon, 18 Sep 2017 09:29:49 GMT.
Server: xxxxxxxx-xxxxx.
Set-Cookie:  SVPNCOOKIE=; path=/; expires=Mon, 18-Sep-2017 09:29:49 GMT; secure; httponly;.
Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Mon, 18-Sep-2017
```

Edit: I can confirm that setting cookie_size even higher fix the issue for me.

**Comment by DimitriPapadopoulos** [comment]
@fcharras When you write that "Openfortivpn used to work well" and now doesn't:
* Have you changed something on the client side, such as the _openfortivpn_ version?
* Has the computer changed?
* When did this error message appear again?

Otherwise it might well be that the cookie size changed again in new VPVN versions...

**Comment by DimitriPapadopoulos** [comment]
Since setting **`COOKIE_SIZE`** higher fixes the problem:

In the long term:
* We should probably detect the cookie size and allocate `tunnel->config->cookie` dynamically.

In the short term:
* Add a debug message that prints the size of the cookie in `buf`.
* Increase `COOKIE_SIZE` to an acceptable size.

Could you tell us the size of the cookie?

**Comment by fcharras** [comment]
Answering both set of questions:
 - nothing changed client side
 - the computer didn't change
 - this error message appeared last week
 - I'm not aware if the server I use to connect to perform an update
 - The size of the cookie is **exactly** 300.

**Comment by DimitriPapadopoulos** [comment]
@fcharras I guess something has been changed/updated on the server then.

Anyway, the cookie printed in debug mode is truncated to 300 already. Need to add code to report the size of the cookie and check it's not larger than `COOKIE_SIZE` a little bit before `log_debug`.

**Comment by DimitriPapadopoulos** [comment]
@fcharras have a look at commit 3304b20.

Could you modify the code accordingly and report the cookie size printed in debug mode?

**Comment by fcharras** [comment]
@DimitriPapadopoulos  
`DEBUG:  Cookie larger than expected: 311 > COOKIE_SIZE`

**Comment by DimitriPapadopoulos** [comment]
Great, thank you for reporting back.

Unfortunately the size of the cookie sent by FortiGate is not documented anywhere, at least not in any public document crawled by Google as far as I can see. Therefore in the short term:
* I can increase `COOKIE_SIZE` from 300 to 350 to be on the safe side.
* A clear error message will be printed and _openfortivpn_ will bail out if ever the cookie size is larger than `COOKIE_SIZE` again.

**Comment by DimitriPapadopoulos** [comment]
According to [RFC 2109](https://www.ietf.org/rfc/rfc2109.txt):

> ### 6.3  Implementation Limits
> 
> Practical user agent implementations have limits on the number and size of cookies that they can store.  In general, user agents' cookie support should have no fixed limits.  They should strive to store as many frequently-used cookies as possible.  Furthermore, general-use user agents should provide each of the following minimum capabilities individually, although not necessarily simultaneously:
> * at least 300 cookies
> * at least 4096 bytes per cookie (as measured by the size of the characters that comprise the cookie non-terminal in the syntax description of the Set-Cookie header)
> * at least 20 cookies per unique host or domain name
> 
> User agents created for specific purposes or for limited-capacity devices should provide at least 20 cookies of 4096 bytes, to ensure that the user can interact with a session-based origin server.
> 
> The information in a Set-Cookie response header must be retained in its entirety.  If for some reason there is inadequate space to store the cookie, it must be discarded, not truncated.
> 
> Applications should use as few and as small cookies as possible, and they should cope gracefully with the loss of a cookie.

**Comment by DimitriPapadopoulos** [comment]
I have increased `COOKIE_SIZE` to 4096 as per [RFC 2109](https://www.ietf.org/rfc/rfc2109.txt).

I have also add some code to handle more gracefully larger cookie sizes should that ever happen - but it shouldn't!

**Comment by fcharras** [comment]
This looks good, thank you!
