### ISSUE TITLE
Update Install documentation for Arch ?

### ISSUE THREAD

**Issue by fcharras** [adrienverge/openfortivpn#178]
Somebody is maintaining an up-to-date repository in the AUR:
https://aur.archlinux.org/packages/openfortivpn/

**Comment by patrickhanft** [comment]
I guess, this somebody would be me. :-)

Actually me maintainting the AUR package is kind of "best effort". I did not put out an update for 1.4 as I Arch already shipped OpenSSL 1.1 against which openfortivpn did not compile. I'll do my best as long as  something unexpected like this doesn't happen again … ;-)

**Comment by DimitriPapadopoulos** [comment]
@patrickhanft Thank you Patrick for packaging _openfortivpn_.

Don't worry, on Debian/Ubuntu packages are stuck back to version 1.2 or something like that, so it's much worse there!
