### ISSUE TITLE
Connection closing, when used without --set-dns=0

### ISSUE THREAD

**Issue by xalkina** [adrienverge/openfortivpn#186]
Connecting to a remote by passing on the command line only the following:
- credentials
- trusted cert

Getting the following output:

INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
INFO:   Got addresses: [10.240.240.8], ns [172.22.250.244, 172.22.250.214]
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

When adding --set-dns=0 in the command line everything works properly.

Had a quick look in io.c, but not enough to make sense...

**Comment by skuti-is** [comment]
@xalkina  wild guess... loop at remote host? Have you tested reboot or firmware upgrade on the Fortigate box?

**Comment by xalkina** [comment]
a) I don't really have control on the Forti device, so can't do any of these.

b) I'm not sure I understand what kind of loop one could get in when specifying name servers...

c) Not using the name servers anyway, but this was happening consistently.

**Comment by DimitriPapadopoulos** [comment]
Can you run _openfortivpn_ with option `-v`?
Also which versions of _openfortivpn_ is this?
Finally any related _pppd_ messages in the system log?

**Comment by DimitriPapadopoulos** [comment]
@xalkina Any luck getting this to work a more recent version of _openfortivpn_? If you still have problems, please tell us so that we can keep looking into this. Otherwise I shall close this ticket.
