### ISSUE TITLE
"ERROR:  read: Input/output error" on Solus 3.26.1

### ISSUE THREAD

**Issue by llugon** [adrienverge/openfortivpn#194]
I have this error when running on my Solus 3.26.1 distrib : 

DEBUG:  Loaded config file "/etc/openfortivpn/config".
VPN account password: 
DEBUG:  Config host = <actual_host_name>
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = <actual_user_name>
DEBUG:  Config password = "********"
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
Two-factor authentication token: 
DEBUG:  Cookie: SVPNCOOKIE=cV+HTBlCY/KZDGzy72Z9Ow8sbONM5hNFXOGVzHP5eySZq89UhLPH5edz6tvJlIi4%0aCIu79MrHN9mUshbbGB1ZwWjXL2PANoyBhlXjs61AaX/5WqUPlmI5gUTkEiSvkRwC%0at05AQwRu/D6k4EYCUb4ViYgeFqRNUCAZ8VEJFT/FxmY=%0a
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=cV+HTBlCY/KZDGzy72Z9Ow8sbONM5hNFXOGVzHP5eySZq89UhLPH5edz6tvJlIi4%0aCIu79MrHN9mUshbbGB1ZwWjXL2PANoyBhlXjs61AaX/5WqUPlmI5gUTkEiSvkRwC%0at05AQwRu/D6k4EYCUb4ViYgeFqRNUCAZ8VEJFT/FxmY=%0a
INFO:   Remote gateway has allocated a VPN.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  pppd_read_thread
DEBUG:  ssl_read_thread
DEBUG:  ssl_write_thread
DEBUG:  pppd_write thread
DEBUG:  if_config thread
**ERROR:  read: Input/output error**
INFO:   Cancelling threads...
DEBUG:  Waiting for pppd to exit...
DEBUG:  waitpid: pppd exit status code 1
DEBUG:  pppd: pppd has detached, or otherwise the connection was successfully established and terminated at the peer's request
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.

I've looked into src/io.c if_config, but I don't have any clue of what happens.
Credentials and two-factor auth are OK (I've tried from my smartphone).

Here is my config : 
```
# config file for openfortivpn, see man openfortivpn(1)
host = <actual_host_name>
port = 443
username = <actual_user_name>
trusted-cert = d001069b34910f4e29fc718a15062f730d859af10189ad2d9f794d3de1c3c5a4
```

openfortivpn --version : 1.5.0

Any idea ? My guess is a missing package from my distrib ? Thanks !

(if it's not clear, actual_host_name and actual_user_name are just placeholders ^^ It's correctly configured here. I just don't wanna show those information :-P )

**Comment by mrbaseman** [comment]
pppd is installed? That's a typical mistake which results in a similar error. 
Sometimes there is a mismatch between the running kernel and the device driver after a kernel update. A reboot helps to solve the problem (which would anyway be needed to activate the freshly installed kernel). 
Another reason could be a routing issue: check if your vpn gateway is still reachable when the tunnel is up. If by mistake (misconfiguration of the pushed routes) the traffic of the tunnel itself is routed into the tunnel again, it won't work.

**Comment by llugon** [comment]
Thank you. I did not think there was a openfortivpn package for eopkg ! I did not even try to search for it oO' 
Indeed, after a `sudo eopkg install openfortivpn` the following libs where missing : 
libpcap, version 1.3.0, release 2
ppp, version 2.4.7, release 2

Now it's working perfectly ! Thank you !

Maybe you can add that it is packaged as well for Solus on your doc : 

> openfortivpn is packaged for Fedora, Gentoo, NixOS and Arch Linux under the package name openfortivpn.

Cheers !

**Comment by mrbaseman** [comment]
@llugon thanks for the feedback. We have updated the README.md file on our master branch

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Shouldn't version 1.5.0 print the following error message when _pppd_ cannot be found? I cannot find the error message in the output posted by @llugon.
```execvp: No such file or directory```

The relevant code in **tunnel.c** is:
```
		execvp(args[0], args);
		fprintf(stderr, "execvp: %s\n", strerror(errno));
		exit(EXIT_FAILURE);
```

**Comment by DimitriPapadopoulos** [comment]
Is this an effect of `forkpty`?

**Comment by DimitriPapadopoulos** [comment]
In any case it happens often enough that `/usr/sbin/pppd` is missing to have a specific test for that. See pull request #197.

**Comment by mrbaseman** [comment]
hmm... I'm not sure if there should have been the above error message, or if not, why exactly the message would not appear. In any case, like in #56 installing the ppp package seems to have solved the problem.

**Comment by llugon** [comment]
I have done multiple test before installing the missing libs, And I never saw the following message : 
> execvp: No such file or directory

But I can re-produce fairly easily the issue by removing libpcap and ppp. Let me know if this is of any use, and I'll do it !

**Comment by DimitriPapadopoulos** [comment]
I think `frprintf(stderr, ...)` doesn't print anything because of the prior call to _forkpty_(). We can as well remove it and rely on the error message in pull request #197.
