### ISSUE TITLE
Allow other options in config file

### ISSUE THREAD

**Issue by palos-ba** [adrienverge/openfortivpn#20]
The config file can contain only some keys but not all of usable commandline parameters.
Please add support of all of the parameters (notably no-dns) as keys in the config file.

**Comment by lkundrak** [comment]
Yeah, it doesn't sound like a bad idea.

Patches welcome here.

**Comment by mvk** [comment]
Would refactoring the command line processing to use argtable be acceptable change (keeping the old "api", of course)?

**Comment by adrienverge** [comment]
If it's well done and removes more lines than it adds, why not. Does argtable support config files (I don't see the relation with this issue)?

**Comment by mrbaseman** [comment]
@palos-ba the config file options were already supported but just undocumented (at least a few weeks ago, when I had a look at the source). I have submitted a patch for the man page which was accepted a few days ago. The analogon for `--no-dns` is `set-dns = 0` in the config file

**Comment by palosBA** [comment]
You're right, the option is there from commit a64bc64d93a1adaa1f4d612fbcc94e51e66174c1 (24 Dec 2015).
Thanks to you and @kdmcclel

**Comment by palos-ba** [comment]
You're right, the option is there from commit a64bc64d93a1adaa1f4d612fbcc94e51e66174c1 (24 Dec 2015).
Thanks to you and @kdmcclel
