### ISSUE TITLE
Error: syntax error near unexpected token `OPENSSL,'

### ISSUE THREAD

**Issue by ToonMeynen** [adrienverge/openfortivpn#208]
When I ran ./configure --prefix=/usr/local --sysconfdir=/etc I got the following error. 

```
checking host system type... x86_64-pc-linux-gnu
checking whether make supports nested variables... (cached) yes
./configure: line 4493: syntax error near unexpected token `OPENSSL,'
./configure: line 4493: `PKG_CHECK_MODULES(OPENSSL, libcrypto libssl)'
```

I googled a bit and installed 
```
apt-get install pkg-config
```

Afterward I reran 
./autogen.sh
./configure --prefix=/usr/local --sysconfdir=/etc

And it completed.

**Comment by mrbaseman** [comment]
which distribution is this? We could add a hint about `pkg-config` in `README.md`

**Comment by ccollicutt** [comment]
I had this problem in ubuntu 16.04.

**Comment by emepetres** [comment]
I can reproduce the problem, using Ubuntu Xenial x64

**Comment by masacc** [comment]
I can also reproduce it in ubuntu 17.10

**Comment by DimitriPapadopoulos** [comment]
Does the [new branch](https://github.com/mrbaseman/openfortivpn/tree/improve_autoconf) help?

**Comment by masacc** [comment]
I used ToonMeynen procedure not the new branch

**Comment by DimitriPapadopoulos** [comment]
It would be great if someone could try the new branch and report if it helps or not.

**Comment by mrbaseman** [comment]
by the way the improvements for autoconf usage have been merged in the meantime. The current master branch should detect if `pkg-config` is available now and emmit an error message if it is not

**Comment by mrbaseman** [comment]
I think we can close this since the improvements to the build system have been merged quite a while ago

**Comment by 4t8dd** [comment]
> 16.04

This helps me.
when everything works fine in a live container. But when I try to build a image, I would have to install this pkg-config

**Comment by DimitriPapadopoulos** [comment]
@4t8dd I am afraid I cannot understand your post. This is a ticket from 2017 and the issue has been fixed meanwhile.  Please provide some context, at least show an error message. Preferably in a new post.
