### ISSUE TITLE
what's the purpose of the --sysconfdir flag

### ISSUE THREAD

**Issue by fretn** [adrienverge/openfortivpn#21]
Whats the purpose of the --syscondir flag for the configure script ?

I've set it to a folder somewhere but when i run openfortivpn it complains that /etc/openfortivpn/config is not found

**Comment by adrienverge** [comment]
Without `--syscondir`, the sample config file is installed to `/usr/etc/openfortivpn`, which most users (and packaging scripts) don't want.

You can safely remove this flag if you prefer, and use `--config` to reference your other folder.
