### ISSUE TITLE
header file inclusion order: top-down header file ordering

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#216]
I suggest header file inclusion follows these rules:
1. The header file that declares the functions being defined in the source file is the very first that is included.
2. Other header files from the same project are included next.
3. Header files from non-standard projects (e.g., eigen, boost, Qt) are included after local headers.
4. Finally, standard header files are included last.
5. Out of order inclusions need to be clearly documented with regard to why the header was not included in the above order.

See for example:
* [C/C++ header file inclusion order](http://linux.topology.org/include.html)
* [C header file order](https://softwareengineering.stackexchange.com/questions/325549/c-header-file-order)

**Comment by adrienverge** [comment]
Looks good.

What do you propose about alphabetical order? For example in #217 at src/config.h you write:
```diff
 #include <errno.h>
-#include <netinet/in.h>		
 #include <string.h>
+#include <sys/types.h>
+#include <netinet/in.h>
```

**Comment by DimitriPapadopoulos** [comment]
Oh, there's no real alphabetical order here. It's probably in approximate order of appearance of the relevant definitions in the source code. I reviewed the code and for each imported function/type/constant I looked up which header defines the function/type/constant in POSIX. I remove a couple useless includes in the process and explicitly added a few more that are required according to POSIX, but were implicitly included by other headers.

**Comment by adrienverge** [comment]
Good for me!

**Comment by mrbaseman** [comment]
It would be good if this could be tested on MacOSX, because some of the header includes are moved out of the  `#ifdef __APPLE__` areas. 
Maybe, @Mabin-J could you give it a try, please?

**Comment by DimitriPapadopoulos** [comment]
Indeed, they're moved out of  `#ifdef __APPLE__` but they're still and **always** there. So it should work - but I agree it's best to actually test that!

**Comment by DimitriPapadopoulos** [comment]
I've just compiled on OS X 10.11.6 (and Linux of course) and it works without problem.

OK to merge?

**Comment by mrbaseman** [comment]
yes, I don't see any issues
