### ISSUE TITLE
add pppd options "call" or "file"

### ISSUE THREAD

**Issue by leo-b** [adrienverge/openfortivpn#22]
Sometimes additional pppd options are needed, e.g. to set connection specific routes when the link goes up.

If openfortivpn could pass a "call <filename>" (or "file <filename>") option to pppd, any additional pppd-options could be specified in that file.

**Comment by mrbaseman** [comment]
I have just noticed this old issue. In 1.3.1 ipparam is supported. Is that useful for you? it is passed by pppd to the ip-up and ip-down scripts

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Perhaps we should close this issue. I understand the new `ipparam` is an alternative solution.

@leo-b Any comments?

**Comment by mrbaseman** [comment]
I agree, let's close it if there is no further reaction in the ticket in the near future.
