### ISSUE TITLE
configure checks for functions and headers 

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#222]
AC_CHECK_FUNCS in configure.ac checks for the existence of a couple of functions, but the list seems to be incomplete. I have extracted a list of calls to functions or function-like calls to macros for instance, and removed those defined in the source itself. However, a quite lengthy list remains: 
`assert atoi cast_addr close connect CRYPTO_set_id_callback CRYPTO_set_locking_callback execv exit _exit fclose fcntl fflush fopen forkpty fprintf fputs free freeaddrinfo freeifaddrs freopen fwrite getaddrinfo getchar getenv getopt_long htons index inet_addr inet_ntoa isatty malloc memcpy memmem memmove memset open openlog OPENSSL_free pclose popen printable_char printf pthread_cancel pthread_cond_init pthread_cond_signal pthread_cond_wait pthread_join pthread_mutexattr_init pthread_mutexattr_setrobust pthread_mutex_destroy pthread_mutex_init pthread_mutex_lock pthread_mutex_unlock pthread_sigmask puts read realloc rewind  select setenv sigaddset sigemptyset signal snprintf socket sprintf SSL_CTX_free SSL_CTX_new SSL_CTX_set_options  SSL_free SSL_get_error SSL_get_peer_certificate SSL_get_verify_result SSL_library_init SSL_load_error_strings SSL_new SSL_read SSL_set_mode SSL_set_verify SSL_shutdown  SSL_write strcasestr strcat strchr strcmp strcpy strdup strerror strlen strncasecmp strncat strncpy strsignal strstr strtob strtok strtok_r strtol syslog system tcsetattr usleep va_end va_start vprintf vsnprintf vsyslog write`
If I add the list to AC_CHECK_FUNCS the configure run performs a number of checks and adds the result to the Makefile: 
`DEFS = -DPACKAGE_NAME=\"openfortivpn\" -DPACKAGE_TARNAME=\"openfortivpn\" -DPACKAGE_VERSION=\"1.5.0\" -DPACKAGE_STRING=\"openfortivpn\ 1.5.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"openfortivpn\" -DVERSION=\"1.5.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBUTIL=1 -DHAVE_ARPA_INET_H=1 -DHAVE_FCNTL_H=1 -DHAVE_NETDB_H=1 -DHAVE_NETINET_IN_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_IOCTL_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_GETADDRINFO=1 -DHAVE_INET_NTOA=1 -DHAVE_NTOHS=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_MEMMEM=1 -DHAVE_SELECT=1 -DHAVE_SOCKET=1 -DHAVE_STRERROR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_ATOI=1 -DHAVE_CLOSE=1 -DHAVE_CONNECT=1 -DHAVE_EXECV=1 -DHAVE_EXIT=1 -DHAVE__EXIT=1 -DHAVE_FCLOSE=1 -DHAVE_FCNTL=1 -DHAVE_FFLUSH=1 -DHAVE_FOPEN=1 -DHAVE_FORKPTY=1 -DHAVE_FPRINTF=1 -DHAVE_FPUTS=1 -DHAVE_FREE=1 -DHAVE_FREEADDRINFO=1 -DHAVE_FREEIFADDRS=1 -DHAVE_FREOPEN=1 -DHAVE_FWRITE=1 -DHAVE_GETADDRINFO=1 -DHAVE_GETCHAR=1 -DHAVE_GETENV=1 -DHAVE_GETOPT_LONG=1 -DHAVE_HTONS=1 -DHAVE_INDEX=1 -DHAVE_INET_ADDR=1 -DHAVE_INET_NTOA=1 -DHAVE_ISATTY=1 -DHAVE_MALLOC=1 -DHAVE_MEMCPY=1 -DHAVE_MEMMEM=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_OPEN=1 -DHAVE_OPENLOG=1 -DHAVE_PCLOSE=1 -DHAVE_POPEN=1 -DHAVE_PRINTF=1 -DHAVE_PTHREAD_CANCEL=1 -DHAVE_PTHREAD_COND_INIT=1 -DHAVE_PTHREAD_COND_SIGNAL=1 -DHAVE_PTHREAD_COND_WAIT=1 -DHAVE_PTHREAD_JOIN=1 -DHAVE_PTHREAD_MUTEXATTR_INIT=1 -DHAVE_PTHREAD_MUTEXATTR_SETROBUST=1 -DHAVE_PTHREAD_MUTEX_DESTROY=1 -DHAVE_PTHREAD_MUTEX_INIT=1 -DHAVE_PTHREAD_MUTEX_LOCK=1 -DHAVE_PTHREAD_MUTEX_UNLOCK=1 -DHAVE_PTHREAD_SIGMASK=1 -DHAVE_PUTS=1 -DHAVE_READ=1 -DHAVE_REALLOC=1 -DHAVE_REWIND=1 -DHAVE_SELECT=1 -DHAVE_SETENV=1 -DHAVE_SIGADDSET=1 -DHAVE_SIGEMPTYSET=1 -DHAVE_SIGNAL=1 -DHAVE_SNPRINTF=1 -DHAVE_SOCKET=1 -DHAVE_SPRINTF=1 -DHAVE_STRCASESTR=1 -DHAVE_STRCAT=1 -DHAVE_STRCHR=1 -DHAVE_STRCMP=1 -DHAVE_STRCPY=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRLEN=1 -DHAVE_STRNCASECMP=1 -DHAVE_STRNCAT=1 -DHAVE_STRNCPY=1 -DHAVE_STRSIGNAL=1 -DHAVE_STRSTR=1 -DHAVE_STRTOK=1 -DHAVE_STRTOK_R=1 -DHAVE_STRTOL=1 -DHAVE_SYSLOG=1 -DHAVE_SYSTEM=1 -DHAVE_TCSETATTR=1 -DHAVE_USLEEP=1 -DHAVE_VPRINTF=1 -DHAVE_VSNPRINTF=1 -DHAVE_VSYSLOG=1 -DHAVE_WRITE=1`

if there was also an action-if-not-found defined as `AC_MSG_ERROR([Required function not present])` in the macro call (https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Generic-Functions.html) the configure run would stop at the first hit of a call to an unknown function. Well, with the above list it fails for `assert()` which might be a special case. Maybe there are also some false hits still in my list. Anyhow, shall we change the behavior of configure, and shall we expand the list?...and what is the check currently good for? I don't see any `#ifdef HAVE_something` lines

The same applies for the headers: The following system/library headers are included: `arpa/inet.h assert.h ctype.h errno.h fcntl.h getopt.h ifaddrs.h limits.h mach/mach.h netdb.h net/if.h netinet/in.h netinet/tcp.h net/route.h openssl/err.h openssl/ssl.h pthread.h pty.h semaphore.h signal.h stdarg.h stddef.h stdint.h stdio.h stdlib.h string.h sys/ioctl.h syslog.h sys/socket.h sys/stat.h sys/time.h sys/types.h sys/wait.h termios.h unistd.h util.h` 
not all of them are checked with AC_CHECK_HEADER and the configure check doesn't make use of action-if-not-found https://www.gnu.org/software/autoconf/manual/autoconf-2.62/html_node/Generic-Headers.html
Should that be changed or is it ok to set up a basic configure environment and see how far we get when trying to compile?

**Comment by DimitriPapadopoulos** [comment]
I believe all those functions and headers are standard on Linux and BSD systems these days. They might be useful on more exotic systems: very old Linux distributions, Unix systems, etc.

I don't know if it's worth the hassle. If you can setup a basic and not too recent Linux environment, then it's a good idea to see how far we get and fix only the necessary at this point. If there's interest in Solaris or Irix or whatever, then we can try to build on such systems (but then PPPD is probably not installed in `/usr/sbin/pppd`).

Finally _assert_() is necessarily a macro which is maybe why it fails.

Also the checks should emit an error and stop if a function/header is missing. As you noticed we have no `#ifdef HAVE_something` in the code to work around such issues.

One thing that might be nice would be to change the `#ifdef __APPLE__` tests in header inclusions and replace them with autotools-related ifdefs. Typically to switch from `<pty.h>` to `<utils.h>` for _forkpty_(). Don't know if that's possible though.

**Comment by mrbaseman** [comment]
I'll try to set up a very basic VM with an old Ubuntu or CentOS to see where we run into problems. A variant of BSD would also be interesting to look at. Maybe I can do that, too. I have started [this branch](https://github.com/mrbaseman/openfortivpn/tree/improve_autoconf) to address #208 which is somewhat related - at least it is in the same code area.

**Comment by DimitriPapadopoulos** [comment]
Testing on a BSD variant would be nice indeed.

**Comment by mrbaseman** [comment]
I have tested with Centos 6.9 (minimal installation) now. One result of this is that the required autoconf version can be lowered, and `autogen.sh` should check if `aclocal`, `autoconf`, and `automake` exist before calling them.  The CentOS 5 branch is end of life already, so it's probably not worth trying with that one. 
So, next I'll install an oldish Ubuntu and OpenBSD or FreeBSD to see how the build works there.

**Comment by DimitriPapadopoulos** [comment]
On CentOS, is _pkg-config_ always installed if _autoconf_/_automake_ are installed?

**Comment by DimitriPapadopoulos** [comment]
Indeed some "real-life" `autogen.sh` files check `autodonf` and the like exist: 
https://github.com/carlobaldassi/liblqr/blob/master/autogen.sh
https://github.com/erikd/libsndfile/blob/master/autogen.sh

**Comment by mrbaseman** [comment]
On CentOS 6 `pkg-config` was pre-installed. The `autoconf` and `automake` rpms don't require it, but I have added a configure check in https://github.com/adrienverge/openfortivpn/pull/227/commits/a9f2aa714eac3942b2fed47bd4ef73b7bf6111aa which tells the user to install it before the configure script tries to use it

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos do you think we should also check the versions of `autoconf` and `automake` in `autogen.sh`, or is a simple check with `type` like this https://github.com/adrienverge/openfortivpn/pull/227/commits/521d22f939d6cf9a99e869f991cd9377bde2db8b sufficient?

**Comment by DimitriPapadopoulos** [comment]
I believe it will (or should) work with any decently recent version of `automake` or `autoconf`. Unless proven wrong, I wouldn't bother requiring a minimal version - the priority is keeping it simple.

**Comment by DimitriPapadopoulos** [comment]
`type` looks perfect to me.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman Martin, can we close this issue after your latest commits (4c1f79b)?

**Comment by mrbaseman** [comment]
Yes, we can close it. Just a side remark: I have noticed that I have merged the line about FreeBSD in the `README.md` by mistake. I wanted to move everything related to BSD support into a spearate issue. Anyhow, I have already stated that the BSD port is not completed yet. Maybe we can leave it that way and just remove this additional remark when the work on BSD support is completed.

**Comment by DimitriPapadopoulos** [comment]
Doesn't really matter about BSD. Hopefully BSD support will be ready in time for _openfortivpn_ 1.7.0, so it shouldn't be an issue.
