### ISSUE TITLE
Error do-add-ip4-route[0.0.0.0/0]:

### ISSUE THREAD

**Issue by CristianCardosoA** [adrienverge/openfortivpn#224]
I'm using Fedora 26, NetworkManager-fortisslvpn.x86_64
I tried both ways from :
1.- fedora repositories via yum dnf 
2.- git clone make install **(version 1.5.0)**

I had never use the propietary software _FortiClient_, I will do it today.

But with openfortivpn, I'm getting this issue after vpn is connected: platform-linux: do-add-ip4-route[7: 0.0.0.0/0 50]: failure 100 (Network is down). 

The system administrator seems like he putted a couple of static routes.

**Comment by CristianCardosoA** [comment]
Is working with _FortiClient_ property software.

**Comment by DimitriPapadopoulos** [comment]
It is not clear whether you run _openfortivpn_ directly from the command line, or perhaps using the NetworkManager GUI.

**Comment by CristianCardosoA** [comment]
I tried both, but the error is specifically in terminal.

openfortivpn 201.168.***.****:443 -u invitado --no-routes --trusted-cert=3d95c5cce77d7519bbac9ecb6abc2818f55b6bb3f2c88e979e740e17e8896**** --ca-file=/home/cristian/.cert/certificate.crt -v

**Comment by DimitriPapadopoulos** [comment]
@CristianCardosoA Were you able to fix this? Did `--half-internet-routes=1` help?

**Comment by DimitriPapadopoulos** [comment]
Also couldn't this be a NetworkManager issue? See for example:
* [Red Hat Bugzilla - Bug 1266440 - VPN fails when a static route is defined](https://bugzilla.redhat.com/show_bug.cgi?id=1266440)
* [Bugs: network-manager package: Ubuntu - Bug#1608646 - ip4 static routes added in NetworkManager UI fail and prevent connection](https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1608646)

**Comment by CristianCardosoA** [comment]
No, didn't fix it. I don't think is a Red Hat issue because with proprietary software works fine.

**Comment by DimitriPapadopoulos** [comment]
What if you remove the static routes from the Red Hat configuration? Does it help?
If it does, this is probably the Red Hat [Bug 1266440](https://bugzilla.redhat.com/show_bug.cgi?id=1266440)
