### ISSUE TITLE
[Feature request] encrypt text-plain password on config file

### ISSUE THREAD

**Issue by navarroaxel** [adrienverge/openfortivpn#233]
Hi, Could I encrypt the text-plain VPN password on the config file?

**Comment by DimitriPapadopoulos** [comment]
Mmmh... But then how do you decrypt it? With another password?

**Comment by navarroaxel** [comment]
I think about CNTLM what has the following command to generate a hashed password and CNTLM can make the handshake with that hash. I don't know if forti has type of handshake.

```bash
cntlm -H
PassLM          790339D0A7C5FF1948A1F372896AB5AF
PassNT          FFECC4864BF7279221E4F53909921B75
PassNTLMv2      FD4B9F65F8FDDFF3CC9C0C0CCC641E61
```

I don't know how works [theinvisible/openfortigui](https://github.com/theinvisible/openfortigui). But when I run it with sudo, the app takes the config file from my home folder. This saves the encrypted password and the encryption keys on my home dir, I feel this a little more secure.

That project depends of this.

**Comment by DimitriPapadopoulos** [comment]
Thanks for the reference to [theinvisible/openfortigui](https://github.com/theinvisible/openfortigui). Indeed it encrypts/decrypts the password with AES (and Base64). See _ticonfmain.cpp_, [line 194](https://github.com/theinvisible/openfortigui/blob/75ccd62/openfortigui/ticonfmain.cpp#L194):
```
    QTinyAes aes(QTinyAes::CBC, main_settings->getValue("main/aeskey").toByteArray(), main_settings->getValue("main/aesiv").toByteArray());
    ...
    f->setValue("password", QString::fromUtf8(aes.encrypt(profile.password.toUtf8()).toBase64()));
```
and  [line 250](https://github.com/theinvisible/openfortigui/blob/75ccd62/openfortigui/ticonfmain.cpp#L250):
```
                QTinyAes aes(QTinyAes::CBC, main_settings->getValue("main/aeskey").toByteArray(), main_settings->getValue("main/aesiv").toByteArray());
                ....
                vpnprofile->password = QString::fromUtf8(aes.decrypt(QByteArray::fromBase64(f->value("password").toString().toUtf8())));
```
The encryption key is readily available in the application settings under `main/aeskey`. So while the password appears to be encrypted, it can actually be decrypted in a straightforward way.
This whole issue has been often discussed in the past. Encryption provides a false sense of security: if an attacker has access to the VPN profile, then the attacker has also access to the encryption key in the application settings. Is it worth trying to just obfuscate things? If a hacker finds `password` and is interested, it will talk 5 to 10 minutes at most to figure how to decrypt the password the first time, then virtually no time at all once the decryption method is coded in the attack toolkit. Encryption doesn't bring much. If you want more security, don't save your password in a file (better yet use one-time passwords), use a master password manager such as the [GNOME Keyring](https://wiki.gnome.org/Projects/GnomeKeyring), or encrypt the whole hard disk (that's what I do on my laptop). But you still need to remember a master password.
For example have a look at the [Git's credential system](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage).

**Comment by DimitriPapadopoulos** [comment]
I believe the right thing to do would be to interface with [Keychain Access](https://support.apple.com/kb/PH20093) on OS X and equivalent solutions on other systems.
But remember, once an attacker has gained access to your account, there's not much that can be done to protect your passwords, except a new master password different from the session password, to encrypt data such as VPN passwords.

**Comment by navarroaxel** [comment]
@DimitriPapadopoulos openfortigui has a one time wizard when starts the app to generate a new encryption or keep the default one. 
I can keep the password blank to enter when I connect. 
But my home folder is encrypted and maybe there is a better solution than specify a different location for the config file.
How can I integrate GNOME keyring with this app?

**Comment by DimitriPapadopoulos** [comment]
The wizard doesn't change the fact that the encryption key and the encrypted password are both in the home dir. If the home dir is encrypted then you don't really need to encrypt the password, do you?

The main difference between all these solutions is which password is used, and when and for how long is the password available unencrypted:
- account password unlocks the "system" password manager directly at login
- a different master password unlocks another password manager, perhaps only on request.

Currently _openfortivpn_ doesn't interface with Gnome keyring or Keychain Access. Not sure we want that or can do that easily in a command-line program. It's probably best done in a GUI such as [theinvisible/openfortigui](https://github.com/theinvisible/openfortigui).

**Comment by DimitriPapadopoulos** [comment]
Also I'm pretty sure the _CNTLM_ function you describe is about  protecting the password on the server: the server doesn't need to know or store the password, only the hashing function and the hash of the password. Chances are FortiGate devices use something similar internally.

This is not related to storing the plain password on the client side. You still need the plain password on the client side. That plain password is hashed and compared to the hash stored on the server.

**Comment by theinvisible** [comment]
Hi, the latest OpenfortiGUI supports GNOME-Keyring/KWallet Integration as experimental feature. Its implemented via qtkeychain. Hope thus helps.

**Comment by DimitriPapadopoulos** [comment]
@theinvisible Thank you for letting us know. That's a great feature you have added.

Since you now have some experience with password managers, do you think it would make sense to integrate a command-line program such as _openfortivpn_with password managers? I'm asking because _openfortivpn_ also runs on macOS and it would help communicating with password manager independently of Gnome/KDE.

**Comment by DimitriPapadopoulos** [comment]
On macOS [Keychain services](https://developer.apple.com/documentation/security/keychain_services) do not have a C API as far as I can see, they require a Swift wrapper. Perhaps password manager integration is best left to a GUI after all...

**Comment by mrbaseman** [comment]
Given the silence for half a year, I assume we can close this issue. If you don't agree, please reopen (or open a new ticket and refer to this one).

**Comment by linroex** [comment]
or maybe save hashed password in config? 
plain text password is not good

**Comment by DimitriPapadopoulos** [comment]
@linorex See previous https://github.com/adrienverge/openfortivpn/issues/233#issuecomment-344066860. Hashing the password in the config file is not possible without another password, so what's the point?

Two options here:
- do not store the password in the config file, enter it interactively,
- use a password manager ([GNOME Keyring](https://wiki.gnome.org/Projects/GnomeKeyring), [KDE Wallet Manager](https://utils.kde.org/projects/kwalletmanager/), [macOS Keychain Access](https://support.apple.com/guide/keychain-access/kyca1083/mac)), but interfacing with a such  program won't be easy from a command line program such as _openfortivpn_, it's better handled from the GUI.

**Comment by DimitriPapadopoulos** [comment]
@linorex See also #872. If you have ideas on how to better document `--pinentry` and to and favour it over plain password in the configuration file, we're open to suggestions and pull requests.
