### ISSUE TITLE
Release a 1.5.1 with the max routes fix

### ISSUE THREAD

**Issue by daenney** [adrienverge/openfortivpn#234]
I was wondering if someone could release a 1.5.1 which includes the change to MAXROUTES now supporting up to 65k routes? I'm currently hitting the 128 routes limitation that's still present in 1.5.0 meaning I need to revert to the Fortinet client.

**Comment by adrienverge** [comment]
Sure! [openfortivpn 1.6.0 released](https://github.com/adrienverge/openfortivpn/releases/tag/v1.6.0).
