### ISSUE TITLE
pointer being freed was not allocated

### ISSUE THREAD

**Issue by eblot** [adrienverge/openfortivpn#237]
When the VPN connection goes down (on its own or with an explicit "kill"), `openfortivpn` v1.4.0 on macOS triggers a memory error:

    openfortivpn(90207,0x7fffd342b3c0) malloc: *** error for object 0x7fff5713bc57: pointer  being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug

**Comment by DimitriPapadopoulos** [comment]
By teh way, have you tried version 1.6.0? Some issues have been fixed there.

**Comment by DimitriPapadopoulos** [comment]
I'm asking because this won't be necessarily easy to fix. As you can see _valgrind_ (this is _valgrind_, isn't it?) asks to "_set a breakpoint in malloc_error_break to debug_".

**Comment by eblot** [comment]
I did not tried v1.6.0: for some reason (home)brew did not reported 1.4.0 as outdated. 

I just forced (unlink, install) the new version [v1.6.0], I'll keep you posted. Thanks.

**Comment by eblot** [comment]
At least, an explicit kill does not bring up this error anymore with 1.6.0

**Comment by DimitriPapadopoulos** [comment]
Then this might have been fixed between 1.4.0 and 1.6.0, but I cannot find the relevant commit in Git. I nevertheless suggest we close this issue for now, and either reopen this issue or open a new one if such a message occurs again.
