### ISSUE TITLE
[Feature request] BSD support

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#241]
In #222 we have agreed that looking at BSD would be interesting. I have moved BSD support into a  [separate branch](https://github.com/mrbaseman/openfortivpn/tree/bsd_support). I haven't yet made a pull request out of it because there are still a few things to fix, but I have decided to open this issue for discussion and documentation

**Comment by mrbaseman** [comment]
with https://github.com/mrbaseman/openfortivpn/commit/91079d7397ef91a78ac38ddc130f7d8b7c559c11 it compiles on FreeBSD now, but it crashes with a core dump. So far I could determine that the `rtentry` data structures are not yet properly initialized. On FreeBSD [struct rtentry](https://www.freebsd.org/cgi/man.cgi?query=rtentry) starts with two `radix_node` structures that contain the destination address and mask and obviously it is not ok to just zero this memory area. These `rt_nodes` must be properly initialized.

**Comment by mrbaseman** [comment]
one more thing I should link here: the current [README.md](https://github.com/adrienverge/openfortivpn/blob/master/README.md) on master by mistake already mentions FreeBSD support, but at least it states that this BSD port is not finished yet, see also
https://github.com/adrienverge/openfortivpn/issues/222#issuecomment-347519742

**Comment by mrbaseman** [comment]
initialization of the `radix_node` structures should perhaps be done using [rtalloc1_fib](https://www.freebsd.org/cgi/man.cgi?query=rtalloc) or along the lines of the source of the [route](https://github.com/freebsd/freebsd/blob/master/sbin/route/route.c#L790) command. I'm still looking if this is feasible or if we should better use syscalls to the `route` command as a workaround, similar to the syscalls to the `netstat` command in the OSX part of the code (which I also use in the BSD port)

**Comment by mrbaseman** [comment]
I have moved the line about FreeBSD in the README.md to the bsd_support branch and updated the path to netstat for BSD as well. The issue how to deal with the kernel routes on BSD is still open.

**Comment by mrbaseman** [comment]
The `radix_tree` structures for the kernel routing tables don't provide an interface for copying routes around, also the routes are locked on FreeBSD. All does not look as if applications are expected to change routing information this way. Anyhow, we can decide not to set `_WANT_RTENTRY` so that the header does not export the `struct rtentry`. Then we can define our own struct to store routes that we want to restore later on. As an interface for manipulation we can use the `route` command, just like we do on Mac OSX. I have changed the BSD code so far. 

Also, I have added a couple of autoconf checks. A few of them, which check if specific files (like `/proc/net/route` or `/usr/sbin/netstat`) exist, make cross-compiling more difficult. Maybe one can define those with an explicit `export CFLAGS=-D HAVE_PROC_NET_ROUTE` at compile time later on.
The resulting code compiles on Linux and on FreeBSD now. 

The next problem that I have noticed is that FreeBSD does not use `pppd` anymore, but a user space `ppp` application instead. It looks quite different how settings for the connection are made there. Probably one has to pipe a couple of commands into its shell-like interface...

With the additional autoconf checks I could avoid most (if not all) checks for the OS Type (like `#ifdef __APPLE__` now). I haven't tried the current code on OpenBSD yet. Maybe this works better with the improvements I have added to the autoconf system in the meantime.

**Comment by mrbaseman** [comment]
for the record: I have just squashed and rebased my [bsd_support branch](https://github.com/mrbaseman/openfortivpn/tree/bsd_support) to get rid of many changes which I have reverted later on.

**Comment by nferch** [comment]
@mrbaseman you make any progress on this? I got your branch sortof working, I can establish a connection and send/receive traffic but it doesn't add routes or nameservers or anything like that.

**Comment by nferch** [comment]
@mrbaseman I think https://gist.github.com/nferch/5005415825dbfa73eaef3c17b2668379 is the relevant part. It seems that `packet_is_end_negociation` is looking for some PPP frame that never comes so it never fully completes configuration, but the PPP tunnel is up and works if you add routes manually. Will look at the code a bit more later to see how this works with pppd.

**Comment by nferch** [comment]
Some more hacks: https://github.com/nferch/openfortivpn/commit/865f1f92fce07d2883d44dd9ce6669991c3b2970

It connects and adds routes which is good enough for me at the moment. The routing table parsing/manipulation functions seem a bit brittle, I had thought it'd be much cleaner to communicate with the kernel via socket but you seem to have had different experiences above.

**Comment by mrbaseman** [comment]
thanks, I have merged them into my branch, together with the latest development on master, but I didn't find the time to test yet

**Comment by mrbaseman** [comment]
Great, now it works for me, too, on linux and on FreeBSD. Thanks a lot!

**Comment by nferch** [comment]
Added a few commits to my branch at https://github.com/nferch/openfortivpn/tree/bsd_support which clean a few things up and improve the reliability of the end of IPCP negotiation (which is still a bit brittle I'm afraid)

**Comment by mrbaseman** [comment]
I think we can close this ticket now that the necessary changes have been landed on master. Maybe a few notes though:
* #378 may affect FreeBSD, too, and a fix in #385 has also been landed on master.
* I have opened #384 about a two routing issues with specific configurations on FreeBSD 
* somewhere (I think in #300) we have agreed to tag a new release after a testing period with the current master. Perhaps we should go through the pull requests and see which ones we want to take into 1.8.0, too (I assume that the changes suggest not only to increment the patch level, but increase the minor release number).

**Comment by mrbaseman** [comment]
@nferch I'm not sure if you were following the other issues, but we have released version 1.8.0 now, which contains the FreeBSD support and also fixes for the remaining routing issues from #384 
thanks again for the hints that you have given.
