### ISSUE TITLE
vmware ssl vpn-plus 

### ISSUE THREAD

**Issue by sendme365** [adrienverge/openfortivpn#245]
Does openfortivpn able to use vmware ssl vpn-plus to connect DC?

**Comment by mrbaseman** [comment]
_openfortivpn_ is a client for Fortinet's SSL VPN. I doubt that this implementation is compatible with Vmware's ssl vpn-plus, i.e. you probably can not use _openfortivpn_ to connect to a [vmware NSX Edge](https://pubs.vmware.com/NSX-6/topic/com.vmware.nsx.admin.doc/GUID-160E1FF2-7C96-4575-AA8C-3E7962AE22E5.html). 

You can, however, use _openfortivpn_ to connect to a [SSL VPN running on a Fortigate](https://pubs.vmware.com/NSX-6/topic/com.vmware.nsx.admin.doc/GUID-160E1FF2-7C96-4575-AA8C-3E7962AE22E5.html). 

If you have a vmware NSX Edge on the private network behind the Fortigate, you should be able to use the vmware SSL VPN plus client to connect through the Fortinet SSL VPN tunnel to the vmware NSX Edge. This connection would be a second SSL layer, just as if you were browsing a https encrypted intranet page through the VPN tunnel.
