### ISSUE TITLE
Can reach machines on the VPN by IP but not by hostname

### ISSUE THREAD

**Issue by sankasan** [adrienverge/openfortivpn#246]
I've added openfortivpn to the Solus repos a couple of months ago and was mainly targeting machines by IP. However recently I noticed that the resolve step (using VPN nameservers to go from `Some_VPN_Desktop_123` to `172.16.1.123`) doesn't seem to work. I do see a couple of nameservers being added to `/etc/resolv.conf` but for some reason that doesn't seem enough. to translate the hostname to an IP.

Perhaps I'm simply missing something in the setup of either openfortivpn or the configuration of the specific connection.

**Comment by DimitriPapadopoulos** [comment]
Have you checked that the DNS servers are actually able to resolve `Some_VPN_Desktop_123` to `172.16.1.123`?

For example if (one of) the DNS server added to `/etc/resolv.conf` is `8.8.8.8`, then try this:
**`dig Some_VPN_Desktop_123 @8.8.8.8 +short`**

**Comment by sankasan** [comment]
dig could resolve the hostname (including domain suffix) to the correct IP when I use the VPN name server.

```
>dig Some_VPN_Desktop_123.our-vpn-domain.local @172.16.1.234 +short
172.16.1.123
```

However when I `ping Some_VPN_Desktop_123.our-vpn-domain.local` I get `ping: unknown host`

Once the VPN connection is established this is what /etc/resolv.conf looks like 
(haven't seen the warning about max 3 nameservers before so I assume it is not relevant):

```
>cat /etc/resolv.conf
# Generated by NetworkManager
search home
nameserver 172.16.0.234
nameserver 8.8.8.8
nameserver 213.46.228.196
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 62.179.104.196
```

Any clue what might mess with the resolve step?
And as a bonus question do you know how I'd get rid of the `.our-vpn-domain.local` in all the addresses using openfortivpn?

**Comment by DimitriPapadopoulos** [comment]
Is the DNS server **172.16.0.234** (as in `/etc/resolv.conf`) or **172.16.1.234** (as used in your test with *dig*)?

If the libc resolver cannot support more than 3 nameservers, I suggest you limit yourself to 3 nameservers - at least until you have solved all other problems.

Finally the `.our-vpn-domain.local` domain might be added by the DNS server.

**Comment by sankasan** [comment]
Sorry about that typo. The dig command worked with the`172.16.0.234` nameserver and not with the `172.16.1.234`.

I've added the nameserver now also explicit in the `network-manager-fortivpn` GUI under **Additional DNS servers** and the domain `.our-vpn-domain.local` under **Additional search domains**. With this configuration everything seems to work fine. 

Thanks for the support and for this nice piece of software!
