### ISSUE TITLE
kubuntu 17.10 (not fully supported?)

### ISSUE THREAD

**Issue by edwardally** [adrienverge/openfortivpn#247]
I had 3 strange issue here with kubuntu 17.10
1. Can connect through IP address but not the hostname
2. WIFI cannot used after disconnect from VPN. Need manually disconnect an reconnect the wifi again
3. There is a "question" mark in the WIFI icon after successful the VPN connected

**Comment by DimitriPapadopoulos** [comment]
Does this happen with Kubuntu 17.10 only? Other versions of Kubuntu? Ubuntu 17.10?

1. Can you run _openfortivpn_ with the `-v` option?
2. How doesn't it work? Is this a DNS problem (in which case `/etc/resolv.conf` might have not been reset) or is the whole network connectivity down? For example you might try to `ping 8.8.8.8`. If it works and `ping google-public-dns-a.google.com` doesn't, this is a DNS issue.
3. Looks like a KDE problem.

**Comment by edwardally** [comment]
1. Can and it returned "openfortiGUI 0.4.1"
2. unable to ping both IP and hostname 
3. alright..
Before connected
![ok](https://user-images.githubusercontent.com/1024003/34671788-d6593c5e-f4b6-11e7-8747-93470337451e.png)
After connected 
![q](https://user-images.githubusercontent.com/1024003/34671789-d695a3e2-f4b6-11e7-89f6-f9c49d7d5b5f.png)

**Comment by DimitriPapadopoulos** [comment]
You're using [_OpenFortiGUI_](https://hadler.me/linux/openfortigui/), not _openfortivpn_.

I suggest you open a ticket here:
https://github.com/theinvisible/openfortigui/issues

**Comment by edwardally** [comment]
My apologies. wrong forum, Thank you anyway.
