### ISSUE TITLE
how to genertated trusted_cert 

### ISSUE THREAD

**Issue by sendme365** [adrienverge/openfortivpn#248]
I am plan to use python call the openfortivpn script , but how can I get trusted_cert every time. 

The way I am using right now in shell(will convert to python later) . so I am wondering any better idea or ways to call openfotivpn 

trusted_cert=`echo $sudopwd|sudo -S openfortivpn $DC -u $username -p $pwd | grep trusted-cert | head -n 1 | awk -F "--" ' { print $2} '  >/dev/null 

nohup sudo -S openfortivpn $DC -u $username -p $pwd --$trusted_cert >nohup.out 2>&1 &

**Comment by mrbaseman** [comment]
this way you explicitly trust any certificate that a possible man in the middle would present to you. You could create a configuration file for each connection you are planning to use and call _openfortivpn_ with the `-c` option. In the config file you specify the appropriate `trusted-cert` for that server. 

Or, if you want to have a single configuration file, you can add several `trusted-cert` lines, one for each server, so you won't be asked anymore to specify `--trusted-cert` on the command line. 

Another solution would be to create a ca bundle file that contains all the authorities that have issued certificates for the servers to which you connect. If they are trustworthy in your organization, you can add them to the certificate store of your OS, or you create a separate file for _openfortivpn_ which you specify with `--ca-file`.

All these solutions allow you to detect if an intruder breaks up your ssl connection using his own (untrusted) ca certificate. Again, with your workflow you would just ignore any unexpected change of the certificates and trust the new situation explicitly.

**Comment by DimitriPapadopoulos** [comment]
Where does _openfortivpn_ look for certificates by the way?

The certificate on the VPN server I have access to is signed by my organisation's authority and the root certificates of my organisation are in `/etc/ssl/certs/`. Yet I have to force with `--trusted-cert`.

**Comment by mrbaseman** [comment]
It uses the standard locations for the openssl aginst which openfortivpn is linked. To have the certificates active, it is also needed to have the appropriate ssl hashes in the certs directory, and/or you put the certificate into the monolitic file (/etc/ssl/certs/ca-certificates.crt by default). On Ubuntu there is a script update-ca-certificates which is called each time when there are updates for the certificate bundle shipped with the os. The script updates the links and (I think) the monolitic file, too.

**Comment by munsuri** [comment]
Talking about `--trusted-cert`. In my case, I have used it every time as I don't have the certificate itself but the user and passwd. Does `openfortivpn` store (permanently or temporarily) the certificate from the server once trusted with `--trusted-cert`? Or how to retrieve it? I would like to add it to my OS certificate store to avoid using the parameter every time.

**Comment by mrbaseman** [comment]
You can point your web browser to the URL where you normally connect with _openfortivpn_. Within the web browser you can view the details of the certiticate, import it to the browsers known certificates and re-export it to disk. 
_openfortivpn_ does not store the certificate permanently. It tells you the digest, which you use with `--trusted-cert`, but you can also store this digest in the _openfortivpn_ config file. There is nothing wrong with calling _openfortivpn_ with the option `--trusted-cert`, as long as you do this with a hard-coded value out of a script. You should **not** do it the way described in the initial post of the current issue (obtain the digest over an untrusted network and just use it and trust it without further checks). If you do it such a way, you should at least compare the value obtained over the network against a fixed list of digests that you have verified once while connected over a secure and trusted network.
