### ISSUE TITLE
Persistente connection

### ISSUE THREAD

**Issue by christian-aiko** [adrienverge/openfortivpn#251]
It does not have reconnection functionality.
Don´t have a "always up" ....
It would be great functionality.

**Comment by DimitriPapadopoulos** [comment]
Isn't this a duplicate of #190?

**Comment by christian-aiko** [comment]
Yes...

=)

Thank You.

2018-02-09 10:58 GMT-02:00 Dimitri Papadopoulos Orfanos <
notifications@github.com>:
