### ISSUE TITLE
avoid ifndef statements

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#253]
in #250 it was noticed that probably the whole issue was opened based on a misunderstanding. 
The `#ifndef __APPLE__` statements are confusing and should be replaced by `#ifdef __APPLE__` accompanied by the appropriate code-reordering

I have opened this issue as a reminder for myself. I'm going to address this, probably after my next vacation...

**Comment by DimitriPapadopoulos** [comment]
Hasn't this issue been solved by 84b92ac?

**Comment by mrbaseman** [comment]
sure, I just forgot to close the issue
