### ISSUE TITLE
man page: set up two separate /1-routes instead

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#260]
The `--half-internet-routes` option documentation reads:
> set up two separate /1-routes instead.

I don't understand this. Perhaps this was meant to be something like that:
> set up two separate \\(12-routes instead.

**Comment by mrbaseman** [comment]
Maybe the discussion in #149 gives some insight. If I remember right, instead of adding a default route 0.0.0.0 or /0 in cidr notation two /1 routes that cover in sum  the same address space are added, however, they have a higher priority due to their smaller netmask, and therefore it is not necessary to remove and restore the original default route.

**Comment by DimitriPapadopoulos** [comment]
I see, forget this issue then. It's just that this might be cryptic for most users. Either the documentation could be improved, or....

I've started thinking separate /1 routes should perhaps become the default. I'm still far from understanding everything, but:
* it works around issue #252 with _Network Manager_ on Ubuntu 17.10 (and perhaps 18.04 LTS which is around the corner),
* it seems to be fixing the DHCP lease renew issue I have been experiencing like @martinetd (which shouldn't be a surprise since we share the same organization).

**Comment by martinetd** [comment]
My original patch was setting it as default, so I'll obviously support that idea if you think it has gotten enough testing now :)
For all intent and purpose I think it should be equivalent for most people - it effectively redirects all traffic that would go through the default route through the gateway via these two routes, and is less prone to the problems you've been running into.

As for documentation, what about this wording?
> --half-internet-routes=< bool >
> If set, do not replace the default route but add two 0.0.0.0/1 and 128.0.0.0/1 routes that will have priority over the default route.

**Comment by DimitriPapadopoulos** [comment]
Yes, documentation is probably better this way. I can modify it.
