### ISSUE TITLE
Add timestamps to log

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#269]
Perhaps it would help to add timestamps to the log, or at least optional timestamps. I have the feeling it might help investigate errors such as:
```
INFO:   Tunnel is up and running.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
WARN:   Could not delete route to vpn server (No such process).
INFO:   Removing VPN nameservers...
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```
It's hard to find the root cause without a timestamp to associate relevant entries in the system log.

**Comment by DimitriPapadopoulos** [comment]
Ah, option `--use-syslog` is probably good enough: _openfortivpn_ writes to _syslog_ and messages are automatically timestamped.

**Comment by DimitriPapadopoulos** [comment]
I've just tried and it's probably the best solution. Just need to document that a little bit and explain it's best to use `-v` and `--use-syslog` to start debugging errors.

**Comment by reinhard-brandstaedter** [comment]
I think it would still be useful to have the timestamps not only in syslog. I'm using openfortivpn within docker containers (a multi-vpn multiplexing routing setup)  and usually there is no option for syslog there.

**Comment by DimitriPapadopoulos** [comment]
@reinhard-brandstaedter As a workaround you may use [`ts`](https://joeyh.name/code/moreutils/) to prepend a time stamp in front of every line.

**Comment by mrbaseman** [comment]
is the workaround fine, or shall we keep this on the list?

**Comment by DimitriPapadopoulos** [comment]
I suggest we close as _ts_ provides a nice solution without adding complexity to the project. Please do not hesitate to re-open if you feel this is not satisfactory.
