### ISSUE TITLE
pppd: Is not setuid-root and the invoking user is not root

### ISSUE THREAD

**Issue by caffeineflo** [adrienverge/openfortivpn#273]
```
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
ERROR:  pppd: Is not setuid-root and the invoking user is not root.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

Either the error message is misleading or there's seriously something wrong. 

After upgrading to the latest version, this is what I was receiving. User is root and pppd is setuid-root.

**Comment by DimitriPapadopoulos** [comment]
The main error message from _openfortivpn_ is:
```
ERROR:  read: Input/output error
```

The message from _pppd_ looks misleading indeed:
```
ERROR:  pppd: Is not setuid-root and the invoking user is not root.
```

These _pppd_ error messages are generated by new code introduced by commit 7964146:
```
static const char * const pppd_message[] = {
	"Returned an unknown exit status", // fall back
	"Has detached, or otherwise the connection was successfully"
	" established and terminated at the peer's request.",
	"An immediately fatal error of some kind occurred, such as an"
	" essential system call failing, or running out of virtual memory.",
	"An error was detected in processing the options given, such as two"
	" mutually exclusive options being used.",
	"Is not setuid-root and the invoking user is not root.",
	[...]
```
The code that actually prints the error message looks like this:
```
	if (waitpid(tunnel->pppd_pid, &status, 0) == -1) {
		log_error("waitpid: %s\n", strerror(errno));
		return 1;
	}
	if (WIFEXITED(status)) {
		int exit_status = WEXITSTATUS(status);
		log_debug("waitpid: pppd exit status code %d\n", exit_status);
		if (exit_status) {
			size_t len_pppd_message = ARRAY_SIZE(pppd_message);
			if (exit_status >= len_pppd_message)
				exit_status = 0;
			if (exit_status != 16) // emitted when exiting normally
				log_error("pppd: %s\n", pppd_message[exit_status]);
		}
	} else if (WIFSIGNALED(status)) {
		int signal_number = WTERMSIG(status);
		log_debug("waitpid: pppd terminated by signal %d\n",
		          signal_number);
		log_error("pppd: terminated by signal: %s\n",
		          strsignal(signal_number));
	}
```
The error messages are based on the [_pppd_ documentation](https://ppp.samba.org/pppd.html#sect12). So either the _pppd_ documentation is wrong and/or the error codes depend on the version of _pppd_, or I do not retrieve the _pppd_ error code properly. My guess is that this in a _pppd_issue - exit status is not properly documented. If that's the case there is no other solution than printing the numerical error code instead of trying to print a human-friendly error message.

Could you run _openfortivpn_ in debug mode with option `-v` to get the numerical error code?

**Comment by DimitriPapadopoulos** [comment]
OK, I think I got it.

It looks like the [HTML man page](https://ppp.samba.org/pppd.html#sect12) has not been properly generated:

> 1. Pppd has detached, or otherwise the connection was successfully established and terminated at the peer's request.
> 2. An immediately fatal error of some kind occurred, such as an essential system call failing, or running out of virtual memory.
> 3. An error was detected in processing the options given, such as two mutually exclusive options being used.
> 4. Pppd is not setuid-root and the invoking user is not root. 
> 5. The kernel does not support PPP, for example, the PPP kernel driver is not included or cannot be loaded. 

Compare to the [source](https://github.com/paulusmack/ppp/blob/master/pppd/pppd.8#L1522-L1595):
```
.SH EXIT STATUS
The exit status of pppd is set to indicate whether any error was
detected, or the reason for the link being terminated.  The values
used are:
.TP
.B 0
Pppd has detached, or otherwise the connection was successfully
established and terminated at the peer's request.
.TP
.B 1
An immediately fatal error of some kind occurred, such as an essential
system call failing, or running out of virtual memory.
.TP
.B 2
An error was detected in processing the options given, such as two
mutually exclusive options being used.
.TP
.B 3
Pppd is not setuid-root and the invoking user is not root.
.TP
.B 4
The kernel does not support PPP, for example, the PPP kernel driver is
not included or cannot be loaded.
```
In your case the numerical error code was probably **4**. Based on the HTML man page I translated it to:
> Pppd is not setuid-root and the invoking user is not root. 

while according to the source of the man page it should be:
> The kernel does not support PPP, for example, the PPP kernel driver is not included or cannot be loaded.

Does it make sense in your case?

**Comment by DimitriPapadopoulos** [comment]
Added ticket paulusmack/ppp#94 to request a fix for the _pppd_ HTML man page.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman I have tried this at home and _pppd_ messages have started making sense! Does fcbb89f look goot to you?

**Comment by mrbaseman** [comment]
yes, together with the commit message "The enumeration of pppd exit status codes was off by one" it totally makes sense.

**Comment by caffeineflo** [comment]
Yes, now the error message makes sense! 
Thanks for the quick turnaround time on this one
