### ISSUE TITLE
hard coded remote address in pppd parameters

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#280]
In the parameters for calling pppd the address 1.1.1.1 [is hard coded](https://github.com/adrienverge/openfortivpn/blob/master/src/tunnel.c#L128) as remote address on the ppp link, see "Options" Section in [man 8 pppd](https://linux.die.net/man/8/pppd).
My understanding is that this is needed to bring up the connection until the remote side has assigned a proper IP. However, when starting `openfortivpn` a host route is added for this. It seems that this "virtual ip" has been widely used also by other vendors like [Cisco](https://supportforums.cisco.com/t5/getting-started-with-wireless/what-virtual-ip-should-i-use-on-a-cisco-wlc/td-p/3018060), but it has been assigned to [cloudflare](https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/), now. Therefore, one should use a different IP from the range of
[RFC1918 private addresses](http://www.ietf.org/rfc/rfc1918.txt) or an [RFC3330 Test-Net address](https://tools.ietf.org/html/rfc3330) (such as 192.0.2.1/32) as explained for the use case of [DHCP servers](
http://www.revolutionwifi.net/revolutionwifi/2011/03/explaining-dhcp-server-1111.html). In the Cisco case also one of the [rfc5737 test nets](https://tools.ietf.org/rfc/rfc5737.txt) is recommended.
I would suggest to apply a similar change for `openfortivpn`. Does anybody know if this _can_ easily be changed on the client side, or do we have to wait for Fortigate to change it and adapt the client once the server has changed?

**Comment by DimitriPapadopoulos** [comment]
[1.1.1.1 is used by Fortinet VPN as the virtual endpoint so doesn’t work when my VPN is running](https://twitter.com/chriswigginsnz/status/981315362015789056)

**Comment by DimitriPapadopoulos** [comment]
Although I don't have a good understanding of the Fortinet VPN or network routing, it looks like 1.1.1.1 is just a default value and that it can be readily changed on the FortiGate device: [Howto Fortigate](https://www.shrew.net/support/Howto_Fortigate#Gateway_Configuration).

If that's the case, I'm curious how _FortiClient_ handles that. Can the gateway be queried instead of hard-coded in the client software or configuration file?

Have you tried using 1.1.1.1 as the default DNS server for your workstation together with _openfortivpn_? What happens then? Just DNS queries not working? _openfortivpn_ not working?

**Comment by mrbaseman** [comment]
Hmm... In the Howto this really looks like a default value which can be changed easily. But I'm not sure if this default setting for the default gateway on the wan interface has any relation to the 1.1.1.1 that we use in _openfortivpn_ when calling pppd. 

For sure we have a different default gateway on our wan interface(s), and _openfortivpn_ has been working together with this setting.

I have just edited my tunnel.c and replaced 1.1.1.1 by 192.0.2.1 and that version is working, too.  
As expected, instead of a routing entry to 1.1.1.1 I get one to 192.0.2.1, now.

I haven't tried using 1.1.1.1 as DNS together with _openfortivpn_ because that is blocked here. I must use one of the DNS servers in our workstation network. If it were possible, I would assume that in our configuration 1.1.1.1 wouldn't be reachable anymore when connected to the vpn, because the traffic would be routed through `ppp0` and then DNS lookups would probably be blocked by the Fortigate that does not allow DNS  traffic from vpn clients to external DNS servers.

The reason for the current issue was just the question of a colleague, "why does _openfortivpn_ configure a host route to the cloudflare DNS server?".

**Comment by mrbaseman** [comment]
For the record, the proprietary Forticlient uses 1.1.1.1 on the ppp link as well (except for the win-version). For example this is the output when running the linux client:
```
$ ifconfig ppp0
ppp0      Link encap:Point-to-Point Protocol  
          inet addr:192.168.0.115  P-t-P:1.1.1.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1354  Metric:1
          RX packets:106 errors:0 dropped:0 overruns:0 frame:0
          TX packets:107 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:3 
          RX bytes:1070 (1.0 KB)  TX bytes:1091 (1.0 KB)
```
however, pppd does not add an explicit route in this case. pppd is called like this:
```
$ ps auxe | grep ppp | grep root
root     26924  0.0  0.0  33360  3424 pts/2    S+   10:45   0:00 /usr/sbin/pppd noipdefault noaccomp noauth default-asyncmap nopcomp nodefaultroute debug logfile /usr/local/forticlientsslvpn/64bit/helper/pppd.log :1.1.1.1 nodetach lcp-max-configure 40 38400 usepeerdns mru 1354
```
