### ISSUE TITLE
Remote gateway has allocated a VPN.

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [adrienverge/openfortivpn#292]
Hello,

I'm running into issues where openfortivpn is not able to allocate the tunnel. Running 1.6.0 with verbose output I'm getting a INFO and then an ERROR about connection refused after authentication was successful.

DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=<cookie>
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=<cookie>
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: 209.202.160.253
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 209.202.160.253
DEBUG:  gateway_port: 10443
ERROR:  connect: Connection refused
INFO:   Closed connection to gateway.
DEBUG:  server_addr: 209.202.160.253
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 209.202.160.253
DEBUG:  gateway_port: 10443
ERROR:  connect: Connection refused
INFO:   Could not log out.

Trying to log in with a official forticlient the connection works and also logging in to the gateway via browser works. There is no VPN allocated at the gateway.
Any idea what the issue is here?

Cheers!

**Comment by DimitriPapadopoulos** [comment]
```DEBUG: Cookie: SVPNCOOKIE=```
Have you sanitized the log or is `SVPNCOOKIE` really empty?

**Comment by mrbaseman** [comment]
This is how far I could analyze this: _openfortivpn_ fails to [connect the socket](https://github.com/adrienverge/openfortivpn/blob/master/src/tunnel.c#L431) because the [connection was refused](https://linux.die.net/man/3/connect) or the remote side was not listening to connections. There has already been a vpn allocated, and this has happened due to the previous communication to the same host and port, so it can't be that the remote side doesn't listen, and if the permission to open a tunnel is not present, the connection fails later, see #79. So, we have something different here...

**Comment by mrbaseman** [comment]
another idea: it might be the `endpoint-control registered-forticlient` setting or a firewall policy with a dependency on the client device on the Fortigate that only allows _Forticlient_ to open a tunnel

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman But then how does the FortiGate make a difference between FortiClient and _openfortivpn_?

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos You are right, the degree of implementation depends on the type of the OS. Apart from _Endpoint protection_ which is AntiVirus, WebFiltering etc. for the client, there is also _FortiTelimetry_ which lets the FortiGate know details about the client and based on this information grant access or not. 
I don't know the details of the implementation, but it is roughly described in the Chapter "FortiTelimetry/On-Net/FortiClient Endpoint Compliance" in the [Fortinet Communications Ports and Protocols Manual](https://docs.fortinet.com/uploaded/files/3606/fortinet-communication-ports-and-protocols-56.pdf). 
The FortiClient sends some information that it collects on the client (e.g. OS type and version, installed patches and applications). This information is sent on TCP/8013 to the Fortigate. The Client has to be provisioned and configured once from the FortiGate, so FortiClient knows where to send the data. 
Now, the FortiGate already knows some background when a client wants to connect. I don't know how exactly it recognizes a specific client, but I can imagine that FortiClient when provisioned with FortiTelimetry sends an extra query-String that allows the FortiGate to correlate the incoming SSL VPN connection with the collected Telimetry information. 
In my Android FortiClient I also have a separate menu for configuring FortiTelimetry, and I think it's also possible to configure it on the client, but as far as I remember it's possible to lock this confituration during deployment of the FortiClient License Token. 
As what it concerns _openfortivpn_, I believe this is all far beyond the scope of this project and implementing features in this direction would require a deep knowledge of probably closed source. Fortinet offers accounts on their development network for interested contributors (I don't have one), where you can have access to the APIs and some internal documentation, but I doubt that they share that much details that one can successfully mimick these advanced features of FortiClient.

**Comment by mrbaseman** [comment]
@reinhard-brandstaedter do you have access to the error logs on the FortiGate to which you are trying to connect? These logs sometimes don't correctly point to the root cause of the problem, but maybe this time they can give us a hint...

**Comment by DimitriPapadopoulos** [comment]
@reinhard-brandstaedter Do you have additional information that could help us characterize and address this issue?

**Comment by DimitriPapadopoulos** [comment]
@reinhard-brandstaedter Any chance you can help us debug this issue? Was this a FortiGate device issue?
