### ISSUE TITLE
LibreSSL support

### ISSUE THREAD

**Issue by HackerMan69** [adrienverge/openfortivpn#293]
Would it be possible to add support for libressl in a future release?  My OS uses it and I can't compile this. 

http://www.libressl.org/

**Comment by DimitriPapadopoulos** [comment]
In any case it's worth trying. But which OS is this? Do you know what type of changes would be required or how much work it would involve?

**Comment by mrbaseman** [comment]
I have just compiled _openfortivpn_ from current master and linked against the latest libressl 2.7.2 which I have installed locally. Libressl also ships with a pkgconfig directory, and if this directory is added to PKG_CONFIG_PATH it correctly sets up the compiler- and linker flags. 
So, it might be an issue with the libressl version that is packaged for your operating system (or maybe a missing devel-package that you first should install?), or something related to autoconf/automake and friends on this particular OS...

**Comment by HackerMan69** [comment]
@DimitriPapadopoulos I'm running void linux.  Here is my output when running autogen.

```
./autogen.sh
+ type autoconf
+ type automake
+ type aclocal
+ aclocal
+ autoconf
+ automake --add-missing
+ echo now you can run ./configure && make to build openfortivpn
now you can run ./configure && make to build openfortivpn
[b4d@hax openfortivpn]$ ./configure --prefix=/usr/local --sysconfdir=/etc/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make supports nested variables... (cached) yes
checking for libcrypto libssl... no
configure: error: Package requirements (libcrypto libssl) were not met:

No package 'libcrypto' found
No package 'libssl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

```

@mrbaseman 
I'll give it another shot today and report back.  I'm kind of new to manually compiling C stuff, so that information is helpful.

**Comment by mrbaseman** [comment]
hmm... the configure script has found pkg-config but that didn't find libcrypto and libssl. I'm not familiar with void linux and its `xbps`. 
* You could try to find out if the libressl-openssl package contains some .pc files and how the libraries are called in them. 
* You could add the path to those files to the `PKG_CONFIG_PATH` and try again, but normally this should not be necessary for packages that you install from your distribution. For my manual installation of libressl I did `export PKG_CONFIG_PATH=/usr/local/libressl-2.7.2/lib/pkgconfig`, where `PKG_CONFIG_PATH` was empty by default, otherwise you would have to append it.
* You could also look for libcrypto.so and libssl.so in the place where shared libraries are normally installed in your system and add the absolute path to them to the `OPENSSL_LIBS` environment variable, in my case like this:
```export OPENSSL_LIBS="/usr/local/libressl-2.7.2/lib/libcrypto.so /usr/local/libressl-2.7.2/lib/libssl.so"```

**Comment by mrbaseman** [comment]
to me the [template](https://github.com/voidlinux/void-packages/blob/58635831c75e740af29a72d2564e80f2acfd282f/srcpkgs/libressl/template) looks as if the _pkgconfig_ directory is `/usr/lib/pkgconfig` and it is contained in the _libressl-devel_ package. If my understanding is correct, it might be sufficient to install that devel-package

**Comment by HackerMan69** [comment]
@mrbaseman @DimitriPapadopoulos

Looks like I was missing the libressl-devel package. The installation instructions in the readme worked perfectly. 

Thanks for the help and info guys.
