### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [adrienverge/openfortivpn#324]
Hi Sir @adrienverge , good day! I am a graphic designer and I want to contribute to your project by designing a logo for it if you will allow me. I think a logo will add more visibility to the project. It is going to be my gift to the project for free if you will permit me.

Thanks and best regards!
-Tobaloidee

**Comment by adrienverge** [comment]
Hi @Tobaloidee, thanks for contributing!

Could you post a few proposals here, so that the team can decide? I cannot guarantee that we will use a logo (as openfortivpn is a command-line tool without a graphical user interface), but if we like it why not!

It could be made around the concepts of connection, tunnel, VPN, internet, plug...

**Comment by DimitriPapadopoulos** [comment]
@Tobaloidee Nice logo. However _openfortivpn_ is a command line program. I may be missing something but I fail to see how _openfortivpn_ could make use of a logo:
* Command line programs and manual pages don't have a logo.
* There is no web site except the GitHub repository and GitHub repositories cannot be associated to a logo as far as I know.

The only possibility would be [README.md](https://github.com/adrienverge/openfortivpn/blob/master/README.md) but it is probably better to keep this file text-only.

Did you perhaps want to contribute the logo to _[openfortigui](https://github.com/theinvisible/openfortigui)_ which is a GUI that wraps _openfortivpn_?

**Comment by Tobaloidee** [comment]
I understand Sir, thanks so much for the time and feedback. Best regards!

**Comment by DimitriPapadopoulos** [comment]
I'll leave this open for now, just in case I am just failing to see where a logo could be inserted.

I have checked that _openfortigui_ doesn't have a logo yet. Why not offer a logo [there](https://github.com/theinvisible/openfortigui/issues)?

**Comment by adrienverge** [comment]
Thanks for your work @Tobaloidee!

Dimitri is right: you should propose it to openfortigui.
