### ISSUE TITLE
half-internet-routes: the default?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#327]
I find `half-internet-routes` easier to understand and in a case I was interested in it worked better.

@adrienverge @mrbaseman Would you agree on making this option the default?

**Comment by adrienverge** [comment]
Unless @mrbaseman has a different opinion, I have no problem with this.

**Comment by mrbaseman** [comment]
It's fine with me. The half internet routes approach has a few (minor) disadvantages:
* it's different from what forticlient does 
* it might not work well with multiple vpn connections (open a vpn tunnel to a jump-host, then open further vpn tunnels to satellite locations which are reachable through the first tunnel...), but these are quite complex scenarios that might only be used in rare corner-cases

therefore we should keep the traditional behavior available, but I don't see any problem making `half-internet-routes=1` the default while `half-internet-routes=0` switches back to the traditional behavior.

**Comment by DimitriPapadopoulos** [comment]
Both arguments of @mrbaseman make sense. Perhaps it's better to leave things as is then.
