### ISSUE TITLE
plasma-nm and not obtaining DNS servers

### ISSUE THREAD

**Issue by freakynl** [adrienverge/openfortivpn#328]
Hi,

I'm using NetworkManager with plasma-nm and openfortivpn.

Have configured openfortivpn through plasma-nm. It connects nicely (might want to add a note that the port is required in the URL), but so far I've been unable to ignore the DNS servers provided by DHCP.

On CLI (--pppd-no-peerdns) or via config file (pppd-use-peerdns = 0) the servers aren't replaced in /etc/resolv.conf. When using plasma-nm I don't see such options, but under IPv4 tab you can set it to Automatic or to 'Automatic (addresses only)'. The latter is normally used to not configure DNS.

It does configure the DNS unfortunately.

Would also be nice if the CLI parameters match the config ones (pppd-no-peerdns vs pppd-use-peerdns).

Thanks in advance and huge thanks for the client :).

**Comment by DimitriPapadopoulos** [comment]
Which exact URL requires a port? If you're referring to the arguments passed to _openfortivpn_, the port is mentioned:
* in the manual page: `openfortivpn [<host>:<port>]`
* in the help printed by `--help`: `Usage: openfortivpn [<host>:<port>]`
* in the [README](https://github.com/adrienverge/openfortivpn/blob/master/README.md) examples:
> * Simply connect to a VPN:
     `openfortivpn vpn-gateway:8443 --username=foo`

Should we document it elewhere?

**Comment by DimitriPapadopoulos** [comment]
Use both `--pppd-no-peerdns` and `--set-dns=0`. Does it help?

The existence of two options and the confusion they cause is a known issue:
* #230
* #326
Hopefully we can get rid of `--set-dns` and let _pppd_ always handle DNS.

**Comment by DimitriPapadopoulos** [comment]
Finally it is true there is a discrepancy between `--pppd-no-peerdns` as command line option and the `pppd-use-peerdns` option in the config file.

@mrbaseman Perhaps it's best to stick to the `--set-dns=[01]` / `set-dns` pair of options and get rid of the  `--pppd-no-peerdns` / `pppd-use-peerdns` pair of options. Reasons for that:
1. Consistency with `--set-routes=[01}` / `set-routes`.
2. At this point it is not clear whether enabling/disabling DNS should be left to _pppd_, or perhaps left to the up/down scripts. We're experimenting with that in the current master branch. In any case the user does not need to know whether setting DNS is handled by _openfortivpn_ or handled over to _ppdp_.
3. If we keep the `--pppd-no-peerdns` / `pppd-use-peerdns` pair it should be changed to `--pppd-use-peerdns=[01]` / `pppd-use-peerdns` or even `--pppd-set-peerdns=[01]` / `pppd-set-peerdns` for consistency with the rest.

**Comment by mrbaseman** [comment]
I believe the different options exist for historical reasons and we should clean this up. 
Is any of these used in a plugin (in `plasma-nm` apparently not, but what about NetworkManager-fortisslvpn, maybe @lkundrak can comment on that)?

**Comment by DimitriPapadopoulos** [comment]
@freakynl In upcoming version of _openfortivpn_ we let _pppd_ handle DNS settings, so you won't need `--pppd-no-peerdns` any more, just `--set-dns=0`.
