### ISSUE TITLE
Tag v1.7.1 or release v1.8.0

### ISSUE THREAD

**Issue by millerdev** [adrienverge/openfortivpn#337]
I'm trying to update and submit a Portfile for MacPorts (again). In the process I decided to upgrade to v1.7.0, but the build fails as pointed out in #297. Can we either get a new tag for v1.7.1 that includes the fix (#298) or possibly a new v1.8.0 release?

Thanks!

**Comment by adrienverge** [comment]
Hi Daniel, sure, v1.7.1 released!

**Comment by mrbaseman** [comment]
@lkundrak I have seen you have seen that you have packaged earlier versions of _openfortivpn_ for Fedora. Did you notice the 1.7.x releases? Also, would it be possible to get the package into EPEL as well?
