### ISSUE TITLE
[ques] Whether there is a possibility that the NIC becomes unusable when its system crashes.

### ISSUE THREAD

**Issue by johejo** [adrienverge/openfortivpn#339]
If my question is out of the question, you can close the issue.

# version
1.6.0

# system
ubuntu 18.04

# case
The machine crashed while I was using openfortivpn.
I immediately restarted the machine, but the machine can not connect with the router.
Even if I booted with another OS (Windows 10), I could no longer connect to the router.
As a result of carving out various problems, the cause seems to be in NIC.
If the machine crashes while using openfortivpn, is there any possibility that something negative will remain on the NIC?

**Comment by DimitriPapadopoulos** [comment]
This looks doesn't look related to __openfortivpn__ in any way.
