### ISSUE TITLE
error launching from elementary os

### ISSUE THREAD

**Issue by mmiat** [adrienverge/openfortivpn#343]
hi
when i launch vpn from gui (network-manager-fortisslvpn-gnome) in ubuntu i've no problem but in elementary os it fails 

so i try from command line and also fails with:
>INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
ERROR:  pppd: An immediately fatal error of some kind occurred, such as an essential system call failing, or running out of virtual memory.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

after some test, i've solved launching 
sudo openfortivpn -c myvpn.conf

so, i need sudo in elementary os
but i want to use gui, so i've tried, as you wrote:

sudo visudo -f /etc/sudoers.d/openfortivpn etc etc
but it doesnt work, what else i can try to do ?
thanks

**Comment by DimitriPapadopoulos** [comment]
Why not ask the _network-manager-fortisslvpn-gnome_ guys or even the _elementary OS_ guys? As far as I can see, _openfortivpn_ does work with _sudo_ - and _sudo_ is documented in the README.

**Comment by mmiat** [comment]
ok sorry for disturbing

**Comment by DimitriPapadopoulos** [comment]
@mmiat That said Id' love to help, but I have this impression that this a problem of packaging _openfortivpn_ and/or _network-manager-fortisslvpn-gnome_, thus specific to [elementary OS](https://elementary.io), or a problem (of installation) of _network-manager-fortisslvpn-gnome_,

Just to make sure:
* Have you compiled/installed _openfortivpn_ and f _network-manager-fortisslvpn-gnome_ yourself, or have you installed existing packages provided by [elementary OS](https://elementary.io)?
* Same question for Ubuntu.
