### ISSUE TITLE
the credentials are passed on the URL, which is very unreliable

### ISSUE THREAD

**Issue by mvk** [adrienverge/openfortivpn#35]
hi there.
This is yet another case stressing the importance of library usage.
Click: [http.c](https://github.com/adrienverge/openfortivpn/blob/master/src/http.c#L313)
username and password are sent "as is", not escaped.
Ergo, if they are URL "unsafe", they will be processed by the server differently than expected.

Reproducing:

1. add a user to a working server: username="iamneverhome" with password: `call&my=home`
1. try connecting using official client - works
1. try connecting using openfortivpn with correct password. you get auth failure.

Why? The server interprets & as splitter, end of password param and then "my=home" is also treated as param. so for the server, the password is being processed as "call".

I'm sorry I'm swamped with customers and work, but I looked at `curl/curl.h`, it's a bit ugly, but it exactly addresses these cases - fully. e.g. escaping is done by calling `curl_easy_escape()`.

**Comment by mvk** [comment]
opened this:
https://bugzilla.redhat.com/show_bug.cgi?id=1290902

**Comment by adrienverge** [comment]
Thanks for detecting this!
