### ISSUE TITLE
Network admin gave me a PSK (pre-shared key) How to specify it?

### ISSUE THREAD

**Issue by boltex** [adrienverge/openfortivpn#352]
My workplace VPN details were given to me by our network admin,. 
Adress, port, username, password and a "Pre-shared Key"... 

I run the following command (on ubuntu 18.04)
**sudo openfortivpn MyCompanyVpn:8443 --username=foo**

Then i get asked for a password and after a couple of seconds i get a "ERROR: connect: Connection timed out"

How do I specify the pre-shared key the network admin gave me? 
Thanks in advance!

**Comment by boltex** [comment]
My workplace VPN details were given to me by our network admin,. 
Adress, port, username, password and a "Pre-shared Key"... 

I run the following command (on ubuntu 18.04)
**sudo openfortivpn MyCompanyVpn:8443 --username=foo**

Then i get asked for a password and after a couple of seconds i get a "ERROR: connect: Connection timed out"

How do I specify the pre-shared key the network admin gave me? 
Thanks in advance!

**Comment by DimitriPapadopoulos** [comment]
`--user-key` ?

**Comment by DimitriPapadopoulos** [comment]
Also what does the key look like? File name extension? File type?

**Comment by mrbaseman** [comment]
PSK sounds more like details for an ipsec dailup connection, not an sslvpn. Fortigate support both variants (and also different flavors of site2site ipsec etc.). Openfortivpn is an sslvpn client.

**Comment by DimitriPapadopoulos** [comment]
@boltex If indeed this is a PSK (pre-shared key) for an IPSec access, then perhaps you can talk to your sysadmin and make sure SSL access is enabled.

Do not hesitate to re-open this issue if needed.
