### ISSUE TITLE
Can't route traffic through vpn

### ISSUE THREAD

**Issue by telegonicaxx** [adrienverge/openfortivpn#354]
I have successfully connected to the FortiVpn, but my traffic remains being routed int the same way.
I am using Ubuntu 18.04.1 LTS, and when I connect via the terminal I get the following log messages:

> INFO: Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.

For some reason there seem to be multiple Got Addresses logs, that might be why my routing table looks different from the one I have found online: 

> Kernel IP routing table
Destination        Gateway         Genmask                Flags Metric Ref    Use Iface
default                _gateway         0.0.0.0                  UG    600    0        0 wlp3s0
1dot1dot1dot1.c 0.0.0.0             255.255.255.255  UH    0      0        0 ppp0
link-local             0.0.0.0              255.255.0.0         U     1000   0        0 virbr0
172.16.0.0          telix-ThinkPad- 255.255.0.0         UG    0      0        0 ppp0
172.31.0.0          telix-ThinkPad- 255.255.255.248 UG    0      0        0 ppp0
172.31.1.0          telix-ThinkPad- 255.255.255.240 UG    0      0        0 ppp0
192.168.1.0        0.0.0.0             255.255.255.0     U     600    0        0 wlp3s0
192.168.122.0    0.0.0.0             255.255.255.0     U     0      0        0 virbr0
192.168.229.0    telix-ThinkPad- 255.255.255.0     UG    0      0        0 ppp0
192.168.230.0    telix-ThinkPad- 255.255.255.0     UG    0      0        0 ppp0
192.168.231.0    telix-ThinkPad- 255.255.255.0     UG    0      0        0 ppp0
206.165.205.130 _gateway        255.255.255.255 UGH   0      0        0 wlp3s0

When I check the traffic using `sudo tcp -i ppp0 ` I get nothing, so this has lead me to believe that there must be routing table problem.

Any help would be greatly appreciated!

**Comment by DimitriPapadopoulos** [comment]
The multiple lines are OK: 
`INFO: Got addresses: [10.212.134.200], ns [0.0.0.0, 0.0.0.0]`
Not sure why there are many of them but I see them too and it works for me.

**Comment by DimitriPapadopoulos** [comment]
I wasn't aware of command `tcp`. What do you expect and what do you see?

**Comment by DimitriPapadopoulos** [comment]
Which version of _openfprtivpn_ is this? Verbose logs (`openfortivpn -v`) would help.

**Comment by DimitriPapadopoulos** [comment]
Which exact online routing table are you referring to?

**Comment by mrbaseman** [comment]
the problem might have been that _openfortivpn_ wasn't launched with enough privileges to set up the routes. Up to now _openfortivpn_ has continued nevertheless in the hope that something else (like ppp-ip-up scripts or anything alike) would assist to set up everything. Starting with version 1.8.0 it exits directly when detecting the situation of not having enough privileges.
