### ISSUE TITLE
Password shouldn't have max size

### ISSUE THREAD

**Issue by jbfavre** [adrienverge/openfortivpn#358]
Hello,
Currently, password max size is hardcoded to 64 in `config.h`.
When using a longer password, openfortivpn fails to establish any VPN since it'll truncate the password in `struct vpn_config` to 64 (`FIELD_SIZE` value from `config.h`), leading to authentication failure on Fortinet side.

Password size shouldn't be capped

**Comment by mrbaseman** [comment]
the above fix has been merged and we have released 1.8.1
