### ISSUE TITLE
Keep-alive?

### ISSUE THREAD

**Issue by dharkness** [adrienverge/openfortivpn#359]
The Windows client will often stay connected for days at a time, but I get disconnected after about 10 hours (sometimes less) using this client on Linux. Is there a keep-alive or session timeout setting in the client?

**Comment by mrbaseman** [comment]
No, there isn't. But you can initiate some traffic through the tunnel, e.g. a loop of sleeps and ocational pings, just to keep the session alive. I think there should be some mechanism on the lower levels, too. 
There is an adjustable timeout on the server side which defaults to 10 hours, but if I remember correctly it is Independent if there is some traffic or not. When no two factor authentication is configured, openfortivpn can reestablish the connection in a loop (see the --persistent option). For this, the password has to be supplied in the config file, e.g. in a temporary copy on a ram disk, and the client certificate, if in use, must be passwordless.

**Comment by dharkness** [comment]
Thanks, I'll run `ping` with a 60-second interval in another shell and see how long it stays open. We're using 2FA so persistence isn't an option.

**Comment by DimitriPapadopoulos** [comment]
need more details here:
* Does the Windows client use IPSec VPN or VPN SSL?
* The default timeout is ~ 8 hours on the FortiGate device. From the [FortiOS™ Handbook SSL VPN for FortiOS 5.0](http://docs.fortinet.com/uploaded/files/1081/fortigate-sslvpn.pdf):
> ### Setting the client authentication timeout
> 
> The client authentication timeout controls how long an authenticated user will remain connected. When this time expires, the system forces the remote client to authenticate again. As with the idle timeout, a shorter period of time is more secure. The default value is 28800 seconds (8 hours). You can only modify this timeout value in the CLI

**Comment by dharkness** [comment]
Thanks for the detailed information. I do not have control over the gate itself, and I don't want to make things less secure. I was just just getting annoyed having it drop me when my workday dragged on longer than normal.

Running a ping every hour has kept me connected for twenty hours the past several days which is more than long enough! :)

**Comment by dharkness** [comment]
I only need to use the VPN to access QA/production VMs, and I start up the VPN at the start of every workday. It's quite likely our NOC team set a lower idle timeout than you've got in yours. I may also be misremembering how long the Windows client stayed connected. Maybe I'll start both this next weekend and keep the idle and see how long before they each get shut down.

For now though, twenty hours gets me through even the longest days. :)

**Comment by mrbaseman** [comment]
When the Fortigate assigns a nameserver or pushes a default route ("tunnel mode") DNS traffic or other internet traffic of applications in the background (e.g. mail client) goes through the tunnel, which might keep it up.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman I think I have already left my Gnome session totally unattended for hours (no mail client running, no DNS requests on my behalf) but I agree the system might be generating network traffic through the tunnel nevertheless.

**Comment by mrbaseman** [comment]
this topic came up again in #564 and I have opened #613 as an attempt to solve it
