### ISSUE TITLE
CentOS: command not found

### ISSUE THREAD

**Issue by davidericardo** [adrienverge/openfortivpn#369]
Hello, 

I've followd the README file and also a tutorial on youtube to install the openfortivpn on CentOS, and the installation process seems to be ok. However, when I run the command "openfortivpn" I got the expected error: 

bash: openfortivpn: command not found...

Any ideas about what wrong I'm doing here?
Thanks in advance.

**Comment by DimitriPapadopoulos** [comment]
How exactly have you followed the README?

I guess the directory you have installed _openfortivpn_ into (`/usr/local/bin`?) is not in your `PATH`.
