### ISSUE TITLE
Bail out if not run as root?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#373]
See latest comments in #362.

**Comment by DimitriPapadopoulos** [comment]
> If root privileges are required for parts of the tunnel setup (as they certainly are), just exit immediately if `geteuid() != 0`.

**Comment by mrbaseman** [comment]
I'm not sure if full root privileges are required on all platforms. Some linux capabilities to set up routes and a suid mechanism to start `pppd` might be sufficient.

**Comment by DimitriPapadopoulos** [comment]
It's possible to work around the elevated privileges requirement with an SUID or _sudo_ mechanism or by configuring _sudo_. However the result of a SUID or _sudo_ mechanism would probably be that _openfortivpn_ is run as _root_, in which case `geteuid() == 0` would still be the proper test, wouldn't it?

**Comment by DimitriPapadopoulos** [comment]
If we really want to avoid _root_:

### Setting routes

The [`CAP_NET_ADMIN` capability](http://man7.org/linux/man-pages/man7/capabilities.7.html) might be enough for _ipv4_set_route_() / _ioctl_():
* I don't know how easy it is to manage capabilities (probably apply _setcap_ to _openfortivpn_) and whether Linux distributions are willing to allow/manage capabilities.
* In any case we could check either for _root_ `geteuid() == 0` **or** the current process capabilities with something like [`prctl(PR_CAPBSET_READ, CAP_NET_ADMIN)`](http://man7.org/linux/man-pages/man2/prctl.2.html).

### Spawning _pppd_

Spawning _pppd_ requires a SUID or _sudo_ mechanism on _pppd_ or a wrapper of _pppd_. For example it looks like group ***pid*** does the trick on Ubuntu:
```ls -l /usr/sbin/pppd
-rwsr-xr-- 1 root dip 390888 Jan 29  2016 /usr/sbin/pppd
```
Perhaps we could either check for _root_ `geteuid() == 0` **or** or have a look at the `/usr/sbin/pppd` file permissions and group ID with [_stat_](http://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html)() and compare with the groups returned by [_getgrent_](http://pubs.opengroup.org/onlinepubs/9699919799/functions/endgrent.html)().

**Comment by DimitriPapadopoulos** [comment]
@ageric Running _openfortivpn_ without being root on Ubuntu fails when spawning _pppd_ if I'm not part of group ***dip***.

The resulting error message looks good enough to me:
```
ERROR:  pppd: An immediately fatal error of some kind occurred, such as an essential system call failing, or running out of virtual memory.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

It would be even better if we could [print an error message right after _execv_() fails](https://github.com/adrienverge/openfortivpn/blob/2443c71/src/tunnel.c#L207-L214):
```
		execv(pppd_args.data[0], (char *const *)pppd_args.data);
		free(pppd_args.data);
		/*
		 * The following call to fprintf() doesn't work, probably
		 * because of the prior call to forkpty().
		 * TODO: print a meaningful message using strerror(errno)
		 */
		fprintf(stderr, "execvp: %s\n", strerror(errno));
```
Unfortunately this error messages doesn't print: Any clue how to fix that?

**Comment by DimitriPapadopoulos** [comment]
@ageric _pppd_ stills fails if I am part of group ***dip***, probably because the `noauth` option requires root privilege. Indeed when running _pppd_ standalone::
```
$ /usr/sbin/pppd 38400 :192.0.2.1 noipdefault noaccomp noauth default-asyncmap nopcomp receive-all nodefaultroute nodetach lcp-max-configure 40 mru 1354 usepeerdns
/usr/sbin/pppd: using the noauth option requires root privilege
$ 
```

The resulting error message makes sense although I agree it's too vague::
```
ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```
But then we're currently limited to the [_pppd_ return values](https://ppp.samba.org/pppd.html#sect12) to print an error message and that's all these return values can tell us.

**Comment by DimitriPapadopoulos** [comment]
C program used for testing:
```
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/prctl.h>
#include <linux/capability.h>


static const char *argv[] = {
    "/usr/sbin/pppd",
    "38400", // speed
    "192.0.2.1:", // <local_IP_address>:<remote_IP_address>
    "noipdefault",
    "noaccomp",
    "noauth",
    "default-asyncmap",
    "nopcomp",
    "receive-all",
    "nodefaultroute",
    "nodetach",
    "lcp-max-configure", "40",
    "mru", "1354"
};


int main()
{
    // Can modify routes?
    int status = prctl(PR_CAPBSET_READ, CAP_NET_ADMIN);
    if (status < 0) {
        fprintf(stderr, "prctl: %s (%d)\n", strerror(errno), errno);
    } else {
        fprintf(stderr, "prctl: success (%d)\n", status);
    }

    // Can spawn PPPD with elevated privileges?
    struct stat buf;

    if (stat(argv[0], &buf)) {
        fprintf(stderr, "stat: failed: %s (%d)\n", strerror(errno), errno);
        exit(EXIT_FAILURE);
    }

    if (geteuid() == 0 || buf.st_mode & S_ISUID) {
        execv(argv[0], (char *const *)argv);
		fprintf(stderr, "execv: cannot exec: %s\n", strerror(errno));
		exit(EXIT_FAILURE);
    } else {
        fprintf(stderr, "cannot elevate privileges\n");
    }
}
```

**Comment by mrbaseman** [comment]
shall this C program be integrated into autoconf, and if so, what should happen depending on the test result?

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman No, I was just trying to understand where exactly _openfortivpn_ requires to be _root_. On Linux the main issue seems to be that the `noauth` option of _pppd_ requires root privileges. The rest could be addressed by being part of group ***dip***  for spawning _pppd_ and **CAP_NET_ADMIN** capability for setting routes.

Perhaps we need to explicitly test `geteuid() == 0` in _openfortivpn_ and bail out, at least on Linux but I suspect there are similar issues on other systems.

**Comment by mrbaseman** [comment]
we already have this check in [main.c](https://github.com/adrienverge/openfortivpn/blob/master/src/main.c#L461). So, the suggestion is to not only print out a warning but going directly to `exit:` and destroy the vpn config, right? 

On OSX I have experienced the same problems as described in #362, namely that I just forgot `sudo`. 
I think it's the same situation there, since it uses `pppd` as well.

On FreeBSD it is also assumed that [ppp](https://www.freebsd.org/cgi/man.cgi?query=ppp) is run as root, but one can also [configure a group](https://www.freebsd.org/doc/handbook/userppp.html) that may run ppp.
The [route](https://www.freebsd.org/cgi/man.cgi?route) command, however, requires root privileges to manipulate the routing table.

**Comment by DimitriPapadopoulos** [comment]
Yes, the suggestion is to exit if not run as _root_.

On FreeBSD the ***network*** group seems equivalent to the ***dip*** group on Ubuntu - except on Ubuntu the `noauth` _pppd_ option requires root privileges so being member of ***dip*** is not sufficient in our case.

**Comment by mrbaseman** [comment]
I'm not sure if the *****network***** group is enough. The [route](https://www.freebsd.org/cgi/man.cgi?route) man page states: 
    "The route utility uses a routing socket and the new message types
     RTM_ADD, RTM_DELETE, RTM_GET, and RTM_CHANGE.  As such, only the super-
     user may modify the routing tables."
So, I think we can implement this as a hard exit instead of just writing out a warning.
