### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by alcidess** [adrienverge/openfortivpn#374]
Hi,

I followed the procedure:
1. ./autogen.sh (OK)
2. ./configure --prefix=/usr/local --sysconfdir=/etc (ok)
3. openfortivpn-master]# make
  CC       src/openfortivpn-config.o
  CC       src/openfortivpn-hdlc.o
  CC       src/openfortivpn-http.o
  CC       src/openfortivpn-io.o
  CC       src/openfortivpn-ipv4.o
  CC       src/openfortivpn-log.o
  CC       src/openfortivpn-tunnel.o
  CC       src/openfortivpn-main.o
  CC       src/openfortivpn-xml.o
  CC       src/openfortivpn-userinput.o
  CCLD     openfortivpn
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `deflateInit_'
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `deflate'
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `deflateEnd'
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `inflate'
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `inflateInit_'
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `inflateEnd'
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so: undefined reference to `zError'
collect2: error: ld returned 1 exit status
make: *** [openfortivpn] Error 1

Information about the machine:
[root@srvlnhbpi1 ~]# uname -a
Linux srvlnhbpi1 3.10.108-BPI-M2U-Kernel #1 SMP Sat Nov 11 19:20:49 CST 2017 armv7l armv7l armv7l GNU/Linux

Can you please help me?

Thank You

**Comment by mrbaseman** [comment]
I don't have any experience on arm, but maybe the shared libraries and the headers don't match, or you should link something additional on arm, which is not correctly recognized by pkg-config and autoconf. Did you check the CentOS Wiki and their hint on an inofficial [EPEL repo](https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp#head-2c416cfaecdf675f43a5be7a81ad50e81e640c93), maybe an alternative openssl version from there?

**Comment by DimitriPapadopoulos** [comment]
It looks like you need to link explicitly with the dependencies of the OpenSSL libraries. This works automatically on most systems but possibly doesn't work too well when cross-compiling, or on some old systems.

On my Ubuntu system, OpenSSL's _libcrypto_ library has limited dependencies:
```
$ ldd /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
	linux-vdso.so.1 =>  (0x00007ffc689fd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1cfc454000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1cfc08a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1cfca9c000)
$ 
```

In your case it looks like _libcrypto_ depends on _zlib_ (functions `deflateInit_`, `deflateEnd`, `inflateInit_`, `inflateEnd`) and that you need to link explicitly with _zlib_ (probably add option `-lz` to the linker).

Not sure this is an _openfortivpn_ issue, could be a bug of your tool chain. I used to know better but haven't cross-compiled or compiled for exotic systems in a long time. Sorry. What is the output of this command on the ARM machine?
`ldd /usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so`

**Comment by alcidess** [comment]
Hi, @mrbaseman. I'm going to see. Thank you for your answer.

Hi @DimitriPapadopoulos. Thank you for your answer. 

 ldd /usr/lib/gcc/armv7hl-redhat-linux-gnueabi/4.8.5/../../../libcrypto.so
        libdl.so.2 => /lib/libdl.so.2 (0xb6df1000)
        libz.so.1 => /lib/libz.so.1 (0xb6dcd000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb6d9e000)
        libc.so.6 => /lib/libc.so.6 (0xb6c42000)
        /lib/ld-linux-armhf.so.3 (0xb6f9a000)

**Comment by DimitriPapadopoulos** [comment]
Clearly _zlib_ is a dependency of OpenSSL's _libcrypto_ on your system, but it isn't pulled in automatically when you link with _libcrypto_, so we need to pass explicitly `-lcrypto -lz`to the linker instead of a mere `-lcrypto`.

I think this is a bug in your tool chain, but again I cannot tell for sure since I haven't worked on portability/linking issues for a long time.

**Comment by DimitriPapadopoulos** [comment]
On my Ubuntu system:
```
$ pkg-config --libs openssl
-lssl -lcrypto
$ 
```

What is the output on your ARM system?

**Comment by alcidess** [comment]
pkg-config --libs openssl
-lssl -lcrypto

**Comment by alcidess** [comment]
Sorry, i'm not a expecialist in this particular. But I appreciate all help.

**Comment by DimitriPapadopoulos** [comment]
This means that OpenSSL does not declare an explicit dependency on _zlib_ and that linking with the two OpenSSL libraries ought to be enough: `-lssl -lcrypto`. Yet you do need to link _zlib_ as far as I can see. So there's a bug somewhere in you ARM system / tool chain. You should be able to work around this bug by running `configure`, then manually editing the resulting Makefile before running `make`, changing:
`OPENSSL_LIBS = -lssl -lcrypto`
into:
`OPENSSL_LIBS = -lssl -lcrypto -lz`

Is this a vanilla Linux distribution or a Linux distribution modified in house?

**Comment by alcidess** [comment]
Uau! It works!

It's a centos 7 in a bananpi m2u.
The file is
2018-01-12-centos-7-lite-v1.0-bpi-m2u-sd-emmc.img.zip
and you can find it at
https://drive.google.com/file/d/1FxsmhNL72xM7izJnZGQgc5bzHj6fP1HY/view

Thank you very much, @DimitriPapadopoulos

**Comment by DimitriPapadopoulos** [comment]
It looks like this is a custom CentOS derivative from [Banana Pi](http://forum.banana-pi.org/t/new-image-2018-01-12-centos-7-lite-for-banana-pi/4677). You should try a more recent version and if the problem persists contact the vendor.
