### ISSUE TITLE
Can't connect under Ubuntu cosmic/18.10

### ISSUE THREAD

**Issue by rhaamo** [adrienverge/openfortivpn#379]
Upgraded yesterday and I'm now greeted with (Using either OpenFortiGUI or the builtin gnome network-manager part):
```
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
INFO:   Logged out.
```

Quickly tried on a live-cd from the LTS and OpenfortiGUI and it works.

Any ideas on that issue ?

**Comment by DimitriPapadopoulos** [comment]
Which Linux distribution does _openfortivpn_ work on and on which does it not work? Same version of _openfortivpn_ on both? Which version of _openfortivpn_ ddi you upgrade from and to?

It would help if you could provide more verbose logs. See basic instructions in the [wiki](https://github.com/adrienverge/openfortivpn/wiki).

**Comment by rhaamo** [comment]
It was working under Ubuntu 18.04.1 LTS, it doesn't under Ubuntu 18.10.

I am using here openfortivpn 1.7.1-1, it was the same before the upgrade.

I've done my tests now using : ```sudo openfortivpn ENDPOINT_IP:443 -u ME --set-routes=1 --set-dns=1 --pppd-log pppd.log -vvv --trusted-cert CERT_THING_HERE --otp MY_OTP_PIN```

And run multiple times, when it fails I only got (pppd.log don't exist):
```
WARN:   Bad port in config file: "0".
DEBUG:  Loaded config file "/etc/openfortivpn/config".                                                                                                            
VPN account password:
DEBUG:  Config host = "xxx"
DEBUG:  Config realm = ""                                                                                                                                         
DEBUG:  Config port = "443"                                                                                                                                       
DEBUG:  Config username = "xxx"                                                                                                                            
DEBUG:  Config password = "xxx"                                                                                                                              
DEBUG:  One-time password = "xxx"                                                                                                                              
DEBUG:  server_addr: xxx                                                                                                                                 
DEBUG:  server_port: 443                                                                                                                                          
DEBUG:  gateway_addr: xxx                                                                                                                                
DEBUG:  gateway_port: 443                                                                                                                                         
DEBUG:  Gateway certificate validation failed.                                                                                                                    
DEBUG:  Gateway certificate digest found in white list.                                                                                                           
INFO:   Connected to gateway.                                                                                                                                     
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.                                                                                                                             
DEBUG:  server_addr: xxx
DEBUG:  server_port: 443                                                                                                                                          
DEBUG:  gateway_addr: xxx                                                                                                                                
DEBUG:  gateway_port: 443                                                                                                                                         
DEBUG:  Gateway certificate validation failed.                                                                                                                    
DEBUG:  Gateway certificate digest found in white list.                                                                                                           
INFO:   Logged out.
```

But it sometimes work, but fails most of the time.

**Comment by rhaamo** [comment]
No better luck with full path for the log.
It looks like it isn't created at all since pppd doesn't looks to be launched because of failed auth/cookie thing.

For the password I just moved host/port/username/password to a config file, and -c it, first try vpn ok, second fail, third fail,.. so it doesn't seems a password typo issue.

Interesting about the delay, it could be but why it would suddendly fails is weird.

**Comment by DimitriPapadopoulos** [comment]
I don't like the idea of adding "magic" delays in the code without further characterization of the problem at hand and perhaps some explanation for the need of a delay (probably a Fortigate appliance bug) - such delays may help in some cases and fail in others.

That was just a shot in the dark. I'm far from convinced a missing delay is the problem, because such a delay would be a Fortigate device bug and therefore shouldn't much depend on the client - Ubuntu18.04 or 18.10. _Could not authenticate to gateway (No cookie given)_ errors are usually related to password issues.

I'm a little bit clueless here. I'd have to debug _openfortivpn_ or add a few more `printf` to the code to understand where exactly it fails.

You don't have access to the Fortigate appliance logs by any chance, do you? They may explain what went wrong.

**Comment by rhaamo** [comment]
I can still get some with the delay (applied .patch of the pull):
```
INFO:   Connected to gateway.                                                                                                                                     
INFO:   Delaying OTP by 2 seconds...
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
```

Still a weird issue.
I can't see any pattern indicating time issue, with delay or not it randomly connect either start middle or end of validity period.
But after a cookie fail, if I retry I didn't even get the ```Delaying...``` line so... I don't know. (and it still fails)

Nope, would have been too easy ;)
I'm not in the network/security team so no access, I will try to get someone to dig on the appliance later in the day/week.

**Comment by DimitriPapadopoulos** [comment]
Fortigate appliances may blacklist accounts after a few failures.

**Comment by mrbaseman** [comment]
...and they may disallow multiple sessions per user, depending on the configuration. If the first connection is not closed properly, this may cause issues when trying to reconnect until a certain timeout for the first session has been reached.

**Comment by DimitriPapadopoulos** [comment]
@rhaamo Were you perhaps blacklisted?

**Comment by rhaamo** [comment]
I'm not sure it's a blacklist issue since it works first time at some moment.

I'm still experiencing this issue, I will see with the appliance team to get logs about that anyway.

**Comment by mrbaseman** [comment]
I assume it's some limit on the number of sessions per user. What happens after it works for the first time? Do you drop out or do you actively log out, or does the connection just stall after some time and you try to revive it? Does any logout (initiated either by you or by the shutdown of the ppp connection) succeed?

**Comment by DimitriPapadopoulos** [comment]
@rhaamo You might want to give _openfortivpn_ 1.8.0 a try, it might be a little bit more verbose. Any luck getting the network team look into the appliance logs?

**Comment by mrbaseman** [comment]
@dark-al can you provide the debug output for both cases (when it fails and when you have logged in via browser)? You could also try version 1.8.0 or the current master. Starting with 1.8.0, when the option  `-v` is given twice, the html authentication traffic is printed out.

**Comment by DimitriPapadopoulos** [comment]
@dark-al Please try with _openfortivpn_ 1.8.1 now that it has been released. If it still fails please open a new issue as it is impossible to follow multiple issues that are not necessarily related under a single ticket.

**Comment by dark-al** [comment]
@DimitriPapadopoulos sorry for the late unswer, after upgrading to v1.8.1 on Fedora all work good, I think that issue can be closed. Thanks a lot!

**Comment by DimitriPapadopoulos** [comment]
@dark-al Thank you for the heads up, we are happy it works for you.

**Comment by DimitriPapadopoulos** [comment]
@rhaamo Have you had better success running _openfortivpn_ on Ubuntu 18.10?

**Comment by DimitriPapadopoulos** [comment]
@rhaamo I suspect this was a blacklisting issue. Can we close this issue?
