### ISSUE TITLE
Stuck on "INFO: Tunnel is up and running"

### ISSUE THREAD

**Issue by FK78** [adrienverge/openfortivpn#388]
```
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
INFO:   Got addresses: [***.**.***.***], ns [***.**.**.*, ***.**.**.*]
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

I've tried connecting using a .conf file and its stuck on "INFO: Tunnel is up and running", but I am not actually connected.

**Comment by mrbaseman** [comment]
How do you detect that you are not actually connected? 
Personally, I look for the "Tunnel up and running" message and when I get it, everything is fine.
Can you run with -v option (which gives more details about the connection process)? 
And often also helpful: Which version of openfortivpn is this?

**Comment by FK78** [comment]
> How do you detect that you are not actually connected?
> Personally, I look for the "Tunnel up and running" message and when I get it, everything is fine.
> Can you run with -v option (which gives more details about the connection process)?
> And often also helpful: Which version of openfortivpn is this?

I try to access my university server when connected, but it fails.
I will get back to you on the -v option results ASAP.
I believe I am on the latest version of openfortivpn, I have downloaded it from the fedora repo.

**Comment by DimitriPapadopoulos** [comment]
@FK78 Might not be related to _openfortivpn_. Check the routes have been modified using command `route` for example. If that's the case, chances are there is a firewall elsewhere, perhaps on the university server itself.

**Comment by DimitriPapadopoulos** [comment]
@FK78 It looks like this is not an _opefortivpn_ issue. Rather a firewall must be blocking access to your server. I suggest we close this issue.

**Comment by FK78** [comment]
> @FK78 It looks like this is not an _opefortivpn_ issue. Rather a firewall must be blocking access to your server. I suggest we close this issue.

You might be right, but I have no been able to try again due to external complications.
