### ISSUE TITLE
tag a new release soon

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#391]
* in #378 the question about a new release has appeared.
* in #300 @DimitriPapadopoulos has expressed that he would like to [test the master ](https://github.com/adrienverge/openfortivpn/pull/300#issuecomment-434314286)before publishing a new release
* in #241 I have suggested to [go through the open pull requests](https://github.com/adrienverge/openfortivpn/issues/241#issuecomment-436998874) and see which ones we can include, too. From my perspective, #389 can be merged,  For #376 and #153 we have to decide if we want to support these additional command line options, and about #361 I'm not sure what's the current status.

**Comment by DimitriPapadopoulos** [comment]
I'm running the current master without problems in my environment.

**Comment by adrienverge** [comment]
Thank you guys, I let you decide when to create a release (should we wait for #389 or not), and I'll do it!

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos do you agree with the changes that I have committed to your branch? :-) 
Ah, and what about the high level changelog which we were asked for in #338?

**Comment by mrbaseman** [comment]
I would like to include 
* #389 which is useful for debugging authentication problems,
* #392 which contains fixes for setting up the routes correctly on FreeBSD - it completes #300 so to say, 
* and #393, the high-level change log

 I have no objections against #376 as it makes the delay configurable. #361 and #153 probably need a bit more effort in order to be applied on the current master.
We would need a bit more testing

**Comment by DimitriPapadopoulos** [comment]
About #376, I'd rather get to the bottom of this issue instead of adding yet another option. Only a single case has been reported where this is useful. Why?

**Comment by mrbaseman** [comment]
#389 might help finding the root cause, or adding more debug output (something like printing the received html code of the login form for loglevel >= 5).

**Comment by mrbaseman** [comment]
@adrienverge has released version 1.8.0, so we can close this one now
