### ISSUE TITLE
Can not connect using FortiToken

### ISSUE THREAD

**Issue by patrickhanft** [adrienverge/openfortivpn#41]
Hi! First of all thanks for this implementation of a fortisslvpn module, which just feels much better than using the proprietary client.

Using **version 1.1.3**, unfortunately, if my account within the fortigate is associated with a FortiToken which is our company standard, I just get this error:

    INFO:   Connected to gateway.
    ERROR:  Could not authenticate to gateway (No cookie given).
    INFO:   Closed connection to gateway.

If I release the association with a fortitoken, it works. I'm a bit irritated now, as some pull requests imply that there should be now some support for "two-factor authentication", but I don't know, if that should mean FortiTokens are supported yet.

Unfortunately I'm not enough developer to find the issue myself, but I'm happy to help with debugging, if someone tells me what I can do.

Thanks!

**Comment by dsgwork** [comment]
Hi @patrickhanft 

I wrote the patch to add two-factor support to the client, so I think I can give you some more information. As far as I know, there is no documentation for the protocol used by the FortiVPN. The two-factor support I wrote was simply done by some simple reverse-engineering of the protocol. Unfortunately, I can only test things as my company has them set up, and we don't use the tokens (our setup has the OTP generated by the FortiGate, which then sends an email which gets converted to an SMS), so the tokens have never been tested (but based on what you say, they probably do not work).

Based on my experience, I expect adding support for the tokens would be quite an easy job, but still needs a VPN account associated with a token for testing. Most likely it's only needed to figure out how the initial login_check response differs from the normal one (to check if we need to do token auth) and in which parameter to the second login_check call we should stuff the OTP code.

If anyone wants to give this a go, the way I used to reverse the protocol was to just set up a stunnel that listens locally, with a self-created key+cert, and then makes an SSL connection to the actual VPN host/port. Then set up a tcpdump on the local port, make a successful connection to it with the official fortinet client and disconnect immediately. Then you can configure wireshark with the self-generated key to decrypt the communications, open the capture file and see what parameters are being sent over the wire.

**Comment by patrickhanft** [comment]
Hi @dsgwork 

Thanks for your comment!

I tried to do a setup to intercept my communication with the fortigate. In the hope that you or anyone else might be able to draw the right conclusions from this, I have two logs created with stunnel and socat.

* [First try with openfortivpn](https://gist.github.com/patrickhanft/82b49ad7911298284d02) which failed
* [Second try with fortinets own client](https://gist.github.com/patrickhanft/c4505439dcc78434d716) which was successful using 6-digit OTP 330230.

Hopefully I did not expose too much here ;-), while being informative enough to someone willing to integrate support for this?

At least I would be very happy, if someone likes to add support!

**Comment by dsgwork** [comment]
Hi @patrickhanft 

Thanks for the trace info. If I'm reading it right, it should be even easier than I though to add support. The two-factor negotiation happens exactly the same with the tokens, it's just that the tokeninfo= parameter does not contain anything, and the code assumes that's invalid.

Can you please apply this patch and try again:
https://gist.github.com/dsgwork/d24cbd2ae22f7ded4554

I suspect that's all it takes. The check for empty tokeninfo doesn't really serve any purpose here, we already handle the case where ret != 1 which should handle all failures.

If this works for you, I will submit it as a pull request, as I've verified it has no effect on the VPNs I have access to (with or without two-factor).

-Davíð

**Comment by patrickhanft** [comment]
It probably took me longer to apply your patch (it somehow got rejected, but that's probably my fault, I did it manually than), than it did you to write it. ;-)

Still fantastic! :+1: 

    patrick@patrick-x240 ~ % sudo openfortivpn 
    VPN account password: 
    INFO:   Connected to gateway.
    2factor authentication token: 
    INFO:   Authenticated.
    INFO:   Remote gateway has allocated a VPN.
    INFO:   Got addresses: [172.25.49.32], ns [172.25.0.11, 172.25.0.11]
    INFO:   Interface ppp0 is UP.
    INFO:   Setting new routes...
    INFO:   Adding VPN nameservers...
    INFO:   Tunnel is up and running.

Thank you very much!

**Comment by adrienverge** [comment]
@dsgwork Thanks for being active here, I couldn't have written a better answer.

Pull requests will be most welcome!

**Comment by patrickhanft** [comment]
@adrienverge well, from my POV we could consider this closed, but I don't know if you want to close this only after you tagged a future release? So, do as you prefer.

Thanks again and BR!

**Comment by adrienverge** [comment]
I consider this solved. :-)

Thanks to both of you for bringing this enhancement.
