### ISSUE TITLE
debug log difficult to read in black terminals

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#413]
A colleague of mine has mentioned that the debug output (grey) is difficult to read on black background. 
A suggested patch changes the color from grey to pink:
```
diff --git a/src/log.c b/src/log.c
index caa2e2d..ed2afae 100644
--- a/src/log.c
+++ b/src/log.c
@@ -44,8 +44,8 @@ static const struct log_param_s log_params[OFV_LOG_DEBUG_DETAILS + 1] = {
        { "ERROR:  ", "\033[0;31m", LOG_ERR},
        { "WARN:   ", "\033[0;33m", LOG_WARNING},
        { "INFO:   ", "",           LOG_INFO},
-       { "DEBUG:  ", "\033[0;90m", LOG_DEBUG},
-       { "DEBUG:  ", "\033[0;90m", LOG_DEBUG},
+       { "DEBUG:  ", "\033[0;95m", LOG_DEBUG},
+       { "DEBUG:  ", "\033[0;95m", LOG_DEBUG},
 };
 
 void init_logging(void)

```
Before making a pull request about his I want to ask for opinions.

**Comment by adrienverge** [comment]
Why not, but pink won't be readable on pink background 😉

I'd be in favor of keeping the same colors. But not opposed to changing them, if several people agree on that!

PS: This is related to https://github.com/adrienverge/openfortivpn/pull/91.

**Comment by mrbaseman** [comment]
Yes, I remember that 😉
And well, personally, I agree that everyone who builds his own client can maintain his favorite colors based on the above patch and apply them at build-time 😉

**Comment by adrienverge** [comment]
:+1:

**Comment by mrbaseman** [comment]
So, let's close this
