### ISSUE TITLE
Could not authenticate to gateway (Bad HTTP response code)

### ISSUE THREAD

**Issue by nirvana9832** [adrienverge/openfortivpn#423]
Bare with me, as I am quite new to the Linux/Ubuntu scene.. Very fresh.
Ubuntu v 18.10
Installed Forticlient(Doesn't support remote access i guess), and openfortiVPN
Our company has 2 Ubuntu users who need the ability to VPN into our servers.

Upon trying to login we get the error in the title.
I've read the other posts and tried debug mode but no further details are given. even with "-v -v"
Do I need to setup a new tunnel on the fortinet firewall in order to allow Linux systems in? I checked and didn't see anything apparent. 

Thanks for any assistance.

**Comment by DimitriPapadopoulos** [comment]
_FortiClient_ is Fortinet's official client. Does it work? Are you able to connect to connect to your company's FortiGate device with it?

_openfortivpn_ is an open-source alternative. Concerning the error message, you are most probably entering incorrect credentials. Please explain which kind of credentials you use: login/password, one time password, hardware token? Also I suggest running _openfortivpn_ in debug mode as described in the [wiki](https://github.com/adrienverge/openfortivpn/wiki#debugging-openfortivpn) and report back. Include both the _openfortivpn_ log and the _pppd_ log, just make sure to **remove sensitive data** before posting here.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos now our messages have crossed. Never mind, that's what I was just typing: 

The version packaged with Ubuntu 18.10 is probably still below 1.8.x, so the "-v -v" option does not give more detailed debugging output. 
Out of experience the bad HTTP response code often is a sign for incorrect authentication. Things you could try:
* double check correct spelling of the username and the password
* if possible, clarify that your account is allowed to use the VPN
* try if the Forticlient can authenticate you
* try logging in via browser at the web page that should be shown when pointing it to the vpn gateway
* compile a more recent version of openfortivpn from source and try with '-v -v'  (make sure to remove passwords etc. before posting this output.

**Comment by nirvana9832** [comment]
$ sudo openfortivpn ********* -v -v -u *********
[sudo] password for *********: 
DEBUG:  Loaded config file "/etc/openfortivpn/config".
VPN account password: 
DEBUG:  Config host = "*********"
DEBUG:  Config realm = ""
DEBUG:  Config port = "*********"
DEBUG:  Config username = "*********"
DEBUG:  Config password = "********"
DEBUG:  server_addr: *********
DEBUG:  server_port: *********
DEBUG:  gateway_addr: *********
DEBUG:  gateway_port: *********
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (Bad HTTP response code).
INFO:   Closed connection to gateway.
DEBUG:  server_addr: *********
DEBUG:  server_port: *********
DEBUG:  gateway_addr: *********
DEBUG:  gateway_port: *********
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.

**Comment by DimitriPapadopoulos** [comment]
Where have you read that _FortiClient_ doesn't support remote access yet? It might be that it does not support Ubuntu 18.10 yet, using an LTS (Long-Term Support) version of Ubuntu such as Ubuntu 18.04 might be a better idea.

Note that on Windows _FortiClient_ uses IPSec by default, while on Linux both _FortiClient_ and _openfortivpn_ use SSLVPN. I know close to nothing on FortiGate appliance internals, but has SSLVPN been enabled on the FortiGate appliance? Also if you are the administrator you should have access to the FortiGate logs that might shed some light on the authentication failure.

**Comment by mrbaseman** [comment]
the fortigate logs are often misleading, for example "reason: unknown user" can mean that there was a typo in the password.
Another hint I can give: you should enable both, web-mode and tunnel-mode (the web interface is used for the authentication, and then it switches over to tunnel mode for the actual encrypted transport), and you need at least one policy that allows some traffic from the ssl_vpn to somewhere (without any policy at all that uses the ssl vpn authentication also fails).

**Comment by nirvana9832** [comment]
I got FortiClient to run on the LTS, but there is no Remote Access tab, such as the Windows version.

**Comment by mrbaseman** [comment]
hmm... I have an older version installed here, and there is a separate executable `forticlientsslvpn`. I can check a newer version tomorrow

**Comment by mrbaseman** [comment]
In the Download area for the FortiGate Firmware 5.2 there is a folder for SSLVPN which contains also the linux vpn client. I think it should be integrated into the Forticlient for Linux, but the latest in the specifications for 6.0 on forticlient.com, there is no mention of vpn (neither ipsec nor sslvpn).

**Comment by DimitriPapadopoulos** [comment]
@nirvana9832 Any luck connecting with `openfortivpn` or `forticlientsslvpn`?

**Comment by DimitriPapadopoulos** [comment]
@nirvana9832 Is this still an issue for you? Have you found a solution?

**Comment by rizwankh** [comment]
I have exactly the same issue as well.

**Comment by DimitriPapadopoulos** [comment]
@rizwankh This is an old issue. I believe it would be better to create a new one describing the problem you face and provide some information:
* Version of operating system and _openfortivpn_
* Verbose (sanitized) output of `openfortivpn --v -v`
* Does _FortiClient_ work while _openfortivpn_ doesn't?
