### ISSUE TITLE
Trusted cert random in every machine

### ISSUE THREAD

**Issue by Adonist** [adrienverge/openfortivpn#434]
The trusted cert option changes value every time.
The real forticlient has an option to ignore cert. Can this be added to the app so it avoid having to figure out each time.

Thanks

**Comment by mrbaseman** [comment]
The trusted certificate is the certificate of the Fortigate to which you connect. It should contain the fully qualified host name and/or the ip address and therefore it should be different for each device you are connecting to.
If it changes every time you connect, then this is something that should not happen. It is a sign that  your ssl connection is intercepted, either by another Fortigate on the path between you and the one you are connecting to, or by something else (similar devices from other vendors) or there is an untrusted man in the middle. 
In the latter case you definitely want to know that the certificate has changed and that you should not continue to connect.
In the case of a well-known interception (you are sitting behind a Fortigate that does full packet inspection also on your sslvpn connections to other sites), _openfortivpn_ tells you the issuer of the certificate that it sees.  You can add that one (or the root-ca of that chain) to your ca-file (either you add it globally to your trusted ca's in the OS, or you specify a ca-file on the command line or via config file option. That is a concatenated list of PEM-encoded root-ca certificates that you trust.

**Comment by Adonist** [comment]
I'm sorry, I thought that ID was auto generated by the application and thought it would be different for each machine.
I'm closing this since it's not an issue. I'm sorry for that. It was my mistake and misunderstanding.

**Comment by mrbaseman** [comment]
No problem. That "ID" is the sha256 digest of the server certificate used on the Fortigate that you connect to (or, if the connection is intercepted, the one that you see from the perspective of the client). You can verify it by connecting with a web browser and saving the certificate as a PEM file to disk. Then, you can obtain the digest with `openssl dgst -sha256 server-cert.pem`. The browsers usually can display it, too, but the output format may differ.

**Comment by DimitriPapadopoulos** [comment]
That's indeed documented in the man page:

**--trusted\-cert=**\<digest\>
Trust a given gateway. If classical SSL certificate validation fails, the gateway certificate will be matched against this value. \<digest\> is the X509 certificate's sha256 sum. The certificate has to be encoded in DER form.
