### ISSUE TITLE
vpn connection from debian

### ISSUE THREAD

**Issue by iBet7o** [adrienverge/openfortivpn#437]
I need to connect to vpn from debian and how much with the following data:

peer: -----
pre shared key: -----
user: -----
password: -----

With this client could I connect to the vpn?

**Comment by DimitriPapadopoulos** [comment]
What sort of VPN? A Fortinet VPN? Is the Fortinet VPN appliance configured for IPSec only or SSL too?

**Comment by iBet7o** [comment]
Fortinet VPN with IPSec

**Comment by DimitriPapadopoulos** [comment]
_openfortivpn_ is a VPN SSL client.
