### ISSUE TITLE
openfortivpn adds garbage to the end of my resolv.conf file

### ISSUE THREAD

**Issue by fretn** [adrienverge/openfortivpn#44]
some garbage characters are added to the end of the file, see screenshot

![openfortivpn](https://cloud.githubusercontent.com/assets/8073722/12608423/50640a72-c4dc-11e5-95b0-092918852f74.png)

**Comment by adrienverge** [comment]
Hi @fretn.

Could you give more details? For instance, what type of "garbage" characters?

```sh
tail -n 4 /etc/resolv.conf | hexdump -C
```

**Comment by fretn** [comment]
```[frlae@modimo openfortivpn]$ tail -n 1 /etc/resolv.conf | hexdump -C
00000000  11 04 02 0a                                       |....|
00000004
```

**Comment by fretn** [comment]
I'm currently testing it on ubuntu 14.04

but I discovered it on my OS X port, first I thought it was an OS X glitch.

when I print out the buffer (in ipv4_add_nameservers_to_resolv_conf) after the fread call, I already see the garbage characters

**Comment by fretn** [comment]
ipv4.c line 398: log_debug("%zu : %zu\n", stat.st_size, malloc_usable_size(buffer));

this outputs:

DEBUG:   252 : 264

there is more allocated than requested, this explains where the garbage comes from

**Comment by adrienverge** [comment]
Thanks for debugging!

Actually this bug is probably due to the `fputs` on line 438, that assumes the file content is null-terminated (which is not always the case). Can you check if #47 solves this?

**Comment by fretn** [comment]
PR #47 fixes this problem on both linux and mac, thx !
