### ISSUE TITLE
openfortivpn closes all ports on server

### ISSUE THREAD

**Issue by myuhlz** [adrienverge/openfortivpn#440]
Once I do `$sudo openfortivpn -c openfortivpn.conf` it closes all ports/connections on the server I'm working on and can no longer communicate with it. As it is an ec2 instance, I can't access it unless I run locally the forticlient, therefore shutting down the openfortivpn tunnel on the remote server. Is there any workaround to keep the server available for all other services and at the same time keep the VPN connection?

**Comment by DimitriPapadopoulos** [comment]
The VPN client routes all traffic through the VPN tunnel, you have to connect to he machine running the VPN client from the network at the other end of the VPN tunnel using the IP address assigned by the Fortinet appliance. That's by design, the same would happen with FortiClient You can try to work around by modifying routes yourself (`--no-routes` and add a _pppd_ script).

**Comment by myuhlz** [comment]
Can you please help me with the routing??
When the forticlient fires up, it adds a ppp0 interface with the following configuration:
```

$ netstat -nr | grep ppp0
default            link#15            UCS            62        0    ppp0
1.1.1.1            10.172.241.204     UH              1        2    ppp0
8.8.8.8            link#15            UHW3I           0       18    ppp0     84
17.249.156.12      link#15            UHW3I           0        9    ppp0     77
17.249.156.24      link#15            UHW3I           0        9    ppp0     77
17.249.156.25      link#15            UHW3I           0        9    ppp0     77
17.249.156.26      link#15            UHW3I           0        9    ppp0     77
17.249.156.32      link#15            UHW3I           0        9    ppp0     77
17.249.156.33      link#15            UHW3I           0        9    ppp0     77
17.249.156.74      link#15            UHW3I           0        9    ppp0     77
17.249.156.78      link#15            UHW3I           0        9    ppp0     77
34.220.116.240     link#15            UHWIi           1       12    ppp0
69.31.75.169       link#15            UHWIi           2       17    ppp0
69.31.75.185       link#15            UHWIi           2       17    ppp0
172.20.1.115       link#15            UHWIi           6       29    ppp0
172.20.1.215       link#15            UHW3I           0       10    ppp0     77
172.20.224.100     link#15            UHWIi           6       71    ppp0
172.20.246.136     link#15            UHW3I           0       73    ppp0     65
224.0.0/4          link#15            UmCS            2        0    ppp0
224.0.0.251        link#15            UHmW3I          0        0    ppp0     29
239.255.255.250    link#15            UHmW3I          0        6    ppp0     29
255.255.255.255/32 link#15            UCS             0        0    ppp0

```
Does any of this should be inside the script you mention? Any help will be greatly appreciated.

**Comment by mrbaseman** [comment]
if I understand correctly, you don't want the default route over ppp0. the 1.1.1.1 route is the one to the other end of the tunnel, you probably don't want the route to the 8.8.8.8 nameserver over the vpn. for the other hosts and networks you would need to add the route over ppp0 manually in your pppd script. See the wiki entry about [How to add specific routes using pppd](https://github.com/adrienverge/openfortivpn/wiki#how-to-add-specific-routes-using-pppd) for a tutorial on this topic.

**Comment by myuhlz** [comment]
> if I understand correctly, you don't want the default route over ppp0
>
That's correct. From a EC2 machine I want to be able to serve web on ports 80 and 443 for an app that hits an API accessible only by this vpn. 
I've read the wiki entry but I didn't get how to get the script started. Does it need to be initialized from the openfortivpn command line?

**Comment by mrbaseman** [comment]
oh, the vpn should be kept open all the time and you want to access a single IP that runs the API through the tunnel? So, I would recommend using the `--no-routes`, `--pppd-no-peerdns`, and  `--persistent` option and simply put the single route command into the ip-up script:
```route add ip-to-access dev ppp0```
assuming that the ppp device is ppp0 in your case. The mechanism with the ip-up script is that _openfortivpn_ calls _pppd_ to open the tunnel, and _pppd_ automatically looks in `/etc/ppp/ip-up.d/` for srcipts that it is supposed to execute once the interface is up. 
This way, only traffic to this single ip for which your script adds a route is redirected through the vpn tunnel, everything else is routed as usual.

**Comment by myuhlz** [comment]
Thanks mrbaseman but it didn't work. I'm going to try another approach.

**Comment by mrbaseman** [comment]
it didn't work means the script was not called? - that could be a configuration issue of pppd perhaps
or the route was added but you still weren't able to serve the web service while being able to access the API through the tunnel? - In that case, if the route was added correctly, I would expect it to be an issue on a different level, maybe something like selinux or apparmor that would deny access to the tunnel for the webserver or a backend script called from that context... 
just some thoughts that might help to narrow down what's the problem - independent of the vpn solution
