### ISSUE TITLE
Let's Encrypt certs not trusted

### ISSUE THREAD

**Issue by DClabaut** [adrienverge/openfortivpn#442]
When connecting to an SSL-VPN platform using a Let's Encrypt TLS cert, openfortivpn throws an error and requires the use of the --trusted-cert option.
Since Let's Encrypt certs are renewed often (3 months is the maximum I believe), users have to be taught to blindly allow whatever cert is on the the other side, which is a terrible security practice.
Let's Encrypt is now issuing over 1 million certs every day and the ACME protocol is an IETF standard (RFC 8555).
Can OpenfortiVPN trust the Let's Encrypt CA?

**Comment by DimitriPapadopoulos** [comment]
I think this is not an _openfortivpn_ issue as much as an _OpenSSL_ issue. Which exact OS is this?

**Comment by DimitriPapadopoulos** [comment]
I mean that _openfortivpn_ uses the certification authorities defined at the system level.

**Comment by DimitriPapadopoulos** [comment]
@DClabaut While we believe this is a case of a poorly configured FortiGate appliance, missing the intermediate certificates that are required validate the Let's Encrypt certificate against the relevant root certificate, feel free to reopen this issue if you believe that's not the case. As I said there shoudl be nothing special about Let's Encrypt certificates, we let OpenSSL validate all SSL certificates, _openfortivpn_ just calls OpenSSL functions for that.

**Comment by DimitriPapadopoulos** [comment]
For what it's worth, here is how a Let's Encrypt certificate is validated by a client:
```
DST Root CA X3 (Digital Signature Trust Co.)
└── Let's Encrypt Authority X3
    └── letsencrypt.org
```
OpenSSL does not know about the Let's Encrypt CA, it just knows about the Digital Signature Trust root CA. All servers, including the FortiGate gateway, need to present the certificate chain to clients, be it web browsers or VPN clients. In this case the intermediate certificate that needs to be part of the transmitted certificate chain is the _Let's Encrypt Authority X3_ certificate.

![lencr org](https://user-images.githubusercontent.com/3234522/94799032-cd7dd480-03e2-11eb-8a68-afe9f5913a96.png)

**Comment by DimitriPapadopoulos** [comment]
See [Technical Tip: How to avoid certificate error message by chaining Root CA and Intermediate CA certificates](https://kb.fortinet.com/kb/documentLink.do?externalID=FD41362).
