### ISSUE TITLE
cross compile issues

### ISSUE THREAD

**Issue by lucize** [adrienverge/openfortivpn#446]
trying to cross compile on openwrt and I get some errors with configure

```
checking whether rtentry is available and has rt_dst
configure: error: cannot run test program while cross compiling
checking for /proc/net/route
configure: error: cannot check for file existence when cross compiling
checking for /usr/sbin/ppp
configure: error: cannot check for file existence when cross compiling
checking for /usr/sbin/pppd
configure: error: cannot check for file existence when cross compiling
```

even if I specify some of them in the configure args it doesn't take them (like --disable-proc, --with-ppp, --with-pppd)
is there a better way to specify this ?

also with openssl 1.1.1 is installed in sdk I get this (only 1.0.1 is supported ?) :

```
src/tunnel.c: In function 'ssl_connect':
src/tunnel.c:724:2: warning: implicit declaration of function 'SSL_load_error_strings'; did you mean 'ERR_lib_error_string'? [-Wimplicit-function-declaration]
  SSL_load_error_strings();
  ^~~~~~~~~~~~~~~~~~~~~~
  ERR_lib_error_string
src/tunnel.c:726:2: warning: implicit declaration of function 'SSL_library_init'; did you mean 'SSL_in_init'? [-Wimplicit-function-declaration]
  SSL_library_init();
  ^~~~~~~~~~~~~~~~
  SSL_in_init
  CCLD     openfortivpn
/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/lib/gcc/i486-openwrt-linux-musl/7.4.0/../../../../i486-openwrt-linux-musl/bin/ld: src/openfortivpn-tunnel.o: in function `ssl_connect':
tunnel.c:(.text+0x9c1): undefined reference to `SSL_load_error_strings'
/home/build/openwrt/staging_dir/toolchain-i386_pentium4_gcc-7.4.0_musl/lib/gcc/i486-openwrt-linux-musl/7.4.0/../../../../i486-openwrt-linux-musl/bin/ld: tunnel.c:(.text+0x9c7): undefined reference to `SSL_library_init'
collect2: error: ld returned 1 exit status

```

**Comment by mrbaseman** [comment]
about "rtentry is available and has rt_dst":
you can try to define a preprocessor macro HAVE_RT_ENTRY_WITH_RT_DST 1 if your target platform is linux-like or 0 if the target platform is more mac OSX / BSD like.

--enable-proc / --disable-proc should override the settings that are detected by the configure script. Have a look at the final messages at the very end of the configure output

by means of the switches --with-pppd and --with-ppp you should be able to specify the absolute path to the binary (ppp on FreeBSD, pppd on OSX or linux) or by supplying =yes the default path in /usr/sbin is assumed.

With openssl I think we already support 1.1.x but maybe there have been incompatible changes between 1.1.0 and 1.1.1.. We should check this in a cleaner context (i.e. not during cross compiling, and perhaps on a platform where this is already the system default). But maybe the configure script has not properly detected your ssl header location and takes the wrong ones?

**Comment by lucize** [comment]
> define a preprocessor macro HAVE_RT_ENTRY_WITH_RT_DST 1
> [...]
> --enable-proc / --disable-proc should override the settings that are detected

@mrbaseman thanks for input

wouldn't be better not to run detection if the settings are passed ? detection always fail in cross-compile and config is aborted

like ex (for rt_dst):
```
--- a/configure.ac      2019-06-10 00:23:38.999657271 +0300
+++ b/configure.ac      2019-06-10 00:27:59.463668257 +0300
@@ -216,6 +216,16 @@
 LIBS="${save_openssl_LIBS}"

 # Specialised checks for particular features.
+# when cross compile, don't run the test
+AC_ARG_WITH([rt_dst],
+       AS_HELP_STRING([--with-rt_dst],
+                         [disable rtentry with rt_dst testing (cross compile)]),
+       AS_IF([test "x$with_rt_dst" = "xyes"],[
+       AC_MSG_NOTICE([HAVE_RT_ENTRY_WITH_RT_DST... 1])
+       AC_DEFINE(HAVE_RT_ENTRY_WITH_RT_DST)
+       ])
+)
+AS_IF([test "x$with_rt_dst" = "x" ], [
 AC_MSG_CHECKING(whether rtentry is available and has rt_dst )
 AC_TRY_RUN([
 #include <sys/types.h>
@@ -233,6 +243,7 @@
   AC_DEFINE(HAVE_RT_ENTRY_WITH_RT_DST)
   AC_MSG_RESULT(yes)
 ], AC_MSG_RESULT(no) )
+])

 NETSTAT_PATH=""
 PPP_PATH=""
```
regarding openssl, conf.log
```
configure:4654: checking for libssl >= 0.9.8 libcrypto >= 0.9.8
configure:4661: $PKG_CONFIG --exists --print-errors "libssl >= 0.9.8 libcrypto >= 0.9.8"
configure:4664: $? = 0
configure:4678: $PKG_CONFIG --exists --print-errors "libssl >= 0.9.8 libcrypto >= 0.9.8"
configure:4681: $? = 0
configure:4719: result: yes
[...]
pkg_cv_OPENSSL_CFLAGS=-I/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/include
pkg_cv_OPENSSL_LIBS='-L/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/lib -lssl -lcrypto'
[...]
OPENSSL_CFLAGS='-I/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/include'
OPENSSL_LIBS='-L/home/build/openwrt/staging_dir/target-i386_pentium4_musl/usr/lib -lssl -lcrypto'

```
the location is correct

ssl.h contains
```
# if OPENSSL_API_COMPAT < 0x10100000L
#  define SSL_load_error_strings() \
    OPENSSL_init_ssl(OPENSSL_INIT_LOAD_SSL_STRINGS \
                     | OPENSSL_INIT_LOAD_CRYPTO_STRINGS, NULL)
# endif

```

**Comment by mrbaseman** [comment]
@lucize thanks for the suggestions about the configure.ac Any improvement of the autoconf setup is appreciated. 

It seems you have already covered most of the locations that may be problematic for cross-compiling. Could you open a pull request for this, please? We can complete the work with additional commits, later on. Also I would like to test it on all the platforms that we support before merging. 

I have opened a separate issue about the openssl topic.

**Comment by lucize** [comment]
ok, I've made the PR and I can confirm that openssl 1.1.1 is linking if deprecated apis are selected, didn't test it yet

**Comment by mrbaseman** [comment]
I have merged your pull requests. Shortly after I have merged #451 I have noticed that it has broken the automatic  path detection for the ppp client on FreeBSD. It has always used the cross compile fallback. So I have corrected that in an additional commit in #449 
I think we  have addressed the cross compile topics then, right?

**Comment by lucize** [comment]
yes, adding --with-pppd="$PATH_TO_PPPD" works as expected, no need to add --with-ppp value

maybe a summary info to be added in the readme when cross, ex:

CONFIGURE_ARGS += \
        --disable-proc \
        --with-rt_dst="yes" \
        --with-pppd="/usr/sbin/pppd"

it remains only the ifs for OPENSSL depending on version

**Comment by mrbaseman** [comment]
the openssl issue gets fixed by #452

**Comment by mrbaseman** [comment]
all the fixes went into the [1.10.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.10.0)

**Comment by mrbaseman** [comment]
I have decided to add a more generic hint to check the available configure arguments, and recommend it especially when cross compiling.

**Comment by Foadsf** [comment]
@DimitriPapadopoulos, my apologies if I highjacked this thread. This was one of the first results that came up in the Google search. My comment did not necessarily try to address an issue with `openfortivpn`. Another option as suggested [here](https://stackoverflow.com/a/78182115/4999991) is to use `AC_CHECK_HEADER`

**Comment by DimitriPapadopoulos** [comment]
We don't check for headers with `AC_CHECK_FILE`. We use `AC_CHECK_HEADER` instead.
