### ISSUE TITLE
No browser connections after disconnecting using the Network Manager

### ISSUE THREAD

**Issue by Kevin-at-Navigram** [adrienverge/openfortivpn#456]
**Minor update for future reference**
Original title: *resolv.conf unreadable after disabling openfortisvpn*
See later in thread for workaround

# Setup
Ubuntu 19.04
network-manager-fortisslvpn 1.2.8-2
network-manager-fortisslvpn-gnome 1.2.8-2 
openfortivpn 1.8.1-1

# How to

$ cat /etc/resolv.conf
$ ls /etc/resolv* -l

_Connect to a Forti VPN_
_Disconnect from the Forti VPN_

$ cat /etc/resolv.conf
$ ls /etc/resolv* -l

You'll be able to see that the resolve settings have changed and that it causes further issues.

**Comment by DimitriPapadopoulos** [comment]
Could you please perhaps upgrade to _openfortivpn_ 1.10.0 or at least 1.9.0? Then if the problem persists send a log and further information such as contents of `resolv.conf`? The reason I am asking this can be found for example in #332.

**Comment by Kevin-at-Navigram** [comment]
Who is actually in charge of distributing the binaries for on Debian? They're out of date and that propagates throughout the ecosystem:

https://packages.debian.org/buster/openfortivpn

I've compiled the binaries myself and I'll report back when I have more info.

**Comment by Kevin-at-Navigram** [comment]
Using 1.10.0 (ced2b4cd18e1d134e92dde4c51cb2ffe8b9958d4)

Found an issue in with the read-write settings of the files. After you disable the VPN, it doesn't properly assign the right owners to the resolver. Do mind, i use the GNOME network manager, so that might be related.

# before
```
lrwxrwxrwx 1 root root 39 feb 26 18:13 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
-rw-r--r-- 1 systemd-resolve systemd-resolve 720 jun 24 13:45 /run/systemd/resolve/stub-resolv.conf
```

# after
```
lrwxrwxrwx 1 root root 39 feb 26 18:13 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
-rw------- 1 root root 720 jun 24 13:45 /run/systemd/resolve/stub-resolv.conf
```

**Comment by DimitriPapadopoulos** [comment]
> After_ you disable the VPN, it doesn't properly assign the right owners to the resolver.

Also "it" might be _pppd_, not the VPN. Have you tried the different options such as `--pppd-no-peerdns`?

**Comment by Kevin-at-Navigram** [comment]
@DimitriPapadopoulos If I want to run it with `--pppd-no-peerdns` and `--no-dns`, do I then only have to add it to the `/etc/openfortivpn/config`, or should I then start the openfortisvpn using the Terminal with sudo?

I tried just adding the following lines to  `/etc/openfortivpn/config` but it made no difference.
```
set-dns = 0
pppd-use-peerdns = 0
```

**Comment by mrbaseman** [comment]
I believe the GUI tool creates an ad-hoc config file which it passes to `openfortivpn`. 
`openfortivpn` normally should edit the file without changing the permissions, but if pppd (or one of its ip-up/ip-down-scripts, e.g. the one provided by resolvconf.d) handles the nameserver updates, other things may happen.

**Comment by DimitriPapadopoulos** [comment]
@Kevin-at-Navigram Any luck getting running `openfortivpn` directly from command line with options `--pppd-no-peerdns` and `--no-dns`?

**Comment by epsilon77** [comment]
> Who is actually in charge of distributing the binaries for on Debian? They're out of date and that propagates throughout the ecosystem:
> 
> https://packages.debian.org/buster/openfortivpn
> 
> I've compiled the binaries myself and I'll report back when I have more info.

Hi, 

I am mantainer of openfortivpn in Debian, I will upload to unstable the new version the next week.

Regards.

**Comment by Kevin-at-Navigram** [comment]
@DimitriPapadopoulos I've have not tried that. That said, using the Network Manager, I get perfectly fine access to the VPN service... is just happens that afterwards the system must be restarted for me to have any further network access.

I'll give it another try in the coming days

**Comment by DimitriPapadopoulos** [comment]
It could be a Network Manager issue. Please try the standalone _openfortivpn_ program, otherwise create a ticket for the Network Manager plugin. My gut feeling is that this is not an _openfortivpn_ issue.

**Comment by DimitriPapadopoulos** [comment]
Also as explained by @mrbaseman the GUI usually creates an _ad hoc_ configuration file which is *not* `/etc/openfortivpn/config` - it is passed to _openfortivpn_ using option `-c`. So changing `/etc/openfortivpn/config` won't help.

**Comment by Kevin-at-Navigram** [comment]
I think your idea is confirmed, and that this is a Network Manager issue. When using the cli, the connection is properly set up. When using the Network Manager though, the DNS is not properly reset after disabling the tunnel, likely because of the read-write permissions. 

**Workaround**
If you run `resolvectl status` after disabling the tunnel, you can see the following DNS allocation.

```

Link 3 (wlp3s0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 192.168.1.254
         DNS Servers: 176.103.130.130
                      192.168.1.254
          DNS Domain: ~.
                      home
```

The `Current DNS Server` is wrong. That way, it will be impossible to get any web addresses. The easiest way to restore this, is to disable your current network connection (possibly set your computer in airplane mode) and then reconnect it. It will rebuild the DNS and it will then point to the online server again.

@DimitriPapadopoulos Can you show me how I best log this to the Network Manager team?

**Comment by DimitriPapadopoulos** [comment]
@Kevin-at-Navigram I think [this is the NetworkManager-fortisslvpn page](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn).

Since this looks like a NetworkManager issue, is it OK to close this issue?

**Comment by Kevin-at-Navigram** [comment]
Created an issue for the Network Manager applet:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/issues/18
