### ISSUE TITLE
Ignoring /etc/hosts on linux

### ISSUE THREAD

**Issue by hub20xx** [adrienverge/openfortivpn#459]
Hello,

First, thank you very much for openfortivpn!

It is the perfect way for me to connect to my vpn of choice:
 - command line
 - little configuration
 - simple and effective

It is probably not an issue but when I'm connected using openfortivpn, the contents of `/etc/hosts` are ignored.

For example, the following domain, only reachable through the vpsn, cannot be resolved, even when I have set it like this in my `/etc/hosts`
```
onlythroughvpn.local  10.30.0.11
```
My config is like this:
```
host = my.vpnhost.com
port = 443
username = myusername
set-routes = 1
set-dns = 1
trusted-cert = ei203f92mytrustedcert2309234809
```
All other features work well, dns, etc, just this `/etc/hosts` that is ignored.

Any idea how I could fix it?

**Comment by DimitriPapadopoulos** [comment]
How do you know that the contents of `/etc/hosts` are ignored? Can you please show the actual commands and their output?

**Comment by mrbaseman** [comment]
strange. I didn't observe this. It could be a problem with the host search order, see for example https://www.oreilly.com/library/view/linux-network-administrators/1565924002/ch06.html 
but to be honest I don't understand how this is influenced by the vpn connection. Sure, the vpn, depending on the server-side configuration, can push different name servers (see the `--set-dns` option in the man page), but it should not change anything in the order of sources (files, dns, ...)

**Comment by hub20xx** [comment]
After successfully connecting to the vpn using `sudo openfortivpn -c config`, when I browse the url `onlythroughvpn.local` using a browser for example, I get `cannot resolve onlythroughvpn.local`.
For example with curl:
```
curl -v http://onlythroughvpn.local
* Could not resolve host: onlythroughvpn.local
* Closing connection 0
curl: (6) Could not resolve host: onlythroughvpn.local
```

**Comment by DimitriPapadopoulos** [comment]
Indeed it looks like your entry in `/etc/hosts` is not taken into account. In my case:
```
$ ls -l /etc/hosts
-rw-r--r-- 1 root root 199 Jan 18  2018 /etc/hosts
$ 
$ cat /etc/hosts
127.0.0.1   xxxxxxxx.xxxxx.xxx.xx xxxxxxxx localhost localhost.localdomain
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
$ 
$ curl -v http://localhost.localdomain/
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost.localdomain port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost.localdomain port 80: Connection refused
$ 
$ curl -v http://onlythroughvpn.local/
* Could not resolve host: onlythroughvpn.local
* Closing connection 0
curl: (6) Could not resolve host: onlythroughvpn.local
$ 
```

I suggest:
* Post the exact Linux distribution you are using.
* Post the output of `ls -l /etc/hosts` and `cat /etc/hosts` (sanitize it first if needed).
* Post the output of `ls -l /etc/nsswitch.conf` and `cat /etc/nsswitch.conf`.

**Comment by DimitriPapadopoulos** [comment]
By the way, if the contents of `/etc/hosts` really are:
```
onlythroughvpn.local  10.30.0.11
```
then try changing to the [recommended syntax](http://man7.org/linux/man-pages/man5/hosts.5.html):
```
10.30.0.11  onlythroughvpn.local
```

**Comment by hub20xx** [comment]
> By the way, if the contents of `/etc/hosts` really are:
> 
> ```
> onlythroughvpn.local  10.30.0.11
> ```
> 
> then try changing to the [recommended syntax](http://man7.org/linux/man-pages/man5/hosts.5.html):
> 
> ```
> 10.30.0.11  onlythroughvpn.local
> ```

I did that and it worked!

Thank you very much @DimitriPapadopoulos (and @mrbaseman) for the help!

Closing because it was my mistake, and no bug!

Thank you again for that useful software!

**Comment by mrbaseman** [comment]
a hint which might be related to this topic: The dns-suffix feature is supported with the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0) now
