### ISSUE TITLE
Is it possible to compile files available for Android?

### ISSUE THREAD

**Issue by cnucky** [adrienverge/openfortivpn#461]
Is it possible to compile files available for Android?

**Comment by mrbaseman** [comment]
I haven't tried that. In the latest release we have improved the options for cross compiling. Basically, Android uses a kernel that is derived from the linux kernel, so the chances are not too bad. _openfortivpn_ is a command line, tool though. For most (?) Android users a Java based GUI would be required, which currently doesn't exist. 
On the other hand, an existing command line tool could be a starting point and if that works on a rooted device, the next step would be a port of [openfortigui](https://hadler.me/linux/openfortigui/) or [nm-applet](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) to Android

**Comment by DimitriPapadopoulos** [comment]
For the sake of completeness a proprietary vendor app is available for Android:
[FortiClient](https://play.google.com/store/apps/details?id=com.fortinet.forticlient)

**Comment by Morteza-Rastgoo** [comment]
@DimitriPapadopoulos FortiClient VPN is filled with lots of bugs, Disconnecting every 4 minutes, NOT allowing to reconnect

**Comment by DimitriPapadopoulos** [comment]
@Morteza-Rastgoo Please avoid fictitious claims. If you have a specific issue, please open a **new** issue instead of spamming an existing and unrelated issue.
