### ISSUE TITLE
Can connect on Windows 10, cannot connect on Ubuntu 18.02

### ISSUE THREAD

**Issue by TheLox95** [adrienverge/openfortivpn#463]
Right now I'm able to connect to my VPN using the `FortiVPN` GUI client for windows
![fortivpn censored](https://user-images.githubusercontent.com/17032250/63566290-7b5d5500-c53a-11e9-8368-9d5ef98ddb11.jpg)

But passing the same IP address, user and pass to the `openfortivpn` the CLI hangs up and time out 
Running the following command `sudo openfortivpn -c vpn -v`.
Where vpn is the file where the VPN data is

```
host=xxx
port=xxx
username=xxx
password=xxx
```

This is the ouput
![openfortivpn fail](https://user-images.githubusercontent.com/17032250/63566413-0fc7b780-c53b-11e9-9007-023ae29d8c40.jpg)

**Comment by mrbaseman** [comment]
it seems the vpn is not reachable from the ubuntu system (maybe blocked by a firewall?). 
Can you try to connect via browser or with telnet to vpn?

**Comment by DimitriPapadopoulos** [comment]
Also note that FortiClient on Windows is using IPsec by default. The Linux clients (FortiClient and _openfortivpn_) use SSL.
* Is SSL VPN enabled on your FortiGate appliance?
* Is the SSL port (443?) blocked by a firewall upstream of the FortiGate appliance?

**Comment by DimitriPapadopoulos** [comment]
@TheLox95 Have you succeeded getting _openfortivpn_ to work? If not, do you have answers to the above questions?
