### ISSUE TITLE
ERROR: Could not authenticate to gateway (No cookie given)

### ISSUE THREAD

**Issue by robmukai** [adrienverge/openfortivpn#465]
So I have looked at issues #350 , #458 , #351 , #49  and none are exactly like this. So I have a desktop that I have been using to connect to a Fortigate for a couple of years now. Openfortivpn 1.6.0 on Ubuntu 18.04. Everything works as expected. I have copied the /etc/openfortivpn/config file from that computer and put it on a laptop with Ubuntu 18.04 and Openfortivpn 1.6.0 and it comes up with the Could not authenticate to gateway (No Cookie given) error. Any ideas on what might be happening?

DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "xxx.xxxx.com"
DEBUG:  Config realm = ""
DEBUG:  Config port = "441"
DEBUG:  Config username = "Rob"
DEBUG:  Config password = "********"
DEBUG:  server_addr: xx.xxx.xx.xxx
DEBUG:  server_port: 441
DEBUG:  gateway_addr: xx.xxx.xx.xxx
DEBUG:  gateway_port: 441
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway (No cookie given).
INFO:   Closed connection to gateway.
DEBUG:  server_addr: xx.xxx.xx.xxx
DEBUG:  server_port: 441
DEBUG:  gateway_addr: xx.xxx.xx.xxx
DEBUG:  gateway_port: 441
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.

**Comment by mrbaseman** [comment]
If you have really copied the config (not just typed in the same values) I would be surprised. If you have created a new file my first guess would be a typo. 
It's 1.6.0 in both cases? In 1.8.0 we have improved the debugging output for such cases, maybe trying a newer version helps finding out what's going wrong in this particular case.

**Comment by robmukai** [comment]
@mrbaseman thanks for the response. I got it working last night. My original password contained these characters "!" "@" "#" and "$". I had the admin of the Fortigate add a new user with the same original password. It did the same thing. Worked on my desktop, didn't work on my laptop. We then changed the password to the second user to not include any of the "special" characters and now it works on both machines. Any thoughts?

**Comment by mrbaseman** [comment]
Just to exclude that one of the special characters triggers an encoding bug I have set my password literally to `"!" "@" "#" and "$".` and I could connect successfully. 

If you have a space character in the password that would be #458 which is fixed on the current master, but you have already mentioned that one above. 

`#` starts a comment in the config file, but not if it appears in the middle of a line (I've just double-checked that), and leading or trailing space characters are stripped off. 

Maybe a dos line ending has sneaked into the config file and the `\r` character is appended to the password? I think we don't strip those off if they occur. Just opening a new file with your favorite editor and typing in the config usually helps best. Converting files, especially when the line endings are already messed up, may or may not help...

If you supply the password with -p on the command line you have to enclose it in single quotes `'...'` to prevent the shell from substituting everything that starts with `$` by shell variables. 

Hmm... I'm not sure if one of these points gets you any further, but that's what comes to my mind at the moment.

**Comment by mrbaseman** [comment]
ok. we had something similar in #129 and fixed it with #334 and #336 a while ago. That should handle the carriage returns of the dos line endings, but there are many more non-printable characters, and some of them aren't handled by `isspace()`.
Well... I think we have already tried to find a good trade-off in the previous issue, so I'll close this one.
