### ISSUE TITLE
Howto setup an static ip?

### ISSUE THREAD

**Issue by chrys87** [adrienverge/openfortivpn#469]
Howdy,

Can someone give me a small help how to connect with openfortivpn  client using an static ip?

Maybe could an example added to the wiki?

Thanks!

Thanks chrys

**Comment by DimitriPapadopoulos** [comment]
I'm not sure how a "static IP" could be related to _openfortivpn_. Can you explain in more detail?

**Comment by chrys87** [comment]
how can i configure an connection using openfortivpn client to use an static ip instead of getting always an dynamic one?
as result i wanna have always the same ip on my vpn.

**Comment by DimitriPapadopoulos** [comment]
This is handled by the FortiGate appliance. I'm not aware of a, option to get the FortiGate appliance to provide a static address. Said otherwise this should be a request to the administrators of the FortiGate appliance you connect to, not a request to modify _openfortivpn_.

**Comment by mrbaseman** [comment]
Yes, Fortigates use IP pools to dynamically assign an IP to each client. That said, if you are the administator of the Fortigate and you are the only user, you could try to narrow down the IP range to a single one which you will be assigned then. On the other hand I'm nearly the only VPN user on some of our devices and I usually get the lowest IP. On one of our Fortigates we have assigned several IP ranges to different LDAP groups. Maybe a similar approach also works for different users. You probably have to configure an extra portal for each one. If you like, I can look up how the link to the individual group is implemented.

**Comment by mrbaseman** [comment]
if you have local users and groups, it's straight forward to configure a separate portal with it's own ip-range and assign it to the user or group. With ldap groups [config match](https://kb.fortinet.com/kb/documentLink.do?externalID=FD32359) is the key on the cli to link a group in the ldap with a particular portal.

**Comment by chrys87** [comment]
ah ok, thanks that helps me :).
