### ISSUE TITLE
[feature request] support DNS-SUFFIX Setting

### ISSUE THREAD

**Issue by abenet** [adrienverge/openfortivpn#472]
Hi Everybody,

I use openfortivpn in opensuse to connect to my VPN and I have one problem with DNS configurations. I can connect to my VPN and it adds the new dns servers inside /etc/reslov.conf, but it doesn't configure the suffix DNS. If I use the forticlient in other platform, it's work properly. 

How can I fix this? 

Thank you in advance,

Regards,

Albert

**Comment by DimitriPapadopoulos** [comment]
You mean it doesn't add something like `mydomain.com` to `/etc/reslov.conf`?

True, nowhere in the code do we bother retrieving domain names, let alone adding them to the search list in `/etc/resolv.conf`. The question is, does the FortiGate appliance send that information? See [parse_xml_config ](https://github.com/adrienverge/openfortivpn/blob/320f95f/src/http.c#L685-L734) / [parse_config](https://github.com/adrienverge/openfortivpn/blob/320f95f/src/http.c#L737-L784).

**Comment by abenet** [comment]
Hi Dimitri,

Thank you very much for your prompt response.

Correct, it doesn't add "search domain.com" to /etc/resolv.conf but it adds the DNS servers.

If I test with foritclient it configures the suffix DNS Domain (Fortigate appliance send this information). It's seems the problem is the openfortivpn. Have you planned to add this feature?

Thank you in advance,

Albert

**Comment by DimitriPapadopoulos** [comment]
The problem could be in _openfortivpn_ or _pppd_. We need to investigate first. I hadn't ever noticed this issue myself. I'll try to check _FortClient_/Linux vs. _openfortivpn_/Linux and compare to FortiClient_/Windows.

In the meantime, how do you know the FortiGate appliance sends this information? if you run `openfortivpn -v -v` do you see all the DNS information in the log, including the domain name? If so could you send the relevant part of the log (redact IP addresses and domain names if needed)?

**Comment by DimitriPapadopoulos** [comment]
I tried both _FortiClient_ and _openfortivpn_ on my Linux laptop. Neither of them add a domain name to the search list. In my case the FortiGate appliance does not seem to be sending a domain name:
```
$ openfortivpn -v -v -v
[...]
HTTP/1.1 200 OK
[...]
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

2a0   
<?xml version='1.0' encoding='utf-8'?><sslvpn-tunnel ver='2' dtls='1' patch='1'><dtls-config heartbeat-interval='10' heartbeat-fail-count='10' heartbeat-idle-timeout='10' client-hello-timeout='10' /><tunnel-method value='ppp' /><tunnel-method value='tun' /><fos platform='FG1K2D' major='6' minor='02' patch='1' build='0932' branch='0932' /><auth-ses check-src-ip='1' tun-connect-without-reauth='0' tun-user-ses-timeout='30' /><client-config save-password='off' keep-alive='off' auto-connect='off' /><ipv4><dns ip='xxxx.xxx.xxx.x' /><dns ip='xxx.xxx.xxx.x' /><assigned-addr ipv4='xx.xx.xxx.xx' /></ipv4><idle-timeout val='1500' /><auth-timeout val='28800' /></sslvpn-tunnel>
0
[...]
$ 
```

I have two hypotheses:
1. This might a difference between IPSec (used by the Windows _FortiClient_) and SSL VPN (used by the Linux _FortClient_ and _openfortivpn_). The FortiGate appliance might send the new domain name when using IPsec but not SSL. I'd have to check whether _FortiClient_ behaves differently on Windows - I don't have access to a Windows _FortClient_ for now so this will have to wait.
2. This might be a difference between my FortiGate appliance and yours. Mine might not be set up to modify the domain name search list. It would help if you could check whether `openefortivpn -v -v -v` shows your appliance sending the domain name.

**Comment by mrbaseman** [comment]
Hi Dimitri,

I think it's the [dns-suffix setting](https://kb.fortinet.com/kb/documentLink.do?externalID=FD37484) which has to be enabled on the Fortigate. I have done so on my appliance at home right now. Then I can check from work what it sends when I connect to it from work tomorrow.

As you have already pointed out this can be handled at two places, _openfortivpn_ or _pppd_ just like the nameserver entries in `resolv.conf`. The `pppd-use-peerdns` might have an influence on which one is in charge of updating the file.

**Comment by mrbaseman** [comment]
I didn't see the dns-suffix in the debug log nor in the pppd log. Maybe the client has to request it explicitly, but during a quick scan I didn't find anything about this topic in the pppd man page.

**Comment by abenet** [comment]
Hi,

I test in Fedora and I have the same problem. 

   - FortiClient works properly and it adds the suffix DNS to /etc/resolv.conf.
   - OpenfortiVpn: I can connect to SSL VPN but it doesn't add the suffix DNS (DNS Servers add correctly)

To configure suffix DNS in Fortigate:

config vpn ssl settings
    set dns-suffix "domain.com"

Thank you very much,

Albert

**Comment by DimitriPapadopoulos** [comment]
@abenet In your case has the FortiGate appliance been configured as you suggest?

Also I understand you compare _openfortivpn_/Linux with _FortiClient_/Linux (VPN SSL) and not with _FortiClient_/Windows (IPsec), don't you?

**Comment by abenet** [comment]
@abenet In your case has the FortiGate appliance been configured as you suggest? 

Yes

Also I understand you compare openfortivpn/Linux with FortiClient/Linux (VPN SSL) and not with FortiClient/Windows (IPsec), don't you? 

Correct, I test directly in the same platform (Fedora) both clients.

**Comment by DimitriPapadopoulos** [comment]
OK, this really is an _openfortivpn_ (or _pppd_) issue.

I cannot reproduce it myself: my corporate domain is already in the search list by default and is probably not re-sent by the FortiGate appliance (at least no in VPN SSL mode).

**Comment by mrbaseman** [comment]
I can try once more with mine. In my internal network I use a non-standard domain which does not contain a dot. Maybe such an arbitrary string is not accepted by pppd or Forticlient either. I can change it to a valid ubdomain that I own (it doesn't make any sense to access hosts there through the ssl vpn, but it would be another testing scenario).

**Comment by mrbaseman** [comment]
Now I've got it. Here the (anonymized) debug output:. The relevant part is in the xml output:
```
DEBUG:  http_receive: 
HTTP/1.1 200 OK
Date: Wed, 09 Oct 2019 09:45:00 GMT
Server: xxxxxxxx-xxxxx
Transfer-Encoding: chunked
Content-Type: text/xml
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

26a   
<?xml version='1.0' encoding='utf-8'?><sslvpn-tunnel ver='2' dtls='1' patch='1'><dtls-config heartbeat-interval='10' heartbeat-fail-count='10' heartbeat-idle-timeout='10' client-hello-timeout='10' /><tunnel-method value='ppp' /><tunnel-method value='tun' /><fos platform='FG60DP' major='6' minor='00' patch='6' build='0272' branch='0272' /><client-config save-password='on' keep-alive='on' auto-connect='on' /><ipv4><dns domain='dns-suffix.example.com' /><dns ip='192.168.xx.xx' /><dns ip='8.8.8.8' /><assigned-addr ipv4='10.xx.xx.xx' /></ipv4><idle-timeout val='86400' /><auth-timeout val='28800' /></sslvpn-tunnel>
0


DEBUG:  Establishing the tunnel
DEBUG:  ppp_path: /usr/sbin/pppd
DEBUG:  Switch to tunneling mode
DEBUG:  http_send: 
GET /remote/sslvpn-tunnel HTTP/1.1
Host: sslvpn
Cookie: SVPNCOOKIE=...


DEBUG:  Starting IO through the tunnel
```
so we have to parse for something like `<dns domain='dns-suffix.example.com' />`

**Comment by mrbaseman** [comment]
in [parse_xml_config()](https://github.com/adrienverge/openfortivpn/blob/master/src/http.c#L685) this content is already parsed. We just have to add the code that parses the `dns domain` setting and store it in `tunnel->ipv4_config`. 

Apart from receiving this setting we need a mechanism to update resolv.conf with this (maybe [ipv4_add_nameservers_to_resolv_conf()](https://github.com/adrienverge/openfortivpn/blob/master/src/ipv4.c#L973) can do this job while messing around in that file? 
However, when `pppd-use-peerdns` is set true the function is not called and `pppd` is in charge of updating `resolv.conf`

**Comment by mrbaseman** [comment]
unfortunately, my Forticlient ignores this setting, too. @abenet  what would be the expected behavior? 
* append dns-suffix to the existing search string in /etc/resolv.conf?
* prepend it?
* replace the existing string with the received one?
* append another line containing "search "+ the received string?
* prepend another line for the search?

**Comment by DimitriPapadopoulos** [comment]
@abenet Also which version of _FortiClient_ are you running on Linux?

**Comment by mrbaseman** [comment]
I've changed my config back to what it was before, and the dns-suffix is still present in the config that is sent to the ssl vpn client. I guess earlier I was just looking in the wrong place. I was focused more on the pppd.log.

**Comment by dssouza-ti** [comment]
Hi everyone.

I just discovered the existence of openfortivpn and stumbled upon this problem myself. I'm using version 1.10.0-1 and it does not add the dns-suffix information to my resolv.conf.

@mrbaseman, answering your question to @abenet, when I use the official FortiClient SSLVPN for Linux, it explicitly adds a few lines to my resolv.conf above the current configuration, just like this:

before connecting:
```
#lots of comments
#more comments
nameserver 127.0.0.53
options edns0
```

after connectiong:
```
search mydomain.com
nameserver x.x.x.x
nameserver x.x.x.x
#lots of comments
#more comments
nameserver 127.0.0.53
options edns0
```

Also, when I disconnect from the client, it clears the extra lines from the file.

I would be glad if this was implemented in this client, I love the integration with gnome network manager.

**Comment by mrbaseman** [comment]
thanks @dssouza-ti for this information. A first approach could be just prepending the search string in /etc/resolv.conf. If there is already such a setting present, the new search string just has no effect. Maybe we can improve on this later. So, the easiest approach would be just to prepend an additional line when adding the nameservers.

**Comment by DimitriPapadopoulos** [comment]
@dssouza-ti If at all possible it would be great to test what happens when you already have a domain search line in `/etc/resov.conf`.

In short before connecting:
```
search example.com
```
and after connecting possibly any of:
```
search example.com
search mydomain.com
```
```
search mydomain.com
search example.com
```
```
search mydomain.com example.com
```

**Comment by mrbaseman** [comment]
I have started implementing the first approach. Currently, it would be before connecting:
``` 
# these ones are already present
search example.com another-one.com
nameserver dns.example.com
```
and when connected
```
search mydomain.com
nameserver dns.mydomain.com
# these ones are already present
search example.com another-one.com
nameserver dns.example.com
```
and in my experience the first two nameservers and the last search statement take effect. 
Merging the existing and the new string and correctly reverting the change when the connection drops would be the next step.

**Comment by dssouza-ti** [comment]
Hi guys, I just performed some simple tests to see the what happens in ubuntu 19.10 and 18.04 and the behaviour was the same for me:

@DimitriPapadopoulos for your question, this was the result:

before connecting:
```
nameserver 127.0.0.53
search example.com
```

after connecting:

```
search vpndomain.com
nameserver x.x.x.x
nameserver y.y.y.y

nameserver 127.0.0.53
search example.com
```

> and in my experience the first two nameservers and the last search statement take effect.

@mrbaseman you are absolutely right, I just tested this.

Also, when merging the domains in only one search statement, it works independent of the order of the domains:
`search example.com vpndomain.com` had the same effect as `search vpndomain.com example.com`

Based on this testing, what already happens with the official client is not the optimal result, as merging the search statements into one would be the correct approach.

If you need more info, just let me know.
:)

**Comment by DimitriPapadopoulos** [comment]
According to the [man page](http://man7.org/linux/man-pages/man5/resolv.conf.5.html) the order of the domain in the **search** option is supposed to have an effect:
> Resolver queries having fewer than _ndots_ dots (default is 1) in them will be attempted using each component of the search path in turn until a match is found.

So if both `myhost.vpndomain.com` and `myhost.example.com` exist, in theory `myhost` should be resolved as follows:
* `search example.com vpndomain.com` → `myhost.example.com`
* `search vpndomain.com example.com` → `myhost.vpndomain.com`

**Comment by dssouza-ti** [comment]
I believe the key is "until a match is found." Since the nameserver points to the dns servers of the vpndomain.com, they won't find myhost.example.com even if it comes first in the search statement.

**Comment by DimitriPapadopoulos** [comment]
Ah, but there's no such as thing as "the dns servers of the vpndomain.com". DNS servers usually resolve all hostnames/IP addresses. There may be cases where a corporate server resolves additional hostnames such as `myhost.example.com`. That's not necessarily the case though. In my case all DNS names, even corporate ones, are resolved by all DNS servers. In such a case, both `myhost.example.com` and `myhost.vpndomain.com` are resolved whatever the DNS server - whether the VPN is on or off. In you own example you don't prove that the search order is irrelevant, you only prove the DNS server is unable to resolve `myhost.example.com` - which might be a bug.

**Comment by dssouza-ti** [comment]
I see what you mean. I'll try to run more thorough tests when I have more time, since the only thing I did was to switch the order of the search statement and ping a host to see the results. Maybe analize some logs or try to generate debug info...

Based on that, for the purposes of this feature, I believe the vpndomain.com should come first if merging the search statement and last if adding another search entry. Do you agree?

**Comment by DimitriPapadopoulos** [comment]
At least as a first step Martin's intent to reproduce what _FortiClient_ does sounds like a good idea. But I agree that if we were to merge search lists, the list sent by the VPN should be search first.

**Comment by mrbaseman** [comment]
About the nameservers: Our nameservers provide "public information" to the outside world, but additionally include "information about the intranet" when they are queried from particular internal networks. So, in this case it makes a difference which nameserver you ask. 
Another important point where the order matters are commonly used hostnames like `www`, `login`, `home` etc. which may exist in several domains listed in the search string. You still can access them individually via their FQHN, but it may lead to surprising results if different client software for the same vpn account results in different ordering of the domains in the search string. When you contact a host via hostname without domain you may find yourself connecting to different hosts, depending on the vpn client you use. 
Therefore, apart from being the most simple apporach to implement, I would also vote for reproducing the behavior of the _FortiClient_

**Comment by dssouza-ti** [comment]
> Therefore, apart from being the most simple apporach to implement, I would also vote for reproducing the behavior of the _FortiClient_

That would already be very nice :).

If you intend to improve this later, I could perform more tests and gather more information, since I work with a lot of Fortigate devices everyday.

**Comment by mrbaseman** [comment]
my first approach is in #483 

I have noticed that we still (or again?) have a race condition between openfortivpn and pppd.
Unfortunately with --pppd-use-peerdns=0 also openfortivpn doesn't receive the dns servers (or pppd overwrites them again?)

**Comment by mrbaseman** [comment]
#483 has been merged. It can be tested with the current master branch now.

**Comment by dssouza-ti** [comment]
@mrbaseman, I just tested your first approach with 3 fortigates I have access to and it worked just as the official client. Nice work.

**Comment by ChuckDaniels87** [comment]
I have tested this fix and it is working properly in my case too.

**Comment by mrbaseman** [comment]
This went into the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0).
