### ISSUE TITLE
Coverity oustanding issues

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#484]
There are currently 7 Coverity issues. Some of them look like false positives, others may be theoretical issues that won't happen in real life. In any case, I suggest rewriting the relevant code to obtain less complex sources, easier to review (both for Coverity and human reviewers).

Especially reading/parsing file descriptors results in complex code. Would it make sense to use a parser generator such as ANTLR to simplify the code?

@mrbaseman Do you have access to the Coverity issues?

**Comment by mrbaseman** [comment]
I have access, yes. These issues are not related to #483, right? They have either been there for a longer time or have been introduced by the other pull requests that we have merged in the last months.

**Comment by DimitriPapadopoulos** [comment]
Most issues have been introduced by the other pull requests that we have merged in the last months. I haven't tested #483.

**Comment by mrbaseman** [comment]
I had only 5 issues in the Dashboard. I guess two others are related to these ones and therfore not listed separately. 
Could you have a look at #489 please, and check if coverity is happy with those fixes?

**Comment by DimitriPapadopoulos** [comment]
Unfortunately Coverity Scan seems to have problems right now. There were 304 builds ahead of _openfortivpn_ yesterday and 298 builds today. It might take weeks to obtain a result.

A short note on your changes: the macro _assert()_ generates no code when `NDEBUG` is defined. Perhaps it's best to shut up Coverity with code that is executed whatever the context, using our usual error management routines.

**Comment by mrbaseman** [comment]
I have added a new commit to avoid _assert_. Do you know if Coverity is going to pick this up, or do we have to re-schedule another scan?

**Comment by DimitriPapadopoulos** [comment]
I'll re-schedule a new manual scan. Automatic scans are supposed to happen on the `coverity_scan` branch of the `adrienverge` repository, as suggested by the Coverity documentation, but I seem to recall I haven't been able to finalize the setup.

In any case the Coverity Scan infrastructure seems broken again - last time it had occurred it had taken months to restore the Coverity Scan service.

**Comment by DimitriPapadopoulos** [comment]
The previous scan is over. I haven't received a notification by mail, perhaps the scan server was in a real bad shape and they had to flush the queue / reboot it.

Any way, I have just submitted your branch mrbaseman/coverity for scanning: 72 builds ahead of it.

**Comment by DimitriPapadopoulos** [comment]
Done. There are 3 issues left.

**Comment by mrbaseman** [comment]
The issues have been resolved and the fixes went into the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0).
