### ISSUE TITLE
random disconnects

### ISSUE THREAD

**Issue by amastran** [adrienverge/openfortivpn#487]
Hi everyone, I installed openfortvvpn in a vpn concentrator based on container (LXD, container ALPINE LINUX)
1) alpine linux container with 8 openfortivpn tunnels. 2) in sysctl.conf: net.ipv4.ip_forward = 1
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
net.ipv4.conf.eth0.arp_ignore = 1
net.ipv4.conf.eth0.arp_announce = 2

to avoid problems with the route (example):
192.0.2.1 dev ppp1 scope link src 10.160.56.4
192.0.2.1 dev ppp2 scope link src 10.40.3.42
192.0.2.1 dev ppp3 scope link src 10.47.33.37
192.0.2.1 dev ppp0 scope link src 10.0.5.12
192.0.2.1 dev ppp4 scope link src 10.212.134.4

2) route and nat management using / etc / ppp / ip-up and / etc / ppp / ip-down script

Everything is working properly but sometimes the client disconnects after half an hour. I would like to have clarifications on the reconnect parameter and how it works. Are there standard times? in general the old forticlientsslvpn_cli project had no disconnection problems.

**Comment by DimitriPapadopoulos** [comment]
Chances are these disconnections are not related to _openfortivpn_. Rather they are specific to this setup with containers or to this FortiGate appliance. Have you tried _openfortivpn_ outside containers? Have you tried FortiClient with the same setup?

Also have you had a look at the _openfortivpn_ and _pppd_ logs?

**Comment by DimitriPapadopoulos** [comment]
@amastran Have you been able to look into the above suggestions?

**Comment by DimitriPapadopoulos** [comment]
Closing this issue for now as disconnections are usually related to a time out beyond the scope of _openfortivpn_. It would be great to document that in the wiki as suggested in #485.

Please do not hesitate to re-open if you feel this is an _openfortivpn_ issue - especially if you don't see the time out with _FortiClient_.
