### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by amanjeev** [adrienverge/openfortivpn#490]
Is it possible to cut a new release? Seems like the last one was in June. Thank you.

**Comment by mrbaseman** [comment]
sure. We are currently working on #484, then we plan to update the README.md and CHANGELOG.md for the next release.

**Comment by adrienverge** [comment]
Thanks Martin!

**Comment by amanjeev** [comment]
Thank you!

**Comment by mrbaseman** [comment]
see #494

**Comment by mrbaseman** [comment]
the [1.11.0 Release](https://github.com/adrienverge/openfortivpn/releases/tag/v1.11.0) has been tagged now
