### ISSUE TITLE
Disconnects within few minutes. How to keep up the connection alive for a long duration ?

### ISSUE THREAD

**Issue by rc12** [adrienverge/openfortivpn#50]

**Comment by notandxor** [comment]
try add in /etc/ppp/options
lcp-echo-interval 30

**Comment by DimitriPapadopoulos** [comment]
Reopening this since I have re-opened #92. Most probably the exact same issue.

Should we force `pppd` to keep the tunnel alive with regular LCP echo messages?

**Comment by mrbaseman** [comment]
The `--persistent` option has been implemented in the meantime. If it is not sufficient, and the problem still persists with recent versions of _openfortivpn_, please reopen a new issue and ask again for the LCP echo messages, referring to this one.
