### ISSUE TITLE
/etc/resolv.conf not updated after openfortivpn update to 1.11.0

### ISSUE THREAD

**Issue by blakkheimgw** [adrienverge/openfortivpn#503]
As suggested [here,](https://github.com/adrienverge/openfortivpn/issues/501#issuecomment-562133391) I'm opening a separate report for my problem.

Since the openfortivpn 1.11.0 update on my OpenSUSE Tumbleweed, the _/etc/resolv.conf_ file is not updated anymore at the connection/disconnection of a VPN session, thus the name resolution of my corporate domaine is impossible.
I generally use the NM applet for openfortivpn but the same problem happens when I try to connect by the CLI.

- the contents of /etc/resolv.conf before running a VPN client : 
```
### /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
### autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
### Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
search lan
nameserver 192.168.1.254
```

- the contents of /etc/resolv.conf after running openfortivpn : 
```
### /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
### autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
### Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
search lan
nameserver 192.168.1.254
```

- the debug output of a VPN connection initiated by openfortivpn 1.11.0 (launched by the CLI) : 
```
sudo openfortivpn address.mydomainname.fr:443 -u mylogin --trusted-cert MYDIGEST -p MYPASSWORD -v

DEBUG:  Config host = "address.mydomainname.fr"
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = "mylogin"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: 194.XX.XX.XX
DEBUG:  server_port: 443
DEBUG:  gateway_addr: 194.XX.XX.XX
DEBUG:  gateway_port: 443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=MYCOOKIE
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=MYCOOKIE
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: 194.XX.XX.XX
DEBUG:  server_port: 443
DEBUG:  gateway_addr: 194.XX.XX.XX
DEBUG:  gateway_port: 443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Retrieving configuration
DEBUG:  found dns suffix mydomainname.fr in xml configDEBUG:  found dns server 172.30.XX.XX in xml configDEBUG:  found dns server 172.30.XX.XY in xml configDEBUG:  Establishing the tunnel
DEBUG:  ppp_path: /usr/sbin/pppd
DEBUG:  Switch to tunneling mode
DEBUG:  Starting IO through the tunnel
DEBUG:  pppd_read thread
DEBUG:  ssl_write thread
DEBUG:  ssl_read thread
DEBUG:  if_config thread
Using interface ppp0
Connect: ppp0 <--> /dev/pts/1DEBUG:  pppd_write threadINFO:   Got addresses: [172.30.XX.XX], ns [172.30.XX.XX, 172.30.XX.XY]
INFO:   negotiation complete
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XXDEBUG:  if_config: not ready yet...DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XXDEBUG:  if_config: not ready yet...DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  if_config: not ready yet...INFO:   negotiation completelocal  IP address 172.30.XX.XX
remote IP address 192.0.2.1
DEBUG:  Got Address: 172.30.XX.XX
DEBUG:  Interface Name: ppp0
DEBUG:  Interface Addr: 172.30.XX.XX
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
DEBUG:  ip route show to 0.0.0.0/0.0.0.0 dev !ppp0
DEBUG:  ip route show to 194.XX.XX.XX/255.255.255.255 dev ppp0
DEBUG:  Route not found.
DEBUG:  ip route show to 194.XX.XX.XX/255.255.255.255 dev !ppp0
DEBUG:  Setting route to vpn server...
DEBUG:  ip route show to 194.XX.XX.XX/255.255.255.255 via 192.168.1.254 dev enp0s25
DEBUG:  ip route add to 194.XX.XX.XX/255.255.255.255 via 192.168.1.254 dev enp0s25
DEBUG:  Deleting the current default route...
DEBUG:  ip route del to 0.0.0.0/0.0.0.0 via 192.168.1.254 dev enp0s25
DEBUG:  Setting new default route...
DEBUG:  ip route add to 0.0.0.0/0.0.0.0 dev ppp0
INFO:   Adding VPN nameservers...
DEBUG:  Adding "nameserver 172.30.XX.XX", to /etc/resolv.conf.
DEBUG:  Adding "nameserver 172.30.XX.XY", to /etc/resolv.conf.
DEBUG:  Adding "search mydomainname.fr", to /etc/resolv.conf.
INFO:   Tunnel is up and running.Script /etc/ppp/ip-up finished (pid 15089), status = 0x0
^C
INFO:   Cancelling threads...
DEBUG:  disconnecting
INFO:   Setting ppp interface down.
INFO:   Restoring routes...
DEBUG:  ip route del to 194.XX.XX.XX/255.255.255.255 via 192.168.1.254 dev enp0s25
DEBUG:  ip route del to 0.0.0.0/0.0.0.0 dev ppp0
DEBUG:  ip route add to 0.0.0.0/0.0.0.0 via 192.168.1.254 dev enp0s25
INFO:   Removing VPN nameservers...
DEBUG:  Waiting for pppd to exit...
Hangup (SIGHUP)
Modem hangup
Connect time 0.1 minutes.
Sent 2740 bytes, received 576 bytes.
Connection terminated.
```

Note : 192.168.1.0/24 is my home internal network and 192.168.1.254 is my ISP all-in-one box/router.

Thank you.

**Comment by DimitriPapadopoulos** [comment]
For what it's worth, the issues raised in #349 last time I tried to fix `/etc/resolv.conf` updates had again been raised on OpenSUSE. I think there's something special - doesn't mean wrong - on OpenSUSE.

**Comment by mrbaseman** [comment]
notable are these lines in the debug output:```
INFO:   Adding VPN nameservers...
DEBUG:  Adding "nameserver 172.30.XX.XX", to /etc/resolv.conf.
DEBUG:  Adding "nameserver 172.30.XX.XY", to /etc/resolv.conf.
DEBUG:  Adding "search mydomainname.fr", to /etc/resolv.conf.
```
same suggestion as in #501 could you give `--pppd-use-peerdns=1` a try, 
maybe together with `--set-dns=0` to avoid a race between openfortivpn and pppd

**Comment by DimitriPapadopoulos** [comment]
Also thsi is different from what I get on my Ubuntu machine:
```
INFO:   Tunnel is up and running.Script /etc/ppp/ip-up finished (pid 15089), status = 0x0
```
I'm wondering, does `/etc/ppp/ip-up` do anything special such as overwriting `/etc/resolv.conf`?

**Comment by blakkheimgw** [comment]
Using _--pppd-use-peerdns=1_ is doing the job. Since I mainly use the NM applet, do you know how I could pass this argument to it ?

When launched by NM, here is the command : 
```/usr/bin/openfortivpn -c /var/lib/NetworkManager-fortisslvpn/038d731e-1f20-4f8c-bd01-2f8720cfa73f.config --no-routes --no-dns address.mydomainname.fr 443 --trusted-cert MYCERT --pppd-plugin /usr/lib64/pppd/2.4.7/nm-fortisslvpn-pppd-plugin.so```


> I'm wondering, does `/etc/ppp/ip-up` do anything special such as overwriting `/etc/resolv.conf`?

Nothing seems to be related to _resolv.conf_ in _/etc/ppp/*_ (tried : _sudo grep -ri resolv /etc/ppp/_)

Thanks.

**Comment by mrbaseman** [comment]
Ah, here we have the --no-dns option in the command line. That's why openfortivpn's built-in mechanism doesn't work. I have just checked the NM plugins source. The command line and the config file are both created for each connection attempt. pppd also expects the usepeerdns parameter on the command line and does not pick it up from a global config file, as far as I can see. 
So, I see only two ways
 - update openfortivpn to pick up some additional settings from the environment (which may have security implications and probably won't work with sudo)
 - have the nm plugin updated, either to omit `--no-dns` or pass `--pppd-use-peerdns=1` in addition

**Comment by mrbaseman** [comment]
3rd option:
 - revert the behavior of _openfortivpn_ to `pppd-usepeer-dns = 1` if nothing is specified in the config file and accept the fact that the built-in mechanism may run a race with `pppd` - therefore, it's probably not really an option. 

@lkundrak perhaps you can update the NM plugin (see [my previous comment](https://github.com/adrienverge/openfortivpn/issues/503#issuecomment-562207693)), or is this an issue purely related to OpenSUSE? If that's the case, maybe the packages there can be patched.

**Comment by mrbaseman** [comment]
see [Issue 20 of the NM Plugin](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/issues/20)

**Comment by blitzd** [comment]
@DimitriPapadopoulos this issue is also occurring on Fedora 31, though the messages in the logs seem a bit different just FYI:

```
Dec 16 14:28:04 fasthold pppd[3047]: pppd 2.4.7 started by root, uid 0
Dec 16 14:28:04 fasthold pppd[3047]: Using interface ppp0
Dec 16 14:28:04 fasthold NetworkManager[1220]: Using interface ppp0
Dec 16 14:28:04 fasthold NetworkManager[1220]: Connect: ppp0 <--> /dev/pts/0
Dec 16 14:28:04 fasthold NetworkManager[1220]: {/tmp/.SZRMC0} {/tmp}
Dec 16 14:28:04 fasthold pppd[3047]: Connect: ppp0 <--> /dev/pts/0
Dec 16 14:28:04 fasthold NetworkManager[1220]: {/tmp/.SZRMC0} {.SZRMC0}
Dec 16 14:28:04 fasthold NetworkManager[1220]: <info>  [1576524484.4643] manager: (ppp0): new Ppp device (/org/freedesktop/NetworkManager/Devices/9)
Dec 16 14:28:04 fasthold systemd-udevd[3057]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Dec 16 14:28:04 fasthold kernel: PPP BSD Compression module registered
Dec 16 14:28:04 fasthold kernel: PPP Deflate Compression module registered
Dec 16 14:28:04 fasthold NetworkManager[1220]: INFO:   Got addresses: [172.16.8.1], ns [192.168.5.64, 192.168.5.67]
Dec 16 14:28:04 fasthold NetworkManager[1220]: INFO:   negotiation complete
Dec 16 14:28:07 fasthold NetworkManager[1220]: INFO:   Got addresses: [172.16.8.1], ns [192.168.5.64, 192.168.5.67]
Dec 16 14:28:07 fasthold NetworkManager[1220]: INFO:   negotiation complete
Dec 16 14:28:08 fasthold NetworkManager[1220]: INFO:   negotiation complete
Dec 16 14:28:08 fasthold pppd[3047]: Failed to create /var/run/ppp/resolv.conf: No such file or directory
Dec 16 14:28:08 fasthold NetworkManager[1220]: Failed to create /var/run/ppp/resolv.conf: No such file or directory
Dec 16 14:28:08 fasthold pppd[3047]: local  IP address 172.16.8.1
Dec 16 14:28:08 fasthold NetworkManager[1220]: local  IP address 172.16.8.1
Dec 16 14:28:08 fasthold NetworkManager[1220]: remote IP address 192.0.2.1
Dec 16 14:28:08 fasthold NetworkManager[1220]: primary   DNS address 192.168.5.64
Dec 16 14:28:08 fasthold NetworkManager[1220]: secondary DNS address 192.168.5.67
Dec 16 14:28:08 fasthold pppd[3047]: remote IP address 192.0.2.1
Dec 16 14:28:08 fasthold pppd[3047]: primary   DNS address 192.168.5.64
Dec 16 14:28:08 fasthold pppd[3047]: secondary DNS address 192.168.5.67
Dec 16 14:28:08 fasthold pppd[3047]: Can't execute /etc/ppp/ip-up: Permission denied
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=raw family=2 entries=51
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=mangle family=2 entries=65
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=nat family=2 entries=112
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=filter family=2 entries=219
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=raw family=10 entries=53
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=mangle family=10 entries=64
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=nat family=10 entries=97
Dec 16 14:28:08 fasthold audit: NETFILTER_CFG table=filter family=10 entries=192
Dec 16 14:28:08 fasthold NetworkManager[1220]: Can't execute /etc/ppp/ip-up: Permission denied
Dec 16 14:28:08 fasthold NetworkManager[1220]: <info>  [1576524488.6482] device (ppp0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: 'external')
Dec 16 14:28:08 fasthold NetworkManager[1220]: INFO:   Interface ppp0 is UP.
Dec 16 14:28:08 fasthold NetworkManager[1220]: INFO:   Tunnel is up and running.
```
Downgrading to 1.10 has temporarily resolved the issue for me...

**Comment by scaronni** [comment]
@blitzd I just pushed an update for Fedora / EPEL  that fixes the issue: https://bodhi.fedoraproject.org/users/slaanesh

We just rolled it out onto our corporate laptop and it works fine.

**Comment by marinetteman2** [comment]
Tested this with the updates 1.3.90-3. Did not work for me, on Fedora 31. /etc/resolv.conf not updated.

**Comment by scaronni** [comment]
> Tested this with the updates 1.3.90-3. Did not work for me, on Fedora 31. /etc/resolv.conf not updated.

Sorry, tried to fix it while my kid was annoying me, in a rush and trying to do too many things at once. New update here that also sets `--pppd-use-peerdns=1`: https://bodhi.fedoraproject.org/updates/?packages=NetworkManager-fortisslvpn

**Comment by tonoman3g** [comment]
+1 i reverted to 1.10.0 then it works

**Comment by secustor** [comment]
I can confirm this bug for `1.12.0` on Fedora 31

**Comment by DimitriPapadopoulos** [comment]
@secustor _Fedora 31_ packages have been fixed. Current versions are:
```
$ rpm -q openfortivpn 
openfortivpn-1.12.0-1.fc31.x86_64
$ 
$ rpm -q NetworkManager-fortisslvpn
NetworkManager-fortisslvpn-1.3.90-4.fc31.x86_64
$ 
```
If you are using _Fedora_ packages and your system is not up to date, please upgrade.
If you are building from sources, latest sources have been fixed and we'll release a formal version with the fix at some point.
Otherwise please open a new issue.

**Comment by DimitriPapadopoulos** [comment]
This is an incompatibility between _NetworkManager-fortisslvpn_ and _openfortivpn_.

### _openfortivpn_ 1.11.0 breaks compatibility
Starting with version 1.11.0 the default for _openfortivpn_ is equivalent to these command line options:
```
--set-dns=1 --pppd-use-peerdns=0
```
instead of previously:
```
--set-dns=1 --pppd-use-peerdns=1
```
The rationale is that it's not a good idea to have _openfortivpn_ and _pppd_ both attempt to modify `/etc/resolv.conf` concurrently. So we won't revert this change even if it breaks compatibility.

### Impact on _NetworkManager-fortisslvpn_
_NetworkManager-fortisslvpn_ expects _openfortivpn_ to run as if it were explicitly passed these command line options:
```
--set-dns=0 --pppd-use-peerdns=1
```
To achieve that _NetworkManager-fortisslvpn_ used to run _openfortivpn_ with the following explicit command line option:
https://github.com/GNOME/NetworkManager-fortisslvpn/blob/7f33a9c61d62bd621282eea251b1334e8eba43d3/src/nm-fortisslvpn-service.c#L231
which is equivalent to:
```
--set-dns=0
```
Upgrading to _openfortivpn_ 1.11.0 breaks this expectation as the equivalent command line options change from:
```
--set-dns=0 --pppd-use-peerdns=1
```
to:
```
--set-dns=0 --pppd-use-peerdns=0
```
_NetworkManager-fortisslvpn_ needs to explicitly use command line options to fix this incompatibility. I realize that `--pppd-use-peerdns=1` is not compatible with older versions of _openfoprtivpn_ but I see no other way.

**Comment by DimitriPapadopoulos** [comment]
Pull request to modify _NetworkManager-fortisslvpn_:
https://github.com/GNOME/NetworkManager-fortisslvpn/pull/1

**Comment by angystardust** [comment]
@DimitriPapadopoulos the right gnome repository to make PR is:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn

AFAIK github is just a mirror of gitlab.gnome.org

**Comment by DimitriPapadopoulos** [comment]
Pull request to modify _NetworkManager-fortisslvpn:_:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/13

**Comment by jp7677** [comment]
> > Tested this with the updates 1.3.90-3. Did not work for me, on Fedora 31. /etc/resolv.conf not updated.
> 
> Sorry, tried to fix it while my kid was annoying me, in a rush and trying to do too many things at once. New update here that also sets `--pppd-use-peerdns=1`: https://bodhi.fedoraproject.org/updates/?packages=NetworkManager-fortisslvpn

Hi @scaronni 
Any chance that you could take another look at the patch file for the Fedora package here https://src.fedoraproject.org/rpms/NetworkManager-fortisslvpn/blob/master/f/NetworkManager-fortisslvpn-openvpn-1_11.patch ? This patch removes the —no-dns option in favor of the —pppd-use-peerdns option. That is unfortunately still not correct afaik. The —no-dns option needs to stay and —pppd-use-peerdns should be added conditionally based on the setting in the NetworkManager UI. This bug report here explains this with more details: https://bugzilla.redhat.com/show_bug.cgi?id=1820906 . The attached patch to this bug report show how the patch file should look like instead: https://bugzilla.redhat.com/attachment.cgi?id=1676257&action=diff . The same patch is pending upstream at https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/15#diff-content-caa9b52bd00dac5878d191625beb6f12b0e6ba81
Thanks a lot for your work on the openfortivpn integration for Fedora! (And of course thank a lot to all people involved with openfortivpn itself!)

**Comment by DimitriPapadopoulos** [comment]
@jp7677 You're absolutely correct. I was under the impression that **`-no-dns`** had not been removed because the relevant line does not appear in red in this commit:
https://src.fedoraproject.org/rpms/NetworkManager-fortisslvpn/c/6378487

![fedora](https://user-images.githubusercontent.com/3234522/79050044-b3c7b580-7c27-11ea-89fc-3f33fc8623fb.png)

Yet **`--no-dns`** is indeed missing from the patch!
https://src.fedoraproject.org/rpms/NetworkManager-fortisslvpn/blob/master/f/NetworkManager-fortisslvpn-openvpn-1_11.patch

Unless I am missing something this a visualisation bug in the Fedora forge. It got me completely confused.

@scaronni Can you perhaps help fix this issue as suggested below?
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/15

**Comment by jp7677** [comment]
>@jp7677 You're absolutely correct. I was under the impression that **`-no-dns`** had not been removed because the relevant line does not appear in red in this commit: ...

@DimitriPapadopoulos yeah, the coloring confused me as well, it took me quite a while to match the behavior of my system with that patch because I totally missed the removal of ‘—no-dns’ too. That said the coloring is actually correct :) What we see in the commit/screenshot you just posted is the diff of the second commit of the _patch_ file, not the patch file itself. The removal of ‘—no-dns’ was already part of the initial version of that patch in the former commit. There everything is colored green, since the patch file had been initially been added. As stated, it took a while until I got it ;)

**Comment by scaronni** [comment]
Hi! Yes I can update the patch/configuration. I'm a bit confused now what to do. Shall I remove the `NetworkManager-fortisslvpn-openvpn-1_11.patch` and backport https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/15/diffs?

**Comment by jp7677** [comment]
> Hi! Yes I can update the patch/configuration. I'm a bit confused now what to do. Shall I remove the `NetworkManager-fortisslvpn-openvpn-1_11.patch` and backport https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/merge_requests/15/diffs?

Hi @scaronni, yes, as far as I can judge this would be the correct thing to do (I haven't actually compiled nor tested `NetWorkManager-fortisslvpn` with that PR). @DimitriPapadopoulos could you please confirm?

**Comment by DimitriPapadopoulos** [comment]
@scaronni Yes, that would be the correct thing to do.

Indeed the **`--no-dns`** option is required and needs to stay. The patch adds `—pppd-use-peerdns=1` conditionally based on the setting in the UI.

**Comment by scaronni** [comment]
https://src.fedoraproject.org/rpms/NetworkManager-fortisslvpn/c/3517525da74d6adb08643a756066cd05a4722032?branch=master

Updates for the various supported distributions have been created, we should receive some feedback from the users:

https://bodhi.fedoraproject.org/updates/?packages=NetworkManager-fortisslvpn

Thanks to everyone!

**Comment by DimitriPapadopoulos** [comment]
@scaronni Thank you very much for fixing this. I'll test myself on Fedora  31- provided I can repair VirtualBox which is broken on my workstation since an upgrade to Ubuntu 20.04.

**Comment by scaronni** [comment]
It works fine on my work laptop (we use SSL Fortinet VPN with OTP tokens from FreeIPA).
