### ISSUE TITLE
Failed to set DNS configuration: Could not activate remote peer.

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#514]
issue reported [here](https://github.com/adrienverge/openfortivpn/issues/375#issuecomment-565380174):
it fails to add the nameservers to `/etc/resolv.conf`
```
INFO:   Adding VPN nameservers...
DEBUG:  resolvconf_call: /usr/sbin/resolvconf -a "ppp0.openfortivpn"
Failed to set DNS configuration: Could not activate remote peer.
```

**Comment by mrbaseman** [comment]
The DNS configuration error obviously comes from resolvconf. When searching for the error message I have found [this thread](https://bugzilla.redhat.com/show_bug.cgi?id=1732487) with the hint:
```
It looks like systemd-resolved might not be running. Does it help
if you run 'sudo systemctl enable --now systemd-resolved' ?
```
If that doesn't help, you could try running `--pppd-use-peerdns=1` or disable the usage of resolvconf with the following workaround at configure time `--with-resolvconf=/sbin/nonexistent`

**Comment by DimitriPapadopoulos** [comment]
@nicolaerosia Does this help?

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman I'm closing this issue for now.
@nicolaerosia Please feel free to reopen it if you feel this is not a _resolvconf_ issue.
