### ISSUE TITLE
Problem with Mojave on OSX

### ISSUE THREAD

**Issue by ordimans** [adrienverge/openfortivpn#559]
Hello

It seems it doesn't work since some week on Mojave.
Don't know if Apple push a security update.

But after connected, no trafic is received.

So i reinstalled Forti Client, and is same....
Connected, data is sent, but no data is received.

Ping on name server OK
Ping on IP OK
Safari on name server KO
Safari on IP KO...

If someone have an idea....

I had debug trace for FORTICLIENT if needed.
And for Forti SSL :
VPN account password: 
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Thu Mar  5 18:10:16 2020 : publish_entry SCDSet() failed: Success!
Thu Mar  5 18:10:16 2020 : publish_entry SCDSet() failed: Success!
Thu Mar  5 18:10:16 2020 : Using interface ppp0
Thu Mar  5 18:10:16 2020 : Connect: ppp0 <--> /dev/ttys004
INFO:   Got addresses: [xxxx], ns [xxx, 1xxx]
INFO:   negotiation complete
INFO:   negotiation complete
Thu Mar  5 18:10:16 2020 : local  IP address xxx
Thu Mar  5 18:10:16 2020 : remote IP address 192.0.2.1
Thu Mar  5 18:10:16 2020 : Committed PPP store
Thu Mar  5 18:10:16 2020 : Committed PPP store
INFO:   Interface ppp0 is UP.
INFO:   Tunnel is up and running.

**Comment by DimitriPapadopoulos** [comment]
Do you reproduce this issue on a single or multiple Apple machines? From a single or different networks?

This could be caused by a change on your Apple machine or the network equipments between your Apple machine and the VPN appliance.

On Google search **[publish_entry SCDSet() failed](https://www.google.com/search?q=publish_entry+SCDSet%28%29+failed)**.

**Comment by ordimans** [comment]
Multiple :
2mojave
1 Catalina

From Hotspot Wifi, Cellular from iOS, Cellular for Android.

There is something on the machine , i agree, but what ? 
Because the ping is OK, it seems a NAT problem ? or depend what port is used....

Don't know....

**Comment by DimitriPapadopoulos** [comment]
@ordimans Any update? Since this does not seem specific to _openfortivpn_, can we close this issue?
