### ISSUE TITLE
reset static variables in iteration of the --persistent loop

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#560]
as discussed [here](https://github.com/adrienverge/openfortivpn/pull/558#issuecomment-595279404) in each iteration of [the loop](https://github.com/adrienverge/openfortivpn/blob/b596a0c1b55d9ca8013ba898add00ab37b0a3550/src/main.c#L564) that implements the --persistent option static variables need to be reset.

At least [need_flag_sequence](https://github.com/adrienverge/openfortivpn/blob/b596a0c1b55d9ca8013ba898add00ab37b0a3550/src/hdlc.c#L74l) in hdlc.c should be reinitialized, maybe some others, too.

**Comment by DimitriPapadopoulos** [comment]
`need_flag_sequence` is reset by #558.

**Comment by mrbaseman** [comment]
Oh, sorry, I have missed that. What about these in [io.c](https://github.com/adrienverge/openfortivpn/blob/b596a0c1b55d9ca8013ba898add00ab37b0a3550/src/io.c#L71)?:
```
static pthread_mutex_t *lockarray;
static os_semaphore_t sem_pppd_ready;
static os_semaphore_t sem_if_config;
static os_semaphore_t sem_stop_io;
```

**Comment by DimitriPapadopoulos** [comment]
Yes, #558 focuses on the HDLC implementation. I was thinking of a separate pull request for the variables in `io.c` as the logic behind the code might be quite different. Would that be OK?

**Comment by mrbaseman** [comment]
yes, sure.

**Comment by DimitriPapadopoulos** [comment]
Unlike `need_flag_sequence`, static variables `sem_pppd_ready`, `sem_if_config` and `sem_stop_io` are not initialized when declared:
```C
static os_semaphore_t sem_pppd_ready;
static os_semaphore_t sem_if_config;
static os_semaphore_t sem_stop_io;
```
Instead they are initialized in _io_loop_():
https://github.com/adrienverge/openfortivpn/blob/2fc808df942774305ddc755c98e9e94768a7c6c5/src/io.c#L599-L601
which is called by _run_tunnel_():
https://github.com/adrienverge/openfortivpn/blob/2fc808df942774305ddc755c98e9e94768a7c6c5/src/tunnel.c#L1085-L1087
which is called by the loop in _main_():
https://github.com/adrienverge/openfortivpn/blob/2fc808df942774305ddc755c98e9e94768a7c6c5/src/main.c#L592-L601

No need to worry about these variables as far as I can tell.

**Comment by DimitriPapadopoulos** [comment]
By the way, this tells me `need_flag_sequence` should be initialized not in _main_() but in _io_loop_():
https://github.com/adrienverge/openfortivpn/blob/2fc808df942774305ddc755c98e9e94768a7c6c5/src/io.c#L589-L604
Both work of course , but initialization should happen as close as possible to the code that calls HDLC-related functions, just before is starts calling these functions.

I'll fix that.

**Comment by DimitriPapadopoulos** [comment]
Unlike `need_flag_sequence`, static variable `lockarray` is not initialized when declared:
```C
static pthread_mutex_t *lockarray;
```
Instead it is initialized by _init_ssl_locks_():
https://github.com/adrienverge/openfortivpn/blob/2fc808df942774305ddc755c98e9e94768a7c6c5/src/io.c#L84-L94
which is called by _io_loop_():
https://github.com/adrienverge/openfortivpn/blob/2fc808df942774305ddc755c98e9e94768a7c6c5/src/io.c#L589-L606

No need to worry about this variable as far as I can tell.
