### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [adrienverge/openfortivpn#566]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/adrienverge/openfortivpn/blob/cd9368c6a1b4ef91d77bb3fdbe2e5bc34aa6f4c4/configure.ac#L22 "Update candidate")?

**Comment by DimitriPapadopoulos** [comment]
Sure, why not. But can you expand on why it is needed on _openfortivpn_ supported platforms?

**Comment by elfring** [comment]
I suggest to improve software portability also for the affected build script.

**Comment by DimitriPapadopoulos** [comment]
I had a look at AX_PTHREAD. I'm not convinced. It requires additional dependencies and is complicated. _openfortivpn_ is portable enough as is.

**Comment by DimitriPapadopoulos** [comment]
When running `configure` error I see:
```
$ ./configure
[...]
checking for pthread_cancel... no
configure: error: Required function not found
$ 
```
From `config.status`:
```
[...]
configure:6092: checking for pthread_cancel
configure:6092: gcc -o conftest -g -O2   conftest.c -lutil  >&5
/tmp/ccbMcx1t.o: In function `main':
/foo/bar/openfortivpn/conftest.c:138: undefined reference to `pthread_cancel'
collect2: error: ld returned 1 exit status
configure:6092: $? = 1
configure: failed program was:
[...]
| char pthread_cancel ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined __stub_pthread_cancel || defined __stub___pthread_cancel
| choke me
| #endif
| 
| int
| main ()
| {
| return pthread_cancel ();
|   ;
|   return 0;
| }
configure:6092: result: no
configure:6099: error: Required function not found
[...]
```

**Comment by elfring** [comment]
>It requires additional dependencies and is complicated.

The safe determination of appropriate build parameters can be challenging.
Would you like to reuse any corresponding system variables?


>`checking for pthread_cancel... no`

Do you really stumble on a software library without support for thread cancelability?

**Comment by DimitriPapadopoulos** [comment]
I'm sorry. I'm unable to understand your questions.

**Comment by DimitriPapadopoulos** [comment]
A pull request would be much more useful than this cotinuous stream of questions.

**Comment by elfring** [comment]
I suggest to reconsider the application of the following variables.
* PTHREAD_CFLAGS
* PTHREAD_LIBS
* PTHREAD_CC

-----

How would you like to clarify the failed software build check for the function “pthread_cancel” (in your test environment)?

**Comment by DimitriPapadopoulos** [comment]
Please submit a pull request.
