### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [adrienverge/openfortivpn#567]
I would like to point out that an identifier like “[`_OPENFORTIVPN_LOG_H`](https://github.com/adrienverge/openfortivpn/blob/f3909d8cfb36c0660fc4bcbb9167d891c67016d3/src/log.h#L18 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by DimitriPapadopoulos** [comment]
Sure, I had noticed that as well but since there are no actual conflicts this wasn't really high in my priorities.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by DimitriPapadopoulos** [comment]
Yes, we will fix that. Yet I'm not certain I follow you. In theory, yes there could be conflicts. In practice there aren't. Can you please explain your exact motivation?

**Comment by elfring** [comment]
I would appreciate to improve the standard compliance also for this software.
Will it become a bit more secure then?

**Comment by DimitriPapadopoulos** [comment]
More secure because of modified header guards? I'm not sure I follow you, it looks like you're focusing on details instead of real issues. What is your exact motivation?

**Comment by elfring** [comment]
Do you care for recommendations from well-known programming guidelines?

**Comment by DimitriPapadopoulos** [comment]
I care. Yet I don't see how there is a secuirty issue in this specific case.

**Comment by elfring** [comment]
Can any software users become concerned because of risks around undefined software behaviour?

**Comment by DimitriPapadopoulos** [comment]
Sometimes some recommendations are good for new software. Doesn't mean there is high urgency to fix existing software. There has to be some form of prioritization.

**Comment by elfring** [comment]
The corresponding prioritisation can vary for desired software improvements.

**Comment by DimitriPapadopoulos** [comment]
It should be fixed as this is an easy one. Does it look OK?

Still not sure what you mean "The corresponding prioritisation can vary for desired software improvements" but I agree with all your suggestions - I'm just not certain there's any degree of urgency for this specific issue.

**Comment by elfring** [comment]
The fix was easy for this issue when it seems that only a few include guards were affected.
