### ISSUE TITLE
Check return values

### ISSUE THREAD

**Issue by elfring** [adrienverge/openfortivpn#568]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [uri_unescape](https://github.com/adrienverge/openfortivpn/blob/4c9057a92711df6341344df8899654ca9c66f213/src/userinput.c#L59)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [init_logging](https://github.com/adrienverge/openfortivpn/blob/4c9057a92711df6341344df8899654ca9c66f213/src/log.c#L52)

**Comment by DimitriPapadopoulos** [comment]
This one is most interesting. I have been fixing other such issues recently but am not sure how to find them in a  systematic way. Is this a complete list? How did you obtain it? Are there any tools we could use - except of course re-reading all the code which I have started doing recently (https://github.com/adrienverge/openfortivpn/commit/32f1949).

**Comment by elfring** [comment]
I suggest to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software.

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by DimitriPapadopoulos** [comment]
Sure. Any suggestion? For example we already use _Coverity Scan_ and _Code Inspector_ (I find the latter doesn't really help with an existing code base).

**Comment by elfring** [comment]
Do the mentioned analysis tools indicate any more update candidates besides the source code places which I pointed out?

**Comment by DimitriPapadopoulos** [comment]
I don't know. I probably won't have time to run them soon in the short term. I was hoping you coudl provide some information.

**Comment by elfring** [comment]
I hope that further improvements can be achieved also together with an increasing application of higher level software development tools.

**Comment by DimitriPapadopoulos** [comment]
Sure. Which tools though? You suggest a tool that seems to be sold by _pure-systems GmbH_. While I don't have anything against using this tool, I don't know you, how you are related to _pure-systems GmbH_, and what you background in code analysis and security is. Hard to tell from a few short messages. I would rather have additional insight such as peer-reviewed papers.

**Comment by elfring** [comment]
I am generally interested in improvements for some software areas.
I find evolution around [the software “AspectC++”](https://aspectc.org/Download.php "Getting AspectC++") also interesting then to some degree.

-----

Would you like to consider design possibilities from using a programming language like C++?

-----

>…, and what your background in code analysis and IT security is.

Can you get any more clues from my public development activities through the years?

**Comment by DimitriPapadopoulos** [comment]
Please keep it short and refrain from answering questions with questions. Resources are limited and time is of the essence. Get to the point.

This is a C program, not C++. I have no intent of moving it to C++ and I suspect other maintainers are not interested either - not that I'm against C++ but there are plenty of reasons against such a decision.

If you feel the specific static analysis tool you have used to find these errors is easy to apply to _openfortivpn_ and will find more errors than the tools we already use, please just point us to the specific tool.. Referring us to a long list of tools is not useful - we just don't have time for riddles.

I have started fixing these issues: #648

**Comment by elfring** [comment]
Thanks for your small source code improvement.
