### ISSUE TITLE
zyxel ssl/vpn

### ISSUE THREAD

**Issue by sbechet** [adrienverge/openfortivpn#572]
Maybe it can help if openfortivpn follow 302?

```
username=__my_login__&credential=__my_credential__&realm=&ajax=1&redir=%2Fremote%2Findex&just_logged_in=1
DEBUG:  http_receive: 
HTTP/1.1 302 Found
Date: Mon, 16 Mar 2020 15:03:55 GMT
Location: /
Content-Length: 185
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="/">here</a>.</p>
</body></html>

ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
DEBUG:  HTTP status code 302
INFO:   Closed connection to gateway.

```

**Comment by mrbaseman** [comment]
Openfortivpn is a Fortinet SSL VPN client. The implementation by Zyxel is probably not compatible. Even if we follow the http redirect, the authentication that follows then, could be completely different.

**Comment by sbechet** [comment]
Thx, i'm currently reading binary. I found really interesting strings and think openfortivpn is really near zyxel implementation.

In fact, i can pass SSL without any problem. I'm now on login side.

- "POST / HTTP/1.1\r\nHost: %S:%S\r\nReferer: https://%S:%S\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: Keep-Alive\r\nContent-Length: %d\r\n\r\n%s"

- "POST /setuser.cgi HTTP/1.1\r\nHost: %S:%S\r\nReferer: https://%S:%S\r\nCookie: authtok=%S;\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: Keep-Alive\r\nContent-Length: %d\r\n\r\n%s"

- "username=%S&pwd=%S&password=%S&loginTosslvpn=true"

**Comment by sbechet** [comment]
Ok you right workflow is a little more complex :-/
