### ISSUE TITLE
Received bad header from gateway when you have tons of remote subnets

### ISSUE THREAD

**Issue by m33m33** [adrienverge/openfortivpn#575]
Hi

It seems you get the "Received bad header from gateway" error when your vpn server has tons of routes to remote subnets to push to the client.

I have narrowed the issue down to a hardcoded buffer size. 

Here is the log, and a generous size increase of the buffer size... is it safe ? 

It looks good - works well here at least.

[openfortivpn.log](https://github.com/adrienverge/openfortivpn/files/4356262/openfortivpn.log)

**Comment by DimitriPapadopoulos** [comment]
Strange, I would have expected at least a warning such as `Response too big`:
https://github.com/adrienverge/openfortivpn/blob/f7110c4aa558c5dabd85155e07148d0bbd8798fa/src/http.c#L209-L210
Anyway, thank you for reporting this!

In the short term I don't know if there's some magic buffer size that would be guaranteed to fit all. In any case a `BUFSZ` value of `0x10000` would use 64 KB, which shouldn't be a problem nowadays on any decent computer.
In the long term, we might need to change for a solution based on _realloc()_ or use an existing external library as already suggested for XML or HTTP parsing.

**Comment by DimitriPapadopoulos** [comment]
Ah, nice catch! And we thought `0x8000` "would be enough for everyone"! Perhaps use `0x10000`? For no peculiar reason. I just happen to like it more 😊
