### ISSUE TITLE
resolvconf when cross compiling

### ISSUE THREAD

**Issue by lucize** [adrienverge/openfortivpn#598]
Hi,
On cross compile I tried to disable resolvconf with:

```
        --without-resolvconf \
or
        --with-resolvconf="no" \
or
export RESOLVCONF_PATH=DISABLED
export HAVE_RESOLVCONF=0

```
but I still get the

```
checking for resolvconf... DISABLED
configure: RESOLVCONF_PATH... no
configure: HAVE_RESOLVCONF... 1
checking for no... configure: error: cannot check for file existence when cross compiling

```
I think the logic needs to be verified

Thanks

**Comment by mrbaseman** [comment]
try 
`./configure --with-resolvconf=DISABLED`
we have tweaked this logic the last days, so give the brand new 1.13.2 a try

**Comment by lucize** [comment]
yes, sorry, I forgot to mention that, I looked in the configure and tried that also

```
checking for resolvconf... DISABLED
configure: RESOLVCONF_PATH... DISABLED
configure: HAVE_RESOLVCONF... 0
checking for DISABLED... configure: error: cannot check for file existence when cross compiling

```

**Comment by lucize** [comment]
I think in checking for cross compile is the problem, if we specify a path and cross compile we should bypass the check and trust the input provided:

```
checking for resolvconf... DISABLED
configure: RESOLVCONF_PATH... /usr/sbin/resolvconf
configure: HAVE_RESOLVCONF... 1
checking for /usr/sbin/resolvconf... configure: error: cannot check for file existence when cross compiling

```

**Comment by mrbaseman** [comment]
actually, this is another case which we didn't have so far. There are two different switches, one that determines if resolvconf support is compiled in and another one, which sets the default that is used at runtime. Unfortunately, the configure script tries to determine the latter even if support is not compiled in. Could you try the following in your cross-compile environement:
`./configure --disable-resolvconf --with-resolvconf=DISABLED`

**Comment by lucize** [comment]
> ./configure --disable-resolvconf --with-resolvconf=DISABLED

this solves the problem with DISABLED
Thank you!

**Comment by mrbaseman** [comment]
I'll commit a fix for that
