### ISSUE TITLE
Routes applied to wrong interface when multiple ppp interfaces have the same address

### ISSUE THREAD

**Issue by naav** [adrienverge/openfortivpn#601]
Hello,

I have a case where two instances of openfortivpn connect to two different servers that happen to assign exactly the same IP address to both clients.

This causes the second instance of openfortivpn to mistakenly select the ppp interface of the first one for routing, which naturally doesn't work:
https://github.com/adrienverge/openfortivpn/blob/6258b97424f12a7e1e2ed44cdfad95db0f443489/src/tunnel.c#L437-L441

My understanding of the interactions between openfortivpn and pppd being cursory at best, I've applied what is probably the most naive of patches to take into consideration the interface name in the selection heuristic, and configured `pppd-ifname` to be fixed in each client's config file. This causes openfortivpn to select the interface that matches both in name and address.

```diff
diff --git a/src/tunnel.c b/src/tunnel.c
index 39ed521..9a4cc29 100644
--- a/src/tunnel.c
+++ b/src/tunnel.c
@@ -434,7 +434,8 @@ int ppp_interface_is_up(struct tunnel *tunnel)
                                log_debug("Interface Name: %s\n", ifa->ifa_name);
                                log_debug("Interface Addr: %s\n", inet_ntoa(if_ip_addr));

-                               if (tunnel->ipv4.ip_addr.s_addr == if_ip_addr.s_addr) {
+                               if (tunnel->ipv4.ip_addr.s_addr == if_ip_addr.s_addr
+                                   && strstr(ifa->ifa_name, tunnel->config->pppd_ifname) != NULL) {
                                        strncpy(tunnel->ppp_iface, ifa->ifa_name,
                                                ROUTE_IFACE_LEN - 1);
                                        freeifaddrs(ifap);
```

Ideally, it would be better if pppd could communicate directly its interface back to openfortivpn. Alternatively, perhaps it would be better to remove the interface selection heuristic altogether if `pppd-ifname` is set in the config, or add some configuration flag to let the user pick.

**Comment by DimitriPapadopoulos** [comment]
Communication between openfortivpn and pppd is basic. openfortivpn forks and execs pppd. When pppd exits we retrieve the exit code.

**Comment by mrbaseman** [comment]
@naav  On which platform are you? I believe the code you are looking for is [a few lines above](https://github.com/adrienverge/openfortivpn/blob/6258b97424f12a7e1e2ed44cdfad95db0f443489/src/tunnel.c#L421) but only active if _openfortivpn_ is used together with _pppd_. 

On FreeBSD there is a different client, and the structure for the routing entries looks a little bit different.

On Linux and on Mac you should be able to specify the interface names in the config file and they should be passed to _pppd_ and then the routes should be set to the corresponding interface. Make sure not to use strings that contain `ppp` because that is the fallback which is automatically chosen to match the interface (apart from it's IP address, which isn't unique in your case either).

**Comment by naav** [comment]
@mrbaseman I am on Alpine with pppd.

> Make sure not to use strings that contain ppp because that is the fallback which is automatically chosen to match the interface

I had missed that part: indeed both my interface names start with `ppp`. Choosing names without this prefix makes my above patch redundant. Thanks!

**Comment by mrbaseman** [comment]
One more detail which might be important for others who find this ticket: Not even all implementations of pppd support the ifname option. It's [specific to Linux](https://unix.stackexchange.com/questions/145692/naming-ppp-interfaces). 
...and I have to admit that the detail about the strings containing "ppp" is not documented anywhere. It's a very special case, but in the future we can refer to this github issue.
