### ISSUE TITLE
Old version in universe for Ubuntu 18.04

### ISSUE THREAD

**Issue by akalongman** [adrienverge/openfortivpn#604]
There is a very old version (v1.6 Nov 15, 2017) in universe repository https://packages.ubuntu.com/bionic/openfortivpn

Could it be fixed?

**Comment by DimitriPapadopoulos** [comment]
We don't maintain vendor packages, you'd have to ask Ubuntu maintainers.

Note that version 1.12.0 has been made available on recent Debian distributions and the maintainer might attempt to update to 1.13.2:
https://packages.debian.org/source/bullseye/openfortivpn
https://packages.debian.org/source/sid/openfortivpn
