### ISSUE TITLE
default route wrong

### ISSUE THREAD

**Issue by tobiasoed** [adrienverge/openfortivpn#607]
Hello,
Before starting a forticlient vpn when I have an openvpn connexion 
through which I send all my traffic forticlient vpn sets up a route to 
the wrong gw.
Before starting forticlient vpn:

```
toot@laptob:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.138.5   0.0.0.0         UG    50     0        0 tun0
0.0.0.0         192.168.43.1    0.0.0.0         UG    600    0        0 wlan0
1.2.3.4  192.168.43.1    255.255.255.255 UGH   600    0        0 wlan0
...
```

So it is going to use 192.168.138.5 via the openvpn vpn. After 
starting the vpn, the routes are:

```
root@laptob:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.138.5   0.0.0.0         UG    50     0        0 tun0
0.0.0.0         0.0.0.0         0.0.0.0         U     50     0        0 ppp0
0.0.0.0         192.168.43.1    0.0.0.0         UG    600    0        0 wlan0
4.5.6.7   192.168.43.1    255.255.255.255 UGH   600    0        0 wlan0
1.2.3.4  192.168.43.1    255.255.255.255 UGH   600    0        0 wlan0
...
```

So it adds a route through wlan0 to the vpn gw address (4.5.6.7) and 
the vpn isn't working. If I delete the route to 4.5.6.7 or force it through tun0
things work fine. 
So the client adds the wrong route.
Sincerely,
Tobias Oed

**Comment by DimitriPapadopoulos** [comment]
Hi Tobias,
Could you edit this issue so that it is more readable?

![Edit](https://user-images.githubusercontent.com/3234522/77859422-8df2e780-7209-11ea-95b4-daef3bee757a.png)

**Comment by tobiasoed** [comment]
Hello,
hope this is better.
Sincerely,
Tobias Oed

**Comment by tobiasoed** [comment]
I edited the post and the issue came back as closed. I'm trying to reopen it, sorry for the confusion.

**Comment by mrbaseman** [comment]
You have a case where you have several default routes which only differ in their metric.
openfortivpn _should_ take the metric into account and properly set the route to the vpn gateway. However, the metric code is not portable, because metric exists only on linux. Can you confirm that you are running linux, and which version of openfortivpn is this?

**Comment by tobiasoed** [comment]
Hello, indeed I'm runnning linux (fedora). 
```
Name        : openfortivpn
Version     : 1.12.0
Release     : 1.fc31
Architecture: x86_64
```
Too bad the metic is not portabe. Would it be possible to use something like `ip route get 1.2.3.4` to have whatever os is running calculate the actual route used ?
Tobias

**Comment by mrbaseman** [comment]
Actually, I'm surprised that this doesn't work as expected on Fedora with a quite recent version. I have to look deeper into the routing code. 
On Linux we parse the content of `/proc/net/route`. The hope is that the content of the /proc file system is easier to parse and less prone to format changes than the output of a command. On Mac OSX and FreeBSD, however, we parse the output of the netstat command.
Anyhow, the difficulty in this topic is to make a correct decision based on the routes that are present. It would help if the ip command could do this for us, but then we are left with the problem if the ip command is available on all supported platforms. Probably it would be the route command on some of them, with yet another output format... 
Based on the output that you have posted I'll try to find out what goes wrong in this particular case.

**Comment by mrbaseman** [comment]
Hi Tobias,

I have tried to simulate your setup (I don't have an openvpn, but I have tried it with two nested openfortivpn tunnels) with two default routes that differ in their metric, device, and gateway. Unfortunately, I can not reproduce what you have described. Could you start openfortivpn in verbose mode, please (`-v` option) and post the output between the info messages 
```
INFO:   Interface ppp0 is UP.
...
INFO:   Tunnel is up and running.
```
if you have anonymized the ip addresses in your previous posts (I assume you did so), please do it consistently also in the requested debug output.

**Comment by tobiasoed** [comment]
Uh. 
If I'm running it from the command line I have the correct result. It's when I'm launching it through NetworkManager-fortisslvpn-gnome-1.3.90-4.fc31.x86_64 that the behaviour is wrong.
So I guess this is not the correct place to report this. Sorry for waisting your time!
Toias

**Comment by DimitriPapadopoulos** [comment]
Indeed _Network-Manager_ starts _openfortivpn_ with options `--no-routes --no-dns` and handles routing and DNS parameters directly:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/blob/master/src/nm-fortisslvpn-service.c#L230

This would be the place to report this issue:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues

**Comment by mrbaseman** [comment]
> Sorry for wasting your time!

@tobiasoed never mind. It could have well been a problem in openfortivpn which had been unnoticed so far. There are so many different combinations of the software environment on the client side, network configuration, settings on the Fortigate, etc. and it's usually impossible to tell in advance what's causing a particular problem
