### ISSUE TITLE
Ability to Set Static Routes

### ISSUE THREAD

**Issue by teamosceola** [adrienverge/openfortivpn#614]
Feature Request:
- Ability to configure static routes in the config file.

What I would like to be able do via the config file:
```
host = vpn.domain.com
port = 443
set-routes = 0
set-dns = 0
pppd-use-peerdns = 0
add-static-route = 10.0.1.0/24
add-static-route = 10.0.10.0/24
add-static-route = 10.2.1.0/24
add-static-route = 10.20.1.0/24
```
Which would result in the following commands running after the vpn interface is up
```
ip route add 10.0.1.0/24 dev ppp0
ip route add 10.0.10.0/24 dev ppp0
ip route add 10.2.1.0/24 dev ppp0
ip route add 10.20.1.0/24 dev ppp0
```
This is very useful for people that need to access resources that are behind the vpn, but want their normal web traffic to not use the vpn. A good example is audio/video teleconferencing where the quility would be degraded due to the added latency of the vpn.

**Comment by mrbaseman** [comment]
this can be achieved by an pppd-ipup script, see #371 and the [wiki](https://github.com/adrienverge/openfortivpn/wiki) page

**Comment by obel1x** [comment]
i had the same issue, for me the wiki worked and needed some small changes. i did them, changed the docs and added a few descriptions. is it ok for you @teamosceola to close this issue now?

**Comment by teamosceola** [comment]
I was able to get it to work using the pppd-ipup script, but I actually ended up switching to using 
`sudo apt install network-manager-fortisslvpn-gnome`
to ultimately solve my issue.

**Comment by DimitriPapadopoulos** [comment]
In systems that do have _NetworkManager_ enabled, indeed it sounds best to handle routing and name resolution within _NetworkManager_. Great to hear that you got that working.
