### ISSUE TITLE
Can I reuse config file from forticlient to openfortivpn?

### ISSUE THREAD

**Issue by umbria** [adrienverge/openfortivpn#618]
I'm using forticlient on windows but I want to use on Linux.
There are no forticlient vpn version.
I backup config file from forticlient but I couldn't use on openfortivpn.

I ran 
openfortivpn  222.56.213.12:80 -c myconf.conf -u user01

It shows the error below.

WARN:   Bad key in config file: "<?xml version".
WARN:   Could not load config file "myconf.conf" (unknown).

**Comment by mrbaseman** [comment]
openfortivpn uses a different file format. An example config file should have been installed together with openfortivpn. Have a look at the manual page (`man openfortivpn`). The path of the default config file is mentioned together with the description of the `-c` option, and a lengthy example config file example is included at the end of the man page.

**Comment by DimitriPapadopoulos** [comment]
See also #160.

I suspect it might not help to use the _FortClient_ XML configuration from Windows as the Windows client often uses IPSec while the Linux client uses VPN SSL. But maybe I'm wrong. That said the _FortiClient_ configuration file format is documented here:
[XML configuration file](https://docs.fortinet.com/document/forticlient/6.2.6/xml-reference-guide/812076/xml-configuration-file)

**Comment by DimitriPapadopoulos** [comment]
@umbria If you could send me a **sanitized** version of s sample config file (obfuscate user name, password, IP address, DNS server) I could perhaps write a Python script to convert _FortiCLient_ XML config files to an _opnefortivpn_ config files - time permitting.

**Comment by DimitriPapadopoulos** [comment]
@umbria I did get hold of a _FortiClient_ on Windows but was unable to find a configuration file. The configuration seems to be stored in the registry and I cannot find a way to export it to a file.

How did you retrieve the configuration file from the Windows machine? Has the Windows configuration file been handed over but IT support?

**Comment by DimitriPapadopoulos** [comment]
I have found a Diagnostic Tool in the _About_ dialog:

![Diagnostic_Tool](https://user-images.githubusercontent.com/3234522/78986692-23587a80-7b2c-11ea-997f-56994efb6149.png)

It does generate an `FCT_config.xml` XML file but I don't know if you are referring to the same kind of file. Here is a sanitized excerpt:
https://gist.github.com/DimitriPapadopoulos/ca58f2ccc2cd0a9584f2b97e0d3f7132

**Comment by DimitriPapadopoulos** [comment]
@umbria It would be great to have even a partial XML file to write a conversion script. Please re-open if you can provide one.

**Comment by DimitriPapadopoulos** [comment]
Note that FortiClient 6.4.0 supports importing an XML file:
![XML](https://user-images.githubusercontent.com/3234522/86909003-be56f580-c117-11ea-8a0c-889c12c6d888.png)

**Comment by DimitriPapadopoulos** [comment]
@umbria If you can provide a (sanitized) XML configuration file we could work on that feature.
