### ISSUE TITLE
Access shared folder through VPN

### ISSUE THREAD

**Issue by devondahon** [adrienverge/openfortivpn#638]
Once connected to vpn with `openfortivpn`, how to open remote shared folder which path is `\\foo\bar` ?

**Comment by DimitriPapadopoulos** [comment]
As far as I can see this is not related to _openfortivpn_, isn't it?

I understand you are on a Linux machine and want to access a share on a Windows server. For example with [Gnome Nautilus](https://help.gnome.org/users/gnome-help/stable/nautilus-connect.html.en) you would access it as:
```
smb://foo/bar
```

**Comment by devondahon** [comment]
@DimitriPapadopoulos I have updated my question.

**Comment by devondahon** [comment]
If I replace the address by the IP, then it works so it should be a routing problem. When I connect, I can see this warning:

> WARN:   No gateway address, using interface for routing

**Comment by DimitriPapadopoulos** [comment]
@devondahon Perhaps it would be easier if you could open a new issue with:
* version of _openfortivpn_ and platform (macOS),
* a more detailed description of the failure, here it looks like it's a name resolution (DNS) failure so running `nslookup` on `foo` would help focus on the problem,
* the (sanitized) verbose output of `openfortivpn -v`.

**Comment by devondahon** [comment]
[Here](https://github.com/adrienverge/openfortivpn/issues/639) is the new issue. Thanks!
