### ISSUE TITLE
Knowing the vpn name: what's the ip / port?

### ISSUE THREAD

**Issue by nirgal** [adrienverge/openfortivpn#641]
Hi

My company gave me a fortivpn access. I have the vpnname, a login, a password and an OTP token. The vpn name looks like "My Company Network Token" and sure isn't a hostname.
What IP address should I use? What port?

Maybe there's a smart undocumented mechanism to convert a vpn name to a host name?
Maybe there's a simple undocumented default hostname / port and they gave me a realm?

I would be happy to write a PR if someone answers!

**Comment by mrbaseman** [comment]
This could be Fortinet's Endpoint provisioning Feature with their Security Fabric. If endpoint provisioning is enabled, an unconfigured FortiClient, when connected to the company network automatically receives a configuration with possibly several profiles. The "vpn name" could be the name of the profile to use. That profile contains the hostname and port to connect to. 
_openfortivpn_ can make the connection to the ssl vpn, but it can not integrate into the security fabric and receive the configuration. I think this is a licensed feature covered by a software patent. But you could use the official client to receive the information and then try to connect with openfortivpn (or just ask the it department for the hostname and the port - which is usually 443). 

Maybe it's even much simpler and you just haven't found the place where your company has put the documentation which tells you what they mean when they talk about a specific vpn...
