### ISSUE TITLE
OTP/FortiToken

### ISSUE THREAD

**Issue by xdaass** [adrienverge/openfortivpn#657]
Hi, 
im struggling with this, 
the OpenFortiVPN works fine, but i cannot find a way to use it when required to authenticate using an OTP, 
can you please help ? is this functionality supported?

Thanks for your work

**Comment by DimitriPapadopoulos** [comment]
What have you tried so far? What are the error messages? In verbose mode (`-v -v `)?

**Comment by xdaass** [comment]
I didnt understand where to enter the otp,
Without otp it works fine

**Comment by DimitriPapadopoulos** [comment]
Have you at least tried `man openfortivpn`or `openfortivpn --help`?

**Comment by xdaass** [comment]
I thought i did, 
i see now, will try it, 
thanks 
sorry to disturb

**Comment by xdaass** [comment]
works like a charm , thanks again !
