### ISSUE TITLE
Document prerequisite packages - Ubuntu but generally

### ISSUE THREAD

**Issue by bbulkow** [adrienverge/openfortivpn#658]
It seems some number of packages required to install, I am running into a requirement for pppd, I think. Given that this project claims to be a pppd system, I'm surprised, and I wonder if there is a specific dependent version or package. I'm on Ubuntu Bionic, likely one of the most common distributions of Linux at this point in time - I don't expect covering all the outliers....

In any case, I tend to expect that if a package requires other packages, it's either in package management as a prereq, or in the documentation. I see neither here --- hope it's just a few lines of documentation.

Thanks for listening.

**Comment by DimitriPapadopoulos** [comment]
I think this is covered in the [README](https://github.com/adrienverge/openfortivpn):
> Finally, install runtime dependency `ppp` or `pppd`.

`pppd` is not required at build time as far as I can recall. It is required at run time.

Just to clarify, what do you mean by "package"? Are you building from sources of installing vendor specific (DEB or RPM) packages?

**Comment by DimitriPapadopoulos** [comment]
@bbulkow If you're building from sources, hopefully the above answers your question. Any (reasonably recent) version of `/usr/sbin/pppd` should work as far as we know. No related issues have ever been reported. At build-time we cannot do much more as `/usr/sbin/pppd` is a "soft" build-time dependency not **strictly** required. At run-time I seem to recall _openfortivpn_ does emit an error message if `/usr/sbin/pppd` is missing. Does the error message need to be improved?

If you're installing a DEB package, I think the [Debian `openfortivpn` package does depend on the `pppd`package](https://salsa.debian.org/debian/openfortivpn/-/blob/master/debian/control#L20):
> `Depends: ${misc:Depends}, ${shlibs:Depends}, ppp`

Is that not the case for you on Ubuntu 18.04?
