### ISSUE TITLE
On slow connections, VPN connection stop working after few seconds

### ISSUE THREAD

**Issue by bpresles** [adrienverge/openfortivpn#66]
While it's working perfectly fine with good broadband connection, I've noticed that when used on a slow connection, in my case ReachDSL2 with 2Mbits/sec download and 400Kbits/sec upload, it stops working after few seconds:

PING 192.168.2.49 56(84) bytes of data.
64 bytes from 192.168.2.49: icmp_seq=1 ttl=60 time=48.5 ms
64 bytes from 192.168.2.49: icmp_seq=2 ttl=60 time=49.4 ms
64 bytes from 192.168.2.49: icmp_seq=3 ttl=60 time=50.9 ms
64 bytes from 192.168.2.49: icmp_seq=4 ttl=60 time=51.1 ms
64 bytes from 192.168.2.49: icmp_seq=5 ttl=60 time=48.3 ms
64 bytes from 192.168.2.49: icmp_seq=6 ttl=60 time=51.0 ms
64 bytes from 192.168.2.49: icmp_seq=7 ttl=60 time=52.7 ms
64 bytes from 192.168.2.49: icmp_seq=8 ttl=60 time=49.5 ms
64 bytes from 192.168.2.49: icmp_seq=9 ttl=60 time=49.7 ms
64 bytes from 192.168.2.49: icmp_seq=10 ttl=60 time=50.1 ms
64 bytes from 192.168.2.49: icmp_seq=11 ttl=60 time=51.6 ms
64 bytes from 192.168.2.49: icmp_seq=12 ttl=60 time=52.3 ms
64 bytes from 192.168.2.49: icmp_seq=13 ttl=60 time=48.8 ms
64 bytes from 192.168.2.49: icmp_seq=14 ttl=60 time=53.2 ms
64 bytes from 192.168.2.49: icmp_seq=15 ttl=60 time=51.9 ms
64 bytes from 192.168.2.49: icmp_seq=16 ttl=60 time=50.7 ms
64 bytes from 192.168.2.49: icmp_seq=17 ttl=60 time=50.9 ms
64 bytes from 192.168.2.49: icmp_seq=18 ttl=60 time=57.8 ms
64 bytes from 192.168.2.49: icmp_seq=19 ttl=60 time=117 ms
64 bytes from 192.168.2.49: icmp_seq=20 ttl=60 time=50.1 ms
64 bytes from 192.168.2.49: icmp_seq=21 ttl=60 time=53.5 ms
64 bytes from 192.168.2.49: icmp_seq=22 ttl=60 time=50.1 ms
64 bytes from 192.168.2.49: icmp_seq=23 ttl=60 time=52.0 ms
64 bytes from 192.168.2.49: icmp_seq=24 ttl=60 time=48.0 ms
64 bytes from 192.168.2.49: icmp_seq=25 ttl=60 time=49.4 ms
64 bytes from 192.168.2.49: icmp_seq=26 ttl=60 time=51.2 ms
64 bytes from 192.168.2.49: icmp_seq=27 ttl=60 time=73.6 ms
=> No ping answer after that line

I think it's matter of ppp settings, but I don't know what to change to fix this. I'm using default /etc/ppp/options file from Ubuntu 16.04.1
[openfortivpn-slowconnection-issue.zip](https://github.com/adrienverge/openfortivpn/files/476359/openfortivpn-slowconnection-issue.zip)
 (find a copy attached).

The attached ZIP contains the debug log and the ppp options settings.

**Comment by DimitriPapadopoulos** [comment]
Is this still the case with recent versions of _openfortivpn_? Does #50 help in your case?

**Comment by DimitriPapadopoulos** [comment]
@bpresles Hopefully this has been fixed in more recent versions of _openfortivpn_. Please tell us if that's not the case. Otherwise I shall close this issue.
