### ISSUE TITLE
make install problem

### ISSUE THREAD

**Issue by targzeta** [adrienverge/openfortivpn#666]
Hi,
thank you in advance for your work. I have a problem when I run the make install command:
<pre>
make[1]: Entering directory '/tmp/pkg/openfortivpn-snapshot_20200422'
 /bin/mkdir -p '/tmp/openforti/usr/bin'
  /bin/ginstall -c openfortivpn '/tmp/openforti/usr/bin'
 /bin/mkdir -p '/tmp/openforti/usr/share/openfortivpn'
 /bin/ginstall -c -m 644 etc/openfortivpn/config.template '/tmp/openforti/usr/share/openfortivpn'
 /bin/mkdir -p '/tmp/openforti/usr/man/man1'
 /bin/ginstall -c -m 644 doc/openfortivpn.1 '/tmp/openforti/usr/man/man1'
make  install-data-hook
make[2]: Entering directory '/tmp/pkg/openfortivpn-snapshot_20200422'
make[2]: *** No rule to make target 'lib/systemd/system/openfortivpn@.service', needed by 'install-data-hook'.  Stop.
make[2]: Leaving directory '/tmp/pkg/openfortivpn-snapshot_20200422'
make[1]: *** [Makefile:1082: install-data-am] Error 2
make[1]: Leaving directory '/tmp/pkg/openfortivpn-snapshot_20200422'
make: *** [Makefile:1020: install-am] Error 2
</pre>

The problem seems related to [this commit](https://github.com/adrienverge/openfortivpn/commit/8ea4d6cd83f59787ca14b14c2a333ddd08f932ae).

Note: I don't have systemd:
<pre>
$> grep SYSTEMD config.log 
ac_cv_env_LIBSYSTEMD_CFLAGS_set=
ac_cv_env_LIBSYSTEMD_CFLAGS_value=
ac_cv_env_LIBSYSTEMD_LIBS_set=
ac_cv_env_LIBSYSTEMD_LIBS_value=
HAVE_SYSTEMD_FALSE=''
HAVE_SYSTEMD_TRUE='#'
LIBSYSTEMD_CFLAGS=''
LIBSYSTEMD_LIBS=''
</pre>

Best regards,
Emanuele

**Comment by DimitriPapadopoulos** [comment]
@targzeta Does this above commit help?

I had left a dependency to `lib/systemd/system/openfortivpn@.service` in target `install-data-hook` the whole purpose of which is only to install the configuration file.

Everything related to the service file `openfortivpn@.service` should be guarded with `if HAVE_SYSTEMD`. In your case `HAVE_SYSTEMD` is false.

**Comment by targzeta** [comment]
@DimitriPapadopoulos Thank you!

Emanuele
