### ISSUE TITLE
Update Routing Script in Wiki

### ISSUE THREAD

**Issue by obel1x** [adrienverge/openfortivpn#669]
Hey, i had the same needs as #614 and found the solution in #371 and your [wiki](https://github.com/adrienverge/openfortivpn/wiki).
There is a small bug, which causes the script described there to not work any more, because "route" has now been replaced by "ip route". 

I would like to update the chapter "using pppd ip-up / ip-down scripts" like this:

```
#!/bin/bash
#
# Whitelist here all domains that need to go through FortiVPN
# Domains are separated by a space
domains='example.com example.fr'
ips='10.0.0.0/8'

BASENAME=${0##*/}
INTERFACE=$1
DEVICE=$2
SPEED=$3
LOCALIP=$4
REMOTEIP=$5
IPPARAM=$6
ACTION=${0#/etc/ppp/}

let resolved
for domain in $domains; do
  resolved=`dig +short $domain | tail -n1`
  ips="$ips $resolved"
done

for ip in $ips; do
  ip route add $ip dev $INTERFACE
done
```

Should i just do it, or are there any hints?

**Comment by mrbaseman** [comment]
looks good. 
* the positional parameters `$1 ... $6` are included in the new version 
* the correct interface is set for the routes
* `ip route` is used as more and more distributions change towards the `ip` command

**Comment by obel1x** [comment]
thanks for the review. I now did the changes and added hopefully a few helpful descriptions.

If thats ok, i would close this and maybe take care of the issues above to close them.
