### ISSUE TITLE
[Feature request] Add an option to use dnsmasq instead of resolv.conf

### ISSUE THREAD

**Issue by bpresles** [adrienverge/openfortivpn#67]
Currently OpenFortiVPN adds nameservers directly to resolv.conf. It breaks the name server order (as they are added at the top) and so some name resolutions in my case (using dnsmasq).

I solved it by using the network-manager-fortisslvpn plugin that use dnsmasq, but it could be a good idea to add a command line option to be able to use dnsmasq to add nameservers, instead of adding them to resolv.conf directly, in openfortivpn directly for those who prefer to use the command line program.

**Comment by CircleCode** [comment]
This can be (almost) done without modification to openforticlient by using `--no-dns` and an `/etc/ppp/ip-up.d/` script (see 4th comment on #101)

**Comment by DimitriPapadopoulos** [comment]
@bpresles I am currently trying to rationalize DNS handling in _openfortivpn_. (see #330) The plan is to stop messing with DNS settings in _openfortivpn_ in the future, instead entirely delegate DNS settings to _pppd_.

In this context, would it make sense to drop this issue, and perhaps open an new ticket against _pppd_?

In the short term we could still add _dnsmasq_ support in _openfortivpn_, perhaps as a sample script for `/etc/ppp/ip-up.d/`. I cannot easily make sense of how to use _dnsmasq_ in a distribution such as _Ubuntu_. Could you point me to appropriate documentation?

**Comment by mrbaseman** [comment]
I think the same as for #101 applies here: The necessary options have been implemented in the meantime, the [wiki](https://github.com/adrienverge/openfortivpn/wiki) has been created and improved documentation of the command line options is going to land soon (#419). So, I assume we can close this issue. If you disagree, please reopen and point out what is still missing.
