### ISSUE TITLE
Identify obsolete code and add mechanism to disable it?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#677]
I suggest we start moving obsolete code to `obsolete.h`/`obsolete.c` files and/or guarding such code or calls to such code by `#ifdef OBSOLETE`. Of course`OBSOLETE` would remain defined for some time, unless _openfortivpn_ is configured with something like `--support-obsolete=no`.

Obsolete code I'm thinking of:
* Support for OpenSSL < 1.0.0
* Support for HTTP-formatted configuration sent by FortiOS 4.0.
* Modifying `/etc/resolv.conf` directly, certainly not in the short term but as soon as we have an alternative - more on that in a different issue.

Thoughts?

**Comment by adrienverge** [comment]
Introducing `#ifdef OBSOLETE` or `#ifdef SUPPORT_OBSOLETE_CODE` is a good idea! Moving code to `obsolete.c`: why not, if it helps.
