### ISSUE TITLE
Is it possible to use more then one vpn at the same time?

### ISSUE THREAD

**Issue by boospy** [adrienverge/openfortivpn#68]
Hello, 

i would like to use the programm to have multible vpn's active at the same time. I can call the programm more then once. But have problem with useing all vpn's the same ppp interface, or there are problems with the routing. 

How can i use it more then for one vpn at the same time?

Best Regards

**Comment by adrienverge** [comment]
Hello,

If there's a way to use a different ppp interface for each openfortivpn running, you could try implementing it (you can start by looking at `src/tunnel.c` line 94.

Contributions are welcome!

**Comment by boospy** [comment]
Thank you for you response. But... i'am only user not dev. So I'am sorry but i can't help to modify the code ;(

**Comment by jbergquist** [comment]
This would be a very useful feature to have. I'll try to make a patch for it but I am a really crappy developer... so if anyone else, with more knowledge, can do this it would be awesome!

**Comment by Valantin** [comment]
Hi, I've set up 2 different SSLVPN using openfortivpn, routes are configured manually

**Comment by jbergquist** [comment]
Yeah, I have done the same.
I did a really ugly fix for it in the code... which I am not gonna share... it is that ugly.
Basically I compiled a binary with a static vpn interface..

But until I or someone else has the time to do it properly I encourage everyone to add the routes manually and use the --pppd-no-peerdns and --no-routes options.

**Comment by Mabin-J** [comment]
I think that this issue is related to the #90.

**Comment by mrbaseman** [comment]
now that #95 has been merged into master it should work out of the box. I have successfully tested two of my sslvpn connections at the same time, without the need to configure the routes manually. However, one as to be careful with the default routing mode (default route through one of the vpn tunnels), because it might happen that the connection to one of the Fortigates is routed through the tunnel to the other one (which might not perform very well).

**Comment by jbergquist** [comment]
Yes, #95 seems to solve the issue. Happy days!!!

**Comment by boospy** [comment]
Nice :+1:  will test it on weekend. Best Regards!

**Comment by boospy** [comment]
Yes it is working perfectly :1st_place_medal:  I've tested it with 4 vpn's with clientcertificate. Thank very much. So It's time for me to build some deb-package ;)
