### ISSUE TITLE
Migrating from autotools to CMake

### ISSUE THREAD

**Issue by faustocarva** [adrienverge/openfortivpn#684]
Hi, i'm digging into this project and noted that it uses autotools for the build process. I would mind to know if there is already the idea or task to do the migration to CMake build system, taking in mind that CMake has a plenty of good integrations, checks and is a new de facto standard in the C/C++ ecosystem. Could it be a good idea/work/task/todo to do the migration? Can i be the person in charge of this issue?
Thanks.

Fausto Carvalho

**Comment by DimitriPapadopoulos** [comment]
I definitely don't like _autotools_ but why change something that works? Besides _oepnfortivpn_ is not such a complicated project that _autotools_ hampers future development, does it?

**Comment by DimitriPapadopoulos** [comment]
I'm not saying I'm against it. However a lot of packagers downstream are already building _openfortivpn_ with _autotools_. Moving to _CMake_ would mean a lot for work for lots of people without clear benefit.

Is it possible to have both _autotools_ and _CMake_ at the same time? How many new files would be required - just a handful `CMakeLists.txt` files?

**Comment by faustocarva** [comment]
> I'm not saying I'm against it. However a lot of packagers downstream are already building _openfortivpn_ with _autotools_. Moving to _CMake_ would mean a lot of work for lots of people without clear benefit.

Both tools can live together, autotools and CMake. The project is not a big project, but it may be easier to integrate with other tools/libs/CI as it migrates to CMake, which is being used by most new projects. I don't know if it will have a great benefit, but gets to be a way to do things i a new way that may incorporate some new tools and adds a new technology that is being largely used and with a vast community. 

> Is it possible to have both _autotools_ and _CMake_ at the same time? How many new files would be required - just a handful `CMakeLists.txt` files?

Yes, each pair of Makefile.am/configure.ac generates a Cmakelist.txt file.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman @adrienverge Your opinion about adding a `CMakeLists.txt` file to support building with _CMake_ in addition to _autotools_?

**Comment by mrbaseman** [comment]
Can we create the CMake input using autotools? I wouldn't want to maintain two separate sets of build systems.

**Comment by faustocarva** [comment]
> Can we create the CMake input using autotools? I wouldn't want to maintain two separate sets of build systems.

Probably yes, but the existence of two bulid systems, i think, would occur for a while. After CMake gets well tested in the project, and downstream get to know this new way of doing the build, there would be no need to maintain two build process.

**Comment by adrienverge** [comment]
I don't see a need to change. I'm not against it, but unless I miss something switching from autotools to CMake doesn't solve any existing problem.

**Comment by DimitriPapadopoulos** [comment]
No, it doesn't solve any technical problem, at least in the foreseeable future. On the contrary having both just adds complexity.

I just thought it might attract more contributors who prefer _CMake_.
