### ISSUE TITLE
Restrict SSL options/ciphers to secure defaults

### ISSUE THREAD

**Issue by martinetd** [adrienverge/openfortivpn#69]
Hi,

ssl_connect in tunnel.c[1] probably should probably be using
`SSL_CTX_set_options(tunnel->ssl_context, SSL_OP_NO_SSLv3 | SSL_OP_NO_COMPRESSION)`
("my" server already refuses SSLv3, wasn't able to check if it'd accept compression, but it's likely safer to disable anyway)

We also want to limit the cipher lists, the openssl wiki[2] gives
`SSL_set_cipher_list(tunnel->ssl_handle, "HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4")`

This one is pretty important given "my" server supports very weak ciphers like RC4-MD5 and RC4-SHA, so a man-in-the-middle could downgrade our cipher unless we're strict about it.

For reference, here is a full list of ciphers my server seems to support (obtained looping through available ciphers as described here[3]):
```
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Cipher    : ECDHE-RSA-AES256-SHA384
    Cipher    : ECDHE-RSA-AES256-SHA
    Cipher    : DHE-RSA-AES256-GCM-SHA384
    Cipher    : DHE-RSA-AES256-SHA256
    Cipher    : DHE-RSA-AES256-SHA
    Cipher    : DHE-RSA-CAMELLIA256-SHA
    Cipher    : AES256-GCM-SHA384
    Cipher    : AES256-SHA256
    Cipher    : AES256-SHA
    Cipher    : CAMELLIA256-SHA
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Cipher    : ECDHE-RSA-AES128-SHA256
    Cipher    : ECDHE-RSA-AES128-SHA
    Cipher    : DHE-RSA-AES128-GCM-SHA256
    Cipher    : DHE-RSA-AES128-SHA256
    Cipher    : DHE-RSA-AES128-SHA
    Cipher    : DHE-RSA-SEED-SHA
    Cipher    : DHE-RSA-CAMELLIA128-SHA
    Cipher    : AES128-GCM-SHA256
    Cipher    : AES128-SHA256
    Cipher    : AES128-SHA
    Cipher    : SEED-SHA
    Cipher    : CAMELLIA128-SHA
    Cipher    : ECDHE-RSA-RC4-SHA
    Cipher    : RC4-SHA
    Cipher    : RC4-MD5
    Cipher    : ECDHE-RSA-DES-CBC3-SHA
    Cipher    : EDH-RSA-DES-CBC3-SHA
    Cipher    : DES-CBC3-SHA
```

I'm not sure all servers are as up to date as mine so don't know what defaults are really safe, I'd say the example here is good enough, but haven't looked at openfortivpn's configuration to see if it'd be easy to make configurable :)

[1] https://github.com/adrienverge/openfortivpn/blob/master/src/tunnel.c#L323
[2] https://wiki.openssl.org/index.php/SSL/TLS_Client
[3] http://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers

**Comment by adrienverge** [comment]
Hey @martinetd,

This looks a very good idea! I will welcome any contribution towards this. (Unfortunately I don't have much time to do it myself, and I can't test my changes since I don't have access to a Fortinet VPN anymore).

The only requirement would be to add a `--ssl-unsecure` (or `--ssl-cipher-list "XYZ"`) option, for users that don't have a choice.

**Comment by martinetd** [comment]
I already kludged it locally for myself, will see about adding option/config later this week :)

**Comment by adrienverge** [comment]
Sounds great. Thanks!
