### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by MathyV** [adrienverge/openfortivpn#70]
Can you please tag a new release so I can use it to build a Gentoo package? The current one is quite old (and doesn't include the fix I need ;-))

**Comment by adrienverge** [comment]
Sure! v1.2.0 released :)

Feel free to update the README file once there is a Gentoo package (or send me an email so I can do it).

Thank you!

**Comment by MathyV** [comment]
I created a new pull request for the package:

https://github.com/gentoo/gentoo/pull/2424

Advanced Gentoo users know how to use it, others will have to learn or wait until the PR is approved ;-)

**Comment by MathyV** [comment]
@adrienverge it was merged in the main Portage tree so all users can now enjoy it.

**Comment by adrienverge** [comment]
Thanks @MathyV!

What command should Gentoo users run to install openfortivpn? `emerge openfortivpn`?

**Comment by MathyV** [comment]
@adrienverge yes, but currently it is marked as not stable, so they need to add the package to /etc/portage/package.accept_keywords (they'll know how to do it)

**Comment by adrienverge** [comment]
@MathyV thanks! I updated the README file.
