### ISSUE TITLE
Start VPN in network namespace (using vpnshift script)

### ISSUE THREAD

**Issue by tomatensaus** [adrienverge/openfortivpn#709]
I use openfortivpn to connect to my work vpn and it works great.

I wish to use the vpnshift script to start the vpn in a network namespace so that I can only tunnel a single application to the vpn while the rest of my desktop still uses the normal network connection.

I have made changes to the vpnshift script (attached) to run openfortivpn, I got as far as making it connect and then launching the application, but the application cannot connect to the network resources available on the VPN. 

I am not sure if this is a openfortivpn limitation or a limitation in the vpnshift script that I should change. 

To be honest I do not understand network namespaces well enough to be able to debug. Any help would be greatly appreciated.

**Comment by DimitriPapadopoulos** [comment]
I'm afraid  don't know of any `vpnshift` script. There are no attachments to GitHub issues.

**Comment by DimitriPapadopoulos** [comment]
Are you perhaps mistaking _openfortivpn_ for [_OpenVPN_](https://openvpn.net)?

**Comment by tomatensaus** [comment]
I am aware that openVPN can start in a network namespace so I am not confusing the 2. But I am most definitely using this openfortivpn.
Apologies I see that I cannot attach a shell script... let me rename to txt and attach again.

[vpnshift.sh.txt](https://github.com/adrienverge/openfortivpn/files/4615457/vpnshift.sh.txt)

**Comment by DimitriPapadopoulos** [comment]
But this `vpnshift.sh` script is not part of _openfortivpn_, is it? I have found one [written for _OpenVPN_](https://github.com/crasm/vpnshift.sh). Are you trying to adapt that script to _openfortivpn_? Just trying to understand the context here.

**Comment by DimitriPapadopoulos** [comment]
I think I get it now. You want to adapt [`vpnshift.sh`](https://github.com/crasm/vpnshift.sh), initially written for _OpenVPN_, to work with _openfortivpn_.

Note that _openfortivpn_ handles routing and name resolution changes internally by default. I think one of the issues you will have to solve is that routing and name resolution need to be adapted to namespaces. What you can do is ask _openfortivpn_ not to mess with routes and name resolution (`--no-routes` and `--no-dns`), let _pppd_ handle these (use `--pppd-use-peerdns`) and provide proper ip-up/ip-down scripts.

**Comment by tomatensaus** [comment]
Thank you for the input, yes I wish to adapt vpnshift, I have added the options you suggested
`	nsdo openfortivpn \
		-c "${config}" \
		--pppd-use-peerdns=1 \
		--set-routes=0 \
		--set-dns=0 &
`
Just trying to figure out what needs to go into the /etc/ppp/ip-up.d/ so that it works with the network namespaces

**Comment by nehaljwani** [comment]
I use openfortivpn inside a network namespace on my Linux box with this: https://gist.github.com/nehaljwani/0f63165bf842e22d8d9e80e05f1a53f1

To launch any application inside the network namespace, one can do:
```bash
sudo /usr/sbin/ip netns exec mycompanyvpn su $(id -un)
chromium --incognito
```
