### ISSUE TITLE
Feature request: Use macOS keychain for password

### ISSUE THREAD

**Issue by ikreb7** [adrienverge/openfortivpn#710]
Hello,

I would like it if we could store the password at the macOS keychain. Later I would have this feature also for the gnome keyring. If you are interested at this feature I would also offer my help.

Best regards
Robert

**Comment by DimitriPapadopoulos** [comment]
Most of use don't have a macOS system, but contributions are welcome.

Same for Gnome. Personally I'm not interested in the Gnome keyring: it has always been a source of nuisance for me because the keyring password is initialized to the same password as the account, but later on it is not modified (and cannot in some scenarios) when the account password is modified. That said if you're interested, contributions are welcome.

That said many FortiGate appliances operate with one-time passwords or tokens, a simple password is often not seen as secure enough.

**Comment by ikreb7** [comment]
Many universities use VPN with the student account, which is also used for mail and more.

**Comment by DimitriPapadopoulos** [comment]
Ah true, academic institutions often have a different approach to IT security.

**Comment by davidolrik** [comment]
This is already supported through the `--pinentry` option using `pinentry-mac`.

You can get `pinentry-mac` from brew.

**Comment by juhoautio** [comment]
@davidolrik thanks for that comment!

I put this in my conf file and it worked as expected:

```
pinentry = pinentry-mac
```

Would it be worth documenting this in the README?

**Comment by DimitriPapadopoulos** [comment]
@davidolrik I don't have a mac myself and cannot see for myself how this works, but it's great to have a nice solution such as this one, just re-using existing software. Thank you very much for pointing this out.

Just to clarify, can we close this issue? Does `pinentry-mac` indeed store the password in the macOS keychain in all cases?

@juhoautio  Note that the primary documentation is the **man page** - the README is a quick summary that cannot address all possibles cases. Also, I don't use `--pinentry` option and have no mac myself, but contributions to improve the man page are welcome.

**Comment by davidolrik** [comment]
`pinentry` was originally developed for GnuPG as a secure way to ask for a pin or passphrase in a secure way without storing it in temp files or similar.

The `pinentry` program is available for many platforms and in many different forms, both gui and cli =)

I would say yes, this issue can be closed. - It is better to have code like this in as few places as possible.

**Comment by DimitriPapadopoulos** [comment]
Thanks for the additional information. I needed confirmation that `pinentry` supports the macOS keychain as a secure way to store pin or passphrase, the answer is also in web pages such as this one:
[how2: Using GPG on macOS without GPGTools](https://dev.to/wes/how2-using-gpg-on-macos-without-gpgtools-428f)

> [...] and pinentry-mac which is the part of GPGTools that prompts for your key password and stores it on the OS keychain.

**Comment by juhoautio** [comment]
@DimitriPapadopoulos Thanks for the comment and bringing up the man page.

Currently it's not so easy to figure out that a secure way for storing the password exists at all, unless one finds this issue where it's discussed.

The README currently suggests creating a conf `/etc/openfortivpn/my-config` with `password = bar` ie. plain string. Man page does that too. It's easy to get an impression that plain text in conf file is the only way for storing a permanent password.

I wasn't familiar with pinentry before I read about it in this issue, and it didn't occur to me to search for the meaning of "pinentry program" based on the man page either. I would see value in modifying both the README & the man page to highlight that there's this secure option for storing a password.

I'm ok with making a pull request with concrete suggestions, if this sounds reasonable to you.

As a Mac user I would also appreciate this kind of info in the README:

> pinentry-mac which is the part of GPGTools that prompts for your key password and stores it on the OS keychain.

But again, I can definitely understand if you're not willing to include such platform specifics in project documentation – at least not the man page – but how about the README?

**Comment by DimitriPapadopoulos** [comment]
I have a few suggestions:
- Open an issue or suggest a pull request against [Homebrew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openfortivpn.rb) to specify `pinentry-mac` as an [optional or recommended dependency](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies).
- Add the missing documentation of `--pinentry` to the openfortivpn man page. The option is definitely missing. There is room for an explanation of benefits and a couple examples such as `pinentry-gnome3` on Linux and `pinentry-mac` on macOS.
- The README page should definitely refer to the man page as the primary source of documentation. Could you help with that?
- Still not sure about the README page. I don't want to augment the README with extra information - perhaps you could add a line `pinentry = pinentry-mac` to the sample config file to give a hint.

**Comment by juhoautio** [comment]
Ok, thanks! I will prepare a PR some time soon.

Just asking for one more clarification on this:

> perhaps you could add a line pinentry = pinentry-mac to the sample config file to give a hint

Do you mean the sample config that the man page shows, or maybe the sample config that's in the README? Correct me if I'm wrong, but I couldn't find any plain file with a sample config

**Comment by DimitriPapadopoulos** [comment]
Indeed, I was referring to the small samples in the README file, under [Examples](https://github.com/adrienverge/openfortivpn#examples). Perhaps you can add the suggested line as a hint in the _Using a config file_ example and then hope users will read the man page. Or maybe add a short additional example with a short explanation.

About modifying the README page:
1. We would like to keep the man page as the reference documentation, that's the way command lines have been traditionally documented in the Unix / macOS X world. However, I do acknowledge that many new users are not comfortable with man pages. An alternative would be to convert the man page to HTML (or Markdown or reST) and make it available on the web, for example in the wiki section of our GitHub project. Unfortunately it's not straightforward to convert an existing man page to HTML, see #770.
2. We wouldn't like the README to be obfuscated by details. Also, we do not have the resources to maintain detailed documentation in both documents, the README and the man page.
3. Now if you feel that the benefits of a short paragraph on `pinentry` in the README outweigh the violation of the above two rules, why not? However, my hope is that referring to the man page as the main source of information in the README will be sufficient.

**Comment by davidolrik** [comment]
I would suggest changing the documentation to encourage the use of `pinentry` instead of the very insecure methods currently being "advocated" simply by being displayed in the examples. (And if it were up to me I would remove the `-p` option completely)

**Comment by DimitriPapadopoulos** [comment]
We do need to show the simplest example possible too, although it's not perfect. Perhaps we can reorder the examples.

We also need to keep the simplest options too, including `-p`, at least for compatibility reasons. We do our best to keep it as much secure as possible, although it just occurred to me contribution #747 is incorrect or rather incomplete. One of the two processes still shows the password. Will have to look into it (#871).

**Comment by juhoautio** [comment]
> Open an issue or suggest a pull request against Homebrew to specify pinentry-mac as an optional or recommended dependency.

@DimitriPapadopoulos this I haven't done, and would not feel comfortable doing myself. I hope it's all right.

Otherwise I tried to address everything that you raised here in my PR.

**Comment by DimitriPapadopoulos** [comment]
The Homebrew dependencies seem to be build-time dependencies, not suggestions for run-time.
