### ISSUE TITLE
Overlay "config" file - MacOS

### ISSUE THREAD

**Issue by souwill** [adrienverge/openfortivpn#721]
Hello!

After a brew update my file "config" was overlaid. This always happens when I update the computer using homebrew.
Any justification?

_Previous Version: 1.13.0
Last Version: 1.14.0
MacOS Catalina 
Version: 10.15.4_

Regards!

**Comment by DimitriPapadopoulos** [comment]
I understand that the configuration file (can you give its complete path?) is overwritten whenever you update _openfortivpn_ with Homebrew. Is that correct? If so it is best raise the issue with the Homebrew packager:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/openfortivpn.rb

But then the Homebrew package makes straightforward use of the _openfortivpn_ process:
```
  def install
    system "./autogen.sh"
    system "./configure", "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make", "install"
```
This should:
1. install a **template** configuration file under `{prefix}/share/openfortivpn/config.template`,
2. overwrite `{prefix}/etc/openfortivpn/config` **only if** no such file is already installed:
   https://github.com/adrienverge/openfortivpn/blob/330d8be2d70dd0ca03b2564d0282995f158c1b1d/Makefile.am#L47-L52

**Comment by DimitriPapadopoulos** [comment]
Do you experience something that does not fit the above scenario?

**Comment by souwill** [comment]
I left a copy of the config file in a folder, and whenever I update it I overlay the file. Thanks for the feedback!

**Comment by DimitriPapadopoulos** [comment]
> I left a copy of the config file in a folder, and whenever I update it I overlay the file. Thanks for the feedback!

**Which** folder?

**Comment by souwill** [comment]
Local of file
/usr/local/Cellar/openfortivpn/1.14.0/etc/openfortivpn/config

/usr/local/Cellar/openfortivpn/1.14.0/etc/openfortivpn/
In this folder I create a file config.update configurated with host, port, username and password.
After update using homebrew I delete the file config and rename the config.update to config and is done login sucessfull!

Regards!

**Comment by DimitriPapadopoulos** [comment]
Thank you, that is indeed the config file installed by Homebrew as far as I can tell. I don't know how Homebrew operates. Specifically I don't know whether it builds software at installation time on the end-user machine or before-hand on a build server.

In any case this doesn't look like an issue with _openfortivpn_ itself but with the Homebrew package and should be reported to the _openfortivpn_ Homebrew packager:
https://github.com/Homebrew/homebrew-cask/issues/new/choose

**Comment by DimitriPapadopoulos** [comment]
Here is a piece advice on how to modify the Homebrew formula so that the config file is not overwritten by `brew upgrade`:
https://discourse.brew.sh/t/where-do-i-place-consistent-configuration-files-beginners-question/1250/2

You may add the link to the bug report.

**Comment by mrbaseman** [comment]
Homebrew downloads the sources and builds the executable on the target system before installing. 
IMO, files in "Cellar" are not supposed to be modified. I think you are supposed to change `/usr/local/etc/openfortivpn/config`

**Comment by DimitriPapadopoulos** [comment]
I've tried installing on macOS 10.11. As far as I can see _openfortivpn_ is built with `--prefix=/usr/local/Cellar/openfortivpn/1.14.1`:
```
==> Installing openfortivpn
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/openfortivpn/1.14.1
==> make install
🍺  /usr/local/Cellar/openfortivpn/1.14.1: 9 files, 165.2KB, built in 19 seconds
```
This means the config file ends up in `/usr/local/Cellar/openfortivpn/1.14.1/etc/openfortivpn/config`. Its location changes with each new version of _openfortivpn_. `/usr/local/etc/openfortivpn/config` is only a symlink:
```
$ ls -l /usr/local/etc/openfortivpn/config
lrwxr-xr-x  1 xxxxxxxx  xxxxx  56 May 27 19:33 /usr/local/etc/openfortivpn/config -> ../../Cellar/openfortivpn/1.14.1/etc/openfortivpn/config
$ 
```
This really is a problem with the Homebrew package and needs to be reported here:
https://github.com/Homebrew/homebrew-cask/issues/new/choose

**Comment by DimitriPapadopoulos** [comment]
@souwill Opened this issue for you:
https://github.com/Homebrew/homebrew-core/issues/55420
