### ISSUE TITLE
Could not authenticate to gateway. Please check the password, client certificate, etc.

### ISSUE THREAD

**Issue by filipehdbr** [adrienverge/openfortivpn#722]
I am getting a "Could not authenticate to gateway. Please check the password, client certificate, etc." error. Everything is correct and I can connect using the same credentials using openfortigui. I tried using both config file and directly from command line. Both throw the same error. Trusted-cert is right. Maybe because I use OTP?

**Comment by DimitriPapadopoulos** [comment]
This error really means the credentials used by `openfortivpn` are somehow incorrect.

Now why this happens, it's hard to tell without more information:
* Which command line options do you pass to `openfortivpn`?
* What about config files? Where is the default config file (typically `/etc/openfortivpn/config`) and what are its contents?

**Comment by filipehdbr** [comment]
Thanks for the prompt answer!

OS: Ubuntu 20.04 

If I go to openfortigui and use the same IP/Port/Login/Pass/Cert I can login just fine, that is what intrigues me. 

My config file:

> host = My_vpn_server_Ip
> port = 10443
> username = my_login
> password = my_pass
> set-routes = 0
> set-dns = 0
> pppd-use-peerdns = 0
> # X509 certificate sha256 sum, trust only this one!
> trusted-cert = my_cert

Command line:
filipe@filipe-HP-Spectre-x360-Convertible:~$ sudo openfortivpn IP_HERE:10443 -u my_login  --trusted-cert=my_cert
VPN account password: 
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
INFO:   Closed connection to gateway.
INFO:   Logged out.


I did ctrl+c on my password from this command line to openfortigui just to double check, and I can connect on openfortigui.

**Comment by filipehdbr** [comment]
Also trying from config file, but same error:
filipe@filipe-HP-Spectre-x360-Convertible:~/openfortigui/openfortigui$ sudo openfortivpn -c /etc/openfortivpn/my-config
[sudo] password for filipe: 
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
INFO:   Closed connection to gateway.
INFO:   Logged out.
filipe@filipe-HP-Spectre-x360-Convertible:~/openfortigui/openfortigui$

**Comment by DimitriPapadopoulos** [comment]
Strange. Which version of _openfortivpn_ is this? Have you built it yourself? The config file you've shown me is `/etc/openfortivpn/my-config`, isn't it? But the there must be a `/etc/openfortivpn/config` file, what are its contents?

The password is incorrect, we need to understand where it is read from.

**Comment by filipehdbr** [comment]
```
filipe@filipe-HP-Spectre-x360-Convertible:~/openfortigui/openfortigui$ openfortivpn --version
1.12.0
filipe@filipe-HP-Spectre-x360-Convertible:~/openfortigui/openfortigui$ 

```

```
filipe@filipe-HP-Spectre-x360-Convertible:~/openfortigui/openfortigui$ cat /etc/openfortivpn/config 
# ### config file for openfortivpn, see man openfortivpn(1) ###
# 
# host = vpn.example.org
# port = 443
# username = vpnuser
# password = VPNpassw0rd
filipe@filipe-HP-Spectre-x360-Convertible:~/openfortigui/openfortigui$ 


```


Yes, the config file shown to you is at /etc/openfortivpn/my-config and I am invoking it when trying to connect as I posted above

**Comment by filipehdbr** [comment]
I didnt build myself. I installed from apt

**Comment by filipehdbr** [comment]
My password starts with # and has special characters like %, $ and (

Maybe a bug when parsing it?

**Comment by DimitriPapadopoulos** [comment]
Perhaps an issue with passwords containing **`#`** because **`#`** starts a comment in the config file? But then that would affect only the case where you use a config file.

Perhaps a problem with **`%`** which is a special character in URLs? But then the problem would affect _openfortigui_ too. Since _openfortigui_ runs _openfortivpn_, I doubt the problem is very deep in the code, it  has to be in the way login or password are read and passed to the the same C routines used by _openfortigui_.

Do you have non-ASCII characters in your password?

Also I understand the version of _openfortivpn_ you're using is 1.12.0. Have you installed _fortigui_ with `apt` too? Which version?

**Comment by filipehdbr** [comment]
I am using openFortiGUI 0.9.0. Downloaded the package directly from their site. I don't have non-ASCII characters on my password. I will change it and see if it makes any difference and comment back here

**Comment by filipehdbr** [comment]
Ok I changed my password and used no special characters. It worked! Let me know if I can be useful debugging it somehow. Thanks!

**Comment by DimitriPapadopoulos** [comment]
Ah, if you do have the possibility to change the password, that's very helpful! Can you remove special characters one by one until it works, so that we can identify which character is the culprit?

**Comment by DimitriPapadopoulos** [comment]
Note that different characters might be a problem when reading the confg file and when prompting the user.

I haven't found any difference between the _openfortigui_ code and the _openfortivpn_ code so far that could explain this issue.

**Comment by filipehdbr** [comment]
For some reason it is just working fine.

0. Changed password to AbcAbc1234. Connected just fine.
1. Removed # from the password. Connected just fine
2. Changed password to #abc1234. Connected just fine
3.  Changed password back to my old password. Connected just fine.

I dont really understand. I never typed the password, only ctrl+v'ing. 

All good anyways, thanks for your attention

**Comment by DimitriPapadopoulos** [comment]
Then it might an issue with special characters in the copy/paste infrastructure.
You can use `xclipboard` or similar tools to investigate the contents of the clipboard.
