### ISSUE TITLE
FortiOS 5.0 and DH small keys

### ISSUE THREAD

**Issue by juan-rey** [adrienverge/openfortivpn#725]
While connecting to an old device with FortiOS 5.0, I get this error:

**ERROR:  SSL_connect: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small**

And connection is closed. I suppose it is because Diffie-Hellman key exchange size (1024) is insecure.

As a workaround if I set --cipher-list to  'DEFAULT:!DH' (or 'AES256-GCM-SHA384' or ... ) and It successfully connects.

As long as it can use safe TLS v1.2 cipher suites. **Should openfortivpn deal with it ?** (as official forticlient does)

May I hep to implement it?

**Comment by juan-rey** [comment]
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 1024) - A
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (dh 1024) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (rsa 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 1024) - A
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (dh 1024) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (rsa 2048) - A
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (dh 1024) - D
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|       Key exchange (dh 1024) of lower strength than certificate key
|       Weak certificate signature: SHA1
|   TLSv1.2: 
|     ciphers: 
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 1024) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 1024) - A
|       TLS_DHE_RSA_WITH_AES_256_CBC_SHA (dh 1024) - A
|       TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA (dh 1024) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (rsa 2048) - A
|       TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 1024) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 1024) - A
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 1024) - A
|       TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA (dh 1024) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (rsa 2048) - A
|       TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (dh 1024) - D
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|       Key exchange (dh 1024) of lower strength than certificate key
|       Weak certificate signature: SHA1
|_  least strength: D

**Comment by DimitriPapadopoulos** [comment]
Which version of _openfortivpn_ is this exactly, on which Linux distribution?
Doesn't option `-seclevel-1` help?

**Comment by juan-rey** [comment]
Ubuntu 20.04
openfortivpn 1.10.0/1.12.0/1.13.3/1.14.0

--seclevel-1 worked but, as far as I know, it is less secure workaround

**Comment by DimitriPapadopoulos** [comment]
What is not secure is the VPN gateway itself. Whatever workaround you choose cannot change the characteristics of the VPN gateway.

The problem here is that Ubuntu 20.04 changed the default security level from 1 to 2 against the recommendation of the OpenSSL documentation. This breaks communications with TLS servers that are unable to negotiate a protocol compatible with security level 2, like your VPN gateway. In such a case, it's only natural to revert to security level 1.

Am I missing anything?

**Comment by DimitriPapadopoulos** [comment]
> (as official forticlient does)

Actually what does FortiClient do exactly? I know it embarks or used to embark its own version of OpenSSL instead of linking to the system OpenSSL library dynamically like _openfortivpn_ does. See for example:
* [FortiClient 5.2.3 Administration Guide](https://pub.kb.fortinet.com/ksmcontent/Fortinet-Public/current/FortiClient_5_2/forticlient-admin-52-windows.pdf)
  > #### OpenSSL Library
  > The OpenSSL library has been updated to the latest version 1.0.1k.
* [FortiClient (MacOSX) - ReleaseNotes VERSION 5.2.4](https://pub.kb.fortinet.com/ksmcontent/Fortinet-Public/current/FortiClient_5_2/forticlient-5.2.4-os-x-release-notes.pdf)
  > #### OpenSSL Library
  > The OpenSSL Library has been updated to the latest version 1.0.2d.

I suspect the security level has been kept to its default value of 1. Perhaps FortiClient does more, but I'm not aware of such additional actions. Do you have evidence that FortiClient chooses different ciphers for example?

**Comment by juan-rey** [comment]
Thanks Dimitry,

Setting --cipher-list to 'DEFAULT:!DH' (or 'AES256-GCM-SHA384' ) works for me, without --seclevel-1

Since i.e. AES256-GCM-SHA384  => TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) would fit in OpenSSL Level 2, that is why I though my workaround was safer. Maybe I am wrong

**OpenSSL**
**Level 1** :  The security level corresponds to a minimum of 80 bits of security. Any parameters offering below 80 bits of security are excluded. As a result RSA, DSA and DH keys shorter than 1024 bits and ECC keys shorter than 160 bits are prohibited. All export cipher suites are prohibited since they all offer less than 80 bits of security. SSL version 2 is prohibited. Any cipher suite using MD5 for the MAC is also prohibited.
**Level 2** : Security level set to 112 bits of security. As a result RSA, DSA and DH keys shorter than 2048 bits and ECC keys shorter than 224 bits are prohibited. In addition to the level 1 exclusions any cipher suite using RC4 is also prohibited. SSL version 3 is also not allowed. Compression is disabled.

**Comment by juan-rey** [comment]
Windows FortiClient VPN 6.4.0 uses 'OpenSSL (c) 1998-2018'. But I am not sure with what cipher  suite it uses in my case.

(If I had time I could use wireshark to find out it)

**Comment by DimitriPapadopoulos** [comment]
I'm interested in a comparison with FortiCliient because I suspect `openfortivpn --seclevel-1` does not negotiate differently from FortiClient. If it is does negotiate differently than FortiClient, I'm happy to try to fix _openfortivpn_. If t is does not, it is quite possible to choose a different cipher using `--cipher-list` if you want to - but I would argue the VPN gateway needs to be fixed, not the client.

I think you can find the cipher in the logs, without running wireshark. I'll give it a try myself.

**Comment by DimitriPapadopoulos** [comment]
On Ubuntu 20.04, I have found _openfortivpn_ uses `TLS_AES_256_GCM_SHA384` whether I pass `--seclevel-1` or not with FortiOS 6.00.9.0335 or 6.02.3.1066 at the other end. I'm not sure about _FortiClient_ as I wasn't able to find the cipher in the logs and have had no time to run wireshark.

I don't have access to a FortiOS 5.0 VPN appliance to test. That said gateways with FortiOS 5.0 or 5.2 are probably obsolete and vulnerable - I don't think FortiOS 5.0 and 5.2 are maintained anymore. With known vulnerabilities and ongoing attacks, perhaps it's best to focus on the VPN gateway if you're interested in security:
* [VPN users: If you're on Fortinet, Palo Alto, Pulse Secure, patch now, warns spy agency](https://www.zdnet.com/article/vpn-users-if-youre-on-fortinet-palo-alto-pulse-secure-patch-now-warns-spy-agency/)
* [Hackers Hit Unpatched Pulse Secure and Fortinet SSL VPNs](https://www.bankinfosecurity.com/hackers-hit-unpatched-pulse-secure-fortinet-ssl-vpns-a-12958)

**Comment by DimitriPapadopoulos** [comment]
On Ubuntu 20.04, FortiClient SSLVPN 4.4.2335  uses `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`, but then that's an old version of FortiClient that does not support TLS 1.3 - unlike _openfortiivpn_. Without access to a recent version of FortiClient or to a FortiOS 5.0 gateway, it's hard to tell how _openfortivpn_ should behave.

**Comment by DimitriPapadopoulos** [comment]
I've tried _FortiClient_ 6.4.0.0851. As far as I can see it ships with OpenSSL 1.1.0. The VPN client suggests 31 ciphers to the VPN server:
```
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
.
.
.
```
and the VPN server picks this one:
```
TLS_AES_256_GCM_SHA384
```

**Comment by DimitriPapadopoulos** [comment]
I've also tried _openfortivpn_ on the same Ubuntu 18.04 linked to the system OpenSSL library. It suggests 59 ciphers to the VPN server, including the ones sent by _FortiClient_:
```
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
.
.
.
```
and again the VPN server picks:
```
TLS_AES_256_GCM_SHA384
```

**Comment by DimitriPapadopoulos** [comment]
It would be great to have a similar comparison against an obsolete VPN server running _FortiOS_ 5.0, with a complete list of ciphers suggested by a recent _FortiClient_ and _openfortivpn_, and the cipher picked by the VPN server in either case.

**Comment by yeya** [comment]
> Which version of _openfortivpn_ is this exactly, on which Linux distribution?
> Doesn't option `-seclevel-1` help?

--seclevel-1 works great! How do I put it in config file instead the command line?

**Comment by DimitriPapadopoulos** [comment]
See man file:
```
seclevel-1 = 1
```

**Comment by DimitriPapadopoulos** [comment]
Closing this unless we have a comparison with _FortiClient_ against _FortiOS_ 5.0?
