### ISSUE TITLE
server pushes route to itself

### ISSUE THREAD

**Issue by pierremarc** [adrienverge/openfortivpn#729]
Symptoms of this were that the connection would proceed succesfuly but nothing would go through and the pppd would terminate the connection.

The following hack fixed it
```diff
diff --git a/src/ipv4.c b/src/ipv4.c
index 91ff763..7d937c6 100644
--- a/src/ipv4.c
+++ b/src/ipv4.c
@@ -893,6 +893,13 @@ static int ipv4_set_split_routes(struct tunnel *tunnel)
                int ret;
 
                route = &tunnel->ipv4.split_rt[i];
+               // check if the route to be added is not the one to the gateway itself
+               if (route_dest(route).s_addr == route_dest(&tunnel->ipv4.gtw_rt).s_addr)
+               {
+                       log_debug("Skipping route to tunnel gateway (%s).\n",
+                                        ipv4_show_route(route));
+                       continue;
+               }       
                free(route_iface(route));
                route_iface(route) = strdup(tunnel->ppp_iface);
                if (!route_iface(route))
```

I've got no time to make a proper merge request, sorry for this, just hope it will help.

**Comment by DimitriPapadopoulos** [comment]
I'll leave this to @mrbaseman who understands routing much better than me.

In the meantime, please bear with me as I don't understand these issues well, but could it be that the the VPN getaway does not send correct information in this specific case? Is this an issue specific to version 1.14? Just trying to understand why this hadn't been reported so far.

**Comment by mrbaseman** [comment]
If the Fortigate pushes a route to its own public IP through the tunnel I'd consider this a mis-configuration which normally shouldn't happen. Anyhow, the proposed patch makes sense to avoid that such a route is added by openfortivpn. I'll prepare a PR for that.
