### ISSUE TITLE
Issues connecting from Catalina

### ISSUE THREAD

**Issue by huangtinglin** [adrienverge/openfortivpn#736]
Hello.
I wanna use openfortivpn to connect my campus server. But it doesn't work. The command I use is
`sudo openfortivpn address:443 --username=username`.

Here is the command output:
```
VPN account password:
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
...
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
INFO:   Cancelling threads...
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
```
It outputs 'WARN:   read returned 0' until I type in CTRL+C. My MacOS: 10.15.5
I haven't find anything similar on the other reported issues.
Thanks!

**Comment by DimitriPapadopoulos** [comment]
I don't know either, it's first time I see this. Perhaps some special configuration on your machine. It may help if you could send the (**sanitized**) output of `openfortivpn -v`.

Also this looks suspect although I don't have much experience with macOS:
```
ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
```
This should help you find the version of `pppd`:
```
strings /usr/sbin/pppd | grep ppp-
```

How did you install _openfortivpn_?

**Comment by huangtinglin** [comment]
> I don't know either, it's first time I see this. Perhaps some special configuration on your machine. It may help if you could send the (**sanitized**) output of `openfortivpn -v`.
> 
> Also this looks suspect although I don't have much experience with macOS:
> 
> ```
> ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
> ```
> 
> This should help you find the version of `pppd`:
> 
> ```
> strings /usr/sbin/pppd | grep ppp-
> ```
> 
> How did you install _openfortivpn_?

Thanks for replying!
I install openfortivpn by:
` brew install openfortivpn`

The output of  'sudo openfortivpn -v address:443 --username=username.' :
> DEBUG:  Config host = address
DEBUG:  Config realm = ""
DEBUG:  Config port = "443"
DEBUG:  Config username = "<username>"
DEBUG:  Config password = "********"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: 137.132.84.34
DEBUG:  server_port: 443
DEBUG:  gateway_addr: 137.132.84.34
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=sAR7GghSKDGX6I0rd7ctUmSyq8b2G8H2+nM0daPGt+2W+U5aLQ1LT/xfwz4A9rXuCr1kEazk37b1UmFKbTC/brxZgG0NHQ5gLUGtrdcbhiZulwlbKWEUGwWe3MBttmSA+7I7L1iKoeePizaWZnsvTkjB94Oqx+pcqWSvTrDGLGv8rvYOhZkP4bpNM0Xf9zVJon5lUG1KAPbZ+nlBFji1v1Ue1t8DdjJlOoxf2YldL9O+iGXSk/WOoZYL8vvPIJQC9mcUK5DhGeVIfaC4Ka3TBw==
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=sAR7GghSKDGX6I0rd7ctUmSyq8b2G8H2+nM0daPGt+2W+U5aLQ1LT/xfwz4A9rXuCr1kEazk37b1UmFKbTC/brxZgG0NHQ5gLUGtrdcbhiZulwlbKWEUGwWe3MBttmSA+7I7L1iKoeePizaWZnsvTkjB94Oqx+pcqWSvTrDGLGv8rvYOhZkP4bpNM0Xf9zVJon5lUG1KAPbZ+nlBFji1v1Ue1t8DdjJlOoxf2YldL9O+iGXSk/WOoZYL8vvPIJQC9mcUK5DhGeVIfaC4Ka3TBw==
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: 137.132.84.34
DEBUG:  server_port: 443
DEBUG:  gateway_addr: 137.132.84.34
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
DEBUG:  Retrieving configuration
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
...
WARN:   read returned 0
CWARN:   read returned 0
INFO:   Cancelling threads...
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
WARN:   read returned 0
DEBUG:  Got Address: 0.0.0.0
DEBUG:  if_config: not ready yet...
DEBUG:  disconnecting
DEBUG:  Waiting for pppd to exit...
DEBUG:  waitpid: pppd exit status code 2
ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  server_addr: 137.132.84.34
DEBUG:  server_port: 443
DEBUG:  gateway_addr: 137.132.84.34
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.

And the version of pppd is:
`ppp-862.120.2`

**Comment by DimitriPapadopoulos** [comment]
This is currently the most recent version of ppp:
https://opensource.apple.com/source/ppp/
I don't think we have ever tested it but I wouldn't expect major changes compared to other versions we have tested. And I think other users have successfully connected to a VPN from Catalina 10.15.5. I'm afraid I cannot explain the exist status 2 returned by pppd, which according to the pppd man page translates to:
```
ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
```

By the way, does the VPN gateway you're attempting to connect to support VPN SSL - or only IPSec? Are other users able to connect to this VPN gateway  from Linux for example? It might be that VPN SSL is **not** supported. On the other hand I think I have seen other users referring to (successful ?) connections to NUS Computing.

**Comment by huangtinglin** [comment]
> This is currently the most recent version of ppp:
> https://opensource.apple.com/source/ppp/
> I don't think we have ever tested it but I wouldn't expect major changes compared to other versions we have tested. And I think other users have successfully connected to a VPN from Catalina 10.15.5. I'm afraid I cannot explain the exist status 2 returned by pppd, which according to the pppd man page translates to:
> 
> ```
> ERROR:  pppd: An error was detected in processing the options given, such as two mutually exclusive options being used.
> ```
> 
> By the way, does the VPN gateway you're attempting to connect to support VPN SSL - or only IPSec? Are other users able to connect to this VPN gateway from Linux for example? It might be that VPN SSL is **not** supported. On the other hand I think I have seen other users referring to (successful ?) connections to NUS Computing.

Actually, a official way to connect to NUS Computing is using FortiClient SSL-VPN, and I have seen  some of my classmates connect to campus server successfully. Unfortunately, every time when  I try to connect by FortiClient, it always fails (so I try to use openfortivpn) with the output: 
'Can not connect to VPN server.'

Thanks!

**Comment by DimitriPapadopoulos** [comment]
FortiClient fails to connect too, it's a problem with the computer. Somehow the computer prevents communication through the PPP tunnel. Have you set up a firewall? Try stopping it. Have you installed antivirus software that manages the firewall? Remove it.

Since you have access to FortiClient and it fails, you need to talk to NUS IT support.They will escalate to Fortinet if needed. I can't possibly spend time helping people to run FortiClient.

**Comment by huangtinglin** [comment]
> Since you have access to FortiClient and it fails, you need to talk to NUS IT support.They will escalate to Fortinet if needed. I can't possibly spend time helping people to run FortiClient.

Thanks.
