### ISSUE TITLE
howto install openfortivpn in a router-like machine, and share the VPN to other devices?

### ISSUE THREAD

**Issue by abubelinha** [adrienverge/openfortivpn#737]
Sorry I am not very tech-savy, but I am wondering if this idea is somehow possible.

I come from this scenario: I need to connect to a Fortinet VPN from my old Windows machine, and the Fortinet propietary free version client just [doesn't work for me](https://github.com/adrienverge/openfortivpn/issues/169#issuecomment-644689449). 

So the enterprise recommends to use openfortivpn to enter the VPN, but [there is not a Windows version](https://github.com/adrienverge/openfortivpn/issues/169).

I wonder if I could use a sort of dedicated Linux machine (a [raspberry pi](https://rutten.me/2018/08/01/project-pifi-raspberripi-as-travel-router/), an old pc, a [regular router](https://www.linksys.com/us/r/what-is-a-wifi-access-point/vpn-router/) ...) and then (1) install an openfortivpn client on that machine, (2) connect it to the VPN using ethernet cable or wifi dongle, and (3) share that VPN connection to other machines (like my Windows) using the integrated wifi or another ethernet card in the Linux box.

I have seen some examples of this, but with other VPN clients:
https://www.makeuseof.com/tag/raspberry-pi-vpn-travel-router/

Could you share experiences/recommendations/links about using openfortivpn for this purpose?

Thanks a lot in advance

**Comment by mrbaseman** [comment]
I know that openfortivpn is used on openwrt (this is mentioned e.g. in #80). Maybe there are pre-built packages available... Also on a Raspberry Pi it's used (e.g. #426). 

Basically, you can build it from source on a linux-like platforms or Mac OSX or FreeBSD. If your router OS meets the requirements (e.g. pppd is available), you can cross-compile it. Cross-compiling should also work on Windows with MinGW for instance, provided that you have the necessary sources available there.

One problem with the vpn on a router might be that the vpn connections usually have connection timeout and you would have to set up a mechanism to reconnect (periodically, or somehow each time when a connection is needed). If there is 2 factor authentication or a one time password, this becomes difficult.

**Comment by mrbaseman** [comment]
there are packages for [raspbian](http://raspbian.raspberrypi.org/raspbian/pool/main/o/openfortivpn/) and [openwrt](https://github.com/openwrt/packages/tree/master/net/openfortivpn)

**Comment by abubelinha** [comment]
Thanks a lot for the links @mrbaseman , I'll take a look
