### ISSUE TITLE
support for 2-factor authentication

### ISSUE THREAD

**Issue by red667** [adrienverge/openfortivpn#74]
Is there support for 2-factor authentication? I would need that to follow company policies.

**Comment by mrbaseman** [comment]
Yes, fortitokes are supported which exist as hardware tokens or as mobile app (which basically is the same thing in software on a separate device). 
Also user-certificates for authentication are supported where the private key may be password protected as well.
Just for fun I have recently combined everything (user/password+certificate with password protected key+mobile token) - but then you have to be quick in typing in the passwords while the token is still valid ;-)
Ah, and I forgot to mention the token sent by email/sms, which suffers from a similar problem that the code must arrive before it has already expired ;-)

**Comment by mrbaseman** [comment]
I wasn't aware that hardware tokens were handled differently on the server side. 
A patch to support them has been landed recently (#84).
