### ISSUE TITLE
I request a flatpak of Openfortivpn 

### ISSUE THREAD

**Issue by bilufe** [adrienverge/openfortivpn#742]
I use the Endless OS and it only support flatpak applications.
I request a flatpak of Openfortivpn!

**Comment by DimitriPapadopoulos** [comment]
I've given Snapcraft a try and it's quite complicated to create an _opnenfortivpn_ snap. I probably won't be able to achieve a working snap soon:
https://snapcraft.io/openfortivpn
I suspect the same issues will arise with Flatpak. Given the nature of _openfortivpn_, I believe it's much better to integrate it to the OS.

Also [Flathub is primarily focused on graphical desktop applications and not CLI/TUI applications](https://github.com/flathub/flathub/wiki/App-Requirements#desktop-integration). Does it make sense to create a flatpak if it cannot be uploaded to Flathub?

Finally we probably won't host the flatpak here, as the snap elsewhere too:
https://github.com/openfortivpn/snap

You're free to give this a try, just be warned it will probably require weeks of work. If you get it to work I'm happy to host the result in a repository under https://github.com/openfortivpn.
