### ISSUE TITLE
Cannot connect  - Method not allowed - OTP]

### ISSUE THREAD

**Issue by phpwutz** [adrienverge/openfortivpn#743]
So I run openfortivpn from command line with -vvv using config file for user/pasword/trusted-cert, it asks me for the OTP, I enter and then I get this error.

Am I holding it wrong?

```
DEBUG:  http_send:
POST /remote/logincheck HTTP/1.1
Host: ****:443
User-Agent: Mozilla/5.0 SV1
Accept: */*
Accept-Encoding: gzip, deflate, br
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate
If-Modified-Since: Sat, 1 Jan 2000 00:00:00 GMT
Content-Type: application/x-www-form-urlencoded
Cookie:
Content-Length: 85

magic=****&username=***&reqid=****&grpid=***&credential=****
DEBUG:  http_receive:
HTTP/1.1 405 Method Not Allowed
Date: Wed, 08 Jul 2020 17:18:42 GMT
Server: xxxxxxxx-xxxxx
Set-Cookie:  SVPNCOOKIE=; path=/; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly;
Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=Sun, 11 Mar 1984 12:00:00 GMT; secure; httponly
Transfer-Encoding: chunked
Content-Type: text/html
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'; object-src 'none'; script-src 'self' https 'unsafe-eval' 'unsafe-inline';
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
```

I tried the same credentials using the original forticlient on windows - which works.

Thx for your response

**Comment by DimitriPapadopoulos** [comment]
Looks like a password error somewhere. That said:
* How do you call _openfortivpn_? It asks for an OTP but as far as I can understand OTP is not configured in the config file, which contains a password instead ("using config file for user/pasword/trusted-cert"). Please also clarify whether you should use an OTP or a password.
* Which version of _openforitvpn_ is this, on which platform?
* Do you connect from Windows using VPN IPSec? On Linux _FortiClient_ and _openfortivpn_ do not support VPN IPSec, only VPN SSL. Is VPN SSL enabled on the FortiGate?

**Comment by phpwutz** [comment]
Hi Dimitri!
Thanks for your quick response, I'll try to clarify:

openfortivpn version: current git master (cloned ~1h ago), built and run on arch linux
call method:
I have the config file with the keys "host", "port", "username", "password" and "trusted-cert"
So the expected Auth flow would be "call openfortivpn" => "password is read from config file" => "OTP is requested  by openfortivpn in command line" => "i enter the OTP" => success
Regarding **Please also clarify whether you should use an OTP or a password.** : I expect to use BOTH the password and the OTP, because this is what I also do in the native forticlient on windows.

_Do you connect from Windows using VPN IPSec? On Linux FortiClient and openfortivpn do not support VPN IPSec, only VPN SSL. Is VPN SSL enabled on the FortiGate?_
Ooooh that might actually be the problem here. On Windows, I never made a  conscious choice about IPSec or SSL, I guess the forticlient just picked one? It seems that  VPN SSL is not active on the FortiGate, so probably that's the issue.

Thanks for pointing me in the right direction!
