### ISSUE TITLE
pinentry protocol parsing problem (OTP input problem when using NetworkManager)

### ISSUE THREAD

**Issue by jonas-koeritz** [adrienverge/openfortivpn#744]
I've debugged my NetworkManager-fortisslvpn problems when using the OTP option to login.
The pinentry program is expected to send the OTP in the format `D 123456\n` to the openfortivpn instance that called it. The NetworkManager plugin adds an additional `OK\n` to the response, indicating success.
I could not find any documentation on the pinentry protocol to determine wether this side or the NetworkManager side is wrong on this but the resulting OTP contains a `%0AOK` and is rejected by the gateway, preventing a successful login.
To fix this issue openfortivpn should drop the `OK` from the input or parse lines individually, the `D 123456\nOK\n` seems to be so short, and ends with `\n`, that it is treated as a single line by the current parsing code.

See also NetworkManager-fortisslvpn issue: https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/28

**Comment by DimitriPapadopoulos** [comment]
Thank you for the report Jonas. Just to make sure I understand:
* In https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/28 you write:
"It works flawlessly with the same gateway and configuration when using openfortivpn to connect manually."
* Here you say that's an _openfortivpn_ issue.

I'm happy to have a look at this issue if needed, but could you clarify the above first? I t looks like _openfortivpn_ might already be taking "OK" into account:
https://github.com/adrienverge/openfortivpn/blob/713c836/src/userinput.c#L134-L142

**Comment by jonas-koeritz** [comment]
My problem is that I couldn't find a formal definition of the protocol in use. openfortivpn could be more tolerant in parsing the line sent by the plugin or the plugin could send a modified line. Any of those changes would fix the problem.

**Comment by jonas-koeritz** [comment]
> Thank you for the report Jonas. Just to make sure I understand:
> 
> * In https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/28 you write:
>   "It works flawlessly with the same gateway and configuration when using openfortivpn to connect manually."
> * Here you say that's an _openfortivpn_ issue.
> 
> I'm happy to have a look at this issue if needed, but could you clarify the above first? I t looks like _openfortivpn_ might already be taking "OK" into account:
> https://github.com/adrienverge/openfortivpn/blob/713c836/src/userinput.c#L134-L142

It does take OK into account, but only if sent as a separate message, the line break between the OTP token and the OK is not honored by openfortivpn.

**Comment by DimitriPapadopoulos** [comment]
I have read the comments in https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/28 and I'm not certain this is an _openfortivpn_ isee, although I must confess  I don't know much about this part of the code.

As far as I can see, here is the documentation for the pinentry protocol:
https://git.gnupg.org/cgi-bin/gitweb.cgi?p=pinentry.git;a=blob;f=doc/pinentry.texi
It would be worth adding a few prints in _openfortivpn_ to investigate where the error occurs.
