### ISSUE TITLE
Could not authenticate to gateway (SSL error)

### ISSUE THREAD

**Issue by IvanPavlove** [adrienverge/openfortivpn#749]
```
$ sudo openfortivpn *************:10443 -u ++++++++ -p ++++++++ --trusted-cert ************************************* -v
WARN:   You should not pass the password on the command line. Type it interactively or use a config file instead.
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "*************"
DEBUG:  Config realm = ""
DEBUG:  Config port = "10443"
DEBUG:  Config username = "++++++++++++"
DEBUG:  Config password = "********"
DEBUG:  server_addr: ***************
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: ************
DEBUG:  gateway_port: 10443
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Error reading from SSL connection (Connection closed).
DEBUG:  server_addr: ******************
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: **************
DEBUG:  gateway_port: 10443
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Error reading from SSL connection (Connection closed).
WARN:   Error issuing /remote/logincheck request
ERROR:  Could not authenticate to gateway (SSL error).
INFO:   Closed connection to gateway.
DEBUG:  server_addr: ******************
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: ****************
DEBUG:  gateway_port: 10443
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Error reading from SSL connection (Connection closed).
DEBUG:  server_addr: ****************
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: ****************
DEBUG:  gateway_port: 10443
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Error reading from SSL connection (Connection closed).
WARN:   Error issuing /remote/logout request
INFO:   Logged out.
```

openfortivpn version 1.6.0 at Ubuntu 18.04.4 LTS.
Thank you
Ivan

**Comment by DimitriPapadopoulos** [comment]
This looks like a password error. Or maybe the FortiGate appliance you are connecting to does not support VPN SSL, only VPN IPSec. On Windows _FortiClient_ uses primarily VPN IPSec, but on Linux _FortiClient_ and _openfortivpn_ use VPN SSL only.

If the above do not apply in your case, could you try a more recent version of _openfortivpn_? You probably need to build from sources.

**Comment by IvanPavlove** [comment]
Hi,
Thank you for your response. I'll try to build the latest version. The password is OK because the same works in Windows where I'm using **Forcepoint VNP client 6.7**. There is an @ in my password so I also tried it from the config file and also with single and double-quotes. 
I think it's using VPN SSH because I've found the configuration xml in Windows and it has a section:
<ssl-tunnel> with IP and port which is the only parameters for this VPN setup (except of username and password of course). 
there are also multiple sections as: 
<ca file="ipsecca201909260857119901463297538.ca" flags="no-crl">MIIDDjCCAfagAwI.......</ca>
where base64 strings in each look very similar but are not 100% the same.
I have to mention that there's a two-phase authentication configured. When the connection is established I receive the request into the MS Authenticator installed on my mobile which I have to approve. But this is independent I think, and completely within the VPN server responsibility.
I'm running Windows in VirtualBox because of that but I would prefer the have this VPN working at Linux. This client is also available for Mac and Android but not for Linux.

**Comment by IvanPavlove** [comment]
adding sample xml section mentioned above because it was escaped 
section with SSH:
`<ssl-tunnel  name="**********_-_Primary">
         <ssl-peer id="*************" id-type="ip" port="10443">**************</ssl-peer>`
section with ca-file which maybe looks like IPSEc.
`<ca file="ipsecca201909260857119901463297538.ca" flags="no-crl">MIIDDjCCAfagAwI...</ca>`

How can I know if it's IPSec or SSH-based?
Thank you

**Comment by DimitriPapadopoulos** [comment]
I have no clue, I don't know the format of this XML file. Perhaps it shows in the user interface of _FortiClient_. It does look like VPN SSL is supported because of `ssl-tunnel`.

Perhaps it's related to the two-phase authentication. We haven't ever tested it as far as i know.

In any case it would help if you could build and try the latest version.

_FortiClient_ is available for Linux, but not freely available to download - like the Windows and macOS versions. You'd have to ask your IT team.

**Comment by DimitriPapadopoulos** [comment]
@IvanPavlove Any luck building the latest version?

**Comment by IvanPavlove** [comment]
Hi Dimitri,
I've found I can still access the services I need via SSH tunnel. In a higher environment, this option won't be available and then I'll come back to VPN access again. 

Thank you very much for your interest. I'll come back for sure later.

Ivan
