### ISSUE TITLE
configure option --sysconfdir is not honored during runtime

### ISSUE THREAD

**Issue by mrbaseman** [adrienverge/openfortivpn#75]
the configure option --sysconfdir is honored during installation and the config file is correctly placed there. However, when running openfortivpn without command line options it searches the config in the hard coded place /etc/openfortivpn/config, even when --prefix or --sysconfdir at configure time points somewhere else. This could be improved by passing sysconfdir somehow as a macro to the preprocessor. I have been playing around for a while with autoconf, but didn't find a robust solution, yet.

**Comment by adrienverge** [comment]
@mrbaseman Thanks for pointing this problem out. I'm open to contributions towards this.

**Comment by mrbaseman** [comment]
the pull request has been merged, thank you. Closing this issue.
