### ISSUE TITLE
Segfault on Mint 20 (and probabily on latest Ubuntu)

### ISSUE THREAD

**Issue by michelep** [adrienverge/openfortivpn#750]
I've been using OpenFortiClient for months without any problem. After upgrading to Mint 20, i got a segfault while connecting:

```
openfortigui[5420]: segfault at 80 ip 00007f9ae2e145a4 sp 00007ffe02915db8 error 4 in libQt5Core.so.5.12.8[7f9ae2cea000+2e0000]
Code: 48 89 0f 8b 11 83 c2 01 83 fa 01 77 09 c3 0f 1f 84 00 00 00 00 00 f0 83 01 01 c3 90 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa <48> 8b 0e 48 89 f8 48 89 0f 8b 11 83 c2 01 83 fa 01 77 09 c3 0f 1f
```

Thanks for your work.

**Comment by DimitriPapadopoulos** [comment]
This doesn't look  like an issue with _openfortivpn_, rather with [_OpenFortiGUI_](https://hadler.me/linux/openfortigui/). Additionally this happens in the GUI library Qt5, so it's not probably not in code shared with _openfortivpn_.
