### ISSUE TITLE
Feature request: reconnect automatically

### ISSUE THREAD

**Issue by JayceCao** [adrienverge/openfortivpn#751]
In our company, VPN connections would be lost after establishing the connection for several hours. So it's better to have an option to reconnect automatically when disconnecting.

**Comment by DimitriPapadopoulos** [comment]
Like `--persistent`? Still better would be to investigate why the connection is lost though ;-)

**Comment by JayceCao** [comment]
> Like `--persistent`? Still better would be to investigate why the connection is lost though ;-)

Yeah. The connection is still lost when using the official Forticlient app. It seems that it's related to the configuration of the server.

**Comment by DimitriPapadopoulos** [comment]
If you can modify the parameters of the FortiGate appliance, have a look at  [Authentication Settings](https://docs.fortinet.com/document/fortigate/6.4.1/administration-guide/709376/authentication-settings). The default value of Authentication Timeout is 5 hours in FortiGate 6.4.

Anyway, does `--persistent` solve your problem?

**Comment by JayceCao** [comment]
I cannot modify the configuration of the server...
Will try `--persistent` today. I'll give you feedback once finished. Thanks for your answer 😁

**Comment by JayceCao** [comment]
I've tested `--persistent`. It seems that setting it to `0` doesn't work, setting it to `1` works for me.

**Comment by DimitriPapadopoulos** [comment]
I guess 0 is special value meaning "not persistent". I'll double-check and update the documentation accordingly.

**Comment by DimitriPapadopoulos** [comment]
Indeed 0 is an undocumented special value:
https://github.com/adrienverge/openfortivpn/blob/67f9cc0/src/main.c#L623

Yet it is quite possible to set the value to 0, both in the config file:
https://github.com/adrienverge/openfortivpn/blob/67f9cc0/src/config.c#L326-L331
and from the command line:
https://github.com/adrienverge/openfortivpn/blob/67f9cc0/src/main.c#L473-L478

@mrbaseman I don't see why 0 couldn't be an acceptable value for `--persistent`. I plan on changing the initialisation and the checks on `cfg->persistent` so that 0 becomes an acceptable value.

**Comment by mrbaseman** [comment]
It's documented in the [man page](https://github.com/adrienverge/openfortivpn/blob/master/doc/openfortivpn.1.in#L214-L216) and the default 0 means no attempt to reconnect, at least that was how the feature was implemented originally. If we allow for -1 we can make this value take over the role of 0

**Comment by JayceCao** [comment]
Thanks for your answer

**Comment by Morteza-Rastgoo** [comment]
So, To be clear, the solution is:
 ```sudo openfortivpn -c /etc/openfortivpn/config --persistent 1```

**Comment by DimitriPapadopoulos** [comment]
See https://github.com/adrienverge/openfortivpn/issues/751#issuecomment-659265811, it's in the man page.

Besides I still feel this option is a bad idea: that kind of functionality is best left to _systemd_ or its equivalent, no need to re-invent the wheel.

**Comment by NitroCao** [comment]
> See [#751 (comment)](https://github.com/adrienverge/openfortivpn/issues/751#issuecomment-659265811), it's in the man page.
> 
> Besides I still feel this option is a bad idea: that kind of functionality is best left to _systemd_ or its equivalent, no need to re-invent the wheel.

Yeah, using `systemd` on Linux or `launchd` on macOS is another choice. Keep the `persistent` option is okay, just let users to choose which option to use :)
