### ISSUE TITLE
Is This App Use Exim4?

### ISSUE THREAD

**Issue by taufikterdidik** [adrienverge/openfortivpn#753]
This is the last message from systemctl status openfortivpn@myvpn.service
`Jul 19 13:08:51 rumah openfortivpn[533]: INFO:   Interface ppp0 is UP.`
`Jul 19 13:08:51 rumah openfortivpn[533]: INFO:   Setting new routes...`
`Jul 19 13:08:51 rumah openfortivpn[533]: INFO:   Adding VPN nameservers...`
`Jul 19 13:08:51 rumah openfortivpn[533]: Too few arguments.`
`Jul 19 13:08:51 rumah openfortivpn[533]: Too few arguments.`
`Jul 19 13:08:51 rumah openfortivpn[533]: INFO:   Tunnel is up and running.`
`Jul 19 13:09:31 rumah exim[1580]: 2020-07-19 13:09:31 Start queue run: pid=1580 -qqf`
`Jul 19 13:09:31 rumah exim[1580]: 2020-07-19 13:09:31 Cannot open main log file "/var/log/exim4/mainlog": No such file or directory: euid=0 egid=122`
`Jul 19 13:09:31 rumah exim[1580]: exim: could not open panic log - aborting: see message(s) above`

is this app use exim4? the exim[1580]... printed in red text

**Comment by DimitriPapadopoulos** [comment]
Not sure what Exim4 is, so I guess not.

There's no red text.

I don't know what this **`openfortivpn@myvpn.service`** address is.

**Comment by DimitriPapadopoulos** [comment]
It looks like `openfortivpn@myvpn.service` is a _systemd_ service, probably using files `/etc/systemd/system/multi-user.target.wants/openfortivpn.service` and `/etc/openfortivpn/myvpn.conf`. These files or _systemd_ are probably using Exim4.
