### ISSUE TITLE
[HELP] Allow insecure SSL connection

### ISSUE THREAD

**Issue by Mihai-B** [adrienverge/openfortivpn#765]
This option may already be available, but I do not know how to add a VPN that uses an insecure SSL.

Can this option be enabled somehow in the file?

**Comment by DimitriPapadopoulos** [comment]
I think you're after **`seclevel-1 = 1`**, see man page:
https://github.com/adrienverge/openfortivpn/blob/3908da7/doc/openfortivpn.1.in#L362

**Comment by Mihai-B** [comment]
Not realy sure if exactly your option did the trick, since I also added the insecure ssl option, but you did point me in the right direction. Thnx for the help
