### ISSUE TITLE
Input/Output error, pppd: is not setuid-root and the invoking user is not root

### ISSUE THREAD

**Issue by Redzli** [adrienverge/openfortivpn#766]
Hi, I had a similar issue to https://github.com/adrienverge/openfortivpn/issues/273 but it doesn't seem we have the same solution so I opened another issue.

I am trying to run openforti on ubuntu 18.04 in a docker container. My Dockerfile looks like 
```bash
FROM ubuntu:18.04 

COPY . /app

# install all packages
RUN apt-get update && \
  apt-get install -y openfortivpn\
  gcc\ 
  sudo\
  automake\ 
  autoconf\
  libssl-dev\
  make\ 
  pkg-config\
  pptpd \
  libpcap-dev\
  # ssh
  sshpass\
  openssh-server

# add options to pppd options
RUN mkdir -p /etc/pppd && echo "115200\n :192.0.2.1\nnoipdefault\nnoaccomp\nnoauth\ndefault-asyncmap\nnopcomp\nreceive-all\nnodefaultroute\nnodetach\nlcp-max-configure 40\nmru 1354" > /etc/pppd/options

# RUN sudo chmod u+s /etc/pppd
# RUN sudo chmod u+s /usr/sbin/pppd
RUN sudo chmod 777 /etc/pppd

RUN sudo openfortivpn $ZHANGJIANG_VPN_ADDRESS -u $ZHANGJIANG_VPN_USERNAME -p $ZHANGJIANG_VPN_PASSWORD --trusted-cert $ZHANGJIANG_VPN_CERT &
```

I built the container using 
```
➜ docker build --tag forticlient:latest .
```

It gave me 
```
WARN:   Bad port in config file: "0".
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
ERROR:  read: Input/output error
INFO:   Cancelling threads...
ERROR:  pppd: Is not setuid-root and the invoking user is not root.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.
Removing intermediate container d583d2a9ae0b
 ---> 734f6203f6f4
Successfully built 734f6203f6f4
Successfully tagged forticlient:latest
```

I am confused by the error message. Would appreciate any advice. Thanks in advance

**Comment by DimitriPapadopoulos** [comment]
Probably a docker issue. I'm not familiar with _sudo_ issues in Docker. Clearly `RUN sudo openfortivpn` results in _openfortivpn_ being run as root (otherwise it would complain) but then `pppd` seems not to be forked as a root process.

**Comment by nehaljwani** [comment]
@Redzli Could you check if running the container in privileged mode makes any difference?

**Comment by DimitriPapadopoulos** [comment]
See also [LXC: Allow openfortivpn client to create a ppp0 interface](https://discuss.linuxcontainers.org/t/lxc-allow-openfortivpn-client-to-create-a-ppp0-interface/3048/7).
