### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by hossein114** [adrienverge/openfortivpn#767]
I installed the openfortivpn package in macOS with below command:

`brew install openfortivpn`

and after it, I add the config file with own parameter but when I try to connect I get this error:

`INFO:   Connected to gateway.`
`INFO:   Authenticated.`
`INFO:   Remote gateway has allocated a VPN.`
`INFO:   Got addresses: [xx.xxx.xxx.xxx], ns [xxx.xx.x.xxx, 8.8.8.8]`
`INFO:   Interface ppp0 is UP.`
`INFO:   Setting new routes...`
`Segmentation fault: 11`

What's the issue?

**Comment by DimitriPapadopoulos** [comment]
I'm afraid I have no clue, this is the first time I see such an issue reported with recent _openfortivpn_ releases. It would help if you could show us the (sanitized) command line, option file if any, and verbose log (`-v`).

I assume you're running _openfortivpn_ 1.14.1 [as available through Homebrew](https://formulae.brew.sh/formula/openfortivpn).

**Comment by DimitriPapadopoulos** [comment]
By the way, make sure you use these options on mac0S:
```
set-dns = 0
pppd-use-peerdns = 1
```

See #534 for example.

**Comment by DimitriPapadopoulos** [comment]
Also I'm wondering whether this could be `pppd` crashing, not openfortivpn. Anything of interest in the log after `Segmentation fault: 11`?

Also send the `pppd` log (option `--pppd-log=` of _openfortivpn_).

**Comment by DimitriPapadopoulos** [comment]
@hossein114 Any luck getting this to work or getting further at least?

**Comment by DimitriPapadopoulos** [comment]
@hossein114 So does it work or not?

**Comment by hossein114** [comment]
> @hossein114 So does it work or not?

No, it not work as before.

**Comment by DimitriPapadopoulos** [comment]
It would help if you could show how you run _openfortivpn_ in verbose mode and provide the (sanitized) full log and pppd log (--pppd-log=`).

**Comment by DimitriPapadopoulos** [comment]
@Morteza-Rastgoo Are you experiencing or have you experienced the same issue?

**Comment by Morteza-Rastgoo** [comment]
The same issue exists.
I need time to test routes and let you know.

**Comment by DimitriPapadopoulos** [comment]
@Morteza-Rastgoo Not sure I follow. This does not look like a routing issue, instead _openfortivpn_ crashes. Do you think it's related?

**Comment by Morteza-Rastgoo** [comment]
Sorry I mixed up two different issues 🤭

**Comment by DimitriPapadopoulos** [comment]
@hossein114 Perhaps sending the command line and the complete (sanitized) logs can help debug this issue.

> Also I'm wondering whether this could be `pppd` crashing, not _openfortivpn_. Anything of interest in the log after `Segmentation fault: 11`?
> 
> Also send the `pppd` log (option `--pppd-log=` of _openfortivpn_).
