### ISSUE TITLE
Running as root? In macosx

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [adrienverge/openfortivpn#769]
I tried this on macos but does not work:
`visudo -f /etc/sudoers.d/openfortivpn`
```
Cmnd_Alias  OPENFORTIVPN = /usr/bin/openfortivpn

%adm       ALL = (ALL) OPENFORTIVPN
```

after that I run visudo and no error when closing it but no luck removing asking for user password even with `myusername       ALL = (ALL) NOPASSWD:OPENFORTIVPN`

**Comment by florianmutter** [comment]
I have the following in the file and it works:

` %admin  ALL = (ALL) NOPASSWD: /usr/local/bin/openfortivpn`

**Comment by Morteza-Rastgoo** [comment]
So the readme should be changed to:
```
Cmnd_Alias  OPENFORTIVPN = /usr/local/bin/openfortivpn

%admin       ALL = (ALL) NOPASSWD:OPENFORTIVPN
```
I tested this and works.
Thanks to @florianmutter

**Comment by DimitriPapadopoulos** [comment]
This works for me on Linux:
```
%openfortivpn ALL = NOPASSWD: /usr/local/bin/openfortivpn
```

I'm not really aware of the details of the [sudoers](https://www.sudo.ws/man/sudoers.man.html) syntax. Not sure about it.

**Comment by DimitriPapadopoulos** [comment]
The _openfortivpn_ [README](https://github.com/adrienverge/openfortivpn/blob/master/README.md) currently suggests:
```
Cmnd_Alias  OPENFORTIVPN = /usr/bin/openfortivpn

%adm       ALL = (ALL) OPENFORTIVPN
```
What's wrong with it?

**Comment by DimitriPapadopoulos** [comment]
Finally you wrote this doesn't work:
```
myusername ALL = (ALL) NOPASSWD:OPENFORTIVPN
```
and this works:
```
%admin       ALL = (ALL) NOPASSWD:OPENFORTIVPN
```
What's the difference?

**Comment by Morteza-Rastgoo** [comment]
@DimitriPapadopoulos 
The difference between Linux and Mac is
1. Path of openfortivpn
`usr/local/bin/openfortivpn`
In readme the path doesn't have local
2.
`%adm` or `%admin`

**Comment by DimitriPapadopoulos** [comment]
OK, but these are not conceptual differences, just variations over an example. Why change the README?

**Comment by Morteza-Rastgoo** [comment]
@DimitriPapadopoulos ‌Because as a user, I used the readme instructions But No luck making it work and  I searched for the problem for two days and finally had to create an issue to find out the solution.
This helps other Mac users.

**Comment by DimitriPapadopoulos** [comment]
It has been contributed as an example that needs to adapt to the local context, not as complete documentation on the subject.

Also the default path is `/usr/bin/openfortivpn` on most platforms these days, so it won't help users on other platforms.

Perhaps we should completely remove this part, or move to the wiki and hope for more detailed contributions to improve it.


Other suggestions?

**Comment by florianmutter** [comment]
Maybe just add a hint that it is an example and values might vary on different systems

**Comment by DimitriPapadopoulos** [comment]
I think there is already a hint that it is an example (_For example_) but yes, I see there is room for improvement. Can you perhaps start a pull request?
