### ISSUE TITLE
Plans for v1.15.0 release?

### ISSUE THREAD

**Issue by aaronjg** [adrienverge/openfortivpn#779]
Would it be possible to have an openfortivpn release in the next few weeks? It sounds like a the 20.x release of OpenWRT is in the works. I wrote a new [netifd protocol handler](https://github.com/openwrt/packages/tree/master/net/openfortivpn) for openfortivpn that will be included. Now that #708 has been merged into master, I would like to remove my patch in the OpenWRT distribution and just use a openfortivpn release.

**Comment by adrienverge** [comment]
@DimitriPapadopoulos @mrbaseman what do you think?

**Comment by DimitriPapadopoulos** [comment]
Sure. We need to work on the change log and create an issue for release 1.15.0 - unless we use this issue :-)

**Comment by mrbaseman** [comment]
I'm fine with a new release as well, and yes, we would need a pull request for the version increment and the updated change log :-)

**Comment by adrienverge** [comment]
@aaronjg would you like to help in creating this release? We would need a pull request similar to https://github.com/adrienverge/openfortivpn/pull/707 or https://github.com/adrienverge/openfortivpn/pull/719.

**Comment by aaronjg** [comment]
Sure, I can take care of it later this week.

**Comment by msfuentess** [comment]
Hello,
I moved successfully some time ago to use netifd instead of the specific OpenFortiVPN config file (OpenWRT trunk).
But the latest build 1.14-8 stopped working: the script does not get the parameter 'server'. So I had to return to the dedicated config file instead of using netifd.
Thanks for your work

**Comment by DimitriPapadopoulos** [comment]
@msfuentess Not sure how this is related to _openfortivpn_. Can you please explain?

**Comment by aaronjg** [comment]
@msfuentess this is more of an issue with the openwrt package than openfortivpn. 

The netifd is package is only available on the unstable branch, and the configure options recently changed.

https://github.com/openwrt/packages/pull/13220

**Comment by msfuentess** [comment]
I just found a temporary workaround by copying back the previous openfortivpn.sh 1.14.1-7 script.
I saw that in 1-8 there are new parameters like tunlink and peeraddr instead of server.
@aaronjg I hadn't notice netifd had changes too

**Comment by DimitriPapadopoulos** [comment]
There is no `openfortivpn.sh` script in _openfortivpn. This looks like it's specific to OpenWRT.

**Comment by msfuentess** [comment]
> There is no `openfortivpn.sh` script in _openfortivpn_. This looks like it's specific to OpenWRT.
Yes it should be. Now i just use OpenFortiVPN in OpenWRT (trunk)

**Comment by aaronjg** [comment]
@DimitriPapadopoulos @mrbaseman  @adrienverge How does it look now?

@msfuentess - glad to hear it is all working on the OpenWRT side.

**Comment by DimitriPapadopoulos** [comment]
@aaronjg I have suggested a few changes in the change log.

**Comment by aaronjg** [comment]
@DimitriPapadopoulos I'm not seeing the changes you suggested on the P/R, however I'm sure whatever you suggest is fine.
