### ISSUE TITLE
SIGTERM and SIGHUP handling

### ISSUE THREAD

**Issue by paolo-losi** [adrienverge/openfortivpn#78]
I think SIGTERM should be handled as SIGINT is handled
SIGHUP should be ignored

**Comment by DimitriPapadopoulos** [comment]
Commit 15a3686 makes sure SIGTERM is handled the same way as SIGINT, including **not** disabling these signals for future threads on MacOS X.

But should we do that? Any clue why the SIGINT signal was not disabled on MacOS X in the first place?

**Comment by DimitriPapadopoulos** [comment]
@paolo-losi I'm a little rusty on signals... Why should SIGHUP be ignored? So that _openfortivpn_ is not killed when the terminal from which it was started from is closed?

**Comment by paolo-losi** [comment]
exactly for that reason.

There are two sensible choices for openfortivpn:
- handle sighup as INT/TERM
- ignore it

I would favour the second choice.

BTW thanks for your patch

**Comment by DimitriPapadopoulos** [comment]
Commit DimitriPapadopoulos/openfortivpn@e05a912 should make sure SIGHUP is ignored.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos from my perspective we can land #134 now.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman I agree, but of course someone else than me needs to land it.

**Comment by mrbaseman** [comment]
I have just landed #134
