### ISSUE TITLE
VPN works but can't use HTTP/HTTPS

### ISSUE THREAD

**Issue by mithun-b** [adrienverge/openfortivpn#782]
I can use VPN and it's working as expected. But cant browse at the same time. Is there any setting I can do in my PC, so that the HTTP/HTTPS request won't got inside the VPN, but served normally? Is there any software setting to be done in openfortivpn? or do I need to use commands like "ip route" or "iptables", etc to skip ports like 80, 443, etc?

I have also posted the question in below link:
https://serverfault.com/questions/1034274/how-can-i-set-forti-vpn-so-that-http-https-are-not-using-vpn-xubuntu

**Comment by DimitriPapadopoulos** [comment]
The VPN client applies whatever routing the VPN gateway requests. Usually all traffic goes through the VPN and that's by design. If you want something else, you can indeed modify routing using "ip route".

That said are your certain this is a routing issue and not a DNS issue?

Are you able to browse some sites but not others? What happens if you try to access the web site by IP address instead of name? For example try `https://140.82.121.3/` instead of `https://github.com/`.

**Comment by mithun-b** [comment]
I am certain that, it's not the DNS issue. I am able to see the pages of https://140.82.121.3/ and https://github.com/ without VPN. But can't get them after the VPN connected.

My assumption is that these requests are sent to the other side of network, and they are blocked due to some Firewall setting.

**Comment by DimitriPapadopoulos** [comment]
Then yes, you are certainly right. All traffic is routed through the VPN gateway and from there HTTP/HTTPS traffic may be blocked by security rules. The VPN gateway admins probably enforce all these rules on purpose.

You may circumvent these rules by using `--no-routes` and setting routes manually, or simply modifying part of the routes manually after _openfortivpn_ has started.

**Comment by mithun-b** [comment]
I tried the following configuration to skip HTTP/HTTPS requests:

`sudo iptables -t mangle -I OUTPUT -p tcp -m multiport --dports 80,443 -j MARK --set-mark 4`
`echo 101 r_http >> /etc/iproute2/rt_tables`
`sudo ip route add table r_http default via 192.168.0.1 dev wlp3s0`
`sudo ip route flush cache`
`sudo ip rule add fwmark 4 table 101`

I am still having same issues where I stated with. I also tried using `--no-routes` (not directly but via openfortigui which works for and openfortivpn dosen't).

**Comment by DimitriPapadopoulos** [comment]
I believe modifying routing is not related to _openfortivpn_, is it?

Also _openfortigui_ is based on _openfortivpn_ so I am at a loss why _openfortigui_ would work and _openfortivpn_ doesn't. I would need more information on how you use both and how you find one works and the other doesn't. Showing routing before/after starting either might give a hint.

**Comment by mithun-b** [comment]
### I have got another solution with the help of SOCKv5 tunnel (Ubuntu + Firefox).

_I shall close this issue with following info (which could help others facing similar issue):_

1. The command needed for creating SOCKv5 using ssh:
    **ssh -N -D 9090 username@192.168.XXX.YYY**
    (here 9090 can be any unused socket port number)
2. The above command will create a SOCKv5 tunnel which tunnels various protocols between computer you are running the command and the specified IP 192.168.XXX.YYY (doesn't matter it's in local network or in VPN).
3. Go to Firefox and type "about:preferences" in the url.
4. Under "Network Settings" open settings, select the radio-button "Manual proxy configuration".
5. Under "SOCKS Host" text box type "127.0.0.1" and under "Port" text box type "9090" (the same port number set in ssh command above).
6. Further you can add "No proxy for" text box as required. That is, if you need any .com HTTP/HTTPS request need not enter VPN you may add those under "No proxy for" text box.
7. Click "OK" to save this settings.

**How does ssh tunnel solves, the Firewall block I am facing?**

Usually VPN service provider will allow SSH connection, but not the HTTP/HTTPS requests (which is in my case they are allowing ssh connection). So using SSH tunnel, I made the HTTP/HTTPS requests to stay hidden from the organization's Firewall. Of course there is a need of known system IP (192.168.XXX.YYY) username and password present (with in the VPN, in case the HTTP/HTTPS request are organization specific) which has access to HTTP/HTPPS requests. This setting makes the HTTP/HTTPS request, go all the way from my system to VPN (under ssh tunnel) and then open up as HTTP/HTTPS request as if they are originated from the system 192.168.XXX.YYY instead (and get served).

If you are not at all interested in passing the HTTP/HTTPS requests via VPN, then use the "No Proxy for" option which is better option for me. Well this applies for all the HTTP/HTTPS whose requests are served even outside the organization (example: www.google.com).

_Reference:_
https://linuxize.com/post/how-to-setup-ssh-socks-tunnel-for-private-browsing/
https://linuxize.com/post/how-to-setup-ssh-tunneling/
(you can find similar solution for Windows OS using Putty application)

**Comment by 1pix** [comment]
perfect thx.
