### ISSUE TITLE
persistent not available in Ubuntu/Mint?

### ISSUE THREAD

**Issue by ben-utzer** [adrienverge/openfortivpn#783]
Does someone know why `--persistent` is not present in openfortivpn in Ubuntu (Mint)? 
```
openfortivpn --version
1.6.0
```

`openfortivpn: unrecognized option '--persistent=1'
`
```
cat /etc/issue
Linux Mint 19.3 Tricia \n \l
```

**Comment by DimitriPapadopoulos** [comment]
That's because that's an old version of _openfortivpn_.

**Comment by ben-utzer** [comment]
> That's because that's an old version of _openfortivpn_.

ah ok, I somehow thought the version number is strange. Alright then.
