### ISSUE TITLE
Failed verification with Let's Encrypt certs

### ISSUE THREAD

**Issue by Angelin01** [adrienverge/openfortivpn#785]
This is exactly the same issue as #442 

I did not want to reopen that one, but it appears I have run into the exact same problem. We are using Let's Encrypt certs, they are valid and in fact I am using those certificates on a couple internal servers sitting right next to the Fortigate, including an LDAP server and a couple web servers and the Fortigate's own web admin GUI. I can access those services fine, no SSL issues whatsoever, but openfortivpn asks me to use the `--trusted-cert` option.

Could I get some assistance?

**Comment by DimitriPapadopoulos** [comment]
Most probably the root certification authority is known to your web browser but not to the system OpenSSL library used by _openfortivpn_ - they do not share the same certification authorities. Without the certificate it's hard to be more precise.

**Comment by Angelin01** [comment]
No. This is a VPN for my company. The issuer is as thus: `Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3`
My local OpenSSL library (on Manjaro) can verify it just fine as well:
```
openssl verify -CAfile chain1.pem fullchain1.pem
fullchain1.pem: OK
```

Although, I did notice that openssl can't verify it on CentOS 8. Does the FortiGate verify it on it's end? I thought this was local.

**Comment by DimitriPapadopoulos** [comment]
Only _openfortivpn_ verifies the certiicate, to make sure the VPN gateway you're attempting to connect to is legitimate and avoid man-in-the-middle attacks.

By the way, I have never tested _openfortivpn_ with a wildcard certificate such as the one for `*.ufpr.br`.

**Comment by Angelin01** [comment]
The gateway I am trying to connect is legitimate, it's my own, I am the admin trying to set this up, locally from my own network. I'll investigate this further tomorrow (and also with the regular FortiClient), but I cannot find any issue with either my openssl library or my certificate.

**Comment by DimitriPapadopoulos** [comment]
I suppose the certificate has not been correctly set up on the FortiGate gateway.

**Comment by mrbaseman** [comment]
You have to assign the certificate not only to the web admin GUI of the Fortigate, but also for use by the ssl vpn, and I think the device needs a reboot after changing the certificate. You can check by connecting with the browser to the SSLVPN-Port. It shows a login prompt similar to the admin interface.

**Comment by Angelin01** [comment]
The certificate is working, folks. I have assigned in both the VPN and in the web admin GUI. I have opened the web interface for the VPN and it shows the certificate is fine. Again, I am using this same certificate in multiple places, it's a wildcard certificate, and it's working fine. It's working fine in other services in the FortiGate. In fact, I just booted into Windows just to download the regular FortiClient VPN and connect with it, it connects fine and does not complain about the certificate at all: 
![forticlient](https://user-images.githubusercontent.com/17818024/94682368-39850d80-02fb-11eb-892e-5b6b7096b7aa.png)

The ONLY method of connecting to the VPN that I use that complains about the certificate is openfortivpn.

**Comment by DimitriPapadopoulos** [comment]
Windows is probably using IPSec, not SSL, and if so it's not relevant. At this point the most probable cause remains an issue with the SSL setup. Such an issue has never been reported before.

**Comment by Angelin01** [comment]
> Windows is probably using IPSec

Windows is not using IPsec, I have not setup IPSec and in the client I have specifically selected "SSL VPN". I unfortunately cannot share with you an open connection for testing and this is for a private business. I don't understand why it's so hard to accept that the certificates are fine when it works for literally everything else. I'll investigate on my own for a bit and report back.

**Comment by DimitriPapadopoulos** [comment]
Well, it works for everyone else. And even if it were an issue with _openfortivpn_ we cannot fix it without the URL to reproduce the certificate issue (not an actual account but just the URL).

**Comment by Angelin01** [comment]
I am running Manjaro with kernel 5.8.6-1-MANJARO, OpenSSL 1.1.1g  21 Apr 2020. Again, I cannot provide you with an URL, this is a closed VPN, in testing, I am manually assigning the hostname for our external IP address in my hosts file/dns resolver for testing. If you really must know, I am setting it up as `vpn.mycompany.com` and my certificate is valid for `*.mycompany.com`. If you cannot help without a valid endpoint connection for you, unfortunately I'll just have to solve this on my own. 

As stated before, my OpenSSL can validate the certificate fine:
```
> openssl verify -CAfile chain1.pem fullchain1.pem
fullchain1.pem: OK
```
I even manually compiled openfortivpn to make sure it is using my own OpenSSL.

I will have a look at the code and see if I can find anything that might be causing this.

Also, it does NOT work for everyone else, note issue #442  
By the way, @DClabaut, did you ever solve your issue?

**Comment by DimitriPapadopoulos** [comment]
I'm not insisting you provide the URL or IP address. It's just that we cannot help much without actually running _openfortivpn_ against the IP address - which I know is very often not possible of course. The fact remains that in that case we cannot help.

I'm not counting #442 as @DClabaut never answered. We don't even know which version of Linux he runs.

What I can suggest:
1. Run `openfortivpn -v -v` and post the **sanitized** output. See https://github.com/adrienverge/openfortivpn/wiki. Perhaps it will print an error message that will be enough to understand the problem.
2. Perhaps you can add some print statements around here:
https://github.com/adrienverge/openfortivpn/blob/3378911/src/tunnel.c#L733-L828
3. I'm wondering what the value of HAVE_X509_CHECK_HOST might be in your case. Can you provide the log of _autoconf_ if you rebuild _openfortivpn_?

The only other thing that comes to mind is time. is the date correct for both the client and FortiGate?

**Comment by DimitriPapadopoulos** [comment]
Also you do not seem to be controlling the `mycompany.com` so I'm not sure how you got Let's Encrypt issue a certificate for that domain.

**Comment by Angelin01** [comment]
I can do some testing later today and during the rest of the week and I'll report back, if you don't mind keeping the issue open for the time being.

> Also you do not seem to be controlling the mycompany.com domain so I'm not sure how you got Let's Encrypt issue a certificate for it.

Uhm... In case it wasn't obvious, "mycompany" is not actually the name of my company or of my domain and was used as an example.

**Comment by PieceOfWire** [comment]
Just for the record. I also have the same issue. I am running Debian 10.5 amd64 with Gnome 3 and I got my certs from Lets Encrypt. I installed openfortivpn trough apt.

If I go to the SSL VPN trough my browser I get no warnings. I also get no warnings using the Windows client. 

I personally do not mind having to add the trust-cert option in the conf file, but I am just here to say that at least two people are experiencing this lol.

**Comment by DimitriPapadopoulos** [comment]
@PieceOfWire Tank you for reporting this. So it seems there is an issue after all with Let's Encrypt certificates. Generally speaking it's best to avoid the trust-cert option, especially with Let's Encrypt certificates as they change quite often.

If someone could give me the IP address of a VPN gateway with a Let's Encrypt certificate, I could look into this issue. There is no need for an account, the IP address is enough. Otherwise @Angelin01 will hopefully debug this.

**Comment by DimitriPapadopoulos** [comment]
Might be related - or not:
https://blog.apnic.net/2020/04/07/the-wrong-certificate-apache-lets-encrypt-and-openssl/

**Comment by PieceOfWire** [comment]
I don't know what my employer would think about me posting our ip address and port for the VPN.
I mean anyone can run a scan port and find us out, heck if they stalk me on github they might as well find it somewhere lol.

What would you check for if you had the IP address? Perhaps I could act as a proxy and supply you with non-identifiable information.

**Comment by DimitriPapadopoulos** [comment]
@PieceOfWire I don't know what to look for exactly. I just suppose _openfortivpn_ will fail when initiating the SSL connection, before even asking for identifiers. I would run _openfortivpn_ in verbose mode and could add a few additional print statements if needed to understand which OpenSSL call fails and why.

😃 I'm not that good at stalking, I just know the time zone you commit to GitHub from and the name of the company you might be working for. More seriously, you could help by trying https://github.com/adrienverge/openfortivpn/issues/785#issuecomment-701376159 and reporting back.

**Comment by mrbaseman** [comment]
One general thing which comes into mind:

You might have to import an intermediate certificate into the Fortigate so that it can serve the full certificate chain. 
The browser might have the intermediate cached whereas openssl might have the trusted root in its cert-dir, but can't build the full chain without the sub-ca certificates.

**Comment by DimitriPapadopoulos** [comment]
@mrbaseman But how could the intermediate certificate be cached by the browser? From another correctly configured server with Let's Encrypt certificates? Should users clear everything, for example as described in [How do I clear Chrome's SSL cache?](https://serverfault.com/questions/279984/how-do-i-clear-chromes-ssl-cache)

**Comment by DimitriPapadopoulos** [comment]
You may also capture the initial SSL handshake using [Wireshark](https://www.wireshark.org/), see [Technical Tip: How to avoid certificate error message by chaining Root CA and Intermediate CA certificates](https://kb.fortinet.com/kb/documentLink.do?externalID=FD41362).

**Comment by Angelin01** [comment]
While debugging I went through the OpenSSL documentation and for the `X509_check_host` function (which is where the check is failing), on the notes it says: "Applications are encouraged to use X509_VERIFY_PARAM_set1_host() rather than explicitly calling X509_check_host(3)."  
Now, I haven't done much OpenSSL myself, but could this be related in some way to the direct usage of check_host?

**Comment by mrbaseman** [comment]
> @mrbaseman But how could the intermediate certificate be cached by the browser? From another correctly configured server with Let's Encrypt certificates?
that's exactly what I thought of when it does work from the browser and it does not work using openssl in this context (i.e. having verified that the root ca is trusted for both scenarios)

**Comment by Angelin01** [comment]
> You might have to import an intermediate certificate into the FortiGate so that it can serve the full certificate chain.  

You know, this gave me the weirdest bloody idea. I was uploading the fullchain.pem and privkey.pem files that I got from Let's Encrypt. This should have ensured that I had both in the chain, right? Right! I even double checked to make sure fullchain.pem is what I thought it was. 

But I was also intrigued. So I started to think, what was different between the certificate I used to check straight with openssl in the command line vs the certificate the Fortigate was serving me? Then it dawned on me. These certificates were handed to me on a USB Stick by my colleague which I uploaded straight to the FortiGate. I then copied them to an encrypted folder on my PC for future usage. 

So from now on, this is all guessing because I don't really know how it happened. I deleted my current certificate on the fortigate and reuploaded the ones I had copied, fullchain and private key... It now works. Why the bloody hell? I don't know, but my guess is that somehow an encoding issue, maybe a rogue \r\n instead of just \n, maybe the format on the file on the USB Stick, a rogue NULL char? I don't know, but I think @mrbaseman was right, the Fortigate was not importing the intermediate from the fullchain, only my certificate. Now, why my browser was not complaining about this, I don't know. I even checked by using JUST the cert.pem file and setting that as the webgui certificate, on the browser it still works fine. They also both look virtually the same on the interface. I guess the problem wasn't with openfortivpn after all.

@PieceOfWire could you try reuploading your fullchain cert as well? Maybe it fixes your issue.

**Comment by mrbaseman** [comment]
@Angelin01 I'm happy that we could solve your problem in a collaborative effort. Also from my side it was just guessing, to some extend (and some experience with similar situations as you have suffered during the last days).

**Comment by Angelin01** [comment]
It appears to be available since 1.0.2, and as far as I know the 1.0.X branch of OpenSSL is marked EOL since the beginning of this year. It's probably a safe switch, however you should probably move this discussion to a different topic.

**Comment by PieceOfWire** [comment]
I also passed it from a USB so probably the same problem. Kind of sucks that Fortinet has no option to do SFTP or something along those lines. Honestly I am so bogged down with other stuff that I probably won't try reloading my cert until it expires... Glad we were able to get some traction and find a solution. It was nice talking with you guys, great piece of software too, definitely better than the official FortiClient that wont even open on Linux lol.

**Comment by mrbaseman** [comment]
I usually install the certificates by means of the admin GUI. I think you can also push it into the config with the CLI, but if the private key is DES3 encrypted it may become difficult. I have already restored certificates and keys from a backup config, i.e. ones which already were installed on a similar box. This might be safer than utilizing an USB stick with whatever kind of file system on it. 

Anyhow, the encoding of the data, i.e. consistent line endings may still be an issue, on the CLI perhaps more than via GUI. Maybe the internal webserver that provides the GUI upload is more tolerant in this aspect and helps cleaning up these inconsistencies. But well, this is all speculation which may or may not explain some specific behavior...

**Comment by Angelin01** [comment]
>  Kind of sucks that Fortinet has no option to do SFTP or something along those lines.

I am working on a little client to push a certificate through the API and trying to make it work with certbot. I'm more than willing to share once I have enough progress.

**Comment by PieceOfWire** [comment]
> > Kind of sucks that Fortinet has no option to do SFTP or something along those lines.
> 
> I am working on a little client to push a certificate through the API and trying to make it work with certbot. I'm more than willing to share once I have enough progress.

Wow, I am pretty new to Fortinet so I did not know there was an API. Yes, it would be nice if you can share it and if I can be of help to test/develop your project I will be glad to do so. Being able to automate certain stuff like certificate renewal on Fortinet would be very useful.

**Comment by Angelin01** [comment]
> Wow, I am pretty new to Fortinet so I did not know there was an API. Yes, it would be nice if you can share it and if I can be of help to test/develop your project I will be glad to do so. Being able to automate certain stuff like certificate renewal on Fortinet would be very useful.

Access to official documentation is limited, need a FNDN account with 2 "sponsors", very strange. However, you can easily check the requests on the web gui directly and see them yourself. They're all regular REST requests.
