### ISSUE TITLE
PKCS11 SSL_CTX_use_certificate error on CentOS only

### ISSUE THREAD

**Issue by nate1908** [adrienverge/openfortivpn#787]
Unable to work on a CentOS 7.8. Works on Debian-based systems.

Following same directions on both CentOS and Debian. Installing, we think, are same packages... due to names of packages different between CentOS and Debian.

On CentOS starts to read card, reader blinking, doesn't prompt for PIN.

/etc/openfortivpn/config contains:

host = 192.x.x.x
port = 10443
user-cert = pkcs11:model=;manufacture=;serial=;token=LAST.FIRST.xxxx;id=%00%01
trusted-cert = {fingerprint}

(as root)
# openfortivpn -c /etc/openfortivpn/config -v

DEBUG:  openfortivpn 1.14.1
DEBUG:  revision unavailable
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Config host = "192.x.x.x"
DEBUG:  Config realm = ""
DEBUG:  Config port = "10443"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: 192.x.x.x
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 192.x.x.x
DEBUG:  gateway_port: 10443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
ERROR:  PKCS11 SSL_CTX_use_certificate: error:140BF10C:SSL routines:SSL_SET_CERT:x509 lib
INFO:   Closed connection to gateway.
DEBUG:  server_addr: 192.x.x.x
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: 192.67.93.25
DEBUG:  gateway_port: 10443
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
ERROR:  PKCS11 SSL_CTX_use_certificate: error:140BF10C:SSL routines:SSL_SET_CERT:x509 lib
INFO:   Could not log out.

**Comment by mrbaseman** [comment]
When smartcard support was added, we have noticed that it needs `openssl pkcs engine` and `opensc` to be installed and  pkcs11-engine from libp11 needs to be compiled with p11-kit-devel installed. (see README.md). I'm wondering if maybe one of these prerequisites was not fulfilled here. Unfortunately, I'm not very familiar with the usage of the pkcs11 engine.

A discussion on the openssl mailing list which might be relevant:
https://mta.openssl.org/pipermail/openssl-users/2016-September/004430.html

**Comment by nate1908** [comment]
Have openssl pkcs engine and opensc installed, plus other p11kit packages. Same thing I did on a Debian system. Of course one difference is RedHat-based systems are older software. Didn't have to compile anything on Debian system. Tried compile anyway, no difference. Even tried compile of newer openssl libs. Not sure how to debug or trace this further.

**Comment by mrbaseman** [comment]
As far as I have understood the hint in the README it's important that p11-kit-devel needs to be installed when the pkcs11-engine in the  libp11 package is compiled. If the package maintainer (or you, when you are compiling the engine from source) have compiled it without having  p11-kit-devel installed, it doesn't work. 

Also, on SUSE there were some issues which couldn't be solved but we have decided to merge the code for smart cards so that we get more testing and feedback about it (and perhaps also some pull requests to improve it)..

**Comment by nate1908** [comment]
More testing shows that it is FIPS causing the issue. As in, when FIPS is enable for kernel via GRUB_CMDLINE_LINUX. Which is required for DoD systems. Smartcard works if FIPS mode disabled. Anyone else?  Or how to work around this?

**Comment by DimitriPapadopoulos** [comment]
Is this a FIPS-compliant card reader? Is it a contactless cart reader? A quick search in Google shows:

**Comment by DimitriPapadopoulos** [comment]
Hopefully some of these pages can help:
* [Smart Card Support in Red Hat Enterprise Linux](https://www.redhat.com/en/blog/smart-card-support-red-hat-enterprise-linux)
* [Bug 1566675 - CAC card no longer unlocks server after update to RHEL 7.5](https://bugzilla.redhat.com/show_bug.cgi?id=1566675)

The bug report might show where to look into to further debug this.

**Comment by nate1908** [comment]
Please understand I am a Linux Admin. Of course it's a FIPS compliant card reader...? Everything is and has to be FIPS. This software works great on any other Linux OS and Without FIPS enabled. And other things on this same system work with the smartcard, login, web browsers, via pkcs11, openssl, pam, etc.
It is a simple test to try yourself... Enable FIPS in kernel, via grub, openfortivpn read certs on card fails. Disable FIPS in kernel, via grub, openfortivpn read certs on card successful and VPN connects.

**Comment by DimitriPapadopoulos** [comment]
Oh, I don't know much about all that either, and I don't even have a card reader at home to test.

I'm just wondering whether one of the above bugs and [RHBA-2020:1871 - Bug Fix Advisory](https://access.redhat.com/errata/RHBA-2020:1871) might point to a relevant RedHat bug. Especially [Bug 1777892 - openssl-pkcs11 does not support using RSA keys in FIPS mode ](https://bugzilla.redhat.com/show_bug.cgi?id=1777892) but I cannot understand whether it relates to RHEL 8 only or RHEL and earlier. Do you know whether the certificate contains an RSA key? It should according to [FIPS mode and TLS](https://wiki.openssl.org/index.php/FIPS_mode_and_TLS#TLS_1.0_and_1.1):
> Theoretically that would permit RSA, DH or ECDH keys in certificates but in practice everyone uses RSA. 

Are you able to check certificates from other software on the same platform but specifically not from _openfortivpn_?

**Comment by DimitriPapadopoulos** [comment]
Do follow the "Steps to Reproduce" in [Bug 1777892 - openssl-pkcs11 does not support using RSA keys in FIPS mode](https://bugzilla.redhat.com/show_bug.cgi?id=1777892). Can you reproduce the bug on your machine?

**Comment by nate1908** [comment]
Thanks to DimitriPapadopoulos, confirmed issue is really with openssl-pkcs11. Varied openfortivpn works on CentOS 8.2 which included updated package.
