### ISSUE TITLE
Add getsockopt() to debug TCP-keepalive

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#795]
Copied from https://github.com/adrienverge/openfortivpn/issues/794#issuecomment-714397002:
> The observation, however, was that this didn't help at least on MacOSX. So I didn't have a clear idea how I should proceed further in #613 . When a timeout has happened to me (on linux) some weeks ago, I have seen the error messages (probably coming from pppd ?), which I understand that something below already implements some sort of keepalive mechanism.
> Maybe instead of guessing what might be happening, we should just put in some lines of debug code which print out the result of getsockopt - and see on which platforms tcp-keepalive is already enabled and where it's not...

**Comment by DimitriPapadopoulos** [comment]
On an Ubuntu 18.04 machine the default SSL socket options are:
```
SO_KEEPALIVE: 0
TCP_KEEPIDLE: 7200
TCP_KEEPINTVL: 75
TCP_KEEPCNT: 9
```

**Comment by ehaupt** [comment]
On a FreeBSD 12.1-RELEASE-p10 the default SSL socket options are:

```
SO_KEEPALIVE: 0
TCP_KEEPIDLE: 7200
TCP_KEEPINTVL: 75
TCP_KEEPCNT: 8
```
