### ISSUE TITLE
WARN: Read return zero

### ISSUE THREAD

**Issue by fasavard** [adrienverge/openfortivpn#806]
I have install the pakage on a Freenas jail.

I am able to connect to the vpn, but i only get WARN: Read return zero looping indefenetly. 

I look on the fortigate client web portal, i see that a connection has been made, but im not able to do any communication trough ping of ssh

Can anybody give me some pointer on where i did something wrong ?

Here part of the log im able to catch by killing the connection before having the Read Retun zero warnin looping:

```
root@VPN:/etc/openfortivpn # openfortivpn -v -c /etc/openfortivpn/config
DEBUG:  openfortivpn 1.15.0
DEBUG:  revision unavailable
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Loaded password from config file "/etc/openfortivpn/config"
DEBUG:  Config host = "Redacted"
DEBUG:  Config realm = ""
DEBUG:  Config port = "Redacted"
DEBUG:  Config username = "freenas"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: Redacted
DEBUG:  server_port: Redacted
DEBUG:  gateway_addr: v
DEBUG:  gateway_port: Redacted
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
DEBUG:  Setting minimum protocol version to: 0x303.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=Redacted
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=Redacted
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: Redacted
DEBUG:  server_port: Redacted
DEBUG:  gateway_addr: Redacted
DEBUG:  gateway_port: Redacted
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
DEBUG:  Setting minimum protocol version to: 0x303.
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
DEBUG:  Retrieving configuration
DEBUG:  Establishing the tunnel
DEBUG:  ppp_path: /usr/sbin/ppp
DEBUG:  Switch to tunneling mode
DEBUG:  Starting IO through the tunnel
DEBUG:  pppd_read thread
DEBUG:  ssl_read thread
DEBUG:  ssl_write thread
DEBUG:  if_config thread
^CINFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
DEBUG:  disconnecting
DEBUG:  Waiting for ppp to exit...
DEBUG:  waitpid: ppp terminated by signal 1
ERROR:  ppp: terminated by signal: Hangup
INFO:   Terminated ppp.
INFO:   Closed connection to gateway.
DEBUG:  server_addr: Redacted
DEBUG:  server_port: Redacted
DEBUG:  gateway_addr: Redacted
DEBUG:  gateway_port: Redacted
```

**Comment by DimitriPapadopoulos** [comment]
I don't see the `WARN: Read return zero` message.

**Comment by DimitriPapadopoulos** [comment]
The message `WARN: read returned 0` originates here:
https://github.com/adrienverge/openfortivpn/blob/c3ae8b9/src/io.c#L213-L215

It looks like `openfortivpn` cannot read from `pppd`. I believe the _read()_ should not fail after the successful _select()_ call, so something's clearly wrong on this system. Perhaps the PPP options (usually under `/etc/ppp`) are not compatible, perhaps there's another issue that might show in system logs.

**Comment by fasavard** [comment]
Hi, it was indeed WARN: read returned 0
I will look into sending a system log thanks

**Comment by DimitriPapadopoulos** [comment]
By the way, [FreeNAS](https://www.freenas.org/) / [TrueNAS](https://www.truenas.com/) are based on FreeBSD so it's `ppp`, not `pppd`.

I still have no clue. Have you been able to look into system logs?

**Comment by DimitriPapadopoulos** [comment]
Is PPP enabled? I do not have much experience with FreeBSD, let alone FreeNAS, but see [28.4. Using PPP over Ethernet (PPPoE)](https://www.freebsd.org/doc/handbook/pppoe.html):
> Add the following to `/etc/rc.conf`:
> ```
> ppp_enable="YES"
> ppp_mode="ddial"
> ppp_nat="YES"	# if you want to enable nat for your local network, otherwise NO
> ppp_profile="name_of_service_provider"
> ```

**Comment by DimitriPapadopoulos** [comment]
@fasavard Have you been able to solve this? Do you agree this looks like a `ppp` issue on TrueNAS rather than an `openfortivpn` issue?

**Comment by fasavard** [comment]
Hi @DimitriPapadopoulos 
I just tried a fresh installed of true nas. No i cannot find the probleme. 

i dont know if that could help, but for the step:
```
On Linux, if you manage your kernel yourself, ensure to compile those modules:

CONFIG_PPP=m
CONFIG_PPP_ASYNC=m
```

I can do it in the main freenas shell, but inside my jail i receive an error like this:
`CONFIG_PPP=m commande not found`

**Comment by DimitriPapadopoulos** [comment]
Oh, it's not a command you can run from the command line. It's an option in the configuration file when you build the Linux kernel.

But then FreeNAS is based on FreeBSD, not on Linux. I don't know whether there are similar options to build FreeBSD with/without PPP support.

**Comment by fasavard** [comment]
Ok that is out of my capacity to debug,
if you would like to do a google meet i am available right now so we could
look into the probleme together

**Comment by DimitriPapadopoulos** [comment]
I don't have experience with building FreeBSD kernels, I'm afraid cannot help much. Perhaps the FreeNAS kernel needs to be recompiled with ppp support:, but I cannot find anything relevant, but for very old versions of FreeBSD:
https://docs.freebsd.org/doc/3.0-RELEASE/usr/share/doc/handbook/handbook202.html

**Comment by fasavard** [comment]
I opened a thread on the truenas forum
https://www.truenas.com/community/threads/ppp-support-for-forticlient-inside-a-jail.91585/

Let's see if something come up

**Comment by DimitriPapadopoulos** [comment]
I just noticed the word _jail_. By definition jails are a place of confinement. In this context jails usually limit what confined software is allowed to do. You probably need to read about FreeNAS jails and how to configure them.

See for example [14. Jails](https://www.ixsystems.com/documentation/freenas/11.2/jails.html) and properties such as `allow_tun`.

Not sure if it is **the** solution, but it should **part of** the solution.

**Comment by fasavard** [comment]
It worked !!! Thank you so much !

**Comment by DimitriPapadopoulos** [comment]
Excellent! Happy to learn it works for you. Closing the issue.

Perhaps you can update the thread in the TrueNAS forum:
https://www.truenas.com/community/threads/ppp-support-for-forticlient-inside-a-jail.91585/

**Comment by fasavard** [comment]
Just did :) Thanks again !
