### ISSUE TITLE
Ignore certificate

### ISSUE THREAD

**Issue by arrowak** [adrienverge/openfortivpn#807]
Is there any way to ignore the certificate validation and warning?

**Comment by DimitriPapadopoulos** [comment]
Bypass the gateway certificate validation? That would be a bad idea. Which warning though? If `openfortivpn` cannot validate the gateway certificate, I seem to recall it ends up in an error, not a warning.

What you can do:
* Pass the expected gateway certificate using option `--trusted-cert`.
* Define the certification authority that will be used to verify the gateway certificate using option `--ca-file`.
