### ISSUE TITLE
Tunnel is UP but no Access

### ISSUE THREAD

**Issue by nikoloutsa** [adrienverge/openfortivpn#815]
Hello, I have compiled `openfortivpn` on Fedora 33. 
I have managed to connect to VPN server and routes seems to be ok all traffic on dev ppp0.
```
INFO:  Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

but then I have no access to RDP server or any other VPN ip address.
Any hints ?

**Comment by DimitriPapadopoulos** [comment]
It could be:
* a DNS issue (in which case you should be able to connect to IP addresses but not names),
* a routing issue (in which case you cannot reach IP addresses either).

It's usually a DNS problem. Fedora 33 has [switched to `systemd-resolved` by default](https://fedoraproject.org/wiki/Changes/systemd-resolved), so I suspect it's probably a DNS issue in your case. Hard to tell without actual information on the problem.

**Comment by nikoloutsa** [comment]
Resolved , vpn server settings.
Thank you for your reply

**Comment by oOwombatOo** [comment]
> Resolved , vpn server settings.
> Thank you for your reply

It would be really nice if you provided more details than that for others experiencing the same problem.
