### ISSUE TITLE
VPN not routing

### ISSUE THREAD

**Issue by CJ1169** [adrienverge/openfortivpn#821]
*Seems* to be an identical issue to [#805](https://github.com/adrienverge/openfortivpn/issues/805)
Go easy on me, I'm not crazy familiar with networking.

```
$ sudo openfortivpn
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/5
INFO:   Got addresses: [10.ip.ip.ip], ns [10.dns.dns.dns, 172.dns.dns.dns], ns_suffix [domain]
INFO:   Negotiation complete.
INFO:   Got addresses: [10.ip.ip.ip], ns [10.dns.dns.dns, 172.dns.dns.dns], ns_suffix [domain]
INFO:   Negotiation complete.
INFO:   Negotiation complete.
Cannot determine ethernet address for proxy ARP
local  IP address 10.ip.ip.ip
remote IP address 192.0.2.1
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
WARN:   Route to gateway exists already.
WARN:   Route to gateway exists already.
WARN:   Route to gateway exists already.
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
No response to 4 echo-requests
Serial link appears to be disconnected.
Connect time 2.5 minutes.
Sent 12494 bytes, received 0 bytes.
Connection terminated.
Modem hangup
ERROR:  read: Input/output error
INFO:   Cancelling threads...
INFO:   Cleanup, joining threads...
INFO:   Setting ppp0 interface down.
INFO:   Restoring routes...
INFO:   Removing VPN nameservers...
INFO:   pppd: The link was terminated by the modem hanging up.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out. 
```

After `Cannot determine ethernet address for proxy ARP` the gateway seems to stop responding.

```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp9s0
wg    0.0.0.0         255.255.255.255 UH    0      0        0 wgpia0
10.wg.wg.wg     0.0.0.0         255.255.255.255 UH    0      0        0 wgpia0
10.wg.wg.wg    0.0.0.0         255.255.255.0   U     0      0        0 server
192.168.0.0     0.0.0.0         255.255.255.0   U     100    0        0 enp9s0
resolver1.priva 0.0.0.0         255.255.255.255 UH    0      0        0 wgpia0
```
```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp9s0
10.0.0.0        0.0.0.0         255.0.0.0       U     0      0        0 ppp0
wg    0.0.0.0         255.255.255.255 UH    0      0        0 wgpia0
10.wg.wg.wg     0.0.0.0         255.255.255.255 UH    0      0        0 wgpia0
10.wg.wg.wg    0.0.0.0         255.255.255.0   U     0      0        0 server
172.16.0.0      0.0.0.0         255.240.0.0     U     0      0        0 ppp0
192.0.2.1       0.0.0.0         255.255.255.255 UH    0      0        0 ppp0
192.168.0.0     0.0.0.0         255.255.255.0   U     100    0        0 enp9s0
192.168.0.0     0.0.0.0         255.255.0.0     U     0      0        0 ppp0
198.xxx.xxx.xxx  _gateway        255.255.255.255 UGH   0      0        0 enp9s0
resolver1.priva 0.0.0.0         255.255.255.255 UH    0      0        0 wgpia0
```

I have 2 wg vpn's running on this device. Strangely enough this particular connection worked earlier today and only now is deciding not to work. I have rebooted between then.

**Comment by DimitriPapadopoulos** [comment]
Just to make sure I understand:
* What are wg vpn's? WatchGuard VPN clients?
* Are you running multiple VPNs at the same time, Fortinet and WatchGuard?
* Which Linux distribution is this?

Generally speaking, having multiple VPNs running at the same time won't work well. Most VPN clients don't handle this correctly, _openfortivpn_ itself will probably need some refactoring to handle concurrent routing and DNS changes for each of the VPN tunnels.

**Comment by DimitriPapadopoulos** [comment]
Note that the "_Cannot determine ethernet address for proxy ARP_" message originates in `pppd`, not `openfortivpn`:
https://github.com/paulusmack/ppp/blob/ad3937a/pppd/sys-linux.c#L1934

**Comment by CJ1169** [comment]
_* What are wg vpn's? WatchGuard VPN clients?_
    * Wireguard, sorry.
_* Are you running multiple VPNs at the same time, Fortinet and WatchGuard?_
    * Yes - this worked up until today. Not sure what changed as I had a successful connection and then on the same boot, an unsuccessful connection. I'll attempt to turn off all other VPNs for more testing later.
_* Which Linux distribution is this?_
    * Arch-based, Manjaro. Using [this package](https://archlinux.org/packages/community/x86_64/openfortivpn/)

**Comment by DimitriPapadopoulos** [comment]
Well, something must have changed recently: _WireGuard_, _openfortivpn_, or system network packages. The truth is _openfortivpn_ does not support tricky routing/DNS parameters, because it still tries to support legacy Linux systems that do not support that well either (at least out-of-the box without manual fiddling). Multiple VPNs do result in tricky routing/DNS parameters. It might work, or not, depending on subtle factors. For example which VPN do you run first? Changing the order the VPNs are launched might explain the apparent change.

I would recommend against running multiple VPN clients. If you do, you may need to set routing/DNS manually.

**Comment by DimitriPapadopoulos** [comment]
Also, some VPNs might not shut down gracefully, especially if other VPNs are running. So it might work the first time but not the second time. You need to compare system routing tables before/after running a VPN client. This will help identify the VPN client that messes up the configuration and perhaps give a chance to fix things. You will need to be a bit familiar with networking.

**Comment by CJ1169** [comment]
Ah, yes - getting a graceful shutdown from everything in the routing table gets me good results. 
Hopefully that helps anyone who stumbles into this thread.

Are there any recommended configs to only route traffic in certain ip ranges (i.e. 10.0.0.0/24) through openfortivpn?

**Comment by DimitriPapadopoulos** [comment]
_openfortivpn_ applies, or at least attempts to apply the routing table pushed by the Fortinet appliance - that's what the administrators of the VPN expect and want to enforce. If you want to apply different routing parameters, you will need to set routing tables manually (together with no `--no-routes`).

For the record, you seem to have modified the setup of either _openfortivpn_ or _WireGuard_, so that it properly resets routing tables when shutting down. Which one? How?

**Comment by CJ1169** [comment]
Unsure - what I can tell you is that systemd loads my custom wg vpn (fairly basic config) first, then [PIA's](https://www.privateinternetaccess.com/) client is loaded. I then disabled my wg vpn and then PIA's then ran it and it worked fine.
This tells me that PIA's client is doing some magic. PIA's client uses wg.

**Comment by luizfelipevbll** [comment]
I had a similar problem some days ago, running `dpkg-reconfigure resolvconf` solved it :v:

**Comment by dventura** [comment]
same problem with openfortigui & ppp 2.5.0, under gentoo
all resolved adding into /etc/ppp/options:

**ipcp-accept-remote**
**plugin /lib64/pppd/2.5.0/pppoe.so**
