### ISSUE TITLE
Encountering getsockopt error on master with MacOS 10.14.6 (Mojave).

### ISSUE THREAD

**Issue by rkirkpat** [adrienverge/openfortivpn#822]
While testing the fix proposed in <https://github.com/adrienverge/openfortivpn/issues/428>, encountered this error:
```
DEBUG:  openfortivpn 1.15.0
DEBUG:  revision v1.15.0+git8.g82933b9
...
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  SO_KEEPALIVE: 0
ERROR:  getsockopt: Protocol not available
```

Had followed the steps provided in `README.md` to build using the master branch cloned today and then ran with a config file that worked fine with v1.15.0. Appears related to changes in <https://github.com/adrienverge/openfortivpn/commit/1c5ec12df8ab7e24b36d048b58ee4f44406be792>.

**Comment by DimitriPapadopoulos** [comment]
Ah, that's annoying. It probably means `TCP_KEEPALIVE` or one of the other `TCP_` macro variables is defined but not supported by _getsockopt_(). I'll probably turn this into a warning anyway, because this code has been added to print debug stuff, and I'll print the _optname_ that's causing the error.

**Comment by DimitriPapadopoulos** [comment]
Does #823 fix this issue?

Also, it should print a warning. Can you show us the warning(s)?

**Comment by DimitriPapadopoulos** [comment]
Also, does the error occur on Linux or macOS? Which exact Linux distribution or version of macOS?

**Comment by ultrafiber** [comment]
On macOS 10.15.7 it breaks on TCP_KEEPIDLE, SO_SNDBUF, and SO_RCVBUF.
The commercial client sets link rate for ppp interface to 230400 and uses a link-local address (169.254.*). I recompiled your sources with these settings and the transfers are now pretty much the same. Everything works smoothly.

**Comment by DimitriPapadopoulos** [comment]
@ultrafiber Than you for the feedback. Just to clarify:
* Does _openfortivpn_ break on `TCP_KEEPIDLE`, `SO_SNDBUF` and `SO_RCVBUF` before or after applying commit 73075e5?
* Really no difference between `2147483647` and `230400`? If so, `230400` look like a good compromise indeed, it is a well-known baud rate that should work on all supported platforms.
* Not sure about the link-local address (169.254.*). Do you mean `192.0.2.1` should be changed to `192.254.2.1` in the following line?
https://github.com/adrienverge/openfortivpn/blob/73075e5/src/tunnel.c#L236

**Comment by ultrafiber** [comment]
Yes, that was before – now it's OK. I tested only `230400` and `460800`, and there was no difference in transfer speed nor performance, so I left `230400`. About the link-local address – yes, that' the line. I was referring to the IP assigned in the commercial client. They use an IP address of that segment. Please check the following documents:
[https://en.wikipedia.org/wiki/Link-local_address](url)
[https://en.wikipedia.org/wiki/Reserved_IP_addresses](url)

**Comment by kevintosh** [comment]
Hi All!
Complete stranger here.
macOS 10.15.7, latest everything, homebrew and stuff.
I have a very specific setup in my company where I work (let's say that I connect to a VPN and within it there is another VPN to somewhere else in the world) so timeout is a thing.
On 99% of the cases the traffic flows fine, but in a very specific scenario where I download big stuff from "that other VPN" through the Company VPN to my home the connection times out.
With official FortiClient, no timeout.
It was crazy to search that, wireshark, check ciphers used, etc, until I found this. So thank you all!
Homebrew openforti was not working (no idea if it used 115200, 230400 or what) so I just downloaded and rebuilt latest 1.15 and set speed to with 20000000 (not 2147483647) and it works now, no timeout.
So I can say that it works.
Funny thing, I don't get getsockop ERR, I just get a WARN but VPN seems to be working fine so I can't be bothered to fix that.
Thank you everyone and have a nice one!

**Comment by DimitriPapadopoulos** [comment]
@kevintosh Perhaps it would be easier to open a new ticket. This one is closed, and it might be a different issue.

Note that combining VPNs is complicated and often doesn't work well. It is theoretically impossible, but it is a complex problem with edge cases everywhere, combined with the fact that DNS management on Linux is chaotic.

**Comment by kevintosh** [comment]
Oh, sorry for opening it up again.

Just wanted to mention that it worked for me and give a big thanks!

And yes, VPN within a VPN is a crazy solution, but is what we have :)

**Comment by rkirkpat** [comment]
Sorry for the delay in replying, life got in the way. Just installed 1.16.0 via brew on MacOS 10.14 (Mojave), and now those previous errors are warnings, so yes #823 did resolve this issue. 
```
WARN:   getsockopt: SO_SNDBUF: Protocol not available
WARN:   getsockopt: SO_RCVBUF: Protocol not available
INFO:   Connected to gateway.
Two-factor authentication token:
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
WARN:   getsockopt: SO_SNDBUF: Protocol not available
WARN:   getsockopt: SO_RCVBUF: Protocol not available
Mon Feb 15 18:12:02 2021 : publish_entry SCDSet() failed: Success!
Mon Feb 15 18:12:02 2021 : publish_entry SCDSet() failed: Success!
Mon Feb 15 18:12:02 2021 : Using interface ppp0
Mon Feb 15 18:12:02 2021 : Connect: ppp0 <--> /dev/ttys011
...
```

Also, I can confirm #820 resolved the transfer speed issue on this same Mac. Hence 1.16.0 works great on MacOS 10.14 (Mojave), no complaints. Thank you!

**Comment by Altap826-pro** [comment]
Hello greetings from planet Garth!!! Uncle vedo
