### ISSUE TITLE
ERROR:  pppd: The kernel does not support PPP

### ISSUE THREAD

**Issue by abubelinha** [adrienverge/openfortivpn#825]
Hello

I am trying to use openfortivpn to connect my office VPN from Android phone in my home network, with the [UserLand app](https://github.com/CypherpunkArmory/UserLAnd).
There I installed a Debian GNU/Linux 10 (buster), and then I tried to use it to connect my office I got this: 

```
me@UserLand-debian:~$  sudo apt install openfortivpn

me@UserLand-debian:~$  openfortivpn --version
1.8.1

me@UserLand-debian:~$  sudo openfortivpn gateway.myofficedomain.net:443 -u myusername -p mypassword -v

WARN:   You should not pass the password on the command line. Type it interactively or use a config file instead.
DEBUG:  openfortivpn 1.8.1
WARN:   Bad port in config file: "0".
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  server_addr: [*** whatever ***]
DEBUG:  server_port: 443
DEBUG:  gateway_addr: [*** whatever ***]
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
INFO:   Connected to gateway.
DEBUG:  Cookie: SVPNCOOKIE=[*** whatever ***]
INFO:   Authenticated.
DEBUG:  Cookie: SVPNCOOKIE=[*** whatever ***]
INFO:   Remote gateway has allocated a VPN.
DEBUG:  server_addr: [*** whatever ***]
DEBUG:  server_port: 443
DEBUG:  gateway_addr: [*** whatever ***]
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
DEBUG:  Retrieving configuration
DEBUG:  Establishing the tunnel
DEBUG:  ppp_path: /usr/sbin/pppd
DEBUG:  Switch to tunneling mode
DEBUG:  Starting IO through the tunnel
DEBUG:  ssl_read thread
DEBUG:  ssl_write thread
DEBUG:  pppd_read thread
DEBUG:  if_config thread
DEBUG:  gateway ---> pppd (12 bytes)
DEBUG:  pppd_write thread
ERROR:  read: Input/output error
INFO:   Cancelling threads...
DEBUG:  disconnecting
DEBUG:  Waiting for pppd to exit...
DEBUG:  waitpid: pppd exit status code 4
ERROR:  pppd: The kernel does not support PPP, for example, the PPP kernel driver is not included or cannot be loaded.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
DEBUG:  server_addr: [*** whatever ***]
DEBUG:  server_port: 443
DEBUG:  gateway_addr: [*** whatever ***]
DEBUG:  gateway_port: 443
DEBUG:  Gateway certificate validation succeeded.
INFO:   Logged out.
```
I don't know how to interpretate the "_ERROR:  pppd: The kernel does not support PPP_" message.
Is that an error concerning my client kernel, or the remote server? 

I googled for and I found [this](http://forums.debian.net/viewtopic.php?f=5&t=146312) and [this](https://forum.snapcraft.io/t/openfortivpn-kernel-does-not-support-ppp/17729/3) threads, where some people suggest this is a problem of the remote part ... or perhaps I am misunderstanding their answers?

Actually, the exact same command works perfectly from a Ubuntu-20 virtualbox instance in the same home network:

```
me@ubuntu20-vm:~$ sudo apt install network-manager-fortisslvpn

me@ubuntu20-vm:~$ openfortivpn --version
1.12.0

me@ubuntu20-vm:~$  sudo openfortivpn gateway.myofficedomain.net:443 -u myusername -p mypassword

WARN:   You should not pass the password on the command line. Type it interactively or use a config file instead.
INFO:   Connected to gateway.
INFO:   Authenticated.
INFO:   Remote gateway has allocated a VPN.
Using interface ppp0
Connect: ppp0 <--> /dev/pts/1
INFO:   Got addresses: [*** whatever ***], ns [*** whatever ***]
INFO:   negotiation complete
INFO:   Got addresses: [*** whatever ***], ns [*** whatever ***]
INFO:   negotiation complete
INFO:   negotiation complete
local  IP address 10.212.135.120
remote IP address 192.0.2.1
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
INFO:   Adding VPN nameservers...
INFO:   Tunnel is up and running.
```

I can connect other machines in the office network with no problem.

The openfortivpn version is different, but the connection command is identical in both cases (other than verbosity option).

So, what is the error message raised when connecting from Android-debian ?
I hope this can be solved installing some ppp related debian packages, but I am not sure what to try.
```
me@UserLand-debian:~$  pppd --version
pppd version 2.4.7

me@ubuntu20-vm:~$  pppd --version
pppd version 2.4.7 
```

I don't know how to upgrade the openfortivpn 1.8.1 version in the UserLand debian packages (perhaps this is not possible at all, but I am not sure).

I would appreciate any help you can provide
Thanks

**Comment by DimitriPapadopoulos** [comment]
The advice given in the forum thread does not make any sense.

I don't know what _UserLand_ is, but I guess the Linux kernel on your Android phone does not support PPP. Since `pppd` requires PPP support in the kernel, it cannot run.

**Comment by abubelinha** [comment]
Thanks a lot for your answer @DimitriPapadopoulos 

I guess that is the case (debian 10 Linux kernel does not support PPP).

Is there any way to tell openfortivpn to use another protocol instead of PPP?
If I understood correctly, [this thread's answer](https://unix.stackexchange.com/a/478298/87879) suggests that (although they are not talking about openfortivpn specifically).

**Comment by DimitriPapadopoulos** [comment]
The Debian 10 kernel certainly supports PPP. The Android kernel does not.

For now, _openfortivpn_ requires `pppd` for PPP support, which in turn requires PPP support in the kernel. At some point we might replace `pppd` with PPP code embedded in _openfortivpn_. We're not there yet.

**Comment by DimitriPapadopoulos** [comment]
I don't know what Google Colab provides (virtual machines?) and I don't know what you mean by “this doesn't work”. All I can say is that openfortivpn currently requires PPP kernel support. If you are certain the problem is the lack of PPP kernel support, you need to find a platform with PPP kernel support to run openfortivpn. If you are not certain that is the problem, open a new ticket and provide logs.

You may also have a look at [OpenConnect](https://gitlab.com/openconnect/openconnect), which does not require `pppd` or PPP kernel support.
