### ISSUE TITLE
path ignored?

### ISSUE THREAD

**Issue by MrManor** [adrienverge/openfortivpn#827]
Our company is currently testing (and want to change to 2fa and splittunnel) as default setup on the fortigate vpn service.

I can connect to the current solution (SMS based password) on the main address for several month, without problems.
host = sslvpn.itu.dk
port = 443

I have been told to test new setup on sslvpn.itu.dk:443**/MFAsplit** and have been experimenting with how to add the path into config or on the command line. I cant find a way - am I right in assuming that it not implemented? If possible, could that be a possible enhancement?

**Comment by DimitriPapadopoulos** [comment]
I believe **MFAsplit** is the name of a realm, in which case you can use the `realm` option.

See #789.

**Comment by MrManor** [comment]
You seems absolutely right. Thank you. 
(Cant make it work though, but that must due to other errors on my side/out setup)
