### ISSUE TITLE
192.0.2.1 → 169.254.2.1

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [adrienverge/openfortivpn#832]
Modify non-routable address used by PPP as suggested by @ultrafiber in https://github.com/adrienverge/openfortivpn/issues/822#issuecomment-763202546

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos  see also  #280

**Comment by DimitriPapadopoulos** [comment]
Indeed, it had been discussed in #280 to change `1.1.1.1` to an address in the "TEST-NET-1" block `192.0.2.0/24` reserved for documentation, as described in [RFC3330](https://tools.ietf.org/html/rfc3330), in order to avoid a collision with IP addresses already used elsewhere.

Now the idea is to change `192.0.2.1` to an address in the `169.254.0.0/16` subnet used for link-local addresses, as described in [RFC3927](https://tools.ietf.org/html/rfc3927).

The intent is to:
* avoid possible speed issues on macOS, as described in #820 / #822,
* use a subnet that has been specifically designed for that purpose.

**Comment by Altap826-pro** [comment]
PLEASE BE ADVISED THAT SHE IS UP AND KNOW WHAT SHES DOING. HER LOCATION IS ALBANY NY 868 SOS SOS 868 HELP UNDERCOVER ATTORNEY GENERAL BADGED NUMBERED CHIEF ARRESTED OFFICER LATAIE MCCALL COLLINS
