### ISSUE TITLE
Error load plug-in pppd

### ISSUE THREAD

**Issue by zingaro1972** [adrienverge/openfortivpn#838]
Hi have inserted static route into files static_route:

when start openfortivpn the routes are not loadaed and i see into log file :
/usr/local/sbin/pppd: /home/vpnconnect/config/static_route: invalid ELF header
/usr/local/sbin/pppd: Couldn't load plugin /home/vpnconnect/config/static_route

static route has a format:
#!/bin/bash
ip route add to xx.xx.xx.xx.xx/24 dev ppp0

Can you help me to solve the issuse ?

**Comment by DimitriPapadopoulos** [comment]
Is that on Linux? Which distribution? Which version of _openfortivpn_ ?

This looks like an error related to `pppd`. I noticed that `pppd` is installed in `/usr/local/sbin`, which is unusual on Linux. Have compiled/installed `pppd` yourself? In any case it looks like the configuration of `pppd` has been altered - maybe by `vpnconnect`.

**Comment by zingaro1972** [comment]
Hi, thanks for your support !
Yes I rebuld the source code before I need to rename the interfaces ....

 which pppd
/usr/local/sbin/pppd
 which openfortivpn
/sr/local/bin/openfortivpn
[pppd --version
pppd version 2.4.9
[ openfortivpn --version
1.15.0
 cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)

**Comment by DimitriPapadopoulos** [comment]
I suggest trying with the built-in `pppd` instead.
