### ISSUE TITLE
How can I use this in a script to execute commands on the remote machine after a connection is established?

### ISSUE THREAD

**Issue by justincy** [adrienverge/openfortivpn#839]
I'd like to use this to connect to a VPN during an automated deploy script. I can successfully connect to the VPN but I can't figure out how to execute any other commands afterward because the process doesn't run in the background. Is there a way to specify a command to run via a config file or cli flag? I see some issues about setting up openfortivpn as a daemon; is that the best solution?

**Comment by justincy** [comment]
I know that I can use `&` to run it in the background but then I don't know how to tell when the connection has been established and I can run other commands which require the VPN connection.

**Comment by DimitriPapadopoulos** [comment]
Running _openfortivpn_ in the background and figuring when the VPN tunnel is up are two distinct things.
* Add to `/etc/ppp/ip-up`.
* Listen to _systemd_ notifications, see #229 for example.
* Parse the `openfortivpn` output and figure when it is up, but that's probably too involved for a script!

**Comment by justincy** [comment]
Thanks @DimitriPapadopoulos. I'm using this in GitHub Actions and the step after establishing the tunnel runs for a minute or two before it uses the connection (and that's more than enough time) so I just started `openfortivpn` in the background. If my script ever changes and I need to actually detect when the tunnel is up, I'll probably try listening for systems notifications.
