### ISSUE TITLE
How to make this work on iOS?

### ISSUE THREAD

**Issue by in42** [adrienverge/openfortivpn#850]
Hi, the default Forticlient VPN iOS app is not working for me. I had used openfortivpn previously in a Arch Linux install, and it used to work. So I am wondering, can the functionality of this application be exposed as a library so that an Forticlient VPN iOS app can be created easily which will use the exposed library?

Also, how tough or easy will it be to create such an openfortivpn iOS app? Can it be done by one person i.e. me?

**Comment by DimitriPapadopoulos** [comment]
See the same question for Android: #461.
I suspect the answer you'll find there applies here. I suspect iOS is more difficult than Android.

**Comment by namaiiee2222** [comment]
Is there any update on this? does anybody have solution to connect to forti on ios?

**Comment by DimitriPapadopoulos** [comment]
Out of curiosity, doesn't the [FortiClient VPN](https://apps.apple.com/fr/app/forticlient-vpn/id1475674905) app work for you?

You could also give [OpenConnect](https://gitlab.com/openconnect/openconnect/) a try. It's certainly easier to port to iOS as it does not depend on `pppd`.
