### ISSUE TITLE
the browser cannot access the private network

### ISSUE THREAD

**Issue by linsongze** [adrienverge/openfortivpn#865]
I successfully established a connection, but the browser cannot access the private network. Do I need other settings? I am using it on macbook m1 big sur.

**Comment by romontei** [comment]
How did you fix your issue ?

**Comment by DimitriPapadopoulos** [comment]
Probably a routing/DNS issue. Have you tried the following?
```
set-dns = 0
pppd-use-peerdns = 1
```
