### ISSUE TITLE
OPENFORTIVPN 2FA EMAIL AUTHENTICATION NOT WORKING USING NETWORK MANAGER

### ISSUE THREAD

**Issue by parthrmistri** [adrienverge/openfortivpn#868]
Hi,
I'm using openfortivpn 1.8.1 on Raspberrypi OS, I am  Openfortivpn using the network manager tool but unfortunately, I can't establish VPN connection using 2FA email-based authentication although it is working good using CLI. Please help someone to give GUI option to connect VPN

**Comment by DimitriPapadopoulos** [comment]
There is no GUI in _openfortivpn_. If running _openfortivpn_ from the command line works, then this is not an _openfortivpn_ issue.

**Comment by parthrmistri** [comment]
> There is no GUI in _openfortivpn_. If running _openfortivpn_ from the command line works, then this is not an _openfortivpn_ issue.

GUI in the sense in NETWORK MANAGER there is an option to connect Openfortivpn using small tool

**Comment by DimitriPapadopoulos** [comment]
Then this does not look like an _openfortivpn_ issue. Does _openfortivpn_ work as expected from the command line?

**Comment by mrbaseman** [comment]
Looks like an issue with [Network Manager Applet  for openfortivpn](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) which is a different project

**Comment by parthrmistri** [comment]
> Then this does not look like an _openfortivpn_ issue. Does _openfortivpn_ work as expected from the command line?

Yes it works properly using Command Line even 2FA also works with CLI

**Comment by parthrmistri** [comment]
> Looks like an issue with [Network Manager Applet for openfortivpn](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) which is a different project

YES

**Comment by DimitriPapadopoulos** [comment]
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/42

**Comment by parthrmistri** [comment]
> https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues/42

I have only reported this issue please keep this open

**Comment by DimitriPapadopoulos** [comment]
It's unrelated to _openfortivpn_, sorry.
