### ISSUE TITLE
Max number of split route

### ISSUE THREAD

**Issue by Valantin** [adrienverge/openfortivpn#87]
Hi in my environment I've 96 different route to add to administrative client
the max number of route in openfortivpn is "#define MAX_SPLIT_ROUTES 32"

**Comment by Mabin-J** [comment]
Wow...
I modified 32 -> 64 in issue #110 because I needed 32-64 split route.
But your case, `MAX_SPLIT_ROUTES` is need to increase.
@mrbaseman, What do you think?

**Comment by mrbaseman** [comment]
let's finish the signal topic first, then if automatic merge fails rebase the above pull request (the changes are in different files, so it should work without rebasing, but let's see...)

**Comment by mrbaseman** [comment]
I have just landed #136 on the current master which solves this issue
