### ISSUE TITLE
Can't ./configure it under Termux

### ISSUE THREAD

**Issue by Kuchiriel** [adrienverge/openfortivpn#876]
checking for index... no
configure: error: Required function not found

**Comment by DimitriPapadopoulos** [comment]
What is Termux? Note that openfortivpn requires a reasonable GNU/Linux system with a working pppd.

You need to debug this a bit more and find why configure fails.

**Comment by DimitriPapadopoulos** [comment]
It looks like Termux lacks function _index_() in <strings.h>.

**Comment by DimitriPapadopoulos** [comment]
Actually _index_() is obsolete and has been removed from source code: #570.

**Comment by DimitriPapadopoulos** [comment]
We need to remove it from `configure.ac` too.

**Comment by DimitriPapadopoulos** [comment]
With #877 you should be able to build further, but again I'm not certain Termux provides a functional pppd.

**Comment by mrbaseman** [comment]
@DimitriPapadopoulos @adrienverge we should update the functions used in configure.ac. The list in the configure script results from the work on porting _openfortivpn_ to FreeBSD some time ago. I wasn't sure to which extend this helps. Like in the current case, on new platforms it already checks for some basic requirements at configure time, on the other hand, these errors would anyway pop up at compile time. The benefit of the configure check is that we have the HAVE_FUNCTION_XY definitions

We have two options: 

- either we update the list of used functions in the code (actually I already had the feeling that it needs to be updated from time to time)
- or we reduce the checks to the cases in which the preprocessor definitions are really used in the code (these are really few places, most distinctions are based on special checks e.g. the openssl version or the outcome of some minimal compile-test.

 Initially my hope was that the HAVE_something definitions were much more helpful. Maybe we just didn't try enough weird compilers and environments... but as long as we rely on `pppd`/`ppp` and some rt-entry-structures / `netstat` commands, we might anyway not be able to build for those platforms

**Comment by DimitriPapadopoulos** [comment]
Hi Martin, I suggest we keep the `configure.ac` file in its current state, as you had set it up. I had already cleaned it up but had forgotten removing _index_() later on. I'll review the list of functions again.

**Comment by DimitriPapadopoulos** [comment]
See pull request #879.
