### ISSUE TITLE
Hint given to `pinentry_read_password` is too generic thus over writing secrets

### ISSUE THREAD

**Issue by davidolrik** [adrienverge/openfortivpn#886]
In `userinput.c` the function `read_password` takes a `hint` parameter which is only used by `pinentry_read_password` to distinguish between secrets.

Unfortunately this `hint` is too generic.

`read_password` is called with a `hint` value of `otp`, `2fa` and `password`, and these are used by `pinentry` to store the secret securely in e.g. Keychain on macOS and similar on other OS'es.

Pinentry can only be used if a username is specified, and using different usernames for different vpn endpoints will either over write the stored secret or use a wrong secret each time you call with a different username.

I suggest that hint is changed to include the username, so the hint becomes `<username>-otp`, `<username>-2fa` and `<username>-password` (where `<username>` is the actual username specified by the user).

In addition to this there appears be bug in the way `SETKEYINFO` is called as the account value in my macOS Keychain is `ssword` and not `password` as the hint specifies.

**Comment by DimitriPapadopoulos** [comment]
The main issue makes sense. Perhaps the key should be `<username>@<host>-otp`.

About the second issue, I'm not familiar with that part of the code. Is this an issue with `openfortivpn` or with `pinentry-mac`?

**Comment by davidolrik** [comment]
Makes sense to make the hint as specific as possible.

The second issue is in `openfortivpn`, the hint given will be passed to any `pinentry-*` implementation, I just happen to use `pinentry-mac`.

I think the `uri_escape` function is broken and possibly totally unnecessary especially given how the code looks right now uri_escape of `otp`, `2fa` and `password` should yield the same output as its input.

I would go with `<username>_<host>_otp` just to keep the characters "clean", and not in need of uri escaping.

The original patch mentions `NetworkManager plugin` which might need uri escaping given that the original author of the patch implemented it.

**Comment by DimitriPapadopoulos** [comment]
I'll look into _uri_escape_(). Since the username or password might contain non-ASCII characters, isn't this function required?

**Comment by davidolrik** [comment]
It might be, I don't think Keychain on the mac needs it, but I can't speak for other platforms though.

I haven't been able to find anything with regards to the pinentry protocol that says uri encoding is needed.

Worst case, the hint will look weird when stored (uri encoded) - The important part is that it is unique and that openfortivpn serializes and de-serializes it in the same way.

**Comment by DimitriPapadopoulos** [comment]
I had a look at _uri_escape_() / _uri_unescape_() and they look just fine to me. The only issue is that [unreserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Types_of_URI_characters)  `-`, ` _`, `.`, `~` are percent-encoded while they don't need to.

**Comment by DimitriPapadopoulos** [comment]
Ah, there is an additional issue with _uri_escape_(): it does not encode non-ASCII characters properly. They need to be converted from `char` to `unsigned char` before they are fed to _sprintf_(). But then they are de-serialized it in the same way, so it shouldn't matter if the serialization is incorrect.

Example: The UTF-8-encoded string `àà` is escaped to `%FFFFFFC3%FFFFFFA9%FFFFFFC3%FFFFFFA9` while it should be escaped to `%C3%A9%C3%A9`.

So we should change this line:
```
			real_len += sprintf(&escaped[real_len], "%%%02X", string[i]);
```
to:
```
			real_len += sprintf(&escaped[real_len], "%%%02X", (unsigned char)string[i]);
```

But again, the _uri_escape_() / _uri_unescape_() functions serialize and de-serialize it in the same way, so it shouldn't be a problem. I'll fix that nevertheless when changing `otp` into `<username>_<realm>_<host>_otp`

**Comment by DimitriPapadopoulos** [comment]
And by the way, strings with non-ASCII characters should be converted  to UTF-8 before being escaped. See [Internationalized Resource Identifier](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier). On recent Linux machines,UTF-8 is the default encoding, but that's not certain.

But again, as long as strings are serialized and de-serialized on the same machine with the same default encoding, that shouldn't be an issue.

**Comment by DimitriPapadopoulos** [comment]
@davidolrik I don't think the problem is with _uri_escape_() but I don't have a mac to test. Do you have any clue where the problem might be?

 Could you print the value of `escaped` in the following part of the code?
https://github.com/adrienverge/openfortivpn/blob/289354d/src/userinput.c#L258-L260

Could it be a problem in _pinentry_exchange_() instead?

**Comment by DimitriPapadopoulos** [comment]
Oh, I think have actually found two issues that may cause memory corruption:
1. The code that reallocates the buffer that holds the escaped string might be wrong. This test does not make any sense to me:
```
if (allocated_len + 4 >= real_len) {
```
and should be changed to:
```
if (allocated_len < real_len + 4) {
```
2. Until now, the _sprintf_() call would escape non-ASCII characters into 9 characters (for example `%FFFFFFC3`for `à`) instead of 3 characters as expected (`%C3` for `à`) so the above code might have resulted in memory corruption issues anyway.

**Comment by DimitriPapadopoulos** [comment]
@davidolrik Does 48ded75e fix the second issue?

**Comment by DimitriPapadopoulos** [comment]
@davidolrik Does #890 fix the first issue?
