### ISSUE TITLE
Authentication using Pre-Shared Key?

### ISSUE THREAD

**Issue by reloadedd** [adrienverge/openfortivpn#887]
Hello, this is a question.

Is there a way to use pre-shared key authentication? I have received my vpn credentials (username / password / PSK) for a project I work, together with the instructions. But the instructions are for Windows, and I don't want to switch to Windows. The Windows program for Forticlient VPN provides the authentication method `Pre-shared key`.

Also, there seems to be a recent question posted on [Server Fault](https://serverfault.com/questions/1060897/connect-openforti-vpn-using-pre-shared-key-psk), which, unfortunately, has 2 downvotes (at the time of writing).

I don't think it matters, but I'm running Manjaro 21 with 5.11 kernel.

Thank you.

**Comment by DimitriPapadopoulos** [comment]
The Windows client often relies on IPSec. The Linux client relies on SSL. So one question is whether your VPN gateway supports VPN SSL or not.

**Comment by DimitriPapadopoulos** [comment]
From `openfortivpn --help`:
```
  -u <user>, --username=<user>  VPN account username.
  -p <pass>, --password=<pass>  VPN account password.
```
```
  --user-cert=<file>            Use specified PEM-encoded certificate if the server
                                requires authentication with a certificate.
```

**Comment by DimitriPapadopoulos** [comment]
@reloadedd Did he above suggestions help?

**Comment by reloadedd** [comment]
Sorry for the late response.

I've spoke with the project supervisor about this and told him that the Windows client relies on IPSec, while the Linux one on SSL. His response was that is possible to connect to the VPN on Linux with IPSec. From what I understood from your response, this is not possible with `openfortivpn`.

Today I should have a talk with him and help me configure the VPN for Linux. This is why I've delayed my response.

Thank you.

**Comment by DimitriPapadopoulos** [comment]
Exactly, it is possible to connect with IPsec from Linux, but neither with _openfortivpn_ nor the [official _FortClient_](https://www.forticlient.com/downloads). To connect with IPsec, you need to configure the IPsec stack yourself. The details depend on the Linux distribution and the VPN gateway. As an example, a colleague of mine had provided a recipe for Ubuntu 14.04 or 16.04 which stopped working with Ubuntu 16.04 or 18.04.

Here are a few links found with keywords `Linux IPSec configure Fortinet`:
* [OpenSwan to fortigate route-based vpn ](http://socpuppet.blogspot.com/2014/05/openswan-to-fortigate-route-based-vpn.html)
* [Configuring an IpSec VPN (fortigate client)](https://ktln2.org/2020/07/28/vpn/)
* [IPsec VPN with strongSwan to FortiGate](https://unix.stackexchange.com/questions/424163/ipsec-vpn-with-strongswan-to-fortigate)
* ...

Feel free to reopen if you're interested in VPN SSL as opposed to VPN IPsec.
