### ISSUE TITLE
WSL: VPN not reflect connection to Windows

### ISSUE THREAD

**Issue by rmomogi** [adrienverge/openfortivpn#893]
Hi guys,
I need to help with the question: I connected by openfortivpn inside WSL. But, when I open the URL to access by VPN not working. What do I do?

**Comment by DimitriPapadopoulos** [comment]
Not sure the VPN can work on Windows, it's supposed to run on Linux. It's worth trying though.

Please show configuration, output of command you run, error messages, etc. Otherwise, we cannot help. See https://github.com/adrienverge/openfortivpn/wiki#reporting-issues.

**Comment by modzilla99** [comment]
Hey there this is definitely not a problem with openfortivpn. You will need to masquerade the traffic that comes from your Windows host to the WSL2 VM. You need to set appropriate iptable rules on WSL and the correct default route on Windows

**Comment by DimitriPapadopoulos** [comment]
Or perhaps _openfortivpn_ cannot even start for lack of PPP support. We really need to see error messages.
