### ISSUE TITLE
Can not exec in Ubuntu which is created in Docker

### ISSUE THREAD

**Issue by idis573** [adrienverge/openfortivpn#895]
**Logs:**
Couldn't open the /dev/ppp device: No such file or directory
/usr/sbin/pppd: You need to create the /dev/ppp device node by
executing the following command as root:
	mknod /dev/ppp c 108 0

ERROR:  read: Input/output error
INFO:   Cancelling threads...
ERROR:  pppd: The kernel does not support PPP, for example, the PPP kernel driver is not included or cannot be loaded.
INFO:   Terminated pppd.
INFO:   Closed connection to gateway.
INFO:   Logged out.

**Comment by idis573** [comment]
root@236ebda8d3e3:/# pppd --version
pppd version 2.4.7

**Comment by DimitriPapadopoulos** [comment]
You have to investigate this, looks like a Docker issue:
```ERROR: pppd: The kernel does not support PPP```

For example see:
* [Cannot run pppd inside Docker with just --cap-add=NET_ADMIN](https://github.com/moby/moby/issues/37193)
* [Anyone managed to use pppd inside a docker container?](https://forums.docker.com/t/anyone-managed-to-use-pppd-inside-a-docker-container/27202)
* [How To Add PPP Kernel Support To OpenVZ Containers](https://www.howtoforge.com/how-to-add-ppp-kernel-support-to-openvz-containers)

**Comment by DimitriPapadopoulos** [comment]
You might try [openconnect](https://gitlab.com/openconnect/openconnect) which implements PPP instead of running _pppd_. It shouldn't need kernel PPP support.

**Comment by niggowai** [comment]
You can checkout my [Repository](https://github.com/niggowai/openforti-docker.git) which can be used to forward ports which are only accessible via a SSL-VPN. Its a docker container combined with an Iptables file to setup the necessary port forwarding. On time writing this i changed my Setup from a Raspberry Pi 4 to a M2 mac mini with Asahi linux but now the compose file does only work with the iptables disabled in contrast to a docker command where the forwarding still works...
