### ISSUE TITLE
Setting user-agent parameter through config file leads to crash

### ISSUE THREAD

**Issue by m29h** [adrienverge/openfortivpn#896]
Adding the line 
`user-agent = FortiSSLVPN (Windows NT; SV1 [SV{v=02.01; f=07;}])`
as suggested by pull request #713 
leads to a crash when running `openfortivpn`
```
free(): invalid pointer
fortivpn: line 3: 12705 Aborted
```
I noticed the problem myself in the official archlinux package of openfortivpn (1.16.0) but as you will see this is a more general issue.

While digging a little into the code and found that the root cause is that in [main.c#240](https://github.com/adrienverge/openfortivpn/blob/b4e7e5155a5df02a40c5de133f95f85be3958449/src/main.c#L240) the `.user_agent` pointer gets initialised to point to a `const char[]` on the stack that (obviously) throws an exception when the later code reading the config file value tries to free() this memory before reallocating it to the config file value.

I hot-fixed the problem by changing the above referenced line to using the `strdup()` call resulting in : 
```.user_agent = strdup("Mozilla/5.0 SV1"),```
I leave the ultimate solution to the experts here as i do not consider myself too familiar with on c memory management and struct initialization.

Best regards,
Martin

**Comment by DimitriPapadopoulos** [comment]
Memory error introduced by #752 which in turn attempts to fix #713.

**Comment by DimitriPapadopoulos** [comment]
@m29h Does the proposed patch help in your case?

**Comment by m29h** [comment]
That fixes the issue! Thank you.
