### ISSUE TITLE
No connection possible with subpath URL

### ISSUE THREAD

**Issue by modzilla99** [adrienverge/openfortivpn#906]
Hey there,

I'm trying to connect to a FortiVPN with URL that has a subpath in it ( http://example.com/subpath). That doesn't seem to work with openforti unfortunately atm since it either just disregards the /subpath or errors out immedietly.

```console
root@exampl-c-modzilla-02-li ~]# cat voplab.conf 
host = example.com/LAB
port = 443
username = modzilla
[root@example-c-modzilla-02-li ~]# openfortivpn -c voplab.conf 
...
DEBUG:  Resolving gateway host ip
ERROR:  getaddrinfo: Name or service not known
INFO:   Closed connection to gateway.
ERROR:  connect: Connection refused
INFO:   Could not log out.
[root@example-c-modzilla-02-li ~]# openfortivpn --version
1.16
```

Starting the VPN like this: `openfortivpn example.com/LAB -u modzilla` or `openfortivpn example.com/LAB -u modzilla` doesn't work either. With the first command I get the exact same problem as before and with the other one it disregards /LAB and presumably wants to connect to `example.com`.

**Comment by DimitriPapadopoulos** [comment]
The `subpath` is a `realm`, you need to break the `https://host:port/realm` URL into `host:port` and `--realm=` arguments.

**Comment by DimitriPapadopoulos** [comment]
See also #827 and #789.

**Comment by modzilla99** [comment]
Oh I'm sorry, I didn't see that and that works like a charm! Thank you for this great piece of software!

I always thought realm was the ActiveDirectory Realm or sth.
