### ISSUE TITLE
Where to download latest RPM package for openfortivpn?

### ISSUE THREAD

**Issue by tanvp112** [adrienverge/openfortivpn#925]
It seems like last openfortivpn built for RPM has stopped at version 1.14.1. Is it the only way to install a higher version than this build from source?

Thanks!

**Comment by DimitriPapadopoulos** [comment]
The answer depends on the Linux distribution. We do not provide RPM packages ourselves.

**Comment by g150421** [comment]
Ok, that means for Fedora distro we need to build from source, is that correct?

**Comment by tanvp112** [comment]
fedora/centos/rhel?

**Comment by DimitriPapadopoulos** [comment]
Have a look at the Fedora/CentOS/RHEL sites. I believe the maintainers (which I'm perhaps part of) don't have time to package a new RPM these days. As for myself, I have switched to Ubuntu, so I would have a hard time preparing new RPM packages. I'd need to install a Fedora virtual machine.

**Comment by tanvp112** [comment]
checked already... 1.14.1 is the last. only arch/opensuse have regular update for openfortivpn. looks like the only way is build from source.

**Comment by ehaupt** [comment]
[Repology](https://repology.org/project/openfortivpn/versions) has a good overview.

**Comment by tanvp112** [comment]
> [Repology](https://repology.org/project/openfortivpn/versions) has a good overview.

Nice one, thanks!

**Comment by adrienverge** [comment]
Hello, I just created official 1.17.0 packages for Fedora 33, Fedora 34, Fedora rawhide, CentOS 7 and CentOS 8. They should be available in "testing" repos today, and in "stable" in a week or two.

**Comment by DimitriPapadopoulos** [comment]
@adrienverge Were you able to [re-enable resolvconf support for Fedora packages](https://bugzilla.redhat.com/show_bug.cgi?id=1983017)?

**Comment by adrienverge** [comment]
@DimitriPapadopoulos oops I didn't think about that, thanks a lot for the kind reminder :pray: 
I'll remove `--with-resolvconf=DISABLED --disable-resolvconf"` and create new releases today.

**Comment by DimitriPapadopoulos** [comment]
@adrienverge  Re-enable resolvconf support only for Fedora, which now has systemd-resolved enabled by default, not for Centos.

**Comment by adrienverge** [comment]
> @adrienverge Re-enable resolvconf support only for Fedora, which now has systemd-resolved enabled by default, not for Centos.

Arg! I will create another release, then.

> By the way, are there distinct Rocky Linux packages, now that Centos' end is near?

Good question. I haven't read much about this, but I think Rocky Linux systems can enable EPEL repos, just like CentOS did, and openfortivpn is packaged inside EPEL (it's not in CentOS/RHEL "base" packages, one needs to install EPEL repos first). So I'm not sure distinct Rocky Linux packages are needed.
