### ISSUE TITLE
Certificate Authentication Only Possible?

### ISSUE THREAD

**Issue by akashrpatel** [adrienverge/openfortivpn#937]
Hello,

I have the FortiClientVPN working with user certificate authentication (no password, no 2FA) and was wondering if would be possible for openfortivpn to do the same.

The command i'm running is:
openfortivpn vpn.company.com:10443 --user-cert=somecertificatechain.cer

When I attempt to connect I get the following error:
ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.

**Comment by DimitriPapadopoulos** [comment]
Have you tried with `--user-key`?
```
  --user-cert=pkcs11:           Use smartcard. Takes also partial or full PKCS11-URI.
  --user-key=<file>             Use specified PEM-encoded key if the server requires
                                authentication with a certificate.
```

**Comment by marcelstoer** [comment]
I feel this should be closed.
