### ISSUE TITLE
MacOSX forticlient deletes default route

### ISSUE THREAD

**Issue by mkayontour** [adrienverge/openfortivpn#938]
Hi, this is something which wonders me I previously used the forticlient the official one. This started to delete my default route, so as long as I added it fast enough before running into a timeout it successful established a connection. 

Now I tried the openfortivpn and I get the same result. I also tried using --no-routes, but still my routes are being configured and my default route is lost. 

```
DEBUG:  Got Address: 172.xxx
DEBUG:  Interface Name: ppp0
DEBUG:  Interface Addr: 172.xxx
INFO:   Interface ppp0 is UP.
INFO:   Setting new routes...
DEBUG:  ip route show to 0.0.0.0/0.0.0.0 dev !ppp0
DEBUG:  netstat_path: /usr/sbin/netstat
DEBUG:  Route not found.
WARN:   Could not get current default route (Route not found).
WARN:   Protecting tunnel route has failed. But this can be working except for some cases.
DEBUG:  /sbin/route -n add -net 172.xxx -netmask 255.255.128.0 -interface ppp0
```

Edit: 
Version Used.:
```
openfortivpn: 1.17.1
Mac BigSur: 11.5.2
```

**Comment by DimitriPapadopoulos** [comment]
How do you use `openfortivpn`? Options?

If you're using `--no-routes` it might be a `pppd` issue.

It's hard to tell without seeing actual routes before and after, and routes sent by the gateway. Routes can be obfuscated, but in a sensible and consistent way.

**Comment by mkayontour** [comment]
Basically there's not much used in this case. 
`sudo openfortivpn hostname:4443 -u myuser --no-routes`

Those are my routes before. 

```
default via 192.168.2.1 dev en0
127.0.0.0/8 via 127.0.0.1 dev lo0
127.0.0.1/32 via 127.0.0.1 dev lo0
169.254.0.0/16 dev en0  scope link
192.168.2.0/24 dev en0  scope link
192.168.2.1/32 dev en0  scope link
192.168.2.106/32 dev en0  scope link
192.168.33.0/24 dev vboxnet  scope link
192.168.50.0/24 dev vboxnet  scope link
224.0.0.0/4 dev en0  scope link
255.255.255.255/32 dev en0  scope link
```

After I established the the VPN connection.:
```
default via link#27 dev ppp0
10.0.1.0/24 via ppp0 dev ppp0
10.0.10.0/24 via ppp0 dev ppp0
10.10.0.0/16 via ppp0 dev ppp0
10.27.0.0/16 via ppp0 dev ppp0
10.77.11.0/24 via ppp0 dev ppp0
10.77.12.0/24 via ppp0 dev ppp0
10.77.13.0/24 via ppp0 dev ppp0
10.77.27.0/24 via ppp0 dev ppp0
10.235.38.0/24 via ppp0 dev ppp0
127.0.0.0/8 via 127.0.0.1 dev lo0
127.0.0.1/32 via 127.0.0.1 dev lo0
169.254.0.0/16 dev en0  scope link
169.254.2.1/32 via 172.18.76.9 dev ppp0
185.11.252.22/32 via ppp0 dev ppp0
192.168.2.0/24 dev en0  scope link
192.168.2.1/32 dev en0  scope link
192.168.2.106/32 dev en0  scope link
192.168.33.0/24 dev vboxnet  scope link
192.168.50.0/24 dev vboxnet  scope link
192.168.111.0/24 via ppp0 dev ppp0
192.168.200.0/21 via ppp0 dev ppp0
192.168.242.0/23 via ppp0 dev ppp0
224.0.0.0/4 dev en0  scope link
224.0.0.0/4 dev ppp0  scope link
255.255.255.255/32 dev en0  scope link
255.255.255.255/32 dev ppp0  scope link
```

Do you mean the gateway will `force push` those routes without my consent :D

**Comment by DimitriPapadopoulos** [comment]
Well, FortClient and openfortivpn are supposed to modify routes as specified by the VPN gateway, at least **by default**  (without `--no-routes`). That's what VPN vendors sell, and that may be part of the agreement you have with your VPN provider.

If you do use `--no-routes`, I'm surprised. We also pass `nodefaultroute` to `pppd`.

See [Debugging _openfortivpn_](https://github.com/adrienverge/openfortivpn/wiki) and [Reporting issues](https://github.com/adrienverge/openfortivpn/wiki).

**Comment by mkayontour** [comment]
Oh thanks, this log showed me that it runs the ppp/ip-up config and that contained some config provided by my company, which deletes and recreates my routes. 

Thanks for your help! And keep up the good work!

**Comment by DimitriPapadopoulos** [comment]
Ah, so it was `pppd` all along. Thank you for sharing!
