### ISSUE TITLE
Disable set static route to VPN Peer

### ISSUE THREAD

**Issue by lcblucas** [adrienverge/openfortivpn#939]
Hi all,

I need to know (and if possible) to disable openfortivpn from creating static route to IP VPN peer after tunnel established. Routes to subnets / hosts behind the tunnel must continue to be created.

Take a look at the debug:
```
DEBUG:  ip route show to 0.0.0.0/0.0.0.0 dev !tun0
DEBUG:  ip route show to **IP PEER VPN**/255.255.255.255 dev tun0
DEBUG:  Route not found.
DEBUG:  ip route show to **IP PEER VPN**/255.255.255.255 dev !tun0
DEBUG:  Setting route to vpn server...
DEBUG:  ip route show to **IP PEER VPN**/255.255.255.255 via 172.31.100.1 dev eth0

DEBUG:  ip route add to **IP PEER VPN**/255.255.255.255 via 172.31.100.1 dev eth0 --- >>> **I need to disable ONLY THIS ROUTE!**

DEBUG:  ip route add to 10.212.134.200/255.255.255.255 dev tun0
DEBUG:  ip route add to 10.212.134.192/255.255.255.248 dev tun0
DEBUG:  ip route add to 10.212.134.128/255.255.255.192 dev tun0
DEBUG:  ip route add to 10.212.134.112/255.255.255.240 dev tun0
DEBUG:  ip route add to 10.212.134.104/255.255.255.248 dev tun0
DEBUG:  ip route add to 10.212.134.100/255.255.255.252 dev tun0
DEBUG:  ip route add to 100.100.100.100/255.255.255.255 dev tun0
```

Thanks and regards.

**Comment by DimitriPapadopoulos** [comment]
`--no-routes`?

**Comment by DimitriPapadopoulos** [comment]
Then you're responsible for creating whatever routes you need.

**Comment by lcblucas** [comment]
Thanks Dimitri. Then I need to create this routes outside from openfortivpn tool, right? Using scripts, etc... Is it correct?

**Comment by DimitriPapadopoulos** [comment]
Yes, absolutely. I'm afraid it's not straightforward, but you will find some information in the wiki:
https://github.com/adrienverge/openfortivpn/wiki
* Using pppd ip-up / ip-down scripts
* How to add specific routes using pppd
