### ISSUE TITLE
Keep alive stopped working in 1.17.1 ?

### ISSUE THREAD

**Issue by msfuentess** [adrienverge/openfortivpn#942]
Hi 
Just updated my Openwrt router to the latest trunk, and saw that openfortivpn 1.17.1 did not recover the connection after any disconnect.
I tried several things but found that by just replacing the main binary (/usr/bin/openfortivpn) to 1.15.0 things went back to normal.
I can check any ideas you may have.

Manuel F.

**Comment by DimitriPapadopoulos** [comment]
Yes, that's the point, they look like they're not formatted like code. And for some reason, I cannot edit the messages to insert ` ``` ` myself. Here is screen capture of what I see:

![firefox_linux](https://user-images.githubusercontent.com/3234522/138087903-8ea6d157-9289-4ce9-af80-cb408741e12c.png)

**Comment by DimitriPapadopoulos** [comment]
Ah, I thought you were already using `--persistent`! If not, I don't know what you mean by "_keep alive_". It looks like an OpenWRT feature, and if so, you're probably experiencing an OpenWRT problem too.

I guess `/lib/netifd/proto/openfortivpn.sh` is this OpenWRT start/restart script:
https://github.com/openwrt/packages/blob/master/net/openfortivpn/files/openfortivpn.sh
So again, it's probably an OpenWRT problem.

Finally, I would recommend against using `--persistent`. Feel free to use it if it helps, but I wouldn't add it to the standard OpenWRT start/restart script. I'd rather fix [`openfortivpn-wrapper`](https://github.com/openwrt/packages/blob/master/net/openfortivpn/files/openfortivpn-wrapper) and [`openfortivpn.sh`](https://github.com/openwrt/packages/blob/master/net/openfortivpn/files/openfortivpn.sh) so they work without `--persistent`. I would look into the `openfortivpn`  exit status code, which may have changed. See for example #798, merged between 1.15.0 and 1.16.0.

**Comment by msfuentess** [comment]
Remember that --persistent was never passed, (not even 1.15) or always used
the default value, so I looked for the problem elsewhere.
In fact maybe I tried persistent in the the early stages (without netifd in
OpenWRT at that time) to no avail when timeouts occurred. So I had to write
my own script and forget persistent forever.
I'm fine for now, I'll adapt openfortivpn.sh for my needs, and may take a
look at the wrapper, but as you may have realized I'm not a developer.

 Thanks for everything.
