### ISSUE TITLE
Could not authenticate to gateway. Please check the password, client certificate, etc.

### ISSUE THREAD

**Issue by seventhsite** [adrienverge/openfortivpn#947]
From the #946 

My config:

```
host = x.x.x.x
port = yyy
username = seventh
password = mypass
trusted-cert = ...54acd
```
Then:

```
root@7thUbuntu:/home/seventh# openfortivpn -v
DEBUG:  openfortivpn 1.12.0
DEBUG:  Loaded config file "/etc/openfortivpn/config".
DEBUG:  Loaded password from config file "/etc/openfortivpn/config"
DEBUG:  Config host = "x.x.x.x"
DEBUG:  Config realm = ""
DEBUG:  Config port = "yyy"
DEBUG:  Config username = "seventh"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: x.x.x.x
DEBUG:  server_port: yyy
DEBUG:  gateway_addr: x.x.x.x
DEBUG:  gateway_port: yyy
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Connected to gateway.
ERROR:  Could not authenticate to gateway. Please check the password, client certificate, etc.
DEBUG:  HTTP status code 405
INFO:   Closed connection to gateway.
DEBUG:  server_addr: x.x.x.x
DEBUG:  server_port: yyy
DEBUG:  gateway_addr: x.x.x.x
DEBUG:  gateway_port: yyy
DEBUG:  Setting cipher list to: HIGH:!aNULL:!kRSA:!PSK:!SRP:!MD5:!RC4
DEBUG:  Gateway certificate validation failed.
DEBUG:  Gateway certificate digest found in white list.
INFO:   Logged out.
```

I succefully connected with this credentials with FortiClient but with options "Client certificate: none" and "Do not warn invalid server certificate". 
We also have 2FA with code sended to e-mail.

**Comment by DimitriPapadopoulos** [comment]
> Is there a deb-package for 1.17.1 or I have to install from source?

I don't think there's a deb package, the policy of Debian is not to upgrade packages after the initial release, unless there are security or other critical issues. And indeed openfortivpn 1.12.0 was released on February 2020.

**Comment by DimitriPapadopoulos** [comment]
> I have a constant password, which I writed in config file and also I supposed to provide a code from email. But there is no mail and no ask for it.

So FortiClient does ask for the second password, doesn't it? I don't have a VPN server to test 2FA to test myself - actually I do have one but it works differently and doesn't require to enter a second code.

I guess openfortivpn doesn't understand that the VPN server requires a second code. It would help if you could send a more verbose log (`-v -v`). I'm specially interested in the server replies to our request, for example the XML configuration sent by the server, and the authentication dialog between the server and the client.

**Comment by lucax88x** [comment]
Unfortunately I started having this error also, exactly same logs as @seventhsite .

It worked flawlessly for more than 1 year, so I guess IT guys have enabled / disabled something.

I tried with OpenConnect as you suggested, but I get the same error, sadly.

**Comment by DimitriPapadopoulos** [comment]
Then may I suggest you create an [OpenConnect issue](https://gitlab.com/openconnect/openconnect/-/issues) too? There might be more resources in that project (or not) to fix this issue.

**Comment by mrbaseman** [comment]
If a client certificate is involved, that one might have expired? - something which has happened to me recently and took me a while to figure out the root cause

**Comment by lucax88x** [comment]
Was thinking the same, but it's not expired, I double checked that.
And unfortunately / fortunately, using official FortiClient everything works fine. I'm forced to use this one for now.

**Comment by LebedevV** [comment]
I have the same issue with exactly the same log since our organization moved to FortiClient v7 with enforced 2FA. OpenConnect is not working for me, as well...

**Comment by ablanco-stratio** [comment]
Same issue here, something have been changed in the forticlient server that I'm unable to log-in using the same password, certificate,etc that I have been using until now. The official forticlient works well (and I haven't updated it)

**Comment by DimitriPapadopoulos** [comment]
I recommend you give [OpenConnect](https://gitlab.com/openconnect/openconnect) a try (you will have to build yourself from the latest sources) and, if it doesn't work, file a ticket there too. They might be able to fix this sooner than us - or not.

**Comment by kkurczewski** [comment]
Hello, I just upgraded my system from Ubuntu 20.04 to 22.04 and after year of usage got same error I think. I don't know if this was caused by dependency bump or something else but I want to share my findings.

My current version is:
```
$ openfortivpn --version
1.17.1
```

(Could be also same root cause as in https://github.com/adrienverge/openfortivpn/issues/909).

***

Once script stopped working I tried to get working connection using GUI available in Ubuntu and finally I managed to connect to VPN. I believe GUI uses [this project](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) used under hood. What is interesting, it depends on openfortivpn so that means that it should work for CLI as well!

Notable difference is that GUI asks for both password and OTP in one go. So I did a test and ran two commands, one with OTP passed manually and second one without it:
```
sudo openfortivpn <host> -u <user> --password <password> -o <otp>
sudo openfortivpn <host> -u <user> --password <password>
```
First command successfully connected to VPN. Second one didn't asked for OTP and obviously failed. I guess GUI just passes both inputs in one go and therefore that is why it is working. Regarding CLI, I did `-v -v` to check how payload differs in those requests and it looks like this:
```
# login with password
POST /remote/logincheck HTTP/1.1
username=<username>&credential=<credential>&realm=&ajax=1

# some magic numbers
HTTP/1.1 200 OK
Set-Cookie:  SVPNCOOKIE=; path=/; expires=...;
Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=...; 

ret=2,reqid=<reqid>,polid=<polid>,grp=SSLVPN_BaseAccess,portal=tunnel-access,magic=<magic>,tokeninfo=ftm_push,chal_msg=

# OTP challenge
POST /remote/logincheck HTTP/1.1
username=<user>&realm=&reqid=<reqid>&polid=<polid>&grp=SSLVPN_BaseAccess&portal=tunnel-access&peer=&code=<code>&code2=&magic=<magic>
# OTP code is passed here!

HTTP/1.1 200 OK
Set-Cookie: SVPNCOOKIE=<somecookie>; path=/; secure;
```

For comparison, command without OTP specified fails like this:
```
# OTP challenge
POST /remote/logincheck HTTP/1.1
username=<user>&realm=&reqid=<reqid>&polid=<polid>&grp=SSLVPN_BaseAccess&portal=tunnel-access&peer=&ftmpush=1
# didn't asked me for OTP code

HTTP/1.1 405 Method Not Allowed
Set-Cookie:  SVPNCOOKIE=; path=/; expires=...;
Set-Cookie: SVPNNETWORKCOOKIE=; path=/remote/network; expires=...; 
```

Hope that helps.

**Comment by kkurczewski** [comment]
Okay, seems this is not a bug but an feature implemented in https://github.com/adrienverge/openfortivpn/commit/2f16d964560d9b00acbf7bfc7131a0ac40c688f2.

From commit description:
> Extend OTP support to also allow using FTM push
If the server claims it's supported (from the initial login response);
send the request for a push notification.
>
> If an OTP is specified using `--otp=` or through the configuration
file, the given OTP will be used, no matter what the server initially
responded with.
>
> Use `--no-ftm-push` to disable this altogether.

So adding `--no-ftm-push` at the end of command end will make it ask for OTP as usual.

**Comment by bruno-eurodyn** [comment]
Hi,
using --no-ftm-push works, but I have to enter manually the token.
It works before ( send a push to my phone), so maybe it's a bug.
I'm using Ubuntu 22.04.1 LTS and  openfortivpn 1.17.1
