### ISSUE TITLE
SO_* options should use SOL_SOCKET instead of the IPPROTO_TCP

### ISSUE THREAD

**Issue by dront78** [adrienverge/openfortivpn#958]
man 7 socket

Socket options
       The socket options listed below can be set by using setsockopt(2)
       and read with getsockopt(2) with the socket level set to
       SOL_SOCKET for all sockets.

SO_SNDBUF
SO_RCVBUF
SO_KEEPALIVE

please correct tcp_getsockopt implementation or implement another function to retrieve the socket values.

**Comment by DimitriPapadopoulos** [comment]
Are you reading the latest sources from the `@master` branch?

**Comment by dront78** [comment]
no, it's 1.17.1. thank you.
