### ISSUE TITLE
Timeout after 10 seconds makes MFA with prompt on smartphone difficult

### ISSUE THREAD

**Issue by KarelDemeyer** [adrienverge/openfortivpn#959]
My company uses Duo (https://duo.com/) for 2 factor authentication on i.a. the Fortinet VPN login. When attempting to connect, a prompt on the companion smarthphone app asks to authenticate.
However, it seems when using openfortivpn, the connection is closed after 10 seconds leaving little time to choose 'Accept' on the prompt as it takes a few seconds for the request to arrive on the smartphone, to unlock the smartphone, open the notification and then choose the right option. 
Would it be possible to extend the timeout or to make this configurable? I am using the Network Manager plugin.

Thank you for your valuable OSS contributions.

**Comment by DimitriPapadopoulos** [comment]
I do not know of any timeout in `openfortivpn`.

Perhaps the VPN server has a timeout. If so, we may need to keep the connection busy. To confirm that, please run `openfortivpn -v -v ...` from the command line - for the purpose of debugging. I would be interested in the (redacted) output, and especially a similar line:
```
<?xml version='1.0' encoding='utf-8'?><sslvpn-tunnel ver='2' dtls='1' patch='1'><dtls-config heartbeat-interval='10' heartbeat-fail-count='10' heartbeat-idle-timeout='10' client-hello-timeout='10' /><tunnel-method value='ppp' /><tunnel-method value='tun' /><fos platform='FGT60D' major='6' minor='00' patch='13' build='0443' branch='0443' /><client-config save-password='off' keep-alive='off' auto-connect='off' /><ipv4><dns domain='xxxx.xx xxx.xxx.xx xxx.xx' /><dns ip='xxx.xx.xxx.xxx' /><dns ip='xxx.xxx.xxx.xxx' /><assigned-addr ipv4='xx.xxx.xxx.xxx' /></ipv4><idle-timeout val='0' /><auth-timeout val='28800' /></sslvpn-tunnel>
```

You may also give [OpenConnect](https://gitlab.com/openconnect/openconnect) a try, but you'll need to compile the `master` branch for Fortinet support.

**Comment by DimitriPapadopoulos** [comment]
Then I guess this is a [NetworkManager-fortisslvpn](https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn) issue. You should create a ticket here:
https://gitlab.gnome.org/GNOME/NetworkManager-fortisslvpn/-/issues
