### ISSUE TITLE
Post processing of routes and DNS

### ISSUE THREAD

**Issue by pschichtel** [adrienverge/openfortivpn#960]
What I'm requesting is basically https://github.com/adrienverge/openfortivpn/wiki#using-pppd-ip-up--ip-down-scripts, buth without the need for `--no-dns` and `--no-routes`.

The VPN I need to connect to has a log of routes and search domains, however there is exist a few problems with that configuration that can't easily be solved on the VPN server side. So instead I want to "post process" the routes and search domains I receive from the VPN. Add additional routes, remove routes, add additional search domains, remove search domains.

Currently I'd need to duplicate all routes and search domains before being able to add my own.

**Comment by pschichtel** [comment]
I don't think I follow

**Comment by pschichtel** [comment]
My point is: I explicitly don't want --no-dns and --no-routes. Want to take what the VPN server provides me, but just customize it a little.

The problem with the pppd script is that they are executed before openfortivpn sets the routes and domains, so the script can't change anything about the values.

**Comment by DimitriPapadopoulos** [comment]
Then I believe the best solution would be to implement the above functionality, where `openfortivpn` calls an external script to set routing and DNS.

**Comment by pschichtel** [comment]
Yes I think that would be the most straight forward solution. Similar to wireguard'a PostUp option or the existing pppd scripts (just executed later).
