### ISSUE TITLE
Openfortivpn fails to start with PrivateTmp=true

### ISSUE THREAD

**Issue by maxsatula** [adrienverge/openfortivpn#961]
https://github.com/adrienverge/openfortivpn/blob/d1b2801b6e866411398414be199c7648eb3e620b/lib/systemd/system/openfortivpn%40.service.in#L8

> pppd[20653]: pppd 2.4.7 started by root, uid 0
> pppd[20653]: Couldn't set tty to PPP discipline: Operation not permitted
> openfortivpn[20482]: Couldn't set tty to PPP discipline: Operation not permitted

A workaround is to remove PrivateTmp line

> Oracle Linux Server release 8.5
> Linux **** 5.4.17-2136.301.1.3.el8uek.aarch64 #hash#2 SMP Mon Nov 29 21:08:57 PST 2021 aarch64 aarch64 aarch64 GNU/Linux
> openfortivpn-1.17.0-3.el8.aarch64

**Comment by DimitriPapadopoulos** [comment]
According to the [systemd.exec(5) man page](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateTmp=):
> `PrivateTmp=`
> 
> Takes a boolean argument. If true, sets up a new file system namespace for the executed processes and mounts private `/tmp/` and `/var/tmp/` directories inside it that are not shared by processes outside of the namespace. This is useful to secure access to temporary files of the process, but makes sharing between processes via `/tmp/` or `/var/tmp/` impossible. If true, all temporary files created by a service in these directories will be removed after the service is stopped. Defaults to false. It is possible to run two or more units within the same private `/tmp/` and `/var/tmp/` namespace by using the `JoinsNamespaceOf=` directive, see [systemd.unit(5)](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#) for details. This setting is implied if `DynamicUser=` is set. For this setting the same restrictions regarding mount propagation and privileges apply as for `ReadOnlyPaths=` and related calls, see above. Enabling this setting has the side effect of adding `Requires=` and `After=` dependencies on all mount units necessary to access `/tmp/` and `/var/tmp/`. Moreover an implicitly `After=` ordering on [systemd-tmpfiles-setup.service(8)](https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles-setup.service.html#) is added.

From the above description, it remains unclear to me whether the error with `PrivateTmp=true` is a feature or a bug.

**Comment by maxsatula** [comment]
I'm not saying let's remove `PrivateTmp=true` and we are done, that's why I used a *workaround* word in my first message, not a *solution*.

Let's step back and see if it is a feature or a bug.

**Actual behavior:** openfortivpn supplied with an operating system fails to start with _Operation not permitted_ error

**Expected behavior:** openfortivpn works out-of-box the way it is supplied (including binaries and systemd units)

Per the two lines above, it definitely sounds as a bug.

**Comment by DimitriPapadopoulos** [comment]
I'm not convinced. Perhaps the question could be rephrased: A bug/feature in file `openfortivpn@.service.in` bundled with openfortivpn or a in systemd?

**Comment by DimitriPapadopoulos** [comment]
Also:
* When you write "openfortivpn supplied with an operating system". Which operating system? CentOS 8 I guess?
* When you write "openfortivpn works out-of-box", does this mean this looks like a packaging error?

**Comment by maxsatula** [comment]
`openfortivpn@.service.in` file is a part of this repository, and it is highly unlikely the root cause is a systemd bug. So I would bet this issue has been created in the right place.

- Oracle Linux Server release 8.5, aarm64 architecture, as specified in my first message
- No, "openfortivpn works out-of-box" expectation is just about being able to run openfortivpn via systemd using provided unit file with zero modifications

**Comment by DimitriPapadopoulos** [comment]
Yet I cannot decide whether `PrivateTmp=true` in `openfortivpn@.service.in` is wrong or correct from the systemd documentation. The `pppd` error message isn't very helpful either.
* [systemd.exec(5)](https://www.freedesktop.org/software/systemd/man/systemd.exec.html)
* [New Red Hat Enterprise Linux 7 Security Feature: PrivateTmp](https://access.redhat.com/blogs/766093/posts/1976243)
* [systemd for Administrators, Part XII](https://0pointer.de/blog/projects/security.html)

Using PrivateTmp=True is recommended, but if  `pppd` cannot work with it, I'll remove i - but I would like to understand why `pppd` fails.

**Comment by DimitriPapadopoulos** [comment]
I don't know much about Oracle Linux, it is not a common distribution. Might be a SELinux problem. Anything in the logs?

**Comment by DimitriPapadopoulos** [comment]
It seems to be working on Ubuntu 20.04 for example, the only caveat is that `systemctl status openfortivpn@test.service` does not return and needs to be interrupted with `Ctrl+C`. Will have to look into it.
```
# systemctl start openfortivpn@test.service
^C
# 
# systemctl status openfortivpn@test.service
● openfortivpn@test.service - OpenFortiVPN for test
     Loaded: loaded (/lib/systemd/system/openfortivpn@.service; disabled; vendor preset: enabled)
     Active: activating (start) since Wed 2021-12-08 09:11:22 CET; 18s ago
       Docs: man:openfortivpn(1)
   Main PID: 8200 (openfortivpn)
      Tasks: 6 (limit: 18969)
     Memory: 1.8M
     CGroup: /system.slice/system-openfortivpn.slice/openfortivpn@test.service
             ├─8200 /my/path/openfortivpn/bin/openfortivpn -c /my/path/openfortivpn/etc/openfortivpn/test.conf
             └─8201 /usr/sbin/pppd 230400 :169.254.2.1 noipdefault noaccomp noauth default-asyncmap nopcomp receive-all nodefaultroute nodetach lcp-max-configure 40 mru 1354 logfd 2

déc. 08 09:11:22 is233895 openfortivpn[8200]: INFO:   Negotiation complete.
déc. 08 09:11:24 is233895 openfortivpn[8200]: INFO:   Negotiation complete.
déc. 08 09:11:24 is233895 openfortivpn[8201]: local  IP address 10.212.134.200
déc. 08 09:11:24 is233895 openfortivpn[8201]: remote IP address xxx.xxx.x.x
déc. 08 09:11:24 is233895 pppd[8201]: local  IP address 10.212.134.200
déc. 08 09:11:24 is233895 pppd[8201]: remote IP address xxx.xxx.x.x
déc. 08 09:11:24 is233895 openfortivpn[8200]: INFO:   Interface ppp0 is UP.
déc. 08 09:11:24 is233895 openfortivpn[8200]: INFO:   Setting new routes...
déc. 08 09:11:24 is233895 openfortivpn[8200]: INFO:   Adding VPN nameservers...
déc. 08 09:11:24 is233895 openfortivpn[8200]: INFO:   Tunnel is up and running.
# 
# systemctl stop openfortivpn@test.service
# 
# systemctl status openfortivpn@test.service | cat
● openfortivpn@test.service - OpenFortiVPN for test
     Loaded: loaded (/lib/systemd/system/openfortivpn@.service; disabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Wed 2021-12-08 09:12:52 CET; 2min 13s ago
       Docs: man:openfortivpn(1)
    Process: 8200 ExecStart=/my/path/openfortivpn/bin/openfortivpn -c /mu/path/openfortivpn/etc/openfortivpn/test.conf (code=exited, status=0/SUCCESS)
   Main PID: 8200 (code=exited, status=0/SUCCESS)

déc. 08 09:12:52 is233895 pppd[8201]: Modem hangup
déc. 08 09:12:52 is233895 pppd[8201]: Connection terminated.
déc. 08 09:12:52 is233895 pppd[8201]: Exit.
déc. 08 09:12:52 is233895 openfortivpn[8200]: INFO:   pppd: The link was terminated by the modem hanging up.
déc. 08 09:12:52 is233895 openfortivpn[8200]: INFO:   Terminated pppd.
déc. 08 09:12:52 is233895 openfortivpn[8200]: INFO:   Closed connection to gateway.
déc. 08 09:12:52 is233895 openfortivpn[8200]: INFO:   GET /remote/logout
déc. 08 09:12:52 is233895 openfortivpn[8200]: INFO:   Logged out.
déc. 08 09:12:52 is233895 systemd[1]: openfortivpn@test.service: Failed with result 'timeout'.
déc. 08 09:12:52 is233895 systemd[1]: Failed to start OpenFortiVPN for test.
#

**Comment by maxsatula** [comment]
> I don't know much about Oracle Linux, it is not a common distribution. Might be a SELinux problem. Anything in the logs?

I would disagree, Oracle Linux is quite popular, based on RedHat and competes with it. Per some googled ratings, it is in [top 10](https://tecadmin.net/best-linux-server-distributions/), and I assume it is a number one in Oracle Cloud. Whatever, sorry about offtopic.

Regarding the logs, I also had another issue described in #563, and already applied a SElinux policy recommended in that issue, so it is irrelevant to the current issue. Nothing else in the logs besides attempting to write into `resolv.conf`

One thing makes it more complicated to provide more details: when I return `PrivateTmp` back into the unit file (not forgetting to reload systemd daemon), I cannot reproduce the error anymore, so apparently it does something persistent on the first run and requires a fresh system to reproduce. ☹

**Comment by DimitriPapadopoulos** [comment]
I wouldn't know where to find reliable figures on distro popularity. [Distrowatch.com](https://distrowatch.com/table.php) measures hits on a minor website. [Oracle is #89](https://distrowatch.com/table.php?distribution=oracle) (last 12 months), whatever that means. Obviously that site focuses on desktops, not on servers, clouds, or IoT. Therefore those figures are far from reliable. But I don't know where to find more reliable ones.

Anyway, it could still be a SELinux issue, but then I would expect it to print some message like:
```
SELinux is preventing pppd from ... access on the file ...
...
...
```

I would like to debug this, but I cannot reproduce this issue on systems I use routinely (Ubuntu and Fedora until recently). If this issue is limited to Oracle Linux, then it should probably be handled by those packaging openfortivpn for Oracle Linux.
