### ISSUE TITLE
cannot connect to MFA vpn

### ISSUE THREAD

**Issue by andreas65m** [adrienverge/openfortivpn#967]
Hello,
to connect to the VPN of my company I have to use MFA.
In the forticlient on a windows machine the VPN must be named MFA-Azure
the adress of the fortinet looks like https://ra.mycompany:443/azure

I found no way to connect to this VPN, because I don't know how to tell openfortivpn to connect to the address above and how to pass the name of the VPN. To get the token I use the microsoft authenticator.
I am the only linux VPN user, so I get no support from my company. 

Could anyone please help me

Regards
Andreas

**Comment by DimitriPapadopoulos** [comment]
Does the following help?
```
openfortivpn ra.mycompany --realm=azure
```
What you call "name" is called "[realm](https://docs.fortinet.com/document/fortigate/7.0.3/administration-guide/724772/ssl-vpn-multi-realm)" by Fortinet.

**Comment by surlykke** [comment]
My company has switched to an url like the OP's . The '--realm' switch works like a charm for me. Thx.

**Comment by DimitriPapadopoulos** [comment]
I guess `--realm` helped.
