### ISSUE TITLE
ERROR:  SSL_connect: error:00000000:lib(0):func(0):reason(0)

### ISSUE THREAD

**Issue by bennoonan92** [adrienverge/openfortivpn#968]
Every time i try and connect to the VPN server i get this. 
```
ERROR:  SSL_connect: error:00000000:lib(0):func(0):reason(0)
You might want to try --insecure-ssl or specify a different --cipher-list
```
It appears to be a generic openssl error
I am using version 1.8.1 on a Debian build.
Here is the debug output
bennoonan@debian-vm:/etc/openfortivpn$ sudo /usr/bin/openfortivpn -vvv
```
DEBUG:  openfortivpn 1.8.1
DEBUG:  Loaded config file "/etc/openfortivpn/config".
VPN account password:
DEBUG:  Config host = "example.com"
DEBUG:  Config realm = ""
DEBUG:  Config port = "10443"
DEBUG:  Config username = "username"
DEBUG:  Config password = "********"
DEBUG:  Resolving gateway host ip
DEBUG:  Establishing ssl connection
DEBUG:  server_addr: x.x.x.x
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: x.x.x.x
DEBUG:  gateway_port: 10443
ERROR:  SSL_connect: error:00000000:lib(0):func(0):reason(0)
You might want to try --insecure-ssl or specify a different --cipher-list
INFO:   Closed connection to gateway.
DEBUG:  server_addr: x.x.x.x
DEBUG:  server_port: 10443
DEBUG:  gateway_addr: x.x.x.x
DEBUG:  gateway_port: 10443
ERROR:  SSL_connect: error:00000000:lib(0):func(0):reason(0)
You might want to try --insecure-ssl or specify a different --cipher-list
INFO:   Could not log out.
```

**Comment by DimitriPapadopoulos** [comment]
First time I see this non-error – `error:00000000` means there is no error.

Are  you certain the VPN gateway supports VPN SSL? I'm asking because the error originates in the OpenSSL library:
https://github.com/adrienverge/openfortivpn/blob/e006833a5ca513f247c29dd29b4bbdf793b770f9/src/tunnel.c#L1225-L1229

The SSL_connect() manpage reads:
> ### RETURN VALUES
> 
> The following return values can occur:
> ##### 0
> The TLS/SSL handshake was not successful but was shut down controlled and by the specifications of the TLS/SSL protocol. Call SSL_get_error() with the return value **ret** to find out the reason.
> ##### 1
> The TLS/SSL handshake was successfully completed, a TLS/SSL connection has been established.
> ##### <0
> The TLS/SSL handshake was not successful, because a fatal error occurred either at the protocol level or a connection failure occurred. The shutdown was not clean. It can also occur if action is needed to continue the operation for nonblocking BIOs. Call SSL_get_error() with the return value **ret** to find out the reason.

It's hard to tell what might be going wrong with SSL_connect() here.

**Comment by DimitriPapadopoulos** [comment]
Might be worth adding a `printf()` to find the exact error value of SSL_connect(), 0 or <0.

**Comment by DimitriPapadopoulos** [comment]
It might also be worth retrieving and printing the value `errno` just after the call to SSL_connect().

**Comment by DimitriPapadopoulos** [comment]
You might also try to initiate an SSL/TLS connection to the VPN gateway with the `openssl` command:
```sh
openssl s_client -connect vpn.company.com:443
```
Anything suspect?

See for example:
* [Using OpenSSL s_client commands to test SSL connectivity](https://docs.pingidentity.com/bundle/solution-guides/page/iqs1569423823079.html)
* [K46853274: curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104](https://support.f5.com/csp/article/K46853274)

**Comment by DimitriPapadopoulos** [comment]
Closing because of the lack of feedback.

**Comment by berkut874** [comment]
Thx

**Comment by DimitriPapadopoulos** [comment]
Mmmh... Thx for what exactly? Did any of the above help fix an issue?

**Comment by MasterInQuestion** [comment]
A probable cause is the network outright responded with nothing (empty reply).
    Resulting alike cryptic non-error TLS errors.

    Typically in environment that blocks proxy traffic.
