### ISSUE TITLE
DNS for sub domains not working

### ISSUE THREAD

**Issue by hadron43** [adrienverge/openfortivpn#970]
Version: 1.15.0
OS: Ubuntu 21.10
Kernel: 5.13

I'm running openfortivpn to access college resources.
I'm able to access website osa.iiitd.edu.in, however there are services hosted as subdomains: eg achieve.osa.iiitd.edu.in. I'm unable to access the sub domains.

When I try to access the same resources using Forticlient SSL VPN client, I can access them easily.

Result on nslookup achieve.osa.iiitd.edu.in:
Server:		1.1.1.9
Address:	1.1.1.9#53

** server can't find achieve.osa.iiitd.edu.in: NXDOMAIN

**Comment by DimitriPapadopoulos** [comment]
I can resolve these names from my own computer, without help from any VPN. It looks the same IP address hides behind these names:
`achieve.osa.iiitd.edu.in` → `1.1.1.240`
`osa.iiitd.edu.in` → `1.1.1.240`

**Comment by hadron43** [comment]
Surprisingly, when I connect to my VPN using openfortivpn, it doesn't resolve achieve.osa.iiitd.edu.in
However, it still resolves osa.iiitd.edu.in
I can browse both the websites when I use forticlient VPN. If any more logs are needed, I can provide them.

**Comment by DimitriPapadopoulos** [comment]
Can you resolve `achieve.osa.iiitd.edu.in` **before** running any VPN?

Something must be wrong with the DNS server used after running openfortivpn. The DNS servers might be different. Perhaps we can start by running **`systemd-resolve --status`**:
1. before running the VPN,
2. after running FortiClient,
3. after running openfortivpn.

**Comment by hadron43** [comment]
1. before running vpn: 
```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (wlp0s20f3)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 2405:201:4027:9ac2::c0a8:1d01
       DNS Servers: 192.168.29.1 2405:201:4027:9ac2::c0a8:1d01
        DNS Domain: --

```

2. after forticlient vpn:
```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (wlp0s20f3)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 2405:201:4027:9ac2::c0a8:1d01
       DNS Servers: 1.1.1.9 2405:201:4027:9ac2::c0a8:1d01

Link 8 (vpn)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.9
       DNS Servers: 1.1.1.9

```

3. After opernfortivpn:

```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (wlp0s20f3)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 2405:201:4027:9ac2::c0a8:1d01
       DNS Servers: 192.168.29.1 2405:201:4027:9ac2::c0a8:1d01
        DNS Domain: --

Link 9 (ppp0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

```

**Comment by hadron43** [comment]
Yes, I can resolve achieve.osa.iiitd.edu.in without using any VPN.

**Comment by DimitriPapadopoulos** [comment]
Note that openfortivpn had been initially written with old Linux systems in mind, where the main way to change the DNS setup was to modify `/etc/resolv.conf`. Of course, that's not a good idea nowadays, for a variety of reasons. That's a known and documented openfortivpn issue, and I believe the proper way to fix that involves moving DNS and routing stuff into an external script. Meanwhile, the only built-in alternative to modifying `/etc/resolv.conf` is to use `resolvconf`. Will come back to that later.

Additionally, openfortivpn does not fully support IPv6. While I am not saying that's an issue here, I do see that not only IPv6 is enabled, but also that the DNS server(s) is(are) defined by IPv6 addresses.

The default DNS server is `2405:201:4027:9ac2::c0a8:1d01` with `192.168.29.1` as the secondary DNS server. FortiClient appears to associate DNS server `1.1.1.9` to the `vpn` link, while openfortivpn remains with the default DNS setup. Not sure why at the moment.

Please find below different tests, trying to resolve `achieve.osa.iiitd.edu.in`, both using the C library:
```
nslookup achieve.osa.iiitd.edu.in 1.1.1.9
nslookup achieve.osa.iiitd.edu.in 192.168.29.1
nslookup achieve.osa.iiitd.edu.in 2405:201:4027:9ac2::c0a8:1d01
````
and systemd:
```
systemd-resolve -i wlp0s20f3 achieve.osa.iiitd.edu.in   # both with FortiClient and openfortivpn
systemd-resolve -i vpn achieve.osa.iiitd.edu.in   # with FortiClient
systemd-resolve -i ppp0 achieve.osa.iiitd.edu.in   # with openfortivpn
````


Finally, I suspect `openfortivpn` is not using `resolvconf`, although it should on a recent system such as Ubuntu 21.10. Have you built `openfortivpn` from sources, or are you using the Ubuntu package? Which exact version?

**Comment by hadron43** [comment]
I'm using openfortivpn 1.15.0. I installed this using Ubuntu package.

**Comment by hadron43** [comment]
```
hadron43@blueDoor:~$ nslookup achieve.osa.iiitd.edu.in 1.1.1.9
Server:		1.1.1.9
Address:	1.1.1.9#53

** server can't find achieve.osa.iiitd.edu.in: NXDOMAIN

hadron43@blueDoor:~$ nslookup achieve.osa.iiitd.edu.in 192.168.29.1
Server:		192.168.29.1
Address:	192.168.29.1#53

Non-authoritative answer:
Name:	achieve.osa.iiitd.edu.in
Address: 1.1.1.240

hadron43@blueDoor:~$ nslookup achieve.osa.iiitd.edu.in 2405:201:4027:9ac2::c0a8:1d01
Server:		2405:201:4027:9ac2::c0a8:1d01
Address:	2405:201:4027:9ac2::c0a8:1d01#53

Non-authoritative answer:
Name:	achieve.osa.iiitd.edu.in
Address: 1.1.1.240

hadron43@blueDoor:~$ 

```

**Comment by DimitriPapadopoulos** [comment]
It looks like the DNS server `1.1.1.9` is unable to resolve `achieve.osa.iiitd.edu.in`. That's strange, since this is the DNS server suggested by the VPN gateway. Yet `1.1.1.9` appears to be reachable during these tests, since the error message is `server can't find achieve.osa.iiitd.edu.in` and not `connection timed out; no servers could be reached`.

The DNS servers used without the VPN gateway, both `2405:201:4027:9ac2::c0a8:1d01` and `192.168.29.1`, can resolve `achieve.osa.iiitd.edu.in` → `1.1.1.240`.

It's puzzling that you can resolve `achieve.osa.iiitd.edu.in` with FortiClient, which switches to `1.1.1.9`, and not with openfortivpn, which remain with the default `2405:201:4027:9ac2::c0a8:1d01`/`192.168.29.1` servers.

Perhaps the default DNS servers are not reachable any more when the VPN is running, or something like that. I need to think about it.

There's one thing we need to clarify. There are multiple DNS resolvers on Linux, running in parallel and not always consistent. For example, `systemd-resolve` will query systemd, while `nslokup` will query the GNU C library, which may or may not be chained to systemd. So, how exactly is “DNS for sub domains not working”? Des `nslookup` fail, `systemd-resolve` fail, or perhaps both?

**Comment by DimitriPapadopoulos** [comment]
While version 1.15.0 that ships with Ubtuntu 21.10 is not the latest, it should be recent enough. There are two questions we need to answer:
1. Has `openfortivpn` been built with `resolvconf` support?
2. Is `resolvconf` available and used by `openfortivpn`?

I cannot recall whether there is an easy way to answer the first question. Perhaps try this and show us the output:
```
strings /usr/bin/openfortivpn | grep resolvconf
```
Then which is the output of the following commands?
```
type resolvconf
dpkg -l resolvconf
dpkg -l openresolv
```

**Comment by hadron43** [comment]
After connecting to forticlientvpn, running systemd-resolve for default interface and VPN interface:
```bash
hadron43@blueDoor:~$ systemd-resolve achieve.osa.iiitd.edu.in -i ppp0
achieve.osa.iiitd.edu.in: resolve call failed: No appropriate name servers or networks for name found
hadron43@blueDoor:~$ systemd-resolve achieve.osa.iiitd.edu.in -i wlp0s20f3 
achieve.osa.iiitd.edu.in: 1.1.1.240            -- link: wlp0s20f3

-- Information acquired via protocol DNS in 4.9ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache network
hadron43@blueDoor:~$ systemd-resolve achieve.osa.iiitd.edu.in
achieve.osa.iiitd.edu.in: 1.1.1.240            -- link: wlp0s20f3

-- Information acquired via protocol DNS in 3.5ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache network

```

**Comment by hadron43** [comment]
```bash
hadron43@blueDoor:~$ strings /usr/bin/openfortivpn | grep resolvconf
use-resolvconf
                                If installed resolvconf is used for the update.
hadron43@blueDoor:~$ type resolvconf
bash: type: resolvconf: not found
hadron43@blueDoor:~$ dpkg -l resolvconf
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  resolvconf     <none>       <none>       (no description available)
hadron43@blueDoor:~$ dpkg -l openresolv
dpkg-query: no packages found matching openresolv

```

**Comment by DimitriPapadopoulos** [comment]
Ah, thank you for this.

I suspect the GNU C library is able to resolve using the default `2405:201:4027:9ac2::c0a8:1d01`/`192.168.29.1` DNS servers. Just to make sure, what is the output of this simple command, with `openfortivpn` running?
```
nslookup achieve.osa.iiitd.edu.in
```

On the other hand, I believe that systemd, which is used by some web browsers, is unable to resolve. Just to make sure, what is the output of this simple command, with `openfortivpn` running?
```
systemd-resolve achieve.osa.iiitd.edu.in
```

Back to `resolvconf`, I suspect that the `openfortivpn` package of Ubuntu 21.10 is built without support for `resolvconf`, which is not a good idea. For example, after building `openfortivpn` from sources with `resolvconf` support, I see:
```
$ strings /my/path/bin/openfortivpn | fgrep resolvconf
use-resolvconf
Bad use-resolvconf value in config file: "%s".
/sbin/resolvconf
resolvconf_call: %s
Could not create command to run resolvconf (%s).
Could not close resolvconf pipe: %s
Bad use-resolvconf option: "%s"
                                If installed resolvconf is used for the update.
                    [--use-resolvconf=<0|1>] [--ca-file=<file>]
  --use-resolvconf=[01]         If possible use resolvconf to update /etc/resolv.conf.
use_resolvconf
resolvconf_call_len
resolvconf_call
$ 
```
To confirm that, what is the output of the following command? 
```
openfortivpn -h
```
In my case, the output includes `--use-resolvconf=[01]`:
```
$ /my/path/bin/openfortivpn -h
[...]
Options:
  -h --help                     Show this help message and exit.
[...]
  --pppd-call=<name>            Move most pppd options from pppd cmdline to
                                /etc/ppp/peers/<name> and invoke pppd with
                                'call <name>'.
  --use-resolvconf=[01]         If possible use resolvconf to update /etc/resolv.conf.

Config file:
[...]
$ 
```

Finally, I recommend you install `resolvconf`:
```
sudo apt install resolvconf
```
Even if it doesn't help right now, because `openfortivpn` is built without `resolvconf` support, it should be enabled on recent Linux distributions.

**Comment by hadron43** [comment]
I forgot to update here. It's somehow weird that I am able to access both these websites now using openfortivpn. I haven't changed anything.
