### ISSUE TITLE
http_send function

### ISSUE THREAD

**Issue by salvaguardia** [adrienverge/openfortivpn#973]
Hi!

**This isn't a really bug**, but I'm unable to use openfortivpn to connect to a drytek ssl vpn because of this:

```
INFO:   Connected to gateway.
DEBUG:  http_send:
POST /remote/logincheck HTTP/1.1
Host: *********:443
User-Agent: Mozilla/5.0 SV1
Accept: text/plain
Accept-Encoding: identity
Content-Type: application/x-www-form-urlencoded
Cookie:
Content-Length: 102

username=******&credential=************&realm=************=1&redir=**********&just_logged_in=1
DEBUG:  http_receive:
HTTP/1.0 501 Not Implemented
Pragma: no-cache
Content-type: text/html

<HEAD><TITLE>501 Not Implemented</TITLE></HEAD>
<BODY><H1>501 Not Implemented</H1>
We are sorry to be unable to perform the method POST to non-script at this time.<P>
If you would like to see this capability in future
releases, send the method which failed, why you
would like to have it, and the server version DrayWeb/0.0.2
to <ADDRESS>http://www.draytek.com/</ADDRESS><P>
</body>
</html>
```

There's some workaround I could use?

Thank you!

**Comment by DimitriPapadopoulos** [comment]
Since openfprtivpn is a client for Fortinet VPN SSL appliances, I'm not surprised it doesn't work for DrayTek appliances. Are Drytek devices supposed to be compatible with Fortinet devices?

Instead, I would try [OpenConnect](https://gitlab.com/openconnect/openconnect), which is designed to work with many VPN SSL devices.

**Comment by salvaguardia** [comment]
Hi Dimitri,

I don't have experience with DrayTek so, I don't have data about his compatibilities. I use openfortivpn in other VPN's and, simply, I tried it.

Thank you for your quick response!

**Comment by DimitriPapadopoulos** [comment]
DrayTek routers ship with [OpenVPN](https://openvpn.net/) as far as I can see. Just use the [OpenVPN client](https://openvpn.net/openvpn-client-for-linux/).

**Comment by salvaguardia** [comment]
Thank you Adrien!

I should read the F*HandBook before asking for help. Thank you again.

Kind regards.
