### ISSUE TITLE
Needing the keep alive or auto connect function

### ISSUE THREAD

**Issue by Jubielee** [adrienverge/openfortivpn#990]
We are having to connect to a payment API but the connection drops and we get the timeout errors on our app.  Wanting to know if there is a auto connect or keep connected function like there is in the Fortinet Client.  Any help would be appreciated.

**Comment by DimitriPapadopoulos** [comment]
Hard to help without additional information:
- versions (OS and openfortivpn)?
- what sort of timeouts and are you certain this is an issue of openfortivpn disconnecting?
- what's in the logs of openfortivpn?
- if the authentication based on a username and password, just write a script to restart openfortivpn (or use `--persistent` although I consider this is a bad option in the current state of openfortivpn).

**Comment by salvavidal** [comment]
I have the same problem, vpn connection drops without any known reason, my S.O. is CentOS Linux release 7.9.2009 (Core) and i use the last openfortivpn version

**Comment by DimitriPapadopoulos** [comment]
@salvavidal I am not sure these issues are related. Opening a new ticket would be preferable, hijacking other tickets ends up in discussions so complex and that no one has the time to address them.

Which the “last openfortivpn version”?

Please provide information as described in [Reporting issues](https://github.com/adrienverge/openfortivpn/wiki#reporting-issues).
