### ISSUE TITLE
Enable NAT for local Network

### ISSUE THREAD

**Issue by creited** [adrienverge/openfortivpn#991]
Not an issue, but I would like to enable NAT from my local network to the VPN, since I'm running openfortivpn in my router.

example: 192.168.0.0/24 network NAT to ppp0 which is vpn interface

My router is running openwrt 22.03 which has migrated to nftables.

Any hints on how to get this working?

**Comment by DimitriPapadopoulos** [comment]
See [Using pppd ip-up / ip-down scripts](https://github.com/adrienverge/openfortivpn/wiki#using-pppd-ip-up--ip-down-scripts).

Alternatively, you can give [OpenConnect](https://gitlab.com/openconnect/openconnect) a try: it calls an external script to set routing/DNS, and you could even write your own script.
