### ISSUE TITLE
Not working - brew services start openfortivpn 

### ISSUE THREAD

**Issue by Nathan-ma** [adrienverge/openfortivpn#998]
I did change the config file defined under `homebrew.mxcl.openfortivpn.plist`

I double check the command being executed by homebrew:

```
 <key>ProgramArguments</key>
 17   <array>
 18     <string>/usr/local/opt/openfortivpn/bin/openfortivpn</string>
 19     <string>-c</string>
 20     <string>/usr/local/etc/openfortivpn/openfortivpn/config</string>
 21   </array>
```

I can run it manually, and it works.

But when using brew, this is the output:

```
❯ brew services start openfortivpn
Warning: openfortivpn must be run as root to start at system startup!
==> Successfully started `openfortivpn` (label: homebrew.mxcl.openfortivpn)
❯ brew services list
Name         Status     User   File
openfortivpn error  256 darvos ~/Library/LaunchAgents/homebrew.mxcl.openfortivpn.plist
```

I think the command needs a `sudo` but running `sudo brew services start` gives me new error messages.

How can I solve this?

**Comment by DimitriPapadopoulos** [comment]
The `openfortivpn` must be run as root. Perhaps a `sudo` is missing somewhere, but I have no clue about mac0S.

**Comment by DimitriPapadopoulos** [comment]
From https://github.com/Homebrew/discussions/discussions/2617#discussioncomment-1783791, you might try:
```
# Clean up the root-based setup
sudo brew services stop openfortivpn
sudo brew services cleanup

# And start it again without root
brew services start openfortivpn
```
